### ISSUE TITLE
"Remove external_link from debates" is beaking migrations

### ISSUE THREAD

**Issue by andion** [consul/consul#1001]
The app's migrations try to remove external_link from debates table twice

* The first app [migration](https://github.com/consul/consul/blob/master/db/migrate/20150715190041_create_debates.rb#L6) creates an external_link column on debates.

* This column gets removed right after that, on the next [migration](https://github.com/consul/consul/blob/master/db/migrate/20150716154501_remove_external_link_from_debates.rb).

* The column is not being added again, but [this migration](https://github.com/consul/consul/blob/master/db/migrate/20160219172824_removes_external_link_from_debates.rb) tries to remove the column again so it breaks any migration from previous versions.

The cause is [this migration]( https://github.com/consul/consul/blob/8841949dd9f23b82087f20b8f00b4e7d7e57fb13/db/migrate/20160207205252_add_external_link_to_debates.rb) being deleted on [this commit](https://github.com/consul/consul/commit/f82a590e1e14028af70757bc23e8ffd2d8a49a38) while adding [the one mentioned](https://github.com/consul/consul/blob/f82a590e1e14028af70757bc23e8ffd2d8a49a38/db/migrate/20160219172824_removes_external_link_from_debates.rb).

It can be solved by re-adding the deleted migration or removing the new one. But either way it will break apps that executed migrations after that commit and will require interaction from the user migrating the database (i.e. remove the migration timestamp from schema_migrations).

**Comment by ferblape** [comment]
Good! I was just going to send the same issue and the same PR

:+1:

**Comment by ferblape** [comment]
@andion you didn´t create a PR, but that's the best way for consul to accept your change. Do you want help to create one?

**Comment by andion** [comment]
@ferblape I only pointed it out and proposed two solutions because I think it's better the team decides about how to solve this one. What do you think?

**Comment by ferblape** [comment]
I'd create a PR as desribed here: https://github.com/consul/consul/blob/master/CONTRIBUTING_EN.md#resolve-an-issue

That way, the team will know that there's a possible solution for an issue.

**Comment by andion** [comment]
@ferblape I'll do that then 😄
