### ISSUE TITLE
Adds new stats on admin

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1042]
Now on `/admin/stats`  there are these stats:

- Visitas
- Email Campaign 3 
- Email Campaign 1 
- Mails Anuncio Plaza España 
- Email Campaign Linea Madrid 
- Level 2 User 
- Proposal Created 
- Debate Created 
- Email Campaign 2 
- Mail Aun No Has Votado Para Plaza España 
- Presupuestos Email De Lanzamiento 
- Propuestas de inversión
- Email Campaign 3 
- Email Campaign 1 
- Mails Anuncio Plaza España 
- Email Campaign Linea Madrid 
- Level 2 User 
- Proposal Created 
- Debate Created 
- Email Campaign 2 
- Mail Aun No Has Votado Para Plaza España 
- Presupuestos Email De Lanzamiento 

**We need these ones:**

- Visitas
- Level 2 User 
- Proposal Created 
- Debate Created 
- Propuestas de inversión
- Votes on spending proposals **NEW**
- Votes on proposals **NEW**
- Coments Created **NEW**
- Level 1 User **NEW**
- Level 3 User **NEW**

**Comment by xuanxu** [comment]
Done. Pending stats will be added once we move away from ahoy
