### ISSUE TITLE
Abstract Manager's section

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1053]
User management tasks are currently being done at Government offices. The Managers allowed to do these tasks are being authenticated using a custom system of Madrid called UWEb.

We should abstract the concept of Manager authentication so that other forks can also use this feature easily.

As an extra, any Admin should be able to access the Manager section, similarly to how they access Moderation and Valuation sections.

Suggestion:
Integrate Managers with Devise and CanCan

**Comment by xuanxu** [comment]
This is done. Manager user role was added and admins can create managers from their control panel
