### ISSUE TITLE
SMS Verification for international phones

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1055]
Some users are living abroad but would still like to verify their accounts and vote.

Right now we are only allowing for spanish phone numbers (9 digits and starting with a 6 or a 7).
We should allow any international phone to be used too.

**Comment by inobCR** [comment]
#nachogomez y #inobcr estamos con esta

**Comment by inobCR** [comment]
Estamos probando web service de envio de SMS y en los envios internacionales esta fallando (teléfono con formato inválido)

**Comment by spanishkangaroo** [comment]
@inobCR it would be great if you would let others know exactly what you're testing (classes, files, data samples, etc.)

**Comment by decabeza** [comment]
Closed because on CONSUL users can introduce any phone number:

In `/models/verification/sms.rb:7`

```ruby
validates :phone, format: { with: /\A[\d \+]+\z/ }
```

This issue was created because the Madrid's Fork API doesn't allow international numbers.
