### ISSUE TITLE
Add demographic data to users

### ISSUE THREAD

**Issue by kikito** [consul/consul#1056]
In order to generate some participation reports, we need to include some new data in our users table:

* Genre
* Date of birth
* District (possibly this is already in, since there is a district_id. Investigate more)

We need to fill these in automatically when calling the Census API. We also need to implement a rake task to fill already-verified people.

**Comment by gitmarcia** [comment]
Hola.
Me pongo con ella.

**Comment by kikito** [comment]
This was done in Madrid
