### ISSUE TITLE
Presupuestos Participativos Fase 3 - Votación Final

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1105]
Votar

  - [ ] En la barra de progreso mostrar cuánto dinero te queda. (https://github.com/AyuntamientoMadrid/consul/pull/178)

  - [ ] Cuando ya has gastado parte de la bolsa, deberían desactivarse las propuestas que superen el dinero disponible. Mola que se sigan mostrando para que veas a lo que renuncias, lo ideal es que con cada selección no se esté recargando la página, pero que se actualice la barra y las ya no disponibles.

  - [ ] Mostrar la cantidad de dinero con format de dinero.(https://github.com/AyuntamientoMadrid/consul/pull/177)

  - [ ] En el listado de propuestas de un distrito, mostrar la barra de progreso para ese distrito.

  - [ ] Si se quitan todos los votos a un distrito se puede seleccionar otro distinto.

  - [ ] Al escoger el distrito por primera vez, mostrar la barra morada explicando que puedes cambiar de distrito en cualquier momento quitando todos los votos a ese distrito.

Navegar

  - [ ] En la página de bienvenida, los dos botones deberían ser "Votar propuestas para toda la ciudad" y "Votar propuestas de distrito", para que quede claro que votas en dos listas separadas, y luego el segundo te lleva a otra página para seleccionar, igual que la del mapa.
(https://github.com/AyuntamientoMadrid/consul/pull/181)

  - [ ] Usar la ordenación aleatoria por defecto y quitar la opción de ordenar por 'mejor valoradas'.

  - [ ] En la página de escoger tu distrito, resaltar cuál es el distrito que has escogido.

  - [ ] Cuando estás votando en un distrito que no es el tuyo, en lugar de la barra mostrar un link a las propuestas de tu distrito.

Revisar mis votos

  - [ ] En la barra de progreso deberían haber subdivisiones correspondientes con cada uno de los gastos, para entender visualmente la relación entre unos y otros.

  - [ ] Quitar el botón de "Confirmar mis votos"

  - [ ] Quitar la página de "Confirmar mis votos"

  - [ ] Añadir un texto aclaratorio: "Has votado X propuestas por un valor de X euros. Puedes cambiar tus votos en cualquier momento hasta  el 30 de junio".

  - [ ] Añadir un espacio desplegable debajo de la barra de dinero con la lista de propuestas votadas.

  - [ ] En la lista de propuestas añadidas, cada una debería tener una x para quitarla. 

  - [ ] Mostrar los proyectos de inversión que he votado desde mi actividad.

Permisos
  - [ ] Hover para los casos habituales con links para arreglar la situación: no estás identificado, no estás verificado. (https://github.com/AyuntamientoMadrid/consul/pull/179)

  - [ ] Hover para cuando no es tu distrito (pending spec at ballots_spec.rb)

Linea Madrid
 - [ ] Permitir votar desde los Centros de Atención Ciudadana
 
Delegar
  
  - [ ]  Mantenemos igual que la otra vez el sistema de delegación: al activar o al votar algo cuando está activado te sale un alert avisando que se activa o desactiva.

Compartir en Redes Sociales
  - [ ] Añadir botones para compartir en redes sociales con un texto por defecto. Por e.j. 'He decidido dónde quiero que se inviertan 1.928.212 para Villa de Vallecas.'

Estadísticas
  - Añadir métricas generales a admin/stats.
    - [ ] Número de usuarios que han votado algún proyecto de inversión.
    - [ ] Número de votos totales en proyectos de inversión.
    - [ ] Ranking en tiempo real de proyectos de inversión por distrito y en toda la ciudad.

--- Post lanzamiento (mover a otro issue) ---

Resultados Finales
  - [ ] Añadir Setting para finalizar la votación.
  - [ ] Añadir hover al botón de votar con el mensaje de votación finalizada.
  - [ ] Página informativa mostrando los proyectos de inversión ganadores.

**Comment by decabeza** [comment]
Continue on https://github.com/AyuntamientoMadrid/consul/issues/182 😉
