### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1108]
We need to refactor and create new helpers for aria attributes on like/support/vote buttons.

When a user can't vote on debate/proposal/spending proposal we need include the attribute **`aria-hidden="true"`** on button link.

Something like this: https://github.com/consul/consul/pull/1107/commits/d46a2f9335e203633d0374e224e9fb019e7f917c

Also add the **`aria-hidden="false"`** on div with reasons for can't vote. Maybe delete the **`style="display:none"`** on that div (only for screen readers)

For testing you can use this [Chrome extension](http://www.chromevox.com/)

Here more reference links:
- [HTML5 Accessibility Chops: hidden and aria-hidden](https://www.paciellogroup.com/blog/2012/05/html5-accessibility-chops-hidden-and-aria-hidden/)
- [Methods to hide content in various ways](https://alastairc.ac/gists/7706437/hiding-content.html)

**Comment by jaimeiniesta** [comment]
Check out also Tenon:

https://tenon.io/testNow.php?url=http://decide.madrid.es

**Comment by decabeza** [comment]
Done on https://github.com/consul/consul/pull/1285 👏
