### ISSUE TITLE
Votos negativos (presupuestos participativos)

### ISSUE THREAD

**Issue by abelmonroy** [consul/consul#1112]
Esta es una petición para los presupuestos participativos de Madrid.

Ahora mismo, un usuario puede dar votos a x propuestas. 
Pero si alguna propuesta en un distrito, o para toda la ciudad, no gusta a muchos usuarios, pero es del agrado de unos pocos, es posible que salga de las mas votadas. 
Los que son contrarios a la propuesta votarán otras, pero si esos votos están suficientemente disgregados, o hay pocos votos (como ha sucedido en los distritos), esa propuesta estará entre las más votadas.

Mi petición es que un usuario pueda tener x votos para dar a propuestas, como ahora, pero que puedan ser votos positivos o negativos.
De este modo, si hay una propuesta en la que no estás en absoluto de acuerdo, puedes decirlo, cosa que ahora es imposible.

**Comment by Frankybuzz** [comment]
Esto es un desarrollo fundamental para entender las implicaciones de llevar a cabo una propuesta. No solamente tienen que salir adelante propuestas muy votadas, sino también que no tengan muchos votos negativos. De otra manera, se pueden hacer y deshacer las mismas medidas continuamente.

**Comment by voodoorai2000** [comment]
Hola!

Muchas gracias por crear este issue, es una propuesta con sentido.
La respuesta desde el Ayuntamiento es la siguiente:

"Este año la idea era hacerlo simple y sin voto negativo, y evaluar la posibilidad para años siguientes teniendo en cuenta el resultado"

Así que, este año me temo que no lo vamos a poder implementar, pero... es posible que el año que viene esté incluida.
