### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by marfil92** [consul/consul#1115]
Buenas tardes,
Nos gustaría implantar el sistema de Consul para el consejo ciudadano de nuestro municipio pero no conseguimos instalar la plataforma.

Alguien nos puede ceder un tutorial para su instalación?

Muchas gracias!

**Comment by voodoorai2000** [comment]
Buenas tardes @marfil92, 

Nos alegramos mucho que estéis instalando Consul en vuestro municipio!
Aparte del [Readme](https://github.com/consul/consul/blob/master/README_ES.md) aún no tenemos un tutorial detallado. Pero es una de las cosas que queremos hacer en breve.

De momento, por favor poneos en contacto con Enrique (muguerzaje@madrid.es), es el encargado de Extensión y os puede ir ayudando con varios temas ;)

**Comment by marfil92** [comment]
Ya lo hemos seguudo pero algo hacemos mal... Estamos usando un servidor de Amazon. Agradeceriamos que alguien nos diera unos pasos a seguir.

Muchas garcias!

**Comment by gmfsab** [comment]
@marfil92 

Quizá te ayude este modesto aporte, donde estoy escribiendo tutoriales

http://consul.esy.es/P%C3%A1gina_principal
