### ISSUE TITLE
Budget public interface

### ISSUE THREAD

**Issue by kikito** [consul/consul#1122]
- Specs for models
  - [x] Budget
  - [x] Heading (For now, it's a simple model with just validations)
  - [x] Investment
  - [x] Ballot
  - [x] Ballot Line (Not needed, included in Ballot)
- [ ] Welcome
- [ ] Add investments to user's show
- Phases
  - [ ] On hold 
  - [ ] Accepting
  - [ ] Selecting phase
  - [ ] Balloting phase
  - [ ] Results (Finished phase)

**Comment by voodoorai2000** [comment]
Closed in favor of https://github.com/consul/consul/issues/1189
