### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#1130]
Add documentation files/tutorials to `/doc` folder detailing:
- [x] Current features (https://github.com/consul/consul/pull/1184)
- [x] Use of different user roles (user, organization, moderator, manager, admin) (https://github.com/consul/consul/pull/1184)
- [ ] Default active features on install
- [x] Admin panel interface (https://github.com/consul/consul/pull/1184)
- [ ] Customization via settings
- [x] Guidelines on how to add translations (https://github.com/consul/consul/pull/1137)
- [x] Have all the docs in english (default README.md in the /docs folder should be in english) (https://github.com/consul/consul/pull/1507)

**Comment by LTCOS** [comment]
I will send the different difficulties I have when I translated to french

**Comment by rafadelascuevas** [comment]
Hi, I'm from @PopulateTools , I'm working on some added content to the spanish documentation with the new features in the admin section & updated images

**Comment by xuanxu** [comment]
@rafadelascuevas that sounds great! 👌

**Comment by voodoorai2000** [comment]
Closed in favor of #1778
