### ISSUE TITLE
Future emails digests

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1149]
-  [ ] After sending a digest, delete the notifications sent.
- [ ] Do not include notifications of proposals that have been deleted.

**Comment by gitmarcia** [comment]
Hola. Me pongo con esta.

**Comment by voodoorai2000** [comment]
Gracias @gitmarcia!

Perdona se nos ha pasado cerrar este issue, ya está implementado. Coge otro por favor ;)

**Comment by gitmarcia** [comment]
ok. Busco otra.
________________________________________
De: Raimond Garcia [notifications@github.com]
Enviado: jueves, 13 de octubre de 2016 10:59
Para: consul/consul
CC: Guijarro Cebrian, Marcia; Mention
Asunto: Re: [consul/consul] Future emails digests (#1149)

Gracias @gitmarcia<https://github.com/gitmarcia>!

Perdona se nos ha pasado cerrar este issue, ya est� implementado. Coge otro por favor ;)

�
