### ISSUE TITLE
Related content

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1164]
The goal of this feature is to show a list of "related contents" to debates, proposals, etc in the platform. The users will see this list in the items `#show` page and would be able to match it as related or not with action buttons.

The main steps to build it could be resumed in the next points:

- Create a polymorphic concern to handle as many models as we want.
- Create a `RelatedContent` model to store the relations. This could have in origin the following attributes:

    - `parent_content_id` (integer): id in table of origin of the element that has attached as related the `related_content_id` (i.e. `23`).
    - `related_content_id` (integer): id in table of origin of the content found as related to `parent_content_id`, which will be shown in its "related content" list (i.e. `456`).
    - `parent_content_type` (string): model name of the parent element to identify its origin (i.e. `Debate`).
    - `related_content_type` (string): model name of the related element to identify its origin (i.e. `Proposal`).
    - `times_reported` (integer): in case a related content has been reported as not related by different users a maximum times (that is pending to be defined), this content will be removed (not yet defined if it will be hidden from the list or removed from the DDBB).

    So using the examples written above, we could have a record for a `Debate` with id `23` that has as related content a `Proposal` with id `456`, which will appear in its list of "related contents".

- Enable methods to perform the actions for users to say if the items in the list are related or not.

- Regarding the topic of _how to start to generate content if the users are the ones responsible for making these relations?_ here are my two cents: when the list of related contents is going to be rendered, and there're no relations created yet, I suggest to make a query to identify a bunch of items (a max number that the platform can assume and won't make the content load slower, maybe 5) from different models as potential relations, based on titles and tags. This way, we avoid not offering anything at all related and can start to encourage the users to decide whether those topics belong together or not. These querys will be random everytime the page is loaded, so the content will be diverse.

![1_related_content](https://cloud.githubusercontent.com/assets/631897/16302548/0deb44b4-394c-11e6-965d-1f8dc7fd7a6a.jpg)

![2_related_content](https://cloud.githubusercontent.com/assets/631897/16302547/0deaf130-394c-11e6-8fb6-880becf2bb30.jpg)

![3_related_content](https://cloud.githubusercontent.com/assets/631897/16302549/0def1b20-394c-11e6-817b-394bcf858532.jpg)

**Comment by ManjiChiba** [comment]
Interesante opción (no había pensado en ella, pero será muy útil).
Hasta ahora, ya venía haciéndolo yo, pero de una manera muy cutre/chapucera, poníendolo como un simple comentario/link a otra propuesta/propuestas complementaria o con la que agruparse.
Aprovecho... si se pudiera llevar a la práctica alguna de estas.... pues estaría muy bien.
https://decide.madrid.es/proposals/8938-recopilacion-de-propuestas-relativas-a-mejora-de-la-administracion-de-la-web-1
https://decide.madrid.es/proposals/11947-recopilacion-de-propuestas-relativas-a-mejora-de-la-administracion-de-la-web-2
