### ISSUE TITLE
Questions to citizens

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1165]
New section of "Questions to citizens":
1. INDEX: List of questions

![1_consultas_ciudadanas_index](https://cloud.githubusercontent.com/assets/631897/16307995/9f551ea4-3963-11e6-9a29-0a13b3897720.jpg)

1.b. If can create new question display button of "Create question"

![2_consultas_ciudadanas_index_b](https://cloud.githubusercontent.com/assets/631897/16308001/a352b8d6-3963-11e6-8f9b-a9e74cdab827.jpg)
1. NEW: Form to create a new question

![3_consultas_ciudadanas_new](https://cloud.githubusercontent.com/assets/631897/16305878/fe415dea-395b-11e6-8bbc-678b2649e13e.jpg)
1. SHOW: display the question (the answer is yes/no)

![4_consultas_ciudadanas_show](https://cloud.githubusercontent.com/assets/631897/16305895/16cac0b8-395c-11e6-9148-4aec87bfde5d.jpg)

3.b. SHOW: when the participation is closed

![4_consultas_ciudadanas_show_2](https://cloud.githubusercontent.com/assets/631897/16305900/1ad8bcb4-395c-11e6-9d03-26e51c52d0e3.jpg)

3.c. SHOW: displays results and participation stats

![5_consultas_ciudadanas_results](https://cloud.githubusercontent.com/assets/631897/16305935/3f4bc5be-395c-11e6-9d68-b4eae1e7e2cc.jpg)

![5_consultas_ciudadanas_results_2](https://cloud.githubusercontent.com/assets/631897/16305939/40689bb6-395c-11e6-9567-b6ad772ca5c2.jpg)

**Comment by ManjiChiba** [comment]
Esta propuesta promete, promete mucho.
Si el Ayto nos pregunta algo a los ciudadanos, y nosotros lo respaldamos mayoritariamente, ya NADIE, NADIE, podrá decir "otra ocurrencia de...".
De esta manera el Ayto estará perfectamente legitimado, refrendado y apoyado por la ciudadanía, y así, se podría cerrar la sucia bocaza a unos cuantos que sólo entran a mal-meter y sembrar cizaña.

**Comment by voodoorai2000** [comment]
Closed in favor of https://github.com/consul/consul/issues/1216

**Comment by ManjiChiba** [comment]
Esta si que la espero con impaciencia.
