### ISSUE TITLE
Mark a proposal as duplicate

### ISSUE THREAD

**Issue by Almorca** [consul/consul#1185]
La idea es que los usuarios puedan marcar propuestas como duplicadas de otras ya creadas anteriormente. El aviso de propuesta duplicada llegaría al creador de la propuesta que tendría la opción de decidir cerrar su propuesta. Si la propuesta se cierra por duplicada le llegaría un correo a todos los usuarios que han votado la propuesta cerrada comentándoles el motivo del cierre y animándoles a votar la propuesta más antigua.

**Comment by xuanxu** [comment]
Todo lo necesario para esto ya está implementado.

-Se pueden enviar mensajes al autor de una propuesta.
-El autor de una propuesta puede retirarla marcándola como duplicada (o por otras razones).
-El autor puede enviar avisos a todos los participantes en una propuesta.

Lo que no hay es la posibilidad de marcar como duplicada por un usuario que no sea el autor, porque eso podría hacer que si A y B son similares, los partidarios de cada una marquen a la otra y acaben apareciendo A y B marcadas como duplicadas.
