### ISSUE TITLE
Archived proposals

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#1208]
Archived proposal are those older than X months

- [x] Add setting for archival: X months
- [x] `.archived?` method in Proposal
- [x] Archived Tab in index
- [x] Remove support button in index/show
- [x] Do not accept votes in model
- [x] Remove archived proposals from general indexes
- [x] Add model spec for archived proposals
- [x] Add number of supports in index/show

**Comment by voodoorai2000** [comment]
Closed via #1213
