### ISSUE TITLE
About configuration instructions

### ISSUE THREAD

**Issue by gentooza** [consul/consul#1209]
Hi!

I've finally this app working in development mode in a server, I had to tweak some things so I'm going to share what I did, for improving docs. (or fix my mistakes at worst)

first of all, say it's a bit nightmare to have this versions of tools (Ruby, postgresql...) as they have versions above of current Debian or Ubuntu distros. (I absolute sure it's necessary, but for a newbie of ruby as me it's difficult to have it working).

So I had to install rvm, and with rvm a correct ruby version, bundler, and gem. (debian default bundler version didn't work)  [http://unix.stackexchange.com/questions/102678/making-ruby-available-to-all-users] [ https://rvm.io/integration/bundler]

I had to use a ppa to have postgresql versions upper than 9.1 (I remember)
pgdg.list

```
deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main
```

and

```
wget https://www.postgresql.org/media/keys/ACCC4CF8.asc
apt-key add ACCC4CF8.asc
apt-get update
apt-get install postgresql-9.4
```

Well, in fact there are lots of tutorials for doing this, but afterwards I was stuck with database configuration of consul.

I removed all postgresql versions except 9.4.
I created my consul user rol in postgresql
and changed database.yml from

```
host: localhost
```

to

```
host: /var/run/postgresql
```

As Postgresql seems to use unix socket as default for localhost connections.

Ruby hackers I think know more about rvm, it could be cool to know more about upgrading, maintenance, etc.

I'm not, but i'll try to participate and share the little I know.

thanks!

**Comment by jaimeiniesta** [comment]
It would be great to have updated docs for installation on ubuntu, maybe osx, vagrant, docker.

**Comment by albertomg994** [comment]
Maybe this can help you, but it's written in spanish:

http://wikis.fdi.ucm.es/ELP/Trabajo:Cómo_colaborar_con_el_ayuntamiento

I'll try to translate the osx installation instructions, which are the ones I wrote, and post them here in the next days.

**Comment by albertomg994** [comment]
You can also find installation instructions here:

http://wikis.fdi.ucm.es/ELP/Trabajo:Cómo_colaborar_con_el_ayuntamiento

**Comment by gentooza** [comment]
Could be nice to have it inside consul project wiki, isn't it?
We can improve it, translate it, etc. (I'm a volunteer! :-D)

(if also original authors and Madrid are agree, of course)

**Comment by albertomg994** [comment]
I'm one of the authors and I know the other two. I'm sure they'll agree but I'll ask them just to be certain. I can volunteer also.

**Comment by jaimeiniesta** [comment]
Better than the wiki, on the docs of this repo.

**Comment by voodoorai2000** [comment]
Hi guys,

Thank you for looking into this!

We have just created the [wiki](https://github.com/consul/consul/wiki/Deployment) page for deployments. Please feel free to update it with the documentation that you find most useful. 

Also if you prefer sending a PR to [doc](https://github.com/consul/consul/tree/master/doc) that would also be great.

Cheers!

**Comment by albertomg994** [comment]
The contents of that wiki are under CC-4, but I don't know the effects of that on the AGPLv3 license of consul.

**Comment by kikito** [comment]
As far as I understand it CC-4 is not "contagious" as AGPLv3 might be - you are not required to preserve that license in derived works as long as you give attribution. So we could add a paragraph such as this.

    > These instructions where adapted from http://wikis.fdi.ucm.es/ELP/Trabajo:Cómo_colaborar_con_el_ayuntamiento, written by <original author> in <date-of-adaptation>, which is distributed under [CC-4](https://creativecommons.org/licenses/by/4.0/). Some changes could have been made later on - <link to github history of the file>. Al subsequent changes are subject to the AGPLv3 license.

**Comment by decabeza** [comment]
Close this one because we have a new repository for [Consul Documentation](https://github.com/consul/docs) (still on progress but we keep working on it!) 🎉
