### ISSUE TITLE
Add emails specs for each commentable

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1241]
Why
===
When a user writes a comment on a proposal or replies to a comment, [an email](https://github.com/consul/consul/blob/master/spec/features/emails_spec.rb#L27) is sent to the author of the proposal or the parent comment respectively.

Currently we only have specs for debates and proposals, but there are other models that use comments too.

What
===
Add specs related to sending these emails, for these models:
`Budget::Investment`, `Poll` and `Topic`

No need to add email notifications for `Legislation::Annotation` yet.

Warning
===
[Email notifications](https://github.com/consul/consul/blob/master/app/mailers/mailer.rb#L8) are integrated with [in-app notifications](https://github.com/consul/consul/blob/master/app/models/notification.rb#L1) 

In this PR or another, we should also make sure, all models can correctly view their [comment notifications](https://github.com/consul/consul/blob/master/spec/features/notifications_spec.rb#L17)

Screenshots
===
- Comments
![comments](https://user-images.githubusercontent.com/4169/30809541-5ecfcb78-a202-11e7-9b57-a79bb9c4bbe8.png)

- In-app notifications
![in-app notifications](https://user-images.githubusercontent.com/4169/30809532-56ea5f04-a202-11e7-986b-3edb6be9f276.jpg)

**Comment by aitbw** [comment]
I could gladly handle this one, but I'll need some context to understand what is it we need to test.

**Comment by voodoorai2000** [comment]
Awesome @aitbw, issue description updated

**Comment by aitbw** [comment]
Small clarification: While reviewing the `Topic` specs, I realized topics are proposals. What's the difference between these 2 and how does this affect the email notifications?

**Comment by voodoorai2000** [comment]
Hey @aitbw 

Right, a Topic is part of a greater concept called Community which is formed around a Proposal
Here is the initial PR for Topics
https://github.com/consul/consul/pull/1815

A Community is a like a forum and the threads are the Topics, which have comments.

When a user creates a root comment on a Topic, the author of the Topic should receive a email.
When a user replies to a non-root comment, the author of the comment being replied to, should receive an email.

**Comment by aitbw** [comment]
We can close this one, as its related PR is already merged :)

**Comment by decabeza** [comment]
Thanks @aitbw ! 

Closed by https://github.com/consul/consul/pull/2126
