### ISSUE TITLE
Attach documents to proposals

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1245]
- Admins should be able to attach "official documents" to a proposal.
- Users should be able to attach a photo to their proposal

Some mockups for this: 

New link for admins:
![1_add_documents](https://cloud.githubusercontent.com/assets/631897/19444612/6cc013f2-9491-11e6-9b3e-cd672e1302e5.png)

When admin clicks on attach document:
![2_add_documents](https://cloud.githubusercontent.com/assets/631897/19444613/6e8e9a64-9491-11e6-98ba-68afbc2af6ca.png)

When document it´s uploaded:
![3_add_documents](https://cloud.githubusercontent.com/assets/631897/19444616/70128e0e-9491-11e6-9579-cd3505c945ce.png)

**Comment by voodoorai2000** [comment]
This feature is being developed by @rockandror

**Comment by decabeza** [comment]
This feature is already working thanks to Rock&RoR with [#1809 Documentable](https://github.com/consul/consul/pull/1809). 

Now the authors (and admins) can attach documents to proposals 🎉
