### ISSUE TITLE
Admin menu redux

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#1249]
The admin's menu is too long and similar visually.
Add specific icons for each menu item.
Optionally redo navigation to use submenus.

Current state: 
![captura de pantalla 2016-10-20 a las 12 33 23](https://cloud.githubusercontent.com/assets/6528/19556498/b275deae-96c1-11e6-881b-cc196bde260b.png)

**Comment by decabeza** [comment]
The new admin menu rocks! 🎉
