### ISSUE TITLE
consul-temp-nginx

### ISSUE THREAD

**Issue by huyifanstar** [consul/consul#1260]
I need to use nginx to a number of different applications to do porxy_pass different ports and load balancing, I would like to ask how should I do

**Comment by voodoorai2000** [comment]
Hello @huyifanstar,

Sorry I think this is not the Consul you are talking about, did you mean this Consul?
https://github.com/hashicorp/consul

**Comment by huyifanstar** [comment]
yes     consul-temp-nginx

**Comment by voodoorai2000** [comment]
Alright, cheers @huyifanstar
