### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1280]
We would like to add maps to visualize proposal and participation locations.

User interface
- [x] allow authors to store geolocation when creating a proposal
- [x] allow authors to update geolocation in their existing proposals
- [ ] allow any user to send geolocation suggestions pending of admin approval
- [x] display a map with the geolocation of a proposal
- [ ] display a heatmap of votes per district for a proposal

Admin
- [ ] interface to store geolocation of a proposal
- [ ] interface to approve geolocation suggestions for proposals

API
- [ ] Add geolocation attributes from proposals

Fase 2
- [ ] Allow polygon areas and lines to store geolocations
- [ ] Allow polygon areas to select proposals in that geolocation

WIP [jorgelf fork](https://github.com/consul/consul/compare/master...jorgelf:jlopez?expand=1) [potential gem](https://github.com/amiedes/emapic_consul)

Seed Hackathon
  Collective Intelligence For Democracy at @medialab-prado 
  With the help of @emapic
  
  Presentation: https://youtu.be/OhIEAc2ULYQ?t=8811
  Slides: http://slides.com/cartolab/deck#/
  Demo: https://consul.inteligenciacolectiva.cc/proposals/1-fugit-facilis-iste-aliquid-delectus

**Comment by devinbalkind** [comment]
Is this issue continuing to be updated? Where is the best place to find the current roadmap related to maps? Thanks.

**Comment by voodoorai2000** [comment]
Hey @devinbalkind!

It's in standby for now, all feedback welcomed 😊

**Comment by decabeza** [comment]
🗺 Maps are already integrated on CONSUL thanks to **Maps frontend** https://github.com/consul/consul/pull/1864 🎉
