### ISSUE TITLE
Redirección de etiquetas

### ISSUE THREAD

**Issue by kikito** [consul/consul#133]
Los moderadores tienen que ser capaces de redirigir etiquetas.

El ejemplo típico sería etiquetas sin acentos: `economia` vs `economía`.

Un moderador debe ser capaz de "hacer que `economia` 'redirija' a economía" en su Dashboard de administración. Las consecuencias a nivel lógico serían:
- Al intentar "listar por etiqueta" utilizando `economia` se haría un "redirect" para mostrar los etiquetados con `economía`.
- Todos los debates etiquetados con `economia` pasarían a estar etiquetados con `economía`

Solamente queremos un nivel de redirección (nada de A -> B -> C ...). Por lo tanto:
- No se puede utilizar una "etiqueta destino" que no exista.
- No se puede "redirigir a una etiqueta que a su vez es una redirección a otra"
- No se puede redirigir una etiqueta A a otra B si ya existen redirecciones apuntando a A

**Comment by apradillap** [comment]
La verdad es que llevo varios días viendo esta issue y es posible que por ejemplo economía apareciera como Economia, Economía o economia y no acabo de ver la solución de la redirección de etiquetas.

Tenía la duda de si no es más sencillo:
- Hacer algo más simple como todas las letras en minúsculas y sin acentos tanto para guardar los tags como para las búsquedas.
- Hacer algo más complejo que sería sanitizar para que todas fueran minúsculas pero pasar un corrector ortográfico para verificar si tiene algún acento.

Por otro lado también es posible que al estar la aplicación en inglés y español no se cual sería la mejor solución para gestionar tags en los 2 idiomas para que no aparecieran por duplicado. ¿Habéis visto alguna solución mas o menos limpia alguna vez para esto?

**Comment by alejanderl** [comment]
Creo que se puede estructurar en dos partes
Por un lado normalizar en un campo las etiquetas. Crear un campo slug() con uniqueness en la tabla tags.
Así se evitan los duplicados por errores en tildes, etc.
Por otro, crear una herramienta de sinónimos para poder agrupar etiquetas por parte de los moderadores y mostrar los resultados agrupados.

**Comment by decabeza** [comment]
This is already working, for the same example `http://localhost:3000/proposals?search=economia` show proposals tagged as `Economía`, `economía`, `Economia` or `economia`.

🎉
