### ISSUE TITLE
Add suggest when creating investments

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1354]
Just like when creating a proposal, we should display a list of possible existing investments when you start typing the title of a new investment project.
 
To reach the new investment screen:
rake db:dev_seed
login_as(verified@consul.dev)
visit /budgets
click on a project accepting investments
click button 'Create budget investment'

![suggest](https://cloud.githubusercontent.com/assets/4169/21961167/bed111fc-db02-11e6-8b95-0a5cf19afa36.png)

**Comment by microweb10** [comment]
I can work on this

**Comment by voodoorai2000** [comment]
Awesome, all yours!

**Comment by microweb10** [comment]
Sorry guys, for personal reasons I can't work on this issue anymore. I gave it a try but for some weird reason it was not working, but I have already have some code that could be used.
https://github.com/microweb10/participacion/tree/ISSUE-1354

**Comment by voodoorai2000** [comment]
Closed via #1635
