### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by jaimeiniesta** [consul/consul#1430]
Hello! I've run an accessibility audit on 1000 pages of decide.madrid.es and found these issues:

https://rocketvalidator.com/s/1e7c5bba-25df-4fcd-a4a4-f68c9656fbe2/v

A11Y validations use the aXe engine, you can install it as a Chrome extension to check each page:

http://www.deque.com/products/axe/

Also, some broken links found:

https://rocketvalidator.com/s/8b035c18-0680-4f8d-a13c-35239729c91e/i/2008645

**Comment by kikito** [comment]
Thanks jaime!

**Comment by decabeza** [comment]
Hi @jaimeiniesta! 

Thanks for the review! :+1:

There are a lot of issues for `https://decide.madrid.es/blog` (redirect to https://diario.madrid.es) and some on `https://decide.madrid.es/users/auth/twitter` (redirect to https://api.twitter.com) and `https://decide.madrid.es/users/auth/facebook` (redirect to https://www.facebook.com/dialog/oauth)

These websites doesn't belong to consul repository and are out of our control :(

The rest of issues should have been solved on: https://github.com/consul/consul/pull/1432 and https://github.com/AyuntamientoMadrid/consul/pull/692

Please, if you can review again ;)

**Comment by jaimeiniesta** [comment]
Nice @decabeza !

Here's another pass of the validator: https://rocketvalidator.com/s/a236d403-7f3c-41ea-a80f-f50576a5fa76/p

If you want to specify the exact pages to validate (and therefore exclude the ones that redirect out of the site and are out of your control), we can submit an XML sitemap containing the URLs to validate. If we use this one, and specify the pages to include, then our web crawler won't end up somewhere else. Let me know if you have an XML sitemap and I'll run the tests!

**Comment by jaimeiniesta** [comment]
Hey there! I've made the scraper more strict about the web pages to include, and now it will only consider the ones within the same subdomain. Here goes a more focused report :)

https://rocketvalidator.com/s/21f9748e-e31b-424d-8f91-79fe0ef5f2a8/v

**Comment by decabeza** [comment]
Thanks again @jaimeiniesta!

Sometimes I see this issue `Data tables should be marked up properly`:

![tables](https://cloud.githubusercontent.com/assets/631897/23912106/073e155c-08df-11e7-99a1-6d8d9e6d4fff.png)
For example on https://decide.madrid.es/budgets/meetings/2016

I don´t know why is an error... maybe **the scope attribute** is mandatory on `<th>` tags?

**Comment by jaimeiniesta** [comment]
If you hover over the errors, a HELP link appears with an in-depth explanation, in this case:

https://dequeuniversity.com/rules/axe/1.1/data-table?ref=rocketvalidator

![captura de pantalla 2017-03-14 18 24 35](https://cloud.githubusercontent.com/assets/2629/23913497/7df147c4-08e3-11e7-8f74-65e5bcf123de.png)

**Comment by jaimeiniesta** [comment]
I've added Decide Madrid to the sites that Rocket will monitor weekly for accessibility and HTML issues:

https://rocketvalidator.com/opensource

You can also head directly to https://rocketvalidator.com/opensource/decide-madrid/p to be redirected to the latest validation run :)

**Comment by jaimeiniesta** [comment]
I've added a PR to add badges on the README that show the accessibility and HTML issues. You can see a working example here:

https://github.com/consul/consul/pull/1454

**Comment by decabeza** [comment]
Thanks again! 👍 

Can you ignore this urls in the report? (this urls redirect out of our website) 😉 

- https://decide.madrid.es/blog  
- https://decide.madrid.es/users/auth/facebook 
- https://decide.madrid.es/users/auth/twitter

**Comment by xuanxu** [comment]
All this thread belongs to [AyuntamientoMadrid/consul](https://github.com/ayuntamientomadrid/consul), not here

**Comment by decabeza** [comment]
This issue continue on correct repo: https://github.com/AyuntamientoMadrid/consul/issues/725
