### ISSUE TITLE
Add a new method to order budget investments

### ISSUE THREAD

**Issue by Almorca** [consul/consul#1436]
Actually the proposals can not be ordered and If I want to review all of them I need to do in the same day. If I only review some proposals in a day the next day I can not continue by the point that I finish the day before because the proposals always are show aleatory.

--

Sugiero añadir un método de ordenación para las propuestas que sea repetible. Ya que ahora mismo si entras un día y revisas unas pocas propuestas al día siguiente no puedes continuar por donde te quedaste ya que se vuelven a ordenar de manera aleatoria.

**Comment by decabeza** [comment]
Hi @Almorca!

Maybe use the **Advanced search** option can help you (you can filter proposals by a customized date) 😉

![advanced_search](https://cloud.githubusercontent.com/assets/631897/23762833/a2373232-04f7-11e7-9002-f2932114e27b.png)

**Comment by Almorca** [comment]
This is exactly that I need but in decide.madrid I only can use this with proposals and not with Budgets

**Comment by MariaCheca** [comment]
Closed here: https://github.com/consul/consul/pull/2142
