### ISSUE TITLE
Add references to decide.es in READMEs

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1449]
Add links to http://www.decide.es/es/ and http://www.decide.es/en/ in the corresponding READMEs

**Comment by divyanshumehta** [comment]
hi @voodoorai2000  I would like to work on this issue.

**Comment by voodoorai2000** [comment]
Great @divyanshumehta! Please go ahead 😊

**Comment by divyanshumehta** [comment]
@voodoorai2000 I got it the references need to be added in `README.md` and `README_ES.md` in the root of the repository, could you say what does this reference tells I users about. I think these references tell about the features of CONSUL and its current use of this can be added near ```You can take a look at the current features in the docs and future features in the open issues list.```  that is line no 22

**Comment by voodoorai2000** [comment]
Any of those two would be fine, up to you @divyanshumehta 👍

**Comment by divyanshumehta** [comment]
@voodoorai2000 adding it to the current state line22 and opening a PR :smile:
