### ISSUE TITLE
support Right to left languages (Arabic,Hebrew , etc ..)

### ISSUE THREAD

**Issue by iamnotgroot2** [consul/consul#1450]
what is the best way to implement Right To left Alignment for the entire App (to support Arabic and Hebrew)? 

in: 
app/assets/stylesheets/_settings.scss
I changed the foundation global to: 
$global-text-direction: rtl;
this does re-arange the main modules on the page to align Right To left,
though all the texts and iner view components are still aligned LTR.

is there some similar global for the the Views ? 
or do I have to redesign and implement the appropriate CSS changed for each and every View.

thanks !!

**Comment by iamnotgroot2** [comment]
foundation allows for Right to left support : 
http://foundation.zurb.com/sites/docs/rtl.html

**Comment by gildvir** [comment]
Hi,
need some help on Right to Left the site.
Can you point me to the place where it is possible to do?
