### ISSUE TITLE
Conexión padrón para verificación usuarios

### ISSUE THREAD

**Issue by sergiochtf** [consul/consul#1461]
Buenas tardes,

¿Podrían darme información técnica sobre como conectar con el padrón municipal desde consul? Como se configura la verificación en la herramienta.

Gracias.

**Comment by taitus** [comment]
Hola @sergiochtf 

Primero de todo perdir disculplas por la demora de la respuesta 🙏 

En cuanto a tu pregunta, actualmente existe una sección de la documentación donde se explica cómo configurar la conexión con el Censo Remoto (https://docs.consulproject.org/docs/spanish-documentation/features/census_configuration#configuracion).

Saludos!

**Comment by javierm** [comment]
@sergiochtf Reitero las disculpas por tardar ni más ni menos que dos años y medio en contestar :pray:.

Espero que con la respuesta se haya contestado a la pregunta. De no ser así, no hay problema en que vuelvas a abrir esta incidencia.
