### ISSUE TITLE
Add rake task to update per page code

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1472]
To solve accessibility issues we have split the Setting's variable per_page_code into per_page_code_head and per_page_code_body.

We should add a rake task to migrate the data from per_page_code to per_page_code_head

**Comment by bertocq** [comment]
I'm not 100% sure about the tasks to be done, does it mean modifying all files with pattern `locales/settings.**.yml`? There is no `per_page_code` in the codebase. I think the context I'm missing is how Settings work.

**Comment by bertocq** [comment]
Okey after a week in this codebase I've learned enough to be able to understand this issue :D. Doing it in a few!

**Comment by bertocq** [comment]
Github is funky today.. but I got the PR created anyway :D https://github.com/consul/consul/pull/1584
