### ISSUE TITLE
how to Enable Voting on Supported Proposals

### ISSUE THREAD

**Issue by iamnotgroot2** [consul/consul#1477]
hello Consul Community,
I am new to Consul, so maybe this is a redundant question but 
I noticed that proposals that  have passed the required support threshold, for voting pass to 'voting' tab, but there is no way to actually vote on them  (even by a verified user)
does the platform support voting on the proposals who passed the support threshold, or does voting occur  outside the platform ... 
if the feature does exist  - how do I enable voting on supported proposals ?
thanks !

**Comment by voodoorai2000** [comment]
Hello @iamnotgroot2 !

Proposals that have reached the required support threshold go to a voting system to vote in favor or against that proposal. Check out this issue for more info: https://github.com/consul/consul/issues/1264
