### ISSUE TITLE
Add Administrators menu on admin panel

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1501]
We need add a new section on `Admin > Profiles > Administrators` to allow searching for an existing user and mark/unmark the user as an administrator.

![administrators](https://cloud.githubusercontent.com/assets/631897/25428532/7062fa76-2a76-11e7-8a01-bc9efec4e818.png)

**Comment by bertocq** [comment]
I'm on to this one too!

**Comment by decabeza** [comment]
Closed by #1560

**Comment by KrzysztofMadejski** [comment]
I still can't find an option to add a given user Administrator / Moderator / other role... Wasn't this implemented?

CC: @WojtekSanko

**Comment by decabeza** [comment]
Hi @KrzysztofMadejski on admin section `/admin` navigate to `Admin > Profiles` there are some subsections where you can find any registered user and assign a new role 😌 

![screen shot 2018-07-25 at 12 16 29](https://user-images.githubusercontent.com/631897/43195232-af393dec-9004-11e8-8f2a-673c7e785870.png)

![screen shot 2018-07-25 at 12 18 20](https://user-images.githubusercontent.com/631897/43195273-d760bd4a-9004-11e8-99f7-10efc544f6ba.png)

**Comment by aitbw** [comment]
To keep track of this: Whitespace trimming is fixed via #2161 but hasn't been merged into `master` yet, @KrzysztofMadejski

**Comment by decabeza** [comment]
Thanks @KrzysztofMadejski I take note of your suggestions, we continue to work continuously to improve the admin panel ☺️
