### ISSUE TITLE
Discussion thread merge feature

### ISSUE THREAD

**Issue by mfidemraizer** [consul/consul#1502]
Hi! I'm participating on [Plaza Podemos 2.0](https://plaza.podemos.info) and some other participant [has requested a new feature.](https://plaza.podemos.info/debates/5183) I would summarize it as follows:

- Moderation tools should provide a feature to merge threads. 
- Merge would be finished unless authors of the affected threads would deny the whole process. 
- Merge process would be also started by the authors of affected threads.

Also, I'd like to add some additional requirement:

- As sometimes the original authors mightn't be available to review merge requests, I wouldn't involve them at all. I would implement merge votes. For example, if 5 users have voted to merge them, the whole threads would be merged. 

BTW, that merge process could never be automatic, since it would produce bad results. Hence, I find that there should be another requirement:

- Collaborative merge editor.
- Approval workflow: once the merge is ready to be committed, I'd implement the approval vote process in the same way as the voting system to start a thread merge workflow.

Thank you ;)

**Comment by voodoorai2000** [comment]
Hello @mfidemraizer !

Thank you very much for this feature request, it sounds great!
However it is a very delicate feature to implement...

Our main concern is regarding the existent votes for those proposals.
There are probably small differences between merged proposals. Some users might not be happy to see their vote included after a merge.

We now have a feature where the author can remove a proposal. For example, due the proposal being a duplicate.

Also during the creation of a proposal, we suggest existent proposals that have similar content.

Finally we are creating a collaborative editor of proposals, where multiple users can get involved in the content of a proposal until it's finally ready.

Hopefully these should slowly reduce the problems introduced by duplicate/similar proposals.

In any case, feel free to implement this feature for your fork and let us know how it works.
We are always open to discussions and improvements!

Cheers!

**Comment by mfidemraizer** [comment]
I see. Well, sadly I've no enough time to implement a feature right now, but thank you for your effort to answer the requirement :)
