### ISSUE TITLE
Update english documentation for available features

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1510]
We have updated[1] the spanish documentation regarding available functionalities, we should add the equivalent english documentation.

[1] https://github.com/consul/consul/pull/1507

**Comment by devinbalkind** [comment]
Hi. I'm an English language user exploring the features of this system for a civic project in the US. More English documentation would be great. I'd be happy to add translation as I go through the system. Not exactly sure I can do that.

Also... how do "Replace with your City Map". I tried create a district and added coordinates but that didn't change anything.

Thanks so much for this very interesting software.

**Comment by voodoorai2000** [comment]
Hi @devinbalkind !

Thank you very much!

That would be very much appreciated it!
Please let us know if you run into any problems :)

And keep us posted on your conclusions please!

Regarding the map, we use the [usemap](https://www.w3schools.com/tags/att_img_usemap.asp) html attribute. [Here](https://decide.madrid.es/proposals/map?locale=en) is a sample implementation for Madrid. 

Hope it helps!

Cheers!

**Comment by devinbalkind** [comment]
Hi. Thanks for the response.

I created the usemap code using this tool:

I then took the coordinated it generated and pasted them into the "Coordinates" column of the Geozone section.

But where do I upload the map image that the coordinates are referencing?

Thanks for your help!

**Comment by decabeza** [comment]
Hi @devinbalkind sorry for the late response, maybe you refer to map image on `app/assets/images/map.jpg` 😉 

Close this one because we have a new repository for [Consul Documentation](https://github.com/consul/docs) (still on progress but we keep working on it!) 🎉

**Comment by devinbalkind** [comment]
Thanks. Great docs. Much clearer.
