### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by virgile-dev** [consul/consul#1531]
Hey guys, 

With Hugo and Valentin, we worked on participatory budget in Paris : https://budget-participatif.rivp.fr.

We translated a big part of the application we would like to complete a full translation of the app in order to send over a pull request. 

On the process, we are thinking of translating each file in this folder : https://github.com/consul/consul/tree/master/config/locales. 

Also like the folks at Decidim, we could use Crowdin ([crowdin.com](https://crowdin.com/)) to make the translation process a little easier.  

Thanks a lot in advance for your help

**Comment by virgile-dev** [comment]
Petter Joelson heard that you can get a Crowdin free account for non profits on Transifex if that's relevant for you guys.

**Comment by voodoorai2000** [comment]
Hey @virgile-dev ! 

Sure we are open to using any translation service, 
if it's open source and free for non profits it would be ideal!

At the moment we have been using Tolk, it's very minimalistic but it's worked great so far :)
However we are trying out Transifex and Crowdin.

Thank you guys for your help spreading Consul in France and always giving good advice to improve :)

**Comment by olivierstern** [comment]
At your disposal if you need any help translating the files

**Comment by CivicTechFR** [comment]
@olivierstern you ask @voodoorai2000 to add you to transifex :)  https://www.transifex.com/consul

**Comment by hugobarthelemy** [comment]
@voodoorai2000 , can you also add me to Transifex please?

**Comment by olivierstern** [comment]
@voodoorai2000 you still need to aproove my request on transifex I believe

**Comment by voodoorai2000** [comment]
@hugobarthelemy invitation sent!
Approved @olivierstern :)
Thank you for your help!

**Comment by olivierstern** [comment]
@voodoorai2000 is there a way to see the file context of the string beeing translated in Transifex to avoid ambiguous meaning ? For instance "Comment" can be a verb or a noun depending on the context.
Thank you.

**Comment by voodoorai2000** [comment]
Closed via #1718

**Comment by voodoorai2000** [comment]
@olivierstern yes there is https://crowdin.com/page/in-context-localization
We'll set it up soon :)
