### ISSUE TITLE
Long string of coordinates pushed Edit/Delete buttons out of view on Geozone Admin page

### ISSUE THREAD

**Issue by devinbalkind** [consul/consul#1558]
Long string of coordinates pushed Edit/Delete buttons out of view.

See two attached images.

![33zoom](https://cloud.githubusercontent.com/assets/444311/26372437/fac79c3e-3fcb-11e7-9244-914e11a1a104.png)
![100zoom](https://cloud.githubusercontent.com/assets/444311/26372436/fab28ef2-3fcb-11e7-9902-7fe1a0de6db1.png)

**Comment by decabeza** [comment]
@devinbalkind already fixed in `master` branch 😉
