### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_sysopen - ):

### ISSUE THREAD

**Issue by jainfante** [consul/consul#1563]
Probably is something very silly, but I cant find it. This error happens when i try to verify a user, so he can vote a proposal, etc.  In the web all I see is a 500 error. 

Looking for a solution, i found that this kind of error is about not finding a file or not having enough rights to do something with a file or folder. I verified that, permissions are not an issue. But in the examples, after the @rb_sysopen, you can see which file/folder is causing the problem. In my case I have no clue what file/folder is because all I have is a space.  I introduce proper data to do the test so dont understand what is happening.

This is the full log I can see in production.log.

> I, [2017-05-24T13:52:15.869751 #3240]  INFO -- : Started POST "/residence" for X.X.X.X at 2017-05-24 13:52:15 +0200
> I, [2017-05-24T13:52:15.872435 #3240]  INFO -- : Processing by Verification::ResidenceController#create as HTML
> I, [2017-05-24T13:52:15.872519 #3240]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"QV75mcSJV/nrJOlnVf+V3Dpx0G5ZbEplmuU3VY+eHqtWanXcuzFTEU0D4xD7FcGZ77FqzJoXmCaM8ka7UVnwHw==", "residence"=>{"document_type"=>"1", "document_number"=>"71343923Q", "date_of_birth(3i)"=>"23", "date_of_birth(2i)"=>"1", "date_of_birth(1i)"=>"1981", "postal_code"=>"09007", "terms_of_service"=>"1"}, "commit"=>"Verificar residencia"}
> D, [2017-05-24T13:52:15.874369 #3240] DEBUG -- :   [1m[36mUser Load (0.4ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."hidden_at" IS NULL AND "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1[0m  [["id", 64]]
> D, [2017-05-24T13:52:15.877405 #3240] DEBUG -- :   [1m[35mLock Load (0.4ms)[0m  SELECT  "locks".* FROM "locks" WHERE "locks"."user_id" = 64 LIMIT 1
> I, [2017-05-24T13:52:15.879109 #3240]  INFO -- : Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.8ms)
> D, [2017-05-24T13:52:15.879789 #3240] DEBUG -- : [Rollbar] Reporting exception: No such file or directory @ rb_sysopen - 
> I, [2017-05-24T13:52:15.899651 #3240]  INFO -- : [Rollbar] Scheduling item
> I, [2017-05-24T13:52:15.899753 #3240]  INFO -- : [Rollbar] Sending item
> W, [2017-05-24T13:52:16.328316 #3240]  WARN -- : [Rollbar] Got unexpected status code from Rollbar api: 400
> I, [2017-05-24T13:52:16.328419 #3240]  INFO -- : [Rollbar] Response: {
>   "err": 1,
>   "message": "access token required"
> }
> I, [2017-05-24T13:52:16.328468 #3240]  INFO -- : [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=478c2566-6ab6-446c-afb1-8001ec138998 (only available if report was successful)
> D, [2017-05-24T13:52:16.328520 #3240] DEBUG -- : [Rollbar] Exception uuid saved in env: 478c2566-6ab6-446c-afb1-8001ec138998
> F, [2017-05-24T13:52:16.329937 #3240] FATAL -- : 
> Errno::ENOENT (No such file or directory @ rb_sysopen - ):
>   lib/census_api.rb:61:in `get_response_body'
>   lib/census_api.rb:7:in `block in call'
>   lib/census_api.rb:6:in `each'
>   lib/census_api.rb:6:in `call'
>   app/models/verification/residence.rb:74:in `call_census_api'
>   app/models/verification/residence.rb:28:in `save'
>   app/controllers/verification/residence_controller.rb:13:in `create'

Thans for the help and regards.

**Comment by bertocq** [comment]
I think it could be because you don't have a correct `Rails.application.secrets.census_api_end_point` value? I suspect https://github.com/consul/consul/blob/32767a08ce39fbeb584ce6193bfca81a4690aeaa/lib/census_api.rb#L68 could be throwing that error while trying to load the wsdl file... but its just a lucky/blindly guess :)

**Comment by jainfante** [comment]
You were right, it was a bad configuration with the values in secrets.yml.

Thanks for the help and kind regards.

**Comment by bertocq** [comment]
No problem @jainfante happy to be helpful ^_^. I'm always paranoid about most basic assumptions when chasing a bug, and sometimes that its the fastest clue to the error.
