### ISSUE TITLE
Allow Telegram Share on desktop

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1577]
## What
I saw on the code that Telegram & Whatsapp share icons are hidden when not in mobile size
https://github.com/consul/consul/commit/15a9198b0f5a0a97db8d64c9c992ef25f8151a40

But Telegram can be used on a Desktop or iPad or other screen sizes. I personally use the macos client, but there is as well a web native option as well as a Windows/Linux native client.

For example https://telegram.me/share/url?url=https://diario.madrid.es/decidemadrid/2017/05/26/haz-tus-aportaciones-para-el-futuro-registro-obligatorio-de-lobbies-del-ayuntamiento-de-madrid/ would in my case open the macos client to share while I'm at my laptop.

Anyway I guess it's a product decission, and I'm lacking for sure some context & reasons behind it.

## How
I guess just reverting https://github.com/consul/consul/commit/15a9198b0f5a0a97db8d64c9c992ef25f8151a40 would be enough

**Comment by decabeza** [comment]
This is totally a product decision. We think Telegram and WhatsApp are apps more used on mobile devices than desktop versions.👌 

If any fork wants show Telegram (and/or WhatsApp) icons on desktop sizes only have to make two minor changes:

- Delete this block on `stylesheets/layout.scss:1443`:
```css
@include breakpoint(medium) {

  .button.button-telegram,
  .ssb-telegram {
    display: none !important;
  }
}
```

- Delete `class="show-for-small-only"` on whatsapp link on `shared/_social_share.html.erb` partial.

Maybe in a future we can add a setting on admin panel to configure easily what social apps shown on mobile/desktop versions.

**Comment by javierm** [comment]
Since @decabeza stated this is done on purpose, I'm closing this issue.

**Comment by lmsalgado** [comment]
Hi, I have the same problem and would like desktop users to be able to share on Telegram and WhatsApp. 
But The proposed solution is no longer valid since neither shared/_social_share.html.erb nor stylesheets/layout.scss no longer have those blocks of code.

I tried to change spec\system\proposals_spec.rb  from line 132, that distinguishes social-share-buttons to be presented on desktop or on mobile (I copied the content of mobile scenario to desktop scenario) but it made no difference.

What can I do?

**Comment by javierm** [comment]
Hi, @lmsalgado :smile:.

You're right, we moved the SCSS file to a different place. These styles are now defined in `app/assets/stylesheets/shared/social_share.scss`. Modifying `app/views/shared/_social_share.html.erb` is no longer necessary :tada:.

The spec folder contains tests that check that the application is properly working and their main purpose is to notify us when we accidentally break something during development. Changing the tests does not affect what the application actually does.

In case it helps, you can have a look at the [customization documentation](https://docs.consuldemocracy.org/tech_docs/customization). For this particular case, check the [Styles with CSS](https://docs.consuldemocracy.org/tech_docs/customization/css) section. Feedback about the documentation is welcome!

**Comment by lmsalgado** [comment]
Ho @javierm, thanks for the fast answer.
I removed the following block from app/assets/stylesheets/shared/social_share.scss, but I'm afraid it still doesn't make a difference, the icons are still not there on desktop.

```
@include breakpoint(medium) {
  .ssb-telegram,
  .ssb-whatsapp_app {
    display: none !important;
  }
}
```

**Comment by lmsalgado** [comment]
Hi @javierm 
Production environment. No capistrano, I am editing the source code and rebooting to make sure it applies everything. 
I doubt it is some cache thing, all other cosmetic changes where applied without issues, including hiding Twitter (which does not exist anymore by that name). I'm guessing there's more code on this somewhere else.
Anyway, this is not a very important feature for us, I just thought it would be easy, If it is taking to much time from you just forget it. Thank you very much!!

**Comment by javierm** [comment]
Hi, @lmsalgado :smile:.

I'm afraid that won't work 🤔. On production environments, SCSS and JavaScript files need to be precompiled after every change.

You could theoretically do the change on the production server and compile the assets, but I **strongly** recommend against that approach, for a couple of reasons.

First, that would go against the license of the software 😅, which states that any change in the code must be publicly available to everyone who can visit the page. If you manually change the code on the server, people visiting the website won't be able to make a copy of the software that includes your modifications.

And, second, doing these changes manually would become a maintenance nightmare really quickly. Things like "the changes to these styles don't take effect" are only the tip of the iceberg 😌.

For both reasons, I'd suggest that you [configure a development environment](https://docs.consuldemocracy.org/tech_docs/introduction/local_installation), upload your changes to a publicly available git repository, and then use capistrano to deploy your changes to production.
