### ISSUE TITLE
Add summary field

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1586]
In the admin section, it should be possible to add a summary for every legislation. 
This summary should substitute the first line of the legislation's description which is currently being displayed.
![legislation description](https://cloud.githubusercontent.com/assets/4169/26720414/758ab01e-4788-11e7-8812-299cf7375871.png)

**Comment by bertocq** [comment]
Can do! PR incoming

**Comment by bertocq** [comment]
Curious to see on the admin Legislation Process controller both description and target summary fields on the params, but that's the only mention on the entire app. https://github.com/consul/consul/blob/medialab-legislation/app/controllers/admin/legislation/processes_controller.rb#L38-L39

I guess it was something planned but never finished
