### ISSUE TITLE
Remove "target" and "how to participate" fields

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1587]
In the admin section of a legislation, remove fields "Target" and "How to participate".
In the user facing interface, increase the size of the remaining field "Description" to fill the space left after removing these other fields
![remove legislation fields](https://cloud.githubusercontent.com/assets/4169/26720493/cf32f6bc-4788-11e7-8f4b-a00a67aaa4ac.png)

Please send PR against the [medialab-legislation branch](https://github.com/consul/consul/compare/medialab-legislation?expand=1)

**Comment by decabeza** [comment]
I think it's better make "target" and "how to participate" optional fields instead of remove them.

And changing the size depending of how many blocks are visible. 😉

**Comment by voodoorai2000** [comment]
+1 👍

**Comment by bertocq** [comment]
I'm into this one. As talked with @voodoorai2000 better to completely remove both target and how to participate fields on both admin and front

**Comment by bertocq** [comment]
@voodoorai2000 should we close this issue?

**Comment by voodoorai2000** [comment]
Yes :)
