### ISSUE TITLE
Display only active dates

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1588]
In the list of processes, display for each process only the dates of the parts of the process that are marked as active.

User interface:
![legislation dates](https://cloud.githubusercontent.com/assets/4169/26720569/188bade0-4789-11e7-8b00-cf119bfcb098.png)

Admin section:
![active dates](https://cloud.githubusercontent.com/assets/4169/26720576/1ce243ea-4789-11e7-9336-8849827f3559.png)

**Comment by bertocq** [comment]
@voodoorai2000 either I don't get the specs or I see this working:

![screen shot 2017-06-02 at 17 44 56](https://cloud.githubusercontent.com/assets/983242/26733496/4972865e-47bb-11e7-814e-81398a63f051.jpg)
![screen shot 2017-06-02 at 17 45 07](https://cloud.githubusercontent.com/assets/983242/26733497/4975c544-47bb-11e7-9f86-14960c7d1a48.jpg)
![screen shot 2017-06-02 at 17 45 15](https://cloud.githubusercontent.com/assets/983242/26733495/497267dc-47bb-11e7-9e53-dbce16997f83.jpg)

Do you mean that the blocks like "Draft publication" or "Allegations" shouldn't even be shown? Dates are being already hidden when not active.

**Comment by bertocq** [comment]
BTW Not sure if bug or feature, but after clicking the "Active" button on the admin panel to disable a process, the dates are removed, and clicking again to enable
