### ISSUE TITLE
Display comments by default

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1590]
In the draft view, the default behaviour is to have comments hidden the table of contents displayed.
Switch this behaviour around and by default display the comment's area and hide the table of contents
![default comments](https://cloud.githubusercontent.com/assets/4169/26720684/7adc21dc-4789-11e7-816a-95a809a6125a.png)

Please send PR against the [medialab-legislation branch](https://github.com/consul/consul/compare/medialab-legislation?expand=1)

**Comment by bertocq** [comment]
Closed via #1671
