### ISSUE TITLE
Limit records and depth of query

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1591]
Add reasonable defaults to avoid timeouts when querying for large data sets

**Comment by voodoorai2000** [comment]
@amiedes is polishing this one

**Comment by amiedes** [comment]
Hey @voodoorai2000, this was already done in [this commit](https://github.com/consul/consul/pull/1257/commits/18db68a4305cd07b68476a7ca4f0346a70673c0f).

**Comment by voodoorai2000** [comment]
Awesome ;)
