### ISSUE TITLE
Incompatible investments

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1594]
### What
Allow admins to mark investments as incompatible and display incompatibles investments in the budget's results page.

Once an investment has been marked as incompatible, automatically recalculate [winners](https://github.com/consul/consul/pull/1555/files#diff-152c45b655078e6bccdda7600adfbfeaR11)

### Why
Some investments become incompatible, even though they have many votes, due to other investments having more votes and implying the same idea.

### Screenshots
![incompatible investments](https://user-images.githubusercontent.com/4169/27130903-a0bc56d2-5108-11e7-94d7-3c014e114b73.png)

### How

Implemented in this [PR](https://github.com/AyuntamientoMadrid/consul/pull/299) for Madrid's fork
Note that spending_proposals are deprecated and have been substituted by budget_investments. This feature is only meant for budget_investments.

**Comment by bertocq** [comment]
I understand this is just a "cherry-pick" job, right?

**Comment by voodoorai2000** [comment]
Yes, also that PR was meant for _spending proposals_. In Consul now _spending_proposals_ are obsolete and have been substituted for a cleaner implementation of _budget_investments_. This feature is only meant for _budget_investments_

**Comment by bertocq** [comment]
Makes sense to allow only on the "Balloting finished" and "Finished" phases... although it could be done at any time in the Bugdet life process.

**Comment by bertocq** [comment]
Ok, I think I'm going with:
1. Add a boolean "incompatible" column on budget_investments table
2. Add a scope "compatibles" to Budget::Investment
3. Add the "compatibles" scope to Budget::Result#calculate_winners at https://github.com/AyuntamientoMadrid/consul/blob/master/app/models/budget/result.rb#L21
4. Adding a checkbox on the investment edit page (only for admins). And checking on model save if the value has changed on to "true", if so... we'll recalculate the winners for the investment's Heading:`Budget::Result.new(budget, heading).calculate_winners`
5. Removing the "Valuators" column from the Admin's Budget Investments list, and adding an 
 "Incompatible" one in between the "Selected" and "Winner" ones. I think table should reflect important info and status... not massive data.
6. Adding a "Incompatible" filter on the Admin's Budget Investments list. A "Compatible" filter doesn't make much sense to me... but it could be a nice improvement to have a double filter.
7. Adding Incompatible list at the bottom of the Budget Results list

**Comment by voodoorai2000** [comment]
Sounds perfect 👌

**Comment by voodoorai2000** [comment]
🎉
