### ISSUE TITLE
Reorganize admin stats

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1596]
The admin stats' section has grown organically and it's currently a little messy and slow.
Reorganize it into meaningful smaller sections

![stats](https://cloud.githubusercontent.com/assets/4169/26722555/c33c00e4-4790-11e7-9d70-d0a9f1f81bb3.png)

**Comment by decabeza** [comment]
This issue is a little ambiguos and maybe outdated. 

We work continuously on improve admin section. We will create a new issue with better specifications to improve this section.

😌
