### ISSUE TITLE
Add toolbar and link 'Back' in the panel "Management"

### ISSUE THREAD

**Issue by sergiochtf** [consul/consul#1614]
Add the toolbar of roles and the link to back in the panel Management. I attach a image.

**Comment by sergiochtf** [comment]
![1](https://cloud.githubusercontent.com/assets/9718722/26828186/34156682-4ab8-11e7-9f46-8c3981504c75.png)

**Comment by xuanxu** [comment]
Management is a special interface used by people in offices in contact with the public, they are not admins and their interface is not meant to be accessed from/to the normal user interface. There is no need for managers to access pages such "My activity" or "My account".
That is why there is no links in their menu bar.

**Comment by voodoorai2000** [comment]
How about displaying the link only if the user has admin rights? 
It's true that admins can reach this section and it's a little confusing to see that link disappear.

**Comment by iagirre** [comment]
I'll do this.
