### ISSUE TITLE
Improve investment's filters

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1624]
Background
===

The admin interface to filter investments has grown organically and it's a little confusing to find what you are looking for. 

What we need
===
 
Reorganize the available filters to find any combination of investments.

Show filters by (currently working):
- **Administrator**
- **Valuator**
- **Heading**
- **Tags**

Adds an **"Advanced filters"** link with the following status:
- **Feasible**: _finished evaluation_ with feasibility = feasible.
- **Visible to valuators**: _in evaluation_ with active checkbox of "Show to valuator"
- **Selected**: those with active checkbox "Selected" (with selected == true)
- **Undecided**
- **Unfeasible**
- **Max supports per heading**: this filter is already done on [Madrid's fork](https://github.com/AyuntamientoMadrid/consul/blob/master/app/models/budget/investment.rb#L102)

And tabs with these **status**:
- **All**: all investment projects.
- **Without assigned admin**: projects without an assigned admin.
- **Without assigned valuator**: projects without an assigned valuator.
- **Under valuation**: admin and valuator assigned.
- **Valuation finished**: with active checkbox "Valuation finished"

Also, include this **changes**:

- Change table heading "Selection" to "Selected"

To consider:

- The tags should be "reset" to any budget (check this is working correctly)
- The investments should be ordered by supports and created at (last first) when there are still no supports.

🗒 On each of this tab/status, we have to include a line of help text to explain the current filter selected. 

Screenshot
===
![advanced_filters](https://user-images.githubusercontent.com/631897/34821695-e61dfbec-f6c4-11e7-9f33-342f1df066b7.jpg)

**Comment by aitbw** [comment]
Is this one ready to go?

**Comment by bertocq** [comment]
Sure @aitbw go for it 👏  :)

**Comment by rzido** [comment]
I miss in the screenshot a free text search option (search proposals with some text inside title or description) and option for admins to order results list by some or all fields.

**Comment by decabeza** [comment]
Hi, @rzido thanks for the suggestions! I just created a new issue https://github.com/consul/consul/issues/2336 with that 😉
