### ISSUE TITLE
Investment's CSV Exporter

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1625]
In Public Institutions it's common to use excel files to share work in progress.
In the transition to substitute excel files for web interfaces these type of files are still useful.

Add a csv generation of the current selection in the admin investment's section.

**Comment by rfuentesm2c** [comment]
I'll take this one. :)

**Comment by rfuentesm2c** [comment]
maybe we can use https://github.com/randym/axlsx to export directly in xlsx

**Comment by bertocq** [comment]
Closed by #1106
