### ISSUE TITLE
Improves admin banners section

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1626]
During a Participatory Budget some users get confused and create Citizen Proposals instead of Investments.

Ponder on how to make clear the process of creating an investment.

**Comment by decabeza** [comment]
After of a usability report for Decide Madrid (Madrid's fork) it's an error think the user is confused when create a proposal or a budget investment.

The main error (last year) was the name: "Proposal" vs "Spending proposal", the word **proposal** on both options was very confuse. **This is in part already solved**, now the terms are "Proposal" vs. "Budget investment" are easier to differenced.

I think, a good solution to empower this difference would be improve the "Admin banners" section to have a more aggressive impact on the advertising of participatory budgets.

We can include more settings:

- Dates to show/hide
- Title
- Text
- Link to
- Background and text color for banner (Hex value) `new`
- Sections where this banners would be appear `new`

Something like this:

<img width="920" alt="new_admin_banner" src="https://user-images.githubusercontent.com/631897/29324074-2c1ba97a-81e3-11e7-8107-3537552999c6.png">


By the other hand also we have to consider the importance of external elements: paid marketing campaigns, tv/online spots, SEO, SEM, street signs... etc. That don't belong to CONSUL.

**Comment by iagirre** [comment]
I'll do this
