### ISSUE TITLE
Add Roadmap to READMEs

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1627]
We are trying to organize and inform better about the upcoming features.

Add the [Roadmap](https://github.com/consul/consul/projects/6) to the spanish and english READMEs

**Comment by divyanshumehta** [comment]
@voodoorai2000 just a link to the Roadmap page would be sufficient?

**Comment by voodoorai2000** [comment]
@divyanshumehta sure, just a link would be great :)
