### ISSUE TITLE
Dynamically generated routes warnings

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1630]
A list of warnings is available at [code climate critical warnings](https://codeclimate.com/github/consul/consul/issues?severity=critical).

The original list of warnings is not avaialalbe since Gemnasium was acquired by GitLab.

**Comment by bertocq** [comment]
@voodoorai2000 do you refer the brakeman report from gemnasium https://gemnasium.com/github.com/consul/consul/report_runs/246887 and the many `Possible unprotected redirect near line` warnings?

**Comment by voodoorai2000** [comment]
Yes @bertocq :)

**Comment by bertocq** [comment]
Ok a list of the redirect issues can be directly found here :) 
https://codeclimate.com/github/consul/consul/issues?severity=critical

**Comment by zamuro** [comment]
I'll take this one

**Comment by tyrantdavis** [comment]
Is this issue still open? I would like to take this one if so.

Thank you

**Comment by MariaCheca** [comment]
@tyrantdavis feel free to take it! All contributions are welcome!

**Comment by aamarill** [comment]
Hello @tyrantdavis ! Are you still working on this? 😄

**Comment by tyrantdavis** [comment]
Hi Adan. Yes I am. Thanks for asking.

**Comment by cartothemax** [comment]
Hello! I see this is marked as "help wanted" Gemnasium is no longer offered as a stand alone service since being acquired by GitLab. Is there a good replacement? Or does the project still wish to move forward with Gemnasium?

To continue with Gemnasium would involve creating a [CI/CD pipeline using GitLab](https://about.gitlab.com/solutions/github/) and require [migration](https://docs.gitlab.com/ee/user/project/import/gemnasium.html#migrating-to-gitlab) as well.

Thanks!

**Comment by javierm** [comment]
@cartothemax Thank you very much for reporting! :smile: I've updated the title and description of this issue.

**Comment by cartothemax** [comment]
@javierm good deal! Thanks for updating. I will take a look if that's alright? Looks like the issue has been left for a little bit.

**Comment by javierm** [comment]
@cartothemax Sure! Go ahead :smile:.

**Comment by cartothemax** [comment]
Started to work on these warnings here -> https://github.com/cartothemax/consul/tree/address-brakeman-warnings

**Comment by javierm** [comment]
@cartothemax Cool! Feel free to open a pull request with the changes. You can prefix it with [WIP] if it isn't ready for review yet :wink:.

**Comment by cartothemax** [comment]
Won't be able to get this addressed. I don't have the time to take care of all of the failing test scenarios

**Comment by javierm** [comment]
@cartothemax Thank you for telling us! And thank you so much for working on this issue! :smile: If there are any obstacles you found while working on the pull request, it would be great if you write them down in the notes section of your pull request :pray:; maybe that could help us in the future! :wink:
