### ISSUE TITLE
Absolute URL on pagination

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1644]
**consul** use [kaminari gem](https://github.com/kaminari/kaminari) to pagination.

Now in views with pagination the links generated are relative URLs (example on /proposals):

```
<ul class="pagination text-center margin-top" aria-label="Pagination">
  <li>
    <a href="/proposals">First</a>
  </li>
  <li class="pagination-previous">
    <a rel="prev" href="/proposals">Previous</a>
  </li>
  <li>
    <a rel="prev" href="/proposals">1</a>
  </li>
  <li class="current">
    <span class="show-for-sr">You are on page</span> 2
  </li>
  <li>
    <a rel="next" href="/proposals?page=3">3</a>
  </li>
  <li class="pagination-next">
    <a rel="next" href="/proposals?page=3">Next</a>
  </li>
  <li>
    <a href="/proposals?page=3">Last</a>
  </li>
</ul>
```

It seems [kaminari doesn't have this setting and no plans to change it](https://github.com/kaminari/kaminari/pull/822)

**To improve SEO we need to use absolute URLs on pagination**. 

Something like:

```
  <li>
    <a rel="next" href="http://localhost:3000/proposals?page=3">3</a>
  </li>
```

**Comment by zamuro** [comment]
According to this PR https://github.com/kaminari/kaminari/pull/822/commits/37762dbe53e183b8a3712051acb27910561add7e functionality was successfully impmented, yet rejected by thegem author on the grounds of not bein on the roadmap. If the file can be placed on the /lib directory of the project, it might work. I'll give it a shot.

**Comment by zamuro** [comment]
I'll go with this one

**Comment by zamuro** [comment]
@decabeza are you aiming for something in this fashion? 

![captura de pantalla_2017-09-25_10-11-34](https://user-images.githubusercontent.com/1562834/30798446-feeaa728-a1d9-11e7-8b1b-c954f501df87.png)

If it suits you, I'll send a PR for this.

**Comment by bertocq** [comment]
Its a matter of relative/absolute url, not about what appears on the browser's url input.

This is what its being generated:
```
  <li>
    <a rel="next" href="/proposals?page=3">3</a>
  </li>
```

This is what should be generated:
```
  <li>
    <a rel="next" href="http://localhost:3000/proposals?page=3">3</a>
  </li>
```

**Comment by zamuro** [comment]
![captura de pantalla_2017-09-25_12-46-20](https://user-images.githubusercontent.com/1562834/30804956-aed3c1e6-a1ef-11e7-8535-a90619b7c1ac.png)

**Comment by bertocq** [comment]
👍  let's see the code then :)

**Comment by zamuro** [comment]
https://github.com/consul/consul/pull/1916

**Comment by deivid-rodriguez** [comment]
I'd like to learn more about this. Could someone point to any other reference other than the fact that Google uses absolute URLs in their examples?

**Comment by bertocq** [comment]
@deivid-rodriguez https://tools.ietf.org/html/rfc5005#section-3 and https://github.com/kaminari/kaminari/pull/822 has more info about it 👍

**Comment by deivid-rodriguez** [comment]
@bertocq Thanks.

I read the second link, but the OP makes the rather speculative assumption that because Google uses absolute URLs in their examples, that means it's better for SEO. Regarding the first link, I didn't read it all but I grepped for "absolute" and nothing came up :thinking:.

**Comment by decabeza** [comment]
Hi @deivid-rodriguez. Also we had a SEO audit for Decide Madrid (Madrid forks) with an external company and they recommended to us change this urls to avoid minor problems (not specified) with google indexation. 😄

**Comment by deivid-rodriguez** [comment]
¯\_(ツ)_/¯

Thanks! :+1:

**Comment by bertocq** [comment]
Fixed at master branch
