### ISSUE TITLE
Locale site customization

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1647]
## Background

In Admin site customization section `/admin/site_customization/pages` you can create custom info pages. There is an option to show them on `/more-information` page (inside the **Other information of interest** section).

<img width="277" alt="show_on_more_info" src="https://user-images.githubusercontent.com/631897/27090210-e18bc71c-505c-11e7-93ca-37d47f59b410.png">

Now you can create pages in any language using the WYSIWYG editor but you can't select the locale used in the page.

## What we need

- [x] Add a select input for available locales.
- [x] On `/more-information` show only the pages written on selected locale.

With this you can create for example a proposals extra info page and write it in different languages using differents slugs:

English: `proposal-extra-info`
Spanish: `propuestas-informacion-adicional`

Maybe also you want some info pages are showed only in a specific language.

## Extra info links

- [Site customization PR](https://github.com/consul/consul/pull/1484)
- Some `/admin/site_customization/content_blocks` examples:
    - [site_customization/content_block.rb](https://github.com/consul/consul/pull/1484/files#diff-fad3cc5c8309d80c10f2ad32836b1c7cR4)
    - [site_customization/content_blocks/_form.html.erb](https://github.com/consul/consul/pull/1484/files#diff-f1bc7d3446224099f062ffed77f4c342R23)

**Comment by MariaCheca** [comment]
I'm taking this ticket! :) cc @voodoorai2000

**Comment by voodoorai2000** [comment]
Closed via #1716
