### ISSUE TITLE
Complete Admin Budget Heading actions

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1672]
On the Budget details page http://localhost:3000/admin/budgets/1 you can see the list of Groups and Headings. You can create both, but you should be able to edit each Heading name & amount values.

Also Headings should be possible to be deleted, but only if there are no Budget::Investments associated.

Bonus: Add a link to each table row that allows admin to see the Budget's Investments filtered by that row's Heading (i.e: http://localhost:3000/admin/budgets/1/budget_investments?heading_id=1)

**Comment by iagirre** [comment]
I'll take this one.
