### ISSUE TITLE
Guía de instalación / Installation guide

### ISSUE THREAD

**Issue by arturomechan** [consul/consul#1695]
Por favor podrían poner una pequeña guía de instalación.
- Requisitos del servidor.
- Bases de datos?.
- Documentos que cambiar para personalizar.
- Documentos a traducir para nuevos idiomas (puedo ayudar con el Asturiano).

Please could put a small installation guide.
- Server requirements.
- Databases?.
- Documents you change to customize.
- Documents to be translated into new languages ​​(I can help with Asturian).

**Comment by bertocq** [comment]
Hola @arturomechan tenemos esto en mente, por ahora la información esta algo desperdigada:

- Requisitos del Servidor: En esto no tengo una respuesta, quizás @voodoorai2000 o @xuanxu te puedan ayudar, pero nada "fancy" me imagino.

- Base de datos: Actualmente cónsul usa la [librería pg](https://github.com/consul/consul/blob/master/Gemfile#L6) para bases de datos PostgreSQL. Pero si haces un fork puedes modificar eso fácilmente para usar otro adaptador con MySQL, MariaDB etc...

- Documentos que cambiar para personalizar. En el fichero [CUSTOMIZE_ES.md](https://github.com/consul/consul/blob/master/CUSTOMIZE_ES.md) que puedes encontrar en el directorio raiz.

- Documentos a traducir: Todos los .yml que se encuentran en [`config/locales`](https://github.com/consul/consul/tree/master/config/locales) (aunque en breves la estructura cambiará un poco https://github.com/consul/consul/pull/1694). Estamos en proceso de habilitar una herramienta para que gente no-técnica pueda contribuir a añadir más traducciones: https://crowdin.com/project/consul, este lunes van a solucionar un problema interno y podremos empezar a incluir más idiomas fácilmente. Sin duda tu ayuda será muy bienvenida con el asturiano :) 👏

**Comment by bertocq** [comment]
@arturomechan about the guide implementation, our roadmap / idea is the following:

1. Get a consensus in the contents and index (chapters organization), normally this starts with a proposal that gets discussed.
2. Start a new repo under this organization linked to a [gitbook](https://www.gitbook.com/) that easily lets non-tech people both read/update, but also can be updated through git/github.
3. Add existing documentation, and start individual issues for pending chapters, hopefully some of them can be covered by contributors.

**Comment by arturomechan** [comment]
Gracias por toda la información @bertocq (deberíamos tener vida y no trabajar un domingo).
Yo soy una de esas personas no-tech (soy diseñador gráfico) aún que he trabajado con programadores (solía preparar el trabajo en html como base), pensaba que sería interesante crear un instalador para Softaculous o Fantástico que además de facilitar la instalación promueven el uso y por tanto las colaboraciones en el desarrollo.
Conocí Cónsul por la web de participación del Ayto. De Oviedo, y me parece que es también muy útil para asociaciones y otros grupos de trabajo.

Thanks for all the information @bertocq (we should have life and not work a Sunday).
I'm one of those non-tech people (I'm a graphic designer), even though I've worked with programmers (used to prepare the work in html as a base), I thought it would be interesting to create an installer for Softaculous or Fantastico that, besides facilitating installation, use and therefore the collaborations in the development.
I met Cónsul on the web page of the Ayto de Oviedo, and I think it is also very useful for associations and other working groups.

**Comment by bertocq** [comment]
Thanks @arturomechan! We're a very small core team that work for Madrid fork and as a collateral effect maintain this Open-source project. Doing a installer would be awesome but its far from the core improvementa and features we have on roadmaps.

Anyway for local development its as easy as following the guide we've at https://github.com/consul/consul/blob/master/doc/es/dev_test_setup.md

Consul is still a platform that needs a technical person to install and maintain, but hopefully and with the help of contributors that will soon change

**Comment by bertocq** [comment]
@arturomechan I suppose its not the installer you where referring to, but @voodoorai2000 just refreshed my memory... we've on the works an automated production environment setup https://github.com/consul/consul/issues/1491

**Comment by arturomechan** [comment]
@bertocq  Muy interesante y útil, gracies!  /  Very interesting and useful, thanks!

**Comment by arturomechan** [comment]
Sorry

**Comment by bertocq** [comment]
Hey @arturomechan any email/twitter/etc to contact you in private? I'm @bertocq at almost every single service you can imagine :) (gmail, twitter, telegram, skype, hangout, gitter, etc...) Ping me and we'll talk about Asturian translations! https://crowdin.com/project/consul/ast#

**Comment by bertocq** [comment]
@arturomechan please contact me ;)

**Comment by arturomechan** [comment]
I sent you a private route by gmail

**Comment by voodoorai2000** [comment]
Closed in favor #1778
