### ISSUE TITLE
Autocomplete tags

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1703]
## Background

Now when create a new proposal appear an alert box of proposals with the same content (for avoid duplicating)

`This alert prevent duplicated content.`
<img width="889" alt="proposals_alert" src="https://user-images.githubusercontent.com/631897/27549043-0d7b296a-5a9b-11e7-9e54-9c5369c39814.png">

## What

The idea is include a similar behavior to the tags input field (the users can write whatever they want), but if they use the tags already used by others improve the searches for the rest of users. For example, instead of a new tag `motorcycle` it's better if anyone already used `motorbike`

This is needed for tags input field on:

- New debate
- New proposal
- New investment projects

`Example`
<img width="910" alt="tag_suggest" src="https://user-images.githubusercontent.com/631897/27549294-c96ad9ea-5a9b-11e7-9dbf-0421a5a00d8b.png">

**Comment by iagirre** [comment]
I'll take this one.

**Comment by bertocq** [comment]
Closed via #1905
