### ISSUE TITLE
Legislation process HTML

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1704]
## Background

When a legislation process have a **draft version published** and the **allegations phase is enabled** you can go to `/legislation/processes/N/draft_versions/N` 

## What

There is two minor problems to fix in this view:

- There is a duplicated `id="debate-show"` (used to interact with JS), this generates an HTML validation error.

- When you clic on arrow icon "View process information" appears/disappears several `icon-angle-up` icons.

`before clic`
![view_process_info](https://user-images.githubusercontent.com/631897/27550097-ad1de0fe-5a9e-11e7-9514-0299d974e19b.png)

`after clic`
![view_process_info_2](https://user-images.githubusercontent.com/631897/27550099-b06c920a-5a9e-11e7-9033-a12abf8ccda6.png)

**Comment by xarlybovi** [comment]
I can fix it

**Comment by iagirre** [comment]
Is something left to do here?

**Comment by decabeza** [comment]
Hi @iagirre we have a pending PR to review (https://github.com/consul/consul/pull/1899) but I think it's already done ;)

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/1899
