### ISSUE TITLE
Add Heading Population restriction & Validation

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1710]
## What
Budget Headings have a population field that can only be empty or a positive number (only invalid value is `0` a zero)

Heading creation form:
![screen shot 2017-06-27 at 18 35 56](https://user-images.githubusercontent.com/983242/27598984-7d0a56a8-5b67-11e7-9821-61f9c5eca1f6.jpg)

## How
- Add a model validation for `population` field to either be nil, or >0 if present
- Add a form validation to avoid user entering a 0 on the population input
- Add explanation of population field usage and restriction (either empty or >0), something like:

> Budget Heading population field is used for Statistic purposes at the end of the Budget to show for each Heading that represents an area with population what percentage voted. The field is optional so you can leave it empty if it doesn't apply.

**Comment by iagirre** [comment]
I'll take this.

**Comment by bertocq** [comment]
closed via #1679 & #2115  👏
