### ISSUE TITLE
Application scripts initialization after ajax complete event

### ISSUE THREAD

**Issue by Senen** [consul/consul#1736]
We are using turbolinks classic version 2.5.3 … maybe we have to think to upgrade to latest 5.xx stable version.

## What
Application javascript is not working as expected because inconsistency on ajax complete event callbacks.

It seems that remote calls managed by Turbolinks are throwing ajaxComplete event while ajax calls managed directly by jQuery are throwing ajax:complete event. This situation make developers to lose time to understand how application javascript behave and forces them to create unnecessary code inside scripts to make application work as they expect.

## Where
At main application scripts manifest we can find these following lines:

```
$(function(){
  Turbolinks.enableProgressBar()

  // This line initialize application for direct page loading (not through Turbolinks)
  $(document).ready(initialize_modules);
  // This line initialize application for pages loaded by Turbolinks
  $(document).on('page:load', initialize_modules);
  // This line tries to initialize application modules after complete ajax calls but ajax calls 
  // managed by turbolinks is throwing ajaxComplete so this line is not executed
  $(document).on('ajax:complete', initialize_modules);
});
```
Due to this behavior some AJAX responses have to call application modules manually to initialize new DOM elements created.

When we change definition to be turbolinks compliant (ajaxComplete)
```
 $(document).on('ajaxComplete', initialize_modules);
```
… some collateral damage arises, i’ll try to explain with proposal pages as example, that have many ajax components like followable, annotatable, flaggable,

1 - User clicks on flag to mark proposal as offensive, this launches an Turbolinks managed call, this call throws ajaxComplete event when finished
2- This ajaxComplete callback call all application modules initialization again
3- Now, all application modules are initialized again and the javascript behaviour is duplicated

## How
I think it would be nice to have only one of those ajax callbacks working in both situations and avoid unnecessary DOM inititalizations.

**Solution 1: Manual initialization**
1. Remove this line from application js manifest 
```$(document).on('ajax:complete', initialize_modules);```
2. Initialize only modules needed at any ajax response manually. If you are refreshing comments module we should initialize only comments module at the same response, there is no need to call all application modules initialization, we only need to initialize new DOM elements.

**Solution 2: Fix current configuration**
1. Standarize one ajax complete callback for all application.
2. Review all application javascript modules to ensure they are not initializing already initialized DOM elements.

**Comment by bertocq** [comment]
About turbolinks upgrade, with current rails version I think its impossible but once @xuanxu completes the awesome effort to upgrade to rails 5 we'll get turbolinks 5.0.1 along https://github.com/consul/consul/pull/1516/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R22 :)

**Comment by Senen** [comment]
Finally this issue seems not to be related with Turbolinks version, is happening with any version of Turbolinks. We realized while testing #3699. You will find a more detailed explanation at #3997 commits messages.
