### ISSUE TITLE
Budget Results

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1737]
What
===
Polish the result's page:
- [ ] Add link to results from stats page (PR #1712)
- [x] Highlight current heading
- [x] Calculate winners synchronously
- [x] Do not display incompatible investment's table if empty

**Comment by bertocq** [comment]
🤔 Should we hide by default discarded & Incompatible investments?

**Comment by bertocq** [comment]
1. **Add link to results from budget's welcome**:
I'm not sure what page / url you're talking about. As far as I see on a budget main page there is already a results link when its on finished phase https://github.com/consul/consul/blob/master/app/views/budgets/show.html.erb#L39-L44

![screen shot 2017-07-10 at 17 55 13](https://user-images.githubusercontent.com/983242/28027300-f293ba0a-6598-11e7-9c4e-c740da5f58ec.jpg)

2. **Add link to results from stats page**:
Stags page is coming on PR https://github.com/consul/consul/pull/1712 I'll include on it the link to results page

**Comment by bertocq** [comment]
Points **3**, **4** & **5** done at https://github.com/consul/consul/pull/1738

**Comment by voodoorai2000** [comment]
+1 to hidding to discarded and incompatible by default

Regarding 1) true, that was supposed to go in Madrid's fork issue. Moved 💃

**Comment by voodoorai2000** [comment]
Closed via #1738
