### ISSUE TITLE
Empty user interests

### ISSUE THREAD

**Issue by Senen** [consul/consul#1767]
What
=======
When current user is not following anything, his interests list is empty.

How
=====
When users is visiting own user page we should show:
```You don't follow any element yet.```

When users is visiting others user pages we should show:
```This user don't follow any element yet.```

Screenshots
=======

**Now**
![captura de pantalla 2017-07-24 a las 19 10 42](https://user-images.githubusercontent.com/15726/28535365-68ef09dc-70a4-11e7-83d5-d8cc9e3650ab.png)

**After this PR**
![captura de pantalla 2017-07-26 a las 16 54 17](https://user-images.githubusercontent.com/15726/28627916-6dc87bf2-7223-11e7-846d-90ae282de9e7.png)
![captura de pantalla 2017-07-26 a las 16 53 35](https://user-images.githubusercontent.com/15726/28627917-6dcab0d4-7223-11e7-9795-f96cdc7b450d.png)

**Comment by Senen** [comment]
Hi @decabeza.

What do you think?

**Comment by bertocq** [comment]
I prefer the **"This user do not have interests defined yet"** solution 👍  😄

**Comment by Senen** [comment]
@decabeza any advice?

**Comment by decabeza** [comment]
@Senen I think is a little confuse for the users have a "List of interest" when really are "Tags of elements you follow".

I like the solution with the message (better than empty) but I would add the explanation text, something like:

`List of interest (Tags of elements you follow)`

And for the message, something like: **You don't follow any element yet.**

Maybe with another better generic word than "element" 😝

**Comment by Senen** [comment]
Ok @decabeza, it makes more sense to me this way!

**Comment by decabeza** [comment]
@Senen Oh! maybe are necessary two texts:

For the user viewing their own profile:

```
List of interest (Tags of elements you follow)
You don't follow any element yet.
```

And for the user who visit the profile of another user:

```
List of interest (Tags of elements this user follow)
This user don't follow any element yet.
```

**Comment by Senen** [comment]
I have updated final screenshots!

**Comment by voodoorai2000** [comment]
Done 🎉
