### ISSUE TITLE
Comments empty HTML

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1775]
Background
=

When a user create a new comment this also generate an empty HTML code:

```html
<li>
  <ul id="comment_001_children" class="no-bullet comment-children">
  </ul>
</li>
```

Screenshot
=
<img width="1650" alt="children comments" src="https://user-images.githubusercontent.com/631897/28834614-01d7d518-76e3-11e7-8109-2951b272217b.png">

What we need
=

Avoid creating empty HTML code. 

- Only create the new "container" when necessary (a parent comment have children comments).

**Comment by aitbw** [comment]
Since this is already fixed on #1862 and merged into master, we should close this issue.

Cc/ @bertocq @voodoorai2000
