### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1778]
Long overdue, thank you for all your issues with requests for documentation.
We are finally getting serious about it and setting up comprehensive documentation on how to setup Consul.

Related issues in progress:
=====
- Automated production environment setup - https://github.com/consul/consul/issues/1491
- Dockerización - https://github.com/consul/consul/issues/78
- Database Diagram for Documentation - https://github.com/consul/consul/issues/1608

Related issues included in this issue:
=====
- Guía de instalación / Installation guide - https://github.com/consul/consul/issues/1695
- Fork FAQ - https://github.com/consul/consul/issues/1490
- Production server? https://github.com/consul/consul/issues/1199
- Documentation - https://github.com/consul/consul/issues/1130

What
=====

- [x] Creating your fork in Github
- [x] Setting up your fork locally
- [x] Adding Travis CI to your fork
- [ ] Verification
  - [ ] Census
  - [ ] SMS
  - [ ] Skipping Verifications
- [ ] Configuration Variables
- [ ] Active/Inactive Features
- [ ] [Look & Feel](https://github.com/consul/consul/blob/master/CUSTOMIZE_EN.md#images)
- [ ] [Translations](https://github.com/consul/consul/blob/master/CUSTOMIZE_EN.md#internationalization)
- [ ] [Adding new features](https://github.com/consul/consul/blob/master/CUSTOMIZE_EN.md#models)
- [ ] [Overwritting parts of Consul(https://github.com/consul/consul/blob/master/CUSTOMIZE_EN.md#models)
- [ ] Staging and production environments
  - [ ] Unix system
  - [ ] Ruby
  - [ ] Bundler
  - [ ] Git
  - [ ] Postgres
  - [ ] Unicorn
  - [ ] Nginx
  - [ ] Secrets
  - [ ] Emails
  - [ ] Delayed Jobs
  - [ ] Capistrano
  - [ ] Server requirements
- [ ] Monitoring
  - [ ] Rollbar
  - [ ] Newrelic
- [ ] [API](https://github.com/consul/consul/blob/master/doc/api/api_es.md)
- [x] Staying up to date
- [x] Contribuing

Where
=====

URL: https://consul_docs.gitbooks.io/docs/content/
Repo: https://github.com/consul/docs

**Comment by javierm** [comment]
Closing since the requirements seem to be out of date. @taitus If you'd like to reopen this issue and use it as a reference, drop me a line :wink:. But I'd rather have open issues in the docs repository :thinking:.
