### ISSUE TITLE
Admin - Reorganize

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1779]
Related issues 
=====
- Activating and deactivating features - https://github.com/consul/consul/issues/1597
- Reorganize admin stats - https://github.com/consul/consul/issues/1596

What
====
- Reorganize the Admin area to make it easy to configure and run day-to-day operations

How
===
@Decabeza's magic

**Comment by decabeza** [comment]
I close this one in favor of #1597 (Activating and deactivating features) and #1596 (Reorganize admin stats) 😌
