### ISSUE TITLE
Polls - Flow

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1781]
What
===
Make it trivial for users to vote all their allowed poll questions

Why
===
It is currently complicated to move back and forth between polls that you are allowed to vote

How
===
@Decabeza's magic

**Comment by decabeza** [comment]
For improve this flow there is two different options to explore.

## **Option 1. Change Answer button**

Now when a user visit a question show appears a button **Answer this question** when really the correct text would be `Answer this poll` (the index view show all the questions for the poll and user can answer all of them). User only see the show view for more info of this question or read the comments.

**PROS:**
- Users can answer all the questions in the same view. If go to a question to read more info or comments it's easy to return to index view.
- If we use some external service for secure vote (like Nvotes) it's easy integrate the voting part in the index view.
**CONS:**

**Comment by decabeza** [comment]
Closes in favor to #1855
