### ISSUE TITLE
Polls - Comments

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1782]
What
===
Find a nice way to make readily available comments and voting in a Poll Question

Why
===
These two concepts are currently split up into differente pages:

Comments
http://localhost:3000/questions/1

Votes
http://localhost:3000/polls/1

Screenshots
====
Comments
![comments](https://user-images.githubusercontent.com/4169/28995819-9f51c840-79f3-11e7-94b1-c74b0952dd33.png)

Votes
![voting](https://user-images.githubusercontent.com/4169/28995825-ab5b9760-79f3-11e7-84bf-7a883afc9455.png)

How
===
@Decabeza's magic

**Comment by decabeza** [comment]
I think the best solution to show the comments is using the same pattern like other sections: debates, proposals and budget investments.

Show in the index items a link to number of comments:

<img width="894" alt="index_minimal" src="https://user-images.githubusercontent.com/631897/29272165-34a1d9e6-80ff-11e7-9925-aa2164cbb04d.png">

This is the "minimal way" but also we can include more information, for example the polls author and participation dates (although this info is already displayed on index and show sidebar):

<img width="1199" alt="index_duplicated" src="https://user-images.githubusercontent.com/631897/29272226-72240b04-80ff-11e7-95d1-38c177cbf240.png">

<img width="305" alt="show_sidebar" src="https://user-images.githubusercontent.com/631897/29272230-75013356-80ff-11e7-89fe-0623a960f880.png">

**Comment by decabeza** [comment]
Closes in favor to #1855
