### ISSUE TITLE
Backport Polls - Results from madrid

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1786]
What
====
- We need add **Poll results** for each poll.

How
===
- We need to include poll results with this data:

  - List of questions.
  - Each question has a **Total number of votes** for each answer.
  - **Percentage** of answer respect the total votes for this question.

💈 The current content of `poll/show` should be maintained on "Information" tab.

It's easier to understand by checking the mockup image. 

Screenshots
===
You can see the [mockups here](https://invis.io/MSDWMNAWH) _(image 1)_ 

Warnings
===
This issue is related with #1787 and have some things on common.

Notes
===
- This work has already been done in [Madrid's fork](https://github.com/AyuntamientoMadrid/consul/blob/stable/app/controllers/polls_controller.rb#L23) but needs a little love ❤️

**Comment by aitbw** [comment]
I'm on it.

**Comment by bertocq** [comment]
Sorry @aitbw maria has already started it 🙏  mondays are hard 😓

**Comment by MariaCheca** [comment]
Closed here: https://github.com/consul/consul/pull/2082
