### ISSUE TITLE
Polls - Stats

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1787]
What
===
- We need add **Poll participation stats** for each poll.

How
===
- We need to include poll stats with this data:

  - **TOTAL Nº OF BALLOTS**: this is the total number of participants in this polls (independent of the channel, web or booth)

  - The **totals of bottom row** are the sum of each column. 

  - The **totals of right colum** are the sum of each row. 

The percentage of right column are calculated respect to the total of participants in this poll (% of valid vote, white and null, check the values in vertical)

All the rest of percentages are calculated respect to the total of votes in this channel (% of web votes, booth, check the values in horizontal)

💈 The current content of `poll/show` should be maintained on "Information" tab.

It's easier to understand by checking the mockup image.

Screenshots
===
You can see the [mockups here](https://invis.io/MSDWMNAWH) _(image 2)_ 

Warnings
===
This issue is related with https://github.com/consul/consul/issues/1786 and have some things on common.

Notes
===
- This work has already been done in [Madrid's fork](https://github.com/AyuntamientoMadrid/consul/blob/stable/app/controllers/polls_controller.rb#L34) but needs a little love ❤️ 
- Something similar to [Budget Stats](https://github.com/consul/consul/pull/1712)

**Comment by iagirre** [comment]
I'll take this one.

**Comment by iagirre** [comment]
Shall I go with this?

**Comment by voodoorai2000** [comment]
Not yet ;)

**Comment by iagirre** [comment]
I'll go with this one.

**Comment by bertocq** [comment]
Closed via #2075 👏
