### ISSUE TITLE
Switch flag/unflag buttons on use via ajax

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1797]
Right now when you flag a proposal, to get the "unflag" button you need to refresh the page.

https://github.com/consul/consul/blob/master/app/views/proposals/_flag_actions.html.erb has the condition, but is not being refreshed after use of the actions.

Ideally after using a button, the opposite action button should be available replacing it, via ajax like the follow/unfollow button does with https://github.com/consul/consul/blob/master/app/views/follows/refresh_follow_button.js.erb

**Comment by xarlybovi** [comment]
I'll be glad to help you with this one

**Comment by bertocq** [comment]
Awesome @xarlybovi go for it 👏 😄

**Comment by aitbw** [comment]
@xarlybovi submitted #1883 which was merged successfully. Let's close this one, shall we? ;-)
