### ISSUE TITLE
Hacer un deploy en Heroku

### ISSUE THREAD

**Issue by kdfproject** [consul/consul#1799]
Estoy intentando hacer un deploy en Heroku y recibo este error: 

PG::ConnectionBad: could not connect to server: Connection refused
       Is the server running on host "127.0.0.1" and accepting
       TCP/IP connections on port 5432?

Alguna idea de como solucionarlo?
Gracias

**Comment by bertocq** [comment]
Hola @kdfproject parece que es un error de PG (es decir el adaptador de Postgresql) que te esta diciendo que la conexión con la base de datos se ha rechazado. Y te pregunta si la bbdd esta escuchando en ese puerto 5432. No parece unproblema específico de consul, sino más bien de tu instalación en heroku y como la tengas configurada
