### ISSUE TITLE
Refactor Residence Verification

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1838]
## Context

We've a custom model [Verification::Residence](https://github.com/consul/consul/blob/master/app/models/custom/verification/residence.rb#L13) that's being used to always check the user's zip_code matching Madrid's zip code pattern.

This is not good because:
- Forks have to overwrite that `280` leading numbers on the zip_code pattern (as well as `madrid` name on the consul codebase)
- ZipCode check doesn't make sense for CONSUL installations which audience is not just a city but organizations, political parties, etc... but other types of custom verifications.

## What

We need to make CONSUL easier to customize on those features that aren't mandatory but should be optional. The proposed changes to make this better are:

- Code should not have `madrid` name hardcoded.
- The `280` zip code pattern shouldn't be hardcoded, but configurable as a setting value.
- The custom Residence Verification should be possible to be turned off completely using a Settings value (instead of having to totally remove the file and specs).

**Comment by zamuro** [comment]
I'll take this one.

**Comment by zamuro** [comment]
Hi, guys

I've been thinking on using a yml file in which users will check against. Of course, that would need for the devs to create the yml file with the zipcodes they will be using. Something like this gem [1]

What do you think?

[1]: https://github.com/monterail/zip-codes

**Comment by javierm** [comment]
Reopening since this one definitely needs to be implemented at some point, and we've been (intermittenly) working on issues related to verification in the last year and a half.
