### ISSUE TITLE
Disallow user from introduce no-video URLs in the proposals' video field

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#1841]
Currently the proposals form accepts any string in the `video_url` field. This lets users introduce anything that the platform is not able to process as it always expects a URL to a Youtube or Vimeo video.

So in order to avoid strange behaviours in the UI we should:
- Restrict the string format to URLs matching the video platforms we support.
- In case the user submits an invalid format the form will alert about the error.
- Also and just in case, improve https://github.com/consul/consul/blob/master/app/views/proposals/show.html.erb#L75-L81 to avoid showing `flex-video` box if the `embeeded_video_code` is not a video.

Thanks @bertocq for helping me redacting this issue :)

**BONUS: If you increase the supported platforms to Twitter/Facebook/Instagram/etc... extra kudos for you!**

**Comment by aitbw** [comment]
Hi! I'm currently working on this issue but I'm having a hard time trying to understand the third bullet point.

`flex-video` won't show unless the `video_url` field is present and for it to be present, only valid Youtube or Vimeo URLs are allowed.

Could you please shed some light on this?

Thanks in advance!

**Comment by decabeza** [comment]
Hi @aitbw, 

Yes, I think the second bullet also fix the third ^_^ 

The problem is right now if the user introduce any url (not a video) the `flex-video` box appears empty, but with the previous validation would be resolved 👌

**Comment by aitbw** [comment]
Ah, perfect, thanks for the quick response, @decabeza.

**Comment by bertocq** [comment]
Also @aitbw, the background for point 3 was that on Madrid's fork (and maybe on others) there are already existing proposal's with `video_url` values that aren't valid video links. Thus hiding the big blank square that flex-video prints when it can't show a valid video was the objective... but it can be achieved by other means like having a function to validate a `video_url` value that could be rake via rails console or better through rake task
