### ISSUE TITLE
NoMethodError in Officing::ResidenceController#new

### ISSUE THREAD

**Issue by periflo90** [consul/consul#1847]
Dicho error se encuentra en la ruta `/officing/residence/new`, a la que se accede desde Admin > Presidentes de mesa > Validar documento y votar.

El error dice lo siguiente:

**undefined method `officer_assignments' for nil:NilClass**

```
def load_officer_assignment
      @officer_assignments = current_user.poll_officer.
                               officer_assignments.
                               voting_days.
                               where(date: Date.current)
    end
```
app/controllers/officing/residence_controller.rb:27:in `load_officer_assignment'

**Comment by MariaCheca** [comment]
Hi @periflo90! Thank you for reporting this issue. We will take care of it as soon as possible, meanwhile stay tuned here :)

--

Hola @periflo90! Muchas gracias por reportar este error. Lo resolveremos en la mayor brevedad posible, mientras tanto puedes seguir el estado del issue aquí :)

**Comment by zamuro** [comment]
While trying to locate the faulty behavior, I stumbled upon this:

```
2.3.2 :001 > a = User.find(1)
  User Load (2.1ms)  SELECT  "users".* FROM "users" WHERE "users"."hidden_at" IS NULL AND "users"."id" = $1 LIMIT 1  [["id", 1]]
 => #<User id: 1, email: ...> 
2.3.2 :002 > a.poll_officer
  Poll::Officer Load (107.0ms)  SELECT  "poll_officers".* FROM "poll_officers" WHERE "poll_officers"."user_id" = $1 LIMIT 1  [["user_id", 1]]
 => nil 
2.3.2 :003 > 
```
So, maybe this would fix it:

```
    def load_officer_assignment
      @officer_assignments = current_user.poll_officer.
                               officer_assignments.
                               voting_days.
                               where(date: Date.current) if current_user.poll_officer.present?
    end
```

Would that interfere with further validations?

**Comment by zamuro** [comment]
I sent a PR for this issue on https://github.com/consul/consul/pull/1872

**Comment by bertocq** [comment]
Already been fixed at https://github.com/consul/consul/blob/master/app/controllers/officing/base_controller.rb#L10
