### ISSUE TITLE
Routing Error: No route matches [GET] "/admin/poll"

### ISSUE THREAD

**Issue by periflo90** [consul/consul#1848]
Dicho error salta en el apartado Admin > Administrar > Votaciones > cualquier subapartado de esa categoría al pulsar sobre el banner de Consul.

Dicho banner apunta a `/admin/poll`, ruta inexistente (la que sí existe es `/admin/polls`). No obstante, en los demás apartados el banner apunta simplemente a `/admin`.

En el apartado de votaciones dicho banner reza "CONSUL | Title" en lugar de "CONSUL | Administración".

**Comment by MariaCheca** [comment]
Nice one! We're trying to solve this as soon as posible, thank you for your contribution :)

--

Bien visto! Intentaremos arreglarlo lo antes posible, muchas gracias por tu contribución :)

**Comment by aitbw** [comment]
I'm on it.
