### ISSUE TITLE
Display Datepicker arrows

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1851]
At least on the Polls edit page when you popup the datepicker trying to edit a date, the next/prev month arrows icons aren't displaying

![screen shot 2017-09-11 at 22 42 52](https://user-images.githubusercontent.com/983242/30295939-bbac4706-9742-11e7-9a2a-7f5318ff0e64.jpg)

**Comment by iagirre** [comment]
I'll take this one.

**Comment by decabeza** [comment]
Closed by #1869
