### ISSUE TITLE
Break down routes.rb into smaller files and allow custom routes easily

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1852]
Break down big routes.rb file into smaller ones, (polls/admin/legislation/budgets...) and also allow easily custom routes and static pages in a custom_routes.rb file or something alike

**Comment by aitbw** [comment]
GitLab CE did this (which you can find [here](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/config)) and seems (acc. to the related commits) a pretty straightforward task.

Should I proceed with this issue or there are any other high-priority issues first?

**Comment by voodoorai2000** [comment]
Sure @aitbw go for it 👍

**Comment by bertocq** [comment]
@aitbw I would take into account madrid's fork routes to see if the solution will be compatible at least with that fork :) https://github.com/AyuntamientoMadrid/consul/blob/master/config/routes.rb

**Comment by aitbw** [comment]
You mean the custom routes found on the file you mention, @bertocq? It should be compatible.

After all, this change would mean creating the files needed under `config/routes/` and monkey-patch the `ActionDispatch::Routing::Mapper` class to load the new files into Consul (although a new file for this patch under `config/initializers` could be created as well)

See [these](https://www.michaelcho.me/article/how-to-split-rails-routesrb-into-multiple-smaller-files) [posts](http://blog.arkency.com/2015/02/how-to-split-routes-dot-rb-into-smaller-parts/) for reference.

**Comment by bertocq** [comment]
Awesome :) we have many custom routes on madrid's fork, but not only at the bottom but also in the middle of the file that have give us some problems with the order https://github.com/AyuntamientoMadrid/consul/blob/master/config/routes.rb#L80-L84

Once you have a solution, checking out the branch on madrid's fork and seeing it in action would be wonderful :). This will be an example for all the rest of forks to customize their routes 👏

**Comment by aitbw** [comment]
Thanks for the insight on the Madrid's fork, @bertocq.

I'm currently working on this issue as we speak. I'll let you know when the PR is ready.
