### ISSUE TITLE
Legislation proposals

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1856]
What we need
==

Adds a proposals section where the users can create proposals inside a legislation process.

Admin section
==

- [x] Include new `proposals phase` _(Screenshot 1)_:
    - Start date
    - End date
    - Enable/disable checkbox

- [x] Include new `proposals tab` _(Screenshot 2)_:
    - This have a textarea to include a heading text before the proposals to explain the objectives, process, etc.  
    - In this section also the admin can write "categories" (tags) that will be show to the user when create a new proposal inside the process. 

Front views
==

- [x] Include new `proposals section` inside a legislation process with similar behaviour of regular proposals _(Screenshot 3)_:

- ✅ Shows title, summary, comments, supports number, support button
- ❌ Don't shows progress bar neither number of necessary supports

Screenshots
==

### Screenshot 1
![legislation_proposals_1](https://user-images.githubusercontent.com/631897/30344316-122bae5a-9801-11e7-8867-7571fb523e14.jpg)

### Screenshot 2
![legislation_proposal_admin](https://user-images.githubusercontent.com/631897/30393005-f37c778c-98be-11e7-86cf-4152993a908b.jpg)

### Screenshot 3
![legislation_proposals_3](https://user-images.githubusercontent.com/631897/30344321-1723967a-9801-11e7-9813-d9590f4aebb3.jpg)

**Comment by MariaCheca** [comment]
Closed here: https://github.com/consul/consul/pull/1906
