### ISSUE TITLE
Create Poll Recount model

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1870]
We have this three models:
```
::Poll::WhiteResult
::Poll::NullResult
::Poll::TotalResult
```

That could be merged into just one ::Poll:Recount. Sharing in the same table the counters, log history columns etc... 

But a rake task will be needed for those forks that had data on WhiteResult and NullResult tables.

**Comment by aitbw** [comment]
I'd like to make you guys aware of the fact that no rake task is needed to move the data on existing forks, a simple migration will do, as stated [here](https://coderwall.com/p/g4lkbq/3-step-migration-for-moving-columns-with-data-to-a-new-table).

If you're ok with this approach, I'll get this done asap.

**Comment by bertocq** [comment]
@aitbw sorry, the rake task part is not needed because as it appears, no forks (only madrid) have used Polls in real life (or even have the code... because forking Madrid's fork is not supported really :D) so I've just stashed madrid's first poll stats/results/info/landing in plain html https://github.com/AyuntamientoMadrid/consul/pull/885 and we can forget about any data problems :)

**Comment by bertocq** [comment]
Closed via #1963
