### ISSUE TITLE
Admin menu wrongful active items

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1871]
@iagirre  reported

> Cuando se pincha en algún apartado del menú de "Perfiles" (Administradores, Organizaciones, etc.) se despliega el menú de "Personalizar sitio", y que cuando se pincha en algún apartado de "Personalizar sitio", el menú no se mantiene abierto.

And she's going to tackle it! 👏

**Comment by decabeza** [comment]
Closed by #1874
