### ISSUE TITLE
Preview budget results

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1880]
What
===

Allow admins to see the temporary results for a budget before the balloting phase has finished.

Screenshots
===
![budget results](https://user-images.githubusercontent.com/4169/30538954-843a4736-9c70-11e7-88ac-7c5d44b05b3a.png)

How
===
- Adding admin [permissions](https://github.com/AyuntamientoMadrid/consul/pull/840/files#diff-b607881ce04b1fa7d4dd113223378f85R52) for the result's page
- Adding [user](https://github.com/AyuntamientoMadrid/consul/pull/840/files#diff-635cabab9d4148990a6de3f660f8f0faR11) and [admin](https://github.com/AyuntamientoMadrid/consul/pull/840/files#diff-1c352101b31f14f02ff413ffaceb075bR96) specs

Note
===
These commit references are from Madrid's fork, where this feature has already been implemented.

Warnings
===
- Results need be calculated in a budget's admin section before they can visualized.

![calculate winners](https://user-images.githubusercontent.com/4169/30538736-a31959f4-9c6f-11e7-98b7-515b0980663e.jpg)

**Comment by iagirre** [comment]
I'll take this.

**Comment by javierm** [comment]
Closed via #1923.
