### ISSUE TITLE
Legislation comment actions

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1897]
Background
==

In the debates/proposal/budget_investments comments if the user is an admin or moderator appears two links to **hide comment** or **hide author** and for all users appears a flag icon to **flag as inappropriate** (all this links are on the partial `/views/comments/_actions.html.erb`) 

Screenshot
==
<img width="519" alt="comments_actions" src="https://user-images.githubusercontent.com/631897/30656944-15144218-9e36-11e7-9649-16896e70975f.png">

What 
==

We need to include this comments actions on `legislation/processes/N/questions/N` comments.

**Comment by aitbw** [comment]
I'm on it.

**Comment by aitbw** [comment]
Apparently, someone already did this because these actions are already available.

**Comment by decabeza** [comment]
@aitbw you are right! 😬 

We thought there was a issue, but works correctly:

When visit the `legislation/processes/N/questions/N` with a **admin/moderator role** you see all the actions:

<img width="1230" alt="ok" src="https://user-images.githubusercontent.com/631897/30753308-3a28fb72-9fbf-11e7-9ce8-e25e18a6e7ea.png">


When visit the `legislation/processes/N/questions/N` with a **admin role** you see all the actions **(except for your own comments, and this is OK)**:

<img width="1215" alt="screen shot 2017-09-22 at 17 53 09" src="https://user-images.githubusercontent.com/631897/30753325-49e4a340-9fbf-11e7-873e-a3e8c9846fcf.png">

Sometimes we forgot always it's necessary test all cases (admin, regular user, verified user...) 😅  

Close this one then.

Thanks and sorry by the mistake! 🙏
