### ISSUE TITLE
Backport Verification via redeemable code from Madrid's fork

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1907]
## References

* Pull request AyuntamientoMadrid#34
* Pull request AyuntamientoMadrid#54
* Pull request AyuntamientoMadrid#55
* Pull request AyuntamientoMadrid#259
* Pull request AyuntamientoMadrid#453

**Comment by aitbw** [comment]
See also #1908

**Comment by bertocq** [comment]
Yeah nice one @aitbw I was just quickly storing info here, but we should explain a lot more to get this issue to be easily pickable by anyone :) 

For the record `  get '/cuentasegura', to: 'welcome#verification', as: :cuentasegura` route was removed on that 1908 PR as its not being used and its on spanish
