### ISSUE TITLE
Refactor Settings for more intuitive usage

### ISSUE THREAD

**Issue by bertocq** [consul/consul#1909]
Right now we're just looking for the value to be present at https://github.com/consul/consul/blob/master/app/models/setting.rb#L25 if you introduce a `'false`' or `false` on the value, the setting will still act as enabled. We should take some time to rethink this part and make it more easier/intuitive to use taking into account all actual usages of Setting

**Comment by javierm** [comment]
I'm not sure I'm following :thinking:. Settings which are enabled/disabled don't have a text input. Introducing `false` as a value in a text should not disabled a setting; for all we know, in a certain language "false" means "government" and it's used as the sender name in an email :smile:.

Feel free to reopen if I've misunderstood the purpose of this issue :wink:.
