### ISSUE TITLE
Admin sections content overflow

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#1914]
In the admin sections sometimes the content overflows the container as seen in the picture below. Maybe the container should have the same height as the content to avoid this.

<img width="1439" alt="screen shot 2017-09-25 at 11 58 15" src="https://user-images.githubusercontent.com/2141690/30803344-8dfde272-a1e9-11e7-9c9c-5326319b1450.png">

cc/ @decabeza

**Comment by decabeza** [comment]
Closed by #2064
