### ISSUE TITLE
Snake case names on JS coding

### ISSUE THREAD

**Issue by aitbw** [consul/consul#1918]
## Enforce JavaScript coding conventions and linting

Snake case names on JavaScript files should be avoided whatsoever (as in [here](https://github.com/consul/consul/blob/master/app/assets/javascripts/application.js#L68)) and a linter for JS should be adopted as well, just like we've done with rubocop.

In the current JS ecosystem, [standard](https://github.com/standard/standard) and [eslint](https://eslint.org/) are the to-go linters. It's up to us which would would fit better for the project.

**Comment by javierm** [comment]
Actually I prefer snake case :sweat_smile:. For_me_snake_case_is muchEasierToReadThan came case :thinking:. For some reason I don't know about, it seems snake case is the standard in most languages, but not in JavaScript :thinking:.

Anyway, we've added ESLint in #3653, so we can add the rule for camel case if we want to. Unfortunately there's no rule forcing snake case, which I'd gladly add to our `.eslintrc` file.
