### ISSUE TITLE
Is there a way for an admin to delete proposals ?

### ISSUE THREAD

**Issue by fredhampton** [consul/consul#1925]
Is there a way for an admin to delete proposals ?

**Comment by decabeza** [comment]
Hi @fredhampton, if you login as admin in each proposal you have two links: **Hide** (to hide the proposal), or **Hide the author** (to hide all content created by an user):

<img width="468" alt="admin_actions" src="https://user-images.githubusercontent.com/631897/30899537-89e9dd1c-a360-11e7-8a6a-192a8a939d00.png">

You can enter to admin panel `/admin/proposals` to confirm the hide action or restore the proposal:

<img width="1246" alt="admin_moderated" src="https://user-images.githubusercontent.com/631897/30899562-a0a86db6-a360-11e7-8b2a-b1c6437d2e6d.png">
