### ISSUE TITLE
"Maximum number of documents allowed reached" error

### ISSUE THREAD

**Issue by aitbw** [consul/consul#1936]
I noticed the following, somewhat incorrect behavior: When you go to `admin/questions/new` and try to upload/attach a document to the question, you're greeted with the following validation error:

![screenshot-2017-9-28 admin](https://user-images.githubusercontent.com/9470839/30966601-83380012-a427-11e7-9478-5c762fcdee56.png)

This error appears as soon as you click the "Add new document" button. Even though you **can** attach a document when you click the "Select a document" button, this interferes with the UX since:

* End-users might think a document is already attached
* You need to click **two** (2) buttons for your operative system's file browser to show up to let the users search for their documents, when the normal behavior is to click just one button.

The expected behavior should be:

* Click the "Add new document" button once, immediately showing the file browser
* Show the error **only** when a document is selected and ready to be uploaded to the server

**Comment by bertocq** [comment]
I'm sorry we totally forgot about this one @aitbw you found out this only way back :). I'm closing it because this newer one has similar objective but expectations were re-though by decabeza https://github.com/consul/consul/issues/2334 Thanks! ❤️
