### ISSUE TITLE
Polls: Admin questions

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1949]
What we need
==

Improve answer for polls questions:
- Remove old answer input.
- Add new `Add answer` button.
- Add answer `title` input.
- Add answer `description` input. 
- Add a table to list all answers for the question.

Screenshots
==

![ok_polls_admin_question_1](https://user-images.githubusercontent.com/631897/31026902-772924f0-a548-11e7-8c0b-761bea007311.jpg)

![ok_polls_admin_question_2](https://user-images.githubusercontent.com/631897/31026943-a372fd42-a548-11e7-861c-8f06f84bf7f3.jpg)
⬆️  **NOTE:** in this view we've to add the `Poll name` and  `Question` as a breadcrumb to give some context to admin user.

**Comment by zamuro** [comment]
I'll take this one

**Comment by bertocq** [comment]
@zamuro seems like it was assigned to @aitbw , have you talked with him about it?

**Comment by zamuro** [comment]
@bertocq I have not. Although I will in a couple hours. I'll take another one instead. Thanks.
