### ISSUE TITLE
Polls - Voting identifier

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#1985]
What
===
- When voting (as soon as one of the options is marked, even if you do not answer the other questions in a poll) we must generated **in the client side** a random identifier (a string of letters and numbers long enough to ensure that no two are repeated with millions of votes). 

- The following message should be displayed in small format:
"You can write down this vote identifier, to check your vote on the final results."
("Puedes apuntar este identificador de voto, para comprobar tu votación en el resultado final".)

- This string must be saved in db associated to the vote in that poll. 
- We should generate different identifiers for each poll in which the user participates.

Why
===
So that at the end of the voting we can publish a csv with a field with votes, and another field with the identifiers, so that people can see that their vote has been properly collected.

**Comment by bertocq** [comment]
```
var rand = function() {
    return Math.random().toString(36).substr(2); // remove `0.`
};

var token = function() {
    return rand() + rand(); // to make it longer
};

token();
```
Seems good enough? each `Math.random().toString(36).substr(2);` returns 11 chars 

https://stackoverflow.com/a/8532436

But I'm concerned about the fact that we'll be shoving into the user a string too long (like a WIFI password, but without upcase letters :D )
