### ISSUE TITLE
Polls - Questions limit

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1997]
What
==

Remove **question** length limit on `/admin/questions/new` (this form is used only for admin users, there in no need to limit)

Screenshot
==

<img width="574" alt="screen shot 2017-10-06 at 17 11 26" src="https://user-images.githubusercontent.com/631897/31284667-8d8d37a6-aab9-11e7-918a-d9d46ba1b177.png">

**Comment by aitbw** [comment]
I already took care of this, PR is pending along with fix for #1998 as well.

**Comment by voodoorai2000** [comment]
Awesome @aitbw 🙏
