### ISSUE TITLE
Polls - Empty answers

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1998]
Background
==

Maybe some times there is a poll with questions and answers but without answers description or images.

What
==

Don't show empty `<div class="expanded poll-more-info-answers">` if there is no answers description or images.

**Note**: some similar (for answer title is made on https://github.com/consul/consul/pull/1996)

Screenshot
==

**Avoid this empty block**
<img width="1679" alt="screen shot 2017-10-06 at 17 15 13" src="https://user-images.githubusercontent.com/631897/31284810-f1776c5a-aab9-11e7-96b5-8f2930f3bc2f.png">

**Comment by aitbw** [comment]
I'm currently working on this one.
