### ISSUE TITLE
Polls - Admin removes images

### ISSUE THREAD

**Issue by decabeza** [consul/consul#1999]
What
==

- Add link to allow to removes images added on `/admin/answers/N/images`

Screenshot
==

![remove_images](https://user-images.githubusercontent.com/631897/31285373-682e9fa2-aabb-11e7-96e2-5094888a7055.jpg)

**Comment by aitbw** [comment]
I'm on it.

**Comment by aitbw** [comment]
I was looking into this one on Friday and I think I **may** have an idea on how to solve it, so I'm on it (again) 😅
