### ISSUE TITLE
Polls - Voted in booth

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2000]
What
===
- In a poll's show view, display answers, even if the user has voted in a physical booth.
- These answers, should not be clickable and should have an appropriate shadow kind style

**Comment by bertocq** [comment]
I think its just switching line https://github.com/consul/consul/blob/master/app/views/polls/questions/_answers.html.erb#L2

for `<% if can?(:answer, question) && question.poll.voted_in_booth?(current_user) %>`

**Comment by voodoorai2000** [comment]
Oh, the answers' titles appear, and so the tests pass.
However, the buttons to vote with an appropriate css, to represent that they can not be clicked, is not visible.
