### ISSUE TITLE
Add special "blank" web Poll Answer

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2017]
We need to add the concept of "Blank" Answer on Poll Questions.

It has two implications:
**A**- A "Blank answer" button needs to be displayed along the present answers if the question allows it.
**B**- If a user votes on the web for only 1 question out of 5 on a poll, the rest of the questions by default get a "Blank" answer marked (for final recount purposes)

To implement this we need:

1. Add a boolean flag on the `Poll::Question` model `accepts_blank_answers` that can be set/unset through a Checkbox on the Admin Poll Question edit form with "Acepta respuesta En Blanco"/"Accepts Blank answer" and a explanation text "This will include a Blank answer automatically on the user facing voting web"

2. On every place that shows the Question's answer list to the user (Think Poll index, Poll detail and maybe one more place). If the Question has the `accepts_blank_answers` flag, display the "En Blanco"/"Blank" answer button.

3. Add a boolean flag on the `Poll::Answer` model `blank` that defaults to `false`. 

4. A "Blank" answer button will `Poll::Answer` register with that `blank` flag on.

5. Include on the Poll Recount stats the Poll::Answer with blank flag  as "Blanks" along the blank ones from the Booths. But also take into account all the questions unanswered for all Poll::Voters. That means requirement **B**: If an user answers only 1 Question on a Poll that has 2 Questions, the final recount should show 1 Valid vote and 1 Blank vote (check https://github.com/consul/consul/issues/2043)

**Comment by iagirre** [comment]
I'll take this.
