### ISSUE TITLE
Poll::Question::Answer should be orderable

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2018]
Answers are displayed in creation order right now at https://github.com/consul/consul/blob/master/app/views/polls/questions/_answers.html.erb#L3

We need to add a "order" attribute that is used to list them on that "client" view and as well on the backend for the admin.

We'll need a way on the backend panel (admin) to change the order of the Answers, without much hassle :)

**Comment by iagirre** [comment]
I'll take this one.

**Comment by bertocq** [comment]
Here are the parts where we're using order (by id) right now on madrid https://github.com/AyuntamientoMadrid/consul/commit/14a35a2aeadfdb3e9f98dfe32ab9fbdc6fcb756d although the app/views/polls/show.html.erb is not correct, and should be revisited carefully with a spec

**Comment by bertocq** [comment]
Closed via #936
