### ISSUE TITLE
Poll Slugs

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2019]
Backport from madrid https://github.com/AyuntamientoMadrid/consul/pull/919#pullrequestreview-67866805

But adding:
- Generate slug for Polls
- Allow to manually overwrite the slug from the rails console so it won't be overwritten later on (I suspect using Sluggable would do that wrong)

Maybe make Sluggable comply with those specs and use it 👌

**Comment by iagirre** [comment]
I'll take this.

**Comment by javierm** [comment]
Closed via #3504.
