### ISSUE TITLE
Improve dev_seeds rake with Poll entities

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2022]
We need to make dev_seeds generate better scenarios for Poll:
- Reduce the Polls created to one on each scenario:
   - One Active (current) geozone restricted
   - One Active (current) not geo-restricted
   - One Expired 
   - One Incoming (not yet started)
- Create Shifts on each Poll for the poll_officer (maybe add a second poll officer user to double check some scenarios)
- Create Poll::Voter and Poll::Answer (simulate real votes) on the 2 Active and the Expired one (to see results/recounts)

**Comment by iagirre** [comment]
I'll take this.

**Comment by bertocq** [comment]
Closed via #2086
