### ISSUE TITLE
Right answer resize should reorder

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2027]
# Current Behaviour
Right now when you click expand the gallery of the second answer on a Poll you'll get it expanded but below the first answer:
![zoom_right_answer](https://user-images.githubusercontent.com/983242/31355082-2601b8d2-ad39-11e7-800a-8c337b0a27d5.gif)

# Desired Behaviour
Instead of expanding below the first answer, it should be on top of it. With the same effect as expanding the first answer gallery does.

**Comment by iagirre** [comment]
I'll take this.

**Comment by decabeza** [comment]
Hi @iagirre! For this one I use a Foundation "little trick" with [Foundation toggler](https://foundation.zurb.com/sites/docs/toggler.html) to avoid create new js. Feel free to change it if it's necessary 😉
