### ISSUE TITLE
Remove Author and usage from Poll

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2045]
On the Poll Comments PR https://github.com/consul/consul/pull/1961 some things got introduced that shouldnt:
- `author_id` on the polls table
- `belongs_to :author, -> { with_hidden }, class_name: 'User', foreign_key: 'author_id'` on the poll model

In order to remove this without issues, we have to trace all `commentable.author` usage, and add something like `unless  @comment.commentable.is_a?(Poll)` to avoid the usage... as far as I've researched its always code related to email notifications about comments and since Poll comments should not be notificable to author (there is NO author on the specs) that's not neccesary.

**Comment by zamuro** [comment]
I'll take this, since I've worked on the previous one.

**Comment by javierm** [comment]
Closing this one since now there are dashboard polls where having the author makes sense.
