### ISSUE TITLE
Use timestamps at Poll Recount & Partial Result

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2070]
As stated at https://github.com/consul/consul/pull/2069 we're currently setting "manually" the valeu for `date` attribute on both Poll::Recount and Poll::PartialResult to `Date.current`, when we could just rely on the automatic `created_at` timestamp. Check `/app/controllers/officing/results_controller.rb` lines 58 and 74

**Comment by aitbw** [comment]
I'll take this one.

**Comment by bertocq** [comment]
As we talked, we'll refactor this at higher level
