### ISSUE TITLE
Admin - Delete valuator role

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2091]
Background
===

Admin can assign **valuator** role to users on `/admin/valuators` but can't remove it.

What
==

- Adds an "Actions" column on valuators table list to allow remove the valuator role. (You can use as reference the managers section on `admin/managers`

- Adds specs to check this new feature 🙏 

Screenshot
==
**We want this** 😌 

<img width="1238" alt="admin_valuators" src="https://user-images.githubusercontent.com/631897/31824899-c89c3caa-b5b0-11e7-819a-af0aab077391.png">

**Comment by aitbw** [comment]
I'll take this.

**Comment by decabeza** [comment]
@aitbw perfect! 👍 but maybe you have to wait to this https://github.com/consul/consul/pull/2089 is merged (to avoid conflicts) 😬

**Comment by bertocq** [comment]
Closed via #2110 👏
