### ISSUE TITLE
Admin - Searches  

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2092]
Background
==

🔍 On some search forms on admin panel you can search by **user name** and **user email** but in other you only can search by email 😔 

What
==

- Allow search by **name** and **email** on following admin sections:

  - Administrators `/admin/administrators`
  - Moderators `/admin/moderators`
  - Valuators `/admin/valuators`
  - Managers `/admin/managers`

- Don't forget to include specs testing this feature 🙏 

**Note**: for reference this is already done on Officials `/admin/officials`, Organizations`/admin/organizations` and Users section `/admin/users`.

**Comment by aitbw** [comment]
I'm gonna handle this one

**Comment by decabeza** [comment]
Closed by #2105
