### ISSUE TITLE
Remove Admins from login on officing panel

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2097]
Admins shouldn't be able to login in the officing panel if they don't have a Poll::Officer associated to their users. 

Fix it at  https://github.com/consul/consul/blob/master/app/controllers/officing/base_controller.rb#L10
```
  def verify_officer
    raise CanCan::AccessDenied unless current_user.try(:poll_officer?) || current_user.try(:administrator?)
  end
```

By removing `|| current_user.try(:administrator?)` and increasing test coverage to check the positive and negative scenario.

Reason: All the Officing panel controllers assume the current_user has a poll_officer associated.

**Comment by decabeza** [comment]
Closed by https://github.com/consul/consul/pull/2098
