### ISSUE TITLE
Can't confirm user: undefined method `encrypted_password' for nil:NilClass

### ISSUE THREAD

**Issue by domk** [consul/consul#2116]
Hi there,

I have pulled sources from repo and started the consul server following instructions on the installation page. However, when I try to create a user using email address and I copy/paste the URL given in the dumped email message in the console to confirm the email, I've got the following error:

> undefined method `encrypted_password' for nil:NilClass

Is there any bug here or did I miss something in the setup?

**Comment by decabeza** [comment]
Hi @domk I don't know what happened, we have to investigate... Meanwhile when you sign up you can look on `tmp/letter_opener/HASH/rich.html` and use the url provided in this HTML file (different of url given on console and this yes is working)

Thanks for the report! 😉

**Comment by domk** [comment]
Great! Thanks @decabeza! It does work.

**Comment by voodoorai2000** [comment]
Hey @domk!

Yes, that's related to the ASCII encoding used for emails. I don't think it can be fixed.
https://stackoverflow.com/questions/4016067/whats-a-3d-doing-in-this-html

In the development environment, you should see the email that @decabeza commented, popping  up in your browser thanks to the letter_opener gem https://github.com/ryanb/letter_opener

In the staging and production environments, you should receive the email in your email client.

If you don't have the email configuration setup and want to look at the logs to extract the confirmation link, you can check out the users's confirmation token in the database and adapt the url. There are probably these extra characters: "3D  in the confirmation token generated in the logs.

**Comment by javierm** [comment]
Closed via #3432.
