### ISSUE TITLE
API - Add comments from polls

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2122]
What
===
- Add to the GraphQL API comments from [polls](https://github.com/consul/consul/blob/master/app/models/poll.rb#L1)

How
===
- Update [this scope in comment.rb](https://github.com/consul/consul/blob/master/app/models/comment.rb#L31) 
- Don't forget to [update the specs too](https://github.com/consul/consul/blob/master/spec/lib/graphql_spec.rb#L284) 😌 
- Check out the [GraphQL docs](https://consul_docs.gitbooks.io/docs/content/en/features/graphql.html) for more info about queries and GUIs 

Why
===
To provide interesting content to nice peoples doing research about how to make better discussions

Go, Go, Go [ICDemocracia17](https://twitter.com/hashtag/ICDemocracia17)!

**Comment by bertocq** [comment]
Closed via #2148 👏  @xuanxu !
