### ISSUE TITLE
Improve Banners management

### ISSUE THREAD

**Issue by jesushp** [consul/consul#2141]
# What
Implement additional capabilities to help admins create and manage campaign banners.

# Why
Current banner creation lacks flexibility and campaign management is unable to avoid stacking different campaigns displayed at the same time on the same page.

# How
Banner creation process could be improved for example, including a color picker to choose the background. 
Banner management could be improved by setting the number of impressions to display it, and also rotating banners within different positions, as others CMS like [Joomla provide with their core modules](https://docs.joomla.org/Help38:Components_Banners_Banners_Edit).

**Comment by bertocq** [comment]
Thanks for proposing this @jesushp !!

You're right that on the current state of Consul this features are needed to avoid forks to make too much custom html static pages as we do on Madrid's fork to solve this kinds of requirements (for example this current PR that removes three campaigns from welcome page https://github.com/AyuntamientoMadrid/consul/pull/1029)

But I think, as you say with the reference to Joomla, that this is more like a CMS feature than a participation software feature. And currently in our minds is growing an idea that we should start a path of migration into a Rails Engine that will allow consul to be treated as another Gem on a Rails app... that would make it possible to pick any CMS gem, and use it to manage all the required pages of that Rails app, along with the features that Consul has... without having to implement CMS features inside Consul itself.

So, I would say that, yes this is needed! We can solve the non-technical people problem adding this feature right now, but in the long run the full content management problems will be covered by that move onto a gem, to enable forks to just create whatever they need and add the consul features as any other admin panel/security/cms/etc.. gem

**Comment by decabeza** [comment]
We already have the PR https://github.com/consul/consul/pull/2319 to improve this features and a new issue 😉 

Closed in favor to https://github.com/consul/consul/issues/2755
