### ISSUE TITLE
Multilanguage content in Features

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2143]
We need to add support for content in multiple languages on many features, this issue purpose is just to list them all, gathering suggestions and info from the community. We'll chop it into individual issues/tasks afterwards:

- [ ] Allow the User to choose his preferred language from the ones that the installation offers
- [ ] Feature generate content (Polls Title, Questions and Answers)
- [ ] Integration of Google Translator or similar on the view page of Proposals/Debates/Process/Comments...

Please comment with your ideas/suggestions! 🤗

**Comment by aitbw** [comment]
If you'll be needing any help with translations in French, let me know :D

**Comment by bertocq** [comment]
@aitbw you're welcome to contribute on french translations!! https://crwd.in/consul Although this issue is more about supporting content creation on multiple languages on each feature (just clarified title and description a bit more, thanks for making me realize it wasn't clear)

**Comment by bertocq** [comment]
Chopping this into individual issues:
-  Allow the User to choose his preferred language from the ones that the installation offers https://github.com/consul/consul/issues/2435
- Feature generate content (Polls Title, Questions and Answers) https://github.com/consul/consul/issues/2436
-  Integration of Google Translator or similar on the view page of Proposals/Debates/Process/Comments https://github.com/consul/consul/issues/2437
