### ISSUE TITLE
Create "Valuator Manager" rol

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2144]
Actually only Admins can assign Valuators to Budget Investments

That's a task that on some forks needs to be done by a person that shouldn't get full admin privileges. Thus a role that just is able to access the investments and assign Valuator users (one or more) to each of them, would be very helpful

**Comment by rzido** [comment]
When there are several valuators working in same proposal, there is a need to  have a 
Valuator Manager/Coordinator/Supervisor.  Also, when a valuator check the "valuation finished" field a notification e-mail is sent to the author of investment proposal. It could be error prone.  Valuator Manager/Coordinator/Supervisor role and admin should be the only roles that could mark the evaluation as finished.
