### ISSUE TITLE
Improve user search by email/name

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2149]
# Current Behaviour
At the Admin panel, inside any Profile section submenu, searching by email/name doesn't find records if we add a trailing or leading space. 

For example on a clean local installation with `rake db:dev_seed` ran to generate dummy data, if you go to http://localhost:3000/admin/moderators and search ` mod@consul.dev` or  `mod@consul.dev ` you won't find any user, only if you use  `mod@consul.dev`

![search_spaces](https://user-images.githubusercontent.com/983242/33080920-7975a0de-ced9-11e7-989d-b2cef631fbc7.gif)

# Expected Behaviour

Searching by email should ignore leading/trailing blank spaces on the text used to search (either email or name)

**Comment by iagirre** [comment]
I'll go with this.

**Comment by javierm** [comment]
Reopening since it can be considered a bug.
