### ISSUE TITLE
Random order for proposals and debates

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2155]
What
===
- Make random ordering consistent between investments, proposals and debates

Why
===
- Proposals and debates still use a deprecated implementation

How
===
- The [latest implementation](https://github.com/consul/consul/pull/2131) is in investments
- Refactoring the proposal's and debate's controllers and models to use the investment's implementation to display records in random order
- Extract this logic to [model](https://stackoverflow.com/questions/18204565/is-that-a-proper-way-to-refactor-activerecord-fat-models) and [controller concerns](http://elegantbrew.tumblr.com/post/70990048275/controller-concerns-in-rails-4)
- Take into account the scenario ['Random order maintained when going back from show'](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/features/budgets/investments_spec.rb#L175)

**Comment by aitbw** [comment]
I'm gonna handle this one. Should I wait for #2158 to be merged into master first?

**Comment by bertocq** [comment]
Yes @aitbw this is creating big problems in the only fork that's using it, I'm completing and merging that PR today.

**Comment by aitbw** [comment]
I'm gonna take at look at this one
