### ISSUE TITLE
Prevent changes on investments after budget is on final phase

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2159]
When a budget is in "Finished budget" phase, the "Select" buttons on the Budget Investments list should not be allowed to be used to prevent winner recalculations, along with any other thing that should not change... (preventing full investment edit is not a good idea since investment Milestones for example should be possible to still be managed)

![screen shot 2017-11-29 at 12 33 09](https://user-images.githubusercontent.com/983242/33373345-bcdb9f62-d501-11e7-8b41-8377de8ff1d2.jpg)

**Comment by iagirre** [comment]
I'll do this.
