### ISSUE TITLE
Fix in-app notification's exception

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2166]
Steps to reproduce
===
- Login as _user1_  and create a proposal
- Login as _user2_ and add a comment to that proposal
- Login as _an admin_ and hide the proposal
- Login as _user1_ and click on the notifications' icon (🛎)

Expected behaviour
===
- I should see a message, explaining that the notification belongs to a commentable that is now hidden, and therefore the comment for that commentable can not be accessed

Current Behaviour
===
- An exception is raised as the commentable's title can not be found

**Comment by bertocq** [comment]
Closed via #2172
