### ISSUE TITLE
Investment projects execution timeline

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2169]
Related PR
===
- https://github.com/consul/consul/pull/1688

What
===
- [ ] Add images to milestones
- [ ] Add documentos to milestones
- [ ] Allow choosing a date to display for the milestone

**Comment by bertocq** [comment]
Closing in favor of separated issues: 
https://github.com/consul/consul/issues/2175
https://github.com/consul/consul/issues/2174
https://github.com/consul/consul/issues/2173
