### ISSUE TITLE
Add Images to Milestones

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2173]
Related PR
===
- https://github.com/consul/consul/pull/1688

What
===
The admin needs to be able to attach images to milestones so the final user can see them. 

Milestones are managed from the Admin panel from a Investment's detail page (Admin > Participatory budgets > See budget investments (on any Budget of the list) > click on any investment's title link > scroll to the bottom of the page for "Milestone" section)

⚠️ Important! Don't forget to include the `alt=""` attribute for image, also you can include a `class="margin"` to separate correctly from text. 

You have a reference for this on `/admin/polls/new`

How
===
1. [Budget::Investment::Milestone](https://github.com/consul/consul/blob/master/app/models/budget/investment/milestone.rb) needs to be [Imageable](https://github.com/consul/consul/blob/master/app/models/concerns/imageable.rb)

2. The Admin Milestone creation form should let the admin attach an image. 

3. The Admin Milestones list have a new column "Image" that either is empty or has a link to the milestone's image url.

4. If a milestone has an image, the user should see it on the public investment view at the milestones tab (it's between the comments and documents tabs). For now we'll just show the image without much consideration about aesthetics, @decabeza will come afterwards with his magic styling wand to give it a cleaner look :)

Screenshots
===

### Milestone with images
<img width="1020" alt="milestones_images" src="https://user-images.githubusercontent.com/631897/33934107-245c5bc6-dff8-11e7-9857-9cb41189047b.png">

### Admin new milestone with image select
![admin_milestone_image_1](https://user-images.githubusercontent.com/631897/33934122-3360b8e2-dff8-11e7-97e0-abe3eb27a048.png)

![admin_milestone_image_2](https://user-images.githubusercontent.com/631897/33934125-35ec2e0c-dff8-11e7-8217-4f5951658c33.png)

**Comment by iagirre** [comment]
I'll go with this.

**Comment by bertocq** [comment]
Closed via #2186 👏
