### ISSUE TITLE
Add Documents to Milestones

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2174]
Related PR
===
- https://github.com/consul/consul/pull/1688

What
===
The admin needs to be able to attach documents to milestones so the final user can see them. 

Milestones are managed from the Admin panel from a Investment's detail page (Admin > Participatory budgets > See budget investments (on any Budget of the list) > click on any investment's title link > scroll to the bottom of the page for "Milestone" section)

You have a reference of this on `/admin/legislation/processes/new`. Also you can use `class="document-link"` for styles and add `class="text-center"` too.

How
===
1. [Budget::Investment::Milestone](https://github.com/consul/consul/blob/master/app/models/budget/investment/milestone.rb) needs to be [Documentable](https://github.com/consul/consul/blob/master/app/models/concerns/documentable.rb)

2. The Admin Milestone creation form should let the admin attach documents (none, one or multiple). Take into account that issue https://github.com/consul/consul/issues/2171 might appear here as well.

3. The Admin Milestones list have a new column "Documents" that either is empty or has a link to each milestone's document url.

4. If a milestone has documents, the user should see it on the public investment view at the milestones tab (it's between the comments and documents tabs). For now we'll just show a link to each document (with its name as title) without much consideration about aesthetics, @decabeza will come afterwards with his magic styling wand to give it a cleaner look :)

Screenshots
===
### Milestone with document
<img width="617" alt="milestone_doc" src="https://user-images.githubusercontent.com/631897/33934658-dcdcd72e-dff9-11e7-96e3-a4ff817ff3c4.png">

### Admin new milestone with document select
![admin_new_doc_1](https://user-images.githubusercontent.com/631897/33934503-581c9c22-dff9-11e7-80f7-5b4025b710d2.png)

![admin_new_doc_2](https://user-images.githubusercontent.com/631897/33934504-583ebc8a-dff9-11e7-9d67-243a0d075b40.png)

**Comment by iagirre** [comment]
I'll do this.

**Comment by bertocq** [comment]
closed via #2191
