### ISSUE TITLE
Add Dates to Milestones

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2175]
Related PR
===
- https://github.com/consul/consul/pull/1688

What
===
The admin needs to be able to specify a "action date" for a milestone so the final user can see when the milestone action happened (instead of when the milestone was created). To clarify the difference between the creation and action dates: a milestone for "Meeting with citizens" can be created on a monday 15th of July, but it took place on a Saturday 13th of July... and this 13th of July date is the one we want to show to the final user.

We also need to order the milestones in the user facing list (at the investment show view) by the action dates, not the creation dates.

Milestones are managed from the Admin panel from a Investment's detail page (Admin > Participatory budgets > See budget investments (on any Budget of the list) > click on any investment's title link > scroll to the bottom of the page for "Milestone" section)

How
===
1. [Budget::Investment::Milestone](https://github.com/consul/consul/blob/master/app/models/budget/investment/milestone.rb) needs a new `action_date` date attribute that can be nil (just to allow existing milestones without dates to still be valid)

2. The Admin Milestone creation form should let the admin pick a date (mandatory)

3. The Admin Milestones list have a new column "Action Date" that either is empty or has a value.

4. If a milestone has an Action date, the user should see it on the public investment view at the milestones tab. For now we'll just display the date (correctly localized like `l(milestone.action_date, format: :short)` without much consideration about aesthetics, @decabeza will come afterwards with his magic styling wand to give it a cleaner look :)

Screenshots
===
### New milestone
<img width="632" alt="milestone_new" src="https://user-images.githubusercontent.com/631897/33933576-6f773aec-dff6-11e7-8569-cef829e228ca.png">

### Date on milestone
![milestone_date](https://user-images.githubusercontent.com/631897/33933599-8355d67c-dff6-11e7-82fb-8df8b596aef0.png)

**Comment by aitbw** [comment]
I'm gonna go with this one.

**Comment by bertocq** [comment]
closed via #2188
