### ISSUE TITLE
Add related content actions on relationed content lists

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2193]
When visiting a relationable resource, for each element in the list of related contents, show the correspondent actions for each of them. For example if the list includes a proposal, show the support button for it... and if its a debate show the 👍  and 👎  ones...

Not sure if this needs a bit of design, I'll assume just adding buttons will be okey but anyways adding label

**Comment by javierm** [comment]
Closig due to inactivity and because it still needs design.
