### ISSUE TITLE
Use images for social meta tags

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2197]
Background
===

Now when a user share a CONSUL's page by default shows a general image.

### Share on Facebook
![facebook](https://user-images.githubusercontent.com/631897/34053532-74890dbc-e1c7-11e7-8111-287a9d544e31.png)

### Share on Twitter
![twitter](https://user-images.githubusercontent.com/631897/34053536-7716dc30-e1c7-11e7-89e7-fc7097c22c38.png)

What
===

If the user has uploaded an image to their proposal or budget investment show this image when share on social networks instead of default image.

How
===

On **proposals/show.html.erb**:  

- Adds `twitter_image_url` and `og_image_url` properties on `render "shared/social_media_meta_tags"` (only if proposal image is present)

On **investments/_investment_show.html.erb**:

- Adds `shared/social_media_meta_tags` partial (use proposal as reference)

- Adds `twitter_image_url` and `og_image_url` properties on `render "shared/social_media_meta_tags"` (only if investment image is present)

**Comment by aitbw** [comment]
I'll handle this.
