### ISSUE TITLE
Removes all "Link to additional documentation" on forms

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2204]
Background
==

With the new feature for upload documents (and after fixing the [multiple-document upload bug](https://github.com/consul/consul/issues/2171)) the **"Link to additional documentation"** input on forms should be removed.

What we need
==

- Remove `external_url` from proposals form (for users and management views)
- Remove `external_url` from budget investments form (for users and management views)
- Create a **rake task** to move all existing `external_url` to description of the item (see screenshot)

Screenshot
===
### This is the old external url
![old additional info](https://user-images.githubusercontent.com/631897/34735635-6d2558ac-f570-11e7-94a0-2ca87c52c760.png)

### After the rake task is moved to description
![screen shot 2018-01-09 at 19 09 37](https://user-images.githubusercontent.com/631897/34735711-aa5e101a-f570-11e7-914c-99e926f41f6e.png)

### And the users use the new docs tab
![screen shot 2018-01-09 at 19 07 40](https://user-images.githubusercontent.com/631897/34735727-b5bce04e-f570-11e7-9e54-cf7d754f570c.png)

Notes
==
Add a note at Deprecated section of Changelog to warn about those `external_url` columns being removed from database in the v0.14 release, and the necessity to run the rake task after migrating to v0.13

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by javierm** [comment]
Closed via #3397.
