### ISSUE TITLE
Add configuration for recommended lists of proposals and debates

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2212]
Notes
==

**This issue is started in https://github.com/AyuntamientoMadrid/consul/pull/1389, please continue there.**

Background
===

Now with the new feature `Setting['feature.user.recommendations']` a recommended list is displayed on welcome page.

What we need
===

Display this recommendations on `debates/index` and `proposal/index` views.

- The recommendations on  `debates/index` shows only **recommended debates**.

- The recommendations on  `proposals/index` shows only **recommended proposals**.

- A new setting for each one:

  - `Setting['feature.user.recommendations_on_debates']`
  - `Setting['feature.user.recommendations_on_proposals']`

Pending ⚠️ 
==========
- Make the **X close icon** functional to hide the recommendations.
- Add in "My account" two **checkboxes to enable/disable** this new features.

Screenshots
===

<img width="1220" alt="debates_close" src="https://user-images.githubusercontent.com/631897/38020518-baca2046-327a-11e8-8cbc-e44f5d59ed47.png">

<img width="623" alt="screen shot 2018-03-28 at 11 37 18" src="https://user-images.githubusercontent.com/631897/38021154-6573561a-327c-11e8-8487-b64fadba37a5.png">

<img width="319" alt="screen shot 2018-03-28 at 11 38 51" src="https://user-images.githubusercontent.com/631897/38021236-a081113e-327c-11e8-820f-078e81412c97.png">

**Comment by aitbw** [comment]
I'll get on what's pending for this one

**Comment by aitbw** [comment]
Closed via #2760
