### ISSUE TITLE
Sitemap tests

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2219]
Background
===

CONSUL use the [sitemap_generator gem](https://github.com/kjvarga/sitemap_generator) to generate a `sitemap.xml` on public folder. This file improves site indexation and SEO.

What we need
===

New specs to:

- Check sitemap generation.
- Check the `sitemap.xml` generated is valid.
- Check this file contains expected and valid urls.

You can use a `before do / after do` to  delete this file each time the specs run to ensure the scenario conditions are pristine before its run, and reset afterwards

Notes
===

To generate a new sitemap we use [`rake sitemap:refresh:no_ping`](https://github.com/consul/consul/blob/master/config/deploy.rb#L65)

**Comment by aitbw** [comment]
I'm gonna go with this one.
