### ISSUE TITLE
Mappable objects

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2220]
Background
===

CONSUL has a new feature to include a map location on some elements (proposals and budgets investments for now). The problem is if the user don't select a location is generating an empty MapLocation.

What we need
===

- Mappables without a location shouldn’t have an empty MapLocation object associated.

- Also we need to create a rake task to destroy all empty MapLocations already created (an empty MapLocation.

- MapLocation model should have validations for both latitude & longitude attributes (and maybe zoom as well) and reflect those in the model spec.

**Comment by aitbw** [comment]
I'm going in with this one :)
