### ISSUE TITLE
Is there a possibility to use the app without census API

### ISSUE THREAD

**Issue by janssja** [consul/consul#2222]
Anyone experience in using the consul App without census API (just authentication through social media oauth).

Thanks a lot!

**Comment by taitus** [comment]
Hi @janssja 

If the objective is to remove the verification, in the administration area in the section "Settings > Global Settings > Features" you can enable/disable the feature:

> Skip user verification: This will disable user verification and all registered users will be able to participate in all processes

**Comment by javierm** [comment]
@janssja Hope that answers your question! Feel free to reopen this issue if it doesn't :wink:.
