### ISSUE TITLE
Enabling RSpec/InstanceVariable

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2268]
[RSpec/InstanceVariable](http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/InstanceVariable) suggests the usage of rspec's `let` over instance variables

I like that, but not sure if @voodoorai2000 or @MariaCheca have a strong opinion about it. 

There are 868 offenses to fix if we enable this cop (I'll gladly volunteer to do it, although we can always start by creating a PR's-welcome issue for it)

Thoughts?

**Comment by voodoorai2000** [comment]
Absolutely @bertocq!
+1 to `let` over instance variables

However, let's try [not to overuse](https://robots.thoughtbot.com/lets-not) `let` and keep tests as atomic as possible 😌

**Comment by bertocq** [comment]
Cop has been [enabled at master](https://github.com/consul/consul/commit/9aa6d646d418335d09d61c8e689add352598d8a7), pending to fix all offenses

**Comment by javierm** [comment]
Closed via #3736.
