### ISSUE TITLE
New "Draft" and "Show budget investment prices" phases for Budgets

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2278]
Background
===

Now the budgets have these phases on admin:
- Accepting projects
- Reviewing projects
- Selecting projects
- Valuating projects
- Balloting projects
- Reviewing Ballots
- Finished budget

What we need
===

Include two new phases:

- One above all **"Draft budget"** (to allow fill all the info before publishing)

- One between "Valuating projects" and "Balloting projects" called **"Show budget investment price"**

This "Show budget investment price" phase have the same behaviour of valuating projects but shows the price on each budget investment. The idea is show the price of all budgets investment at same time before the users can balloting.

**Comment by bertocq** [comment]
Please 🙏  remember to update the issue https://github.com/consul/docs/issues/20 where we've described the "Action" phases and "Bridge" phases, for when we find time to complete the documentation section for real

**Comment by MariaCheca** [comment]
Closed here: https://github.com/consul/consul/pull/2285

**Comment by bertocq** [comment]
Closed by #2296
