### ISSUE TITLE
Admin can't update budget investment

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2286]
Background
===

The admin (and valuator) should be able to update the budget investments **Classification** and **Dossier** on `/admin/budgets/N/budget_investments/X`

What happen
===

- If you try to edit classification `/admin/budgets/N/budget_investments/X/edit#classification` and clic on "Update" the page refresh if you go back doesn't save the new values.

- If you try to edit de dossier '/valuation/budgets/N/budget_investments/X/edit` when clic on "Save changes" and undetermined error appears.

Notes
===
Maybe this _bug_ is related with new location map feature for budget investments.

Screenshot
===

![dossier_error](https://user-images.githubusercontent.com/631897/34719826-86eca7ba-f53c-11e7-8af6-9acd1faeee62.png)

**Comment by MariaCheca** [comment]
These errors seem to be fixed in the most recent version of `master`, so closing 😄
