### ISSUE TITLE
Budget homepage

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2288]
Background
==

Now for participatory budgets we have the following flow:

1. Budget index page with the list of all budgets.
2. Budget show page with the list of groups of this budget.
3. If the budget has more than one group the list of headings of this budget.

What we need
==

We want to merge these pages with this info:

- Header (showing the last budget):
  - Name of budget
  - Description of the current phase
  - Link with an anchor of "Help about participatory budget"
  - Number of current phase (See https://github.com/consul/consul/issues/2289)
  - Name of current phase
  - Link with an anchor of "See all phases"

- Groups and headings:
  - Name of group
  - List of each heading for the group

- Map with all located investment projects (See https://github.com/consul/consul/issues/2300)
- Link to all investment projects
- Link to all unfeasible investment projects
- Link to investment projects not selected for balloting

- List of phases (See https://github.com/consul/consul/issues/2289)

- List of other participatory budgets with a link to "See results"

- Generic help text for budgets.

All content is already created, the job is to put it together on one page.

🙏  Don't worry about styles. I have the CSS for styling when all is in the same page.

Screenshot
==

![budgets_show_2](https://user-images.githubusercontent.com/631897/34733161-af18be56-f567-11e7-92b7-867e761d499f.jpg)

**Comment by iagirre** [comment]
I'll do it
