### ISSUE TITLE
Budget's phases list partial

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2289]
Background
==

We are working on a new Budgets homepage on https://github.com/consul/consul/issues/2288, this page include a new section with the list of all phases.

What we need
===
At https://github.com/consul/consul/blob/master/app/views/budgets/index.html.erb#L99-L102

We'll need a partial that adds the list of published phases from the current budget (that means using [`@budget.phases.published`](https://github.com/consul/consul/blob/master/app/models/budget/phase.rb#L24) and iterate over that result)

For each phase we'll be showing three attributers:
- The translated name using: `t("budget.phase.#{phase.kind}")`
- The `summary` attribute (don't confuse with the `description` attribute)
- The `starts_at` & `ends_at` attributes (if any exists).

There is no great need to totally imitate the screenshot attached, just show the info in the expected order and @decabeza will add his 🎨  afterwards 👍 . But please mark with a CSS class `active` the phase that is the current active one (you can check that with [`phase == @budget.current_phase`](https://github.com/consul/consul/blob/master/app/models/budget.rb#L39)

Screenshots
==

![budgets_phases_front](https://user-images.githubusercontent.com/631897/34734712-0a9e9f16-f56d-11e7-870b-9f49415560a0.jpg)

**Comment by bertocq** [comment]
Okey this is what I've got in mind:

1. Create a Budget::Phase model, related to Budget with a `has_many :phases, dependent: :destroy`, and that has attributes:
- `kind`:given by us internally and used to display the translated name)
- `description`: It will hold the values that are currently at the [`description_*` columns](https://github.com/consul/consul/blob/master/db/schema.rb#L196-L204) of budget table.
- `summary`: It will be the text showing on that new info timeline
- `starts_at` & `ends_at` attributes as suggested by @voodoorai2000 to hold the optional values (stored as dates although in the future we may want datetimes 🤔 ) maybe its time to finally create a "TimeRange" class to hold starts_at && ends_at values as well as classic values validations... started?, current?, ended? etc...)

2. Add an `after_create` on the Budget model that creates on Budget::Phase for each [Budget::PHASES](https://github.com/consul/consul/blob/master/app/models/budget.rb#L6)

3. Allow those budget phases only to be listed on a table and edited (not really sure about where and how... it could be same as Budget Headings/Groups or in a more rails way)

4. Add the budgets phases list partial for the new #2288 page with the "description || dates" showing logic. 

5. Fallback to existing `description_*` columns at the [Budget's `description` method](https://github.com/consul/consul/blob/master/app/models/budget.rb#L34) when the Budget has no `phases`... so already existing Budgets won't become unusable. And create rake task to migrate existing values at `description_*` columns to new Budget::Phase objects

6. Create a separate PR that totally removes `description_*` columns, and add it to milestone v0.14. And write at the Deprecated section of the CHANGELOG.md some notes to warn about the rake that must be run after upgrading to v0.13 and before upgrading to v0.14
