### ISSUE TITLE
Add setting to skip user verification

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2291]
Context
===
- The verification process consists of three steps:
  - Census verification
  - SMS verification
  - Postal Letter verification

What
===
- Allow a configuration option from admin to disable all user verifications
- When this option is activated, all users should be allowed to carry out verified user actions
- The initial welcome page when you sign up and my account should reflect that the user is verified 

Why
===
- In the first few days of setup, forks do not have access to an API to verify that a user is in the city census nor access to the the API for SMS. Having this option will simplify the initial setup

How
===
- Add the setting at /admin/settings
- The main user verification checks are in [verification.rb](https://github.com/consul/consul/blob/master/app/models/concerns/verification.rb). Add checks for this new setting

Screenshots
===
- Initial welcome page when you sign up
![welcome page after sign up](https://user-images.githubusercontent.com/4169/34736694-2583982a-f574-11e7-8fa5-a7107f93460b.gif)

- My account
![my account](https://user-images.githubusercontent.com/4169/34737135-8a2b8994-f575-11e7-981e-f7e8829f30c9.gif)

- Settings
![settings](https://user-images.githubusercontent.com/4169/34737961-f0908e76-f577-11e7-994c-81a7bcfacd8d.gif)

**Comment by vicentemendozam** [comment]
I'll take this one

**Comment by iagirre** [comment]
I'll do this one.

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by lingani** [comment]
Hi all, what is the stage of this issue? I would much appreciate if someone can guide me to contribute. I really need this feature. Thanks!

**Comment by raul-fuentes** [comment]
I made a PR and now we should wait for a review from the mantainers of the repo

**Comment by raul-fuentes** [comment]
You can fork the repo and add the feature if you are in a hurry, or even pull the branch an merge into master

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2399
