### ISSUE TITLE
Map on budget homepage

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2300]
Background
==

We are working on a new homepage for participatory budgets on https://github.com/consul/consul/issues/2288.

What we need
==

From "Accepting projects" phase show a map including markers with a link to all investment projects with location.

Screenshot
==
<img width="1200" alt="map" src="https://user-images.githubusercontent.com/631897/34818324-bb8f412e-f6ba-11e7-8545-66900227bceb.png">

Notes
==
The screenshot show a Google map, but we can use OSM (the same of the new budget investment form)

**Comment by vicentemendozam** [comment]
I'll take this one !

**Comment by bertocq** [comment]
Closed via #2337
