### ISSUE TITLE
Add an alert when finalizing an investment's report

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2308]
What
===
- Add a standard js popup alert when clicking on the "Valuation finished" checkbox of an investment
- Extend the message in the popup alert if the investment has been marked as "Not feasible"

How
===
Text for all alerts when marking as "Valuation finished":
_"Are you sure you want to mark this report as completed? If you do it, it can no longer be modified."_

Additional text for investments marked as "Not feasible":
_"An email will be sent immediately to the author of the project with the report of unfeasibility."_

Screenshots
===
- Accessing the valuation of an investment
![valuating an investment](https://user-images.githubusercontent.com/4169/34839475-faa3f84a-f701-11e7-8dfa-b1be7939f69e.gif)

**Comment by bertocq** [comment]
Closed via #2324 🤖
