### ISSUE TITLE
Add internal comments to investment's from valuators

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2309]
What
===
- Allow valuators to add internal comments to an investment on the admin panel views.

How
===
- Add comments to the admin view of the investments (those will be independent from the public comments by users... and should not be mixed).
- Hide any usage of the current `internal comments` textarea on forms & views at the admin panel
- Create a rake task that migrates the existing values on the deprecated `internal comments` db column to a new initial comment on each investment. The author of that initial comment could be any admin, just `Administrator.first.user` would do fine.
- Internal comments won't need votes
- Internal comments should be listed from oldest to newest (without any other ordering option)
- Valuator's names should be listed with their Alias and ValuatorGroup (if existent)  https://github.com/consul/consul/issues/2362

Screenshots
===
- Internal comments
![internal comments](https://user-images.githubusercontent.com/4169/34840392-2e28f8a2-f705-11e7-92d8-5fb6a67583e2.gif)

- Standard comments
![standard comments](https://user-images.githubusercontent.com/4169/34840395-30989674-f705-11e7-9fb1-3b9ebe12081a.gif)

Bonus
===
To better support forks updates we'll be totally removing the internal comments column & usage at a separate PR for v0.14 release https://github.com/consul/consul/issues/2321

**Comment by raul-fuentes** [comment]
I'll take this one

**Comment by bertocq** [comment]
Still pending: checking notifications for internal valuation comments work okey

**Comment by bertocq** [comment]
Closing as work is completed and only pending task is described at #2508 & https://github.com/consul/consul/issues/2388
