### ISSUE TITLE
Help users to create investments

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2310]
Background
==
During a Participatory Budget, some users get confused and create Citizen Proposals instead of Investment projects.

What we need
==

- This page appears **only** when there is a participatory budget active (on "accepting projects" phase).

- When a user click on "Create a proposal" or "Create budget investment" redirect to a page of info about the main differences between both processes.

Screenshot
==

![budget_intermediate](https://user-images.githubusercontent.com/631897/35061263-02fb225c-fbc1-11e7-8efb-a53eecbcdc0f.jpg)

**Comment by bertocq** [comment]
Closed via #2343
