### ISSUE TITLE
Related content feature improvements

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2313]
- Add tests for pagination.
- Add unit tests for the URL parsing process https://github.com/consul/consul/pull/2311/files#diff-425f221fe6ce9aa980aa360be32b3dc6R47
- Modify this so it's possible to match any model name without having its namespaces separated, so we can avoid confussion reading that and possible problems in the future https://github.com/consul/consul/pull/2311/files#diff-fa45b2f2a800039a50ed400c1e354432R3
- Think another way to call the relationable object path without having in each model a `url` method https://github.com/consul/consul/pull/2311/files#diff-9ac34ad19228b144193b490b99b417aeR54

**Comment by bertocq** [comment]
This issue is related with changes done at #2311

**Comment by javierm** [comment]
This section has changed a lot over the years, most notably in commit c8d8fae98d and pull request #4563, so this issue is a bit outdated.

I'm opening pull request #4757 with the change regarding the `url` method. Will close this issue after that one is merged.
