### ISSUE TITLE
Admin send emails

### ISSUE THREAD

**Issue by rzido** [consul/consul#2318]
Background
==

It’s very important in participation processes to control communications sent.  Now Consul sends several automatic notifications by email to users along the processes. For example, for budgets/spending proposals: 
-	E-mail to author on creation of spending proposal
-	E-mail to authors of unfeasible and feasible spending proposals
-	E-mail to authors of selected and unselected spending proposals

Format and content of these emails is composed with erb files in consul/app/views/mailer/* and localized mailers.yml files. 
  
But many times it is needed to replace texts for each campaign or phase in several languages to add additional information in e-mail content. It can be error prone. Now only IT staff can do that. There is not a easy option for admins to preview how e-mail will look or to create it. A basic and advanced implementation for functional admins could be developed.  

**1.	Basic implementation. Preview e-mail templates.** At least functional administrator should can preview how will look e-mails, for each language available, that will be sended to users for different communication actions related to the process:  creation of spending proposal, notification to authors of unfeasible and feasible spending proposal, notification to author of selected and unselected investments.

Functional admin users could select language and notification action by e-mail and preview a sample e-mail  that will be send to users. Form could be composed by:   

- _Action:_   [select field with available actions] (i.e.  Investment proposal creation e-mail; selected proposal e-mail; ...)    
- _Language:_    [select field with available languages]   (i.e. English, Spanish,...) 
-  _E-mail preview_

**2. Advanced implementation. Edit and preview e-mail templates option.** Create an admin section where functional admins can edit  and preview e-mail templates, for each language available, that will be send on different communication actions of the process.  Form could be composed by:

- _Action_:    	 [select field for available actions] {budget investment created, budget investment unfeasible, budget investment feasible, budget investment selected, budget investment unselected,...}    
- _Language_:  [select field for available languages]  {English, Spanish,..} 
- _To_:   [text field]  {e-mail user(s) variable: author email, all authors emails}  
- _Email Subject_:   [text field]	 {variable or free text}  
- _Email Content_:   [HTML Editor] {free text with variables embedded} 
- _Help_:  a list of all available variables that could be used in email to, subject or content i.e.   {code}, {title}, {author},{link},{org_name}. ...... 
 And link to usage help or guide 

What we need
==

A new section on Admin panel to allow send emails, notifications and download a CSV file with a specific segment of users to use an external service.

- Send emails (this issue)
- Send notifications (see https://github.com/consul/consul/issues/2145)
- Download emails (see https://github.com/consul/consul/issues/2120)

**Notes**:
- It would be nice if we include on the list (see the first mockup) the default emails of the app (registered users, email verification...) to make easier admin to edit them.

- We need to start the following segments:
  - All users
  - Authors of proposals
  - Authors of current budget projects
  - Authors of current budget with a feasible or non decided project
  - Authors of current budget with a selected project
  - Authors of current budget with a winner project

In coming issues we add new segments.

Screenshots
==

![1_admin_newsletters_index](https://user-images.githubusercontent.com/631897/35633577-e14dbad6-06a9-11e8-8892-fc0c7cd5a1b8.jpg)

![2_admin_newsletters_new_edit](https://user-images.githubusercontent.com/631897/35633580-e22605da-06a9-11e8-8628-aa43893a3026.jpg)

![3_admin_newsletters_send](https://user-images.githubusercontent.com/631897/35633582-e2417c66-06a9-11e8-9b2c-0796fa7fae67.jpg)

**Comment by decabeza** [comment]
Hi @rzido, I have expanded the issue and added some screenshots.

I have also linked other open issues 😉

**Comment by aitbw** [comment]
This one is closed via #2462, right?
