### ISSUE TITLE
Allow supporting investments on more than one heading per group

### ISSUE THREAD

**Issue by rzido** [consul/consul#2320]
Background
==

A fork could decide to allow their users to support investment projects in more than a heading (for example district where a user lives and where users works or more). It should be configurable in the admin panel.

What we need
==

### 1. Allow admins to stablish the Max Support Headings value per Budget::Group
In the budgets admin panel, `/admin/budgets/N` include a select to allow user support on more than one heading of the same group:

- The select only appears if the group have more than one heading
- The select shows the number of headings available in the group
- The select is selected  in option `1` by default

### 2. Change current heading support restrictions
Currently users can only support on one heading per group, that may be too hardcoded or assumed in many parts of the code. We have to check that new group.max_votable_headings new value.

How
==
Please wait for https://github.com/consul/consul/issues/2498 & https://github.com/consul/consul/issues/2438  to be completed to base your work on top of it (or just go do it 💪  😄 )

Screenshot
==
![1_edit_group](https://user-images.githubusercontent.com/631897/35875304-189dbd78-0b6f-11e8-84aa-a9e2d480e828.jpg)

![2_edit_group](https://user-images.githubusercontent.com/631897/35875305-18be5998-0b6f-11e8-984e-49fb1033d42c.jpg)

**Comment by decabeza** [comment]
Hi @rzido, I change a little the issue and add a screenshot 😉 

Some notes:

- I changed `spending proposals`(deprecated) to **`investment projects`** the new model for budgets. 
- I changed `district` to **`heading`** (the budgets have groups and the groups headings, maybe some forks don't use district division).

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2546

Note that this issue has been split in two: 
- One for the support phase (merged https://github.com/consul/consul/pull/2546)
- One for the final voting phase (coming soon! https://github.com/consul/consul/issues/2547)
