### ISSUE TITLE
Remove deprecated investment's internal comments

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2321]
As final act of https://github.com/consul/consul/issues/2309 (Migrating internal comments text area to an actual comments thread) We'll be removing the database column from the app.

We just need a migration that removes the column, as well as the total removal of any usage of that column in the code.

But we'll be including this in the v0.14 release, as the v0.13 release will be only including only the rake task that migrates values and hides the usages.

**Comment by raul-fuentes** [comment]
I'll do this one just after finishing https://github.com/consul/consul/issues/2309

**Comment by bertocq** [comment]
Closed by #2404
