### ISSUE TITLE
Budget: add column show to valuators

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2328]
Background
==

Now on `/admin/budgets/N/budget_investments/X/edit#classification` admin users can assign valuators to a budget investment. Once assigned, the valuators can see their assigned budget investments to valuate.

What we need
==
- When the tab `Under valuation` is active, the last column should show **"Show to valuator"** (instead of "Selected") with a checkbox (_view screenshot_).

- The valuators on `/valuation/budgets/N/budget_investments` only should see their assigned budget investments with this checkbox active.

Notes
==

This feature is created on Madrid's fork on [this commit](https://github.com/AyuntamientoMadrid/consul/commit/0fe631dcdb56b57da44cce757f7600c9ee06aa44), use for reference:

- [`admin/budget_investments/_investments.html.erb (I)`](https://github.com/AyuntamientoMadrid/consul/blob/master/app/views/admin/budget_investments/_investments.html.erb#L18-L24)

- [`admin/budget_investments/_investments.html.erb (II)`](https://github.com/AyuntamientoMadrid/consul/blob/master/app/views/admin/budget_investments/_investments.html.erb#L75-L81)

- [`controllers/admin/budget_investments_controller.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/admin/budget_investments_controller.rb#L63)

- [`controllers/valuation/budget_investments_controller.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/valuation/budget_investments_controller.rb#L17)

- [`models/budget/investment.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/app/models/budget/investment.rb#L55)

- [`spec/factories.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/factories.rb#L355)

- [`db/schema.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/db/schema.rb#L193)

🙏  Don't forget specs to this features (references on):

[`features/admin/budget_investments_spec.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/features/admin/budget_investments_spec.rb) and [`features/valuation/budget_investments_spec.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/spec/features/valuation/budget_investments_spec.rb)

Also don't forget to include this on [`dev_seeds.rb`](https://github.com/AyuntamientoMadrid/consul/blob/master/db/dev_seeds.rb#L562-L566)

Screenshot
==
![show_to_valuators](https://user-images.githubusercontent.com/631897/34985978-33f56856-fab6-11e7-8ab7-189481c2b790.png)

**Comment by iagirre** [comment]
I'll do this.
