### ISSUE TITLE
Error trying to deploy on Ubuntu 14.04

### ISSUE THREAD

**Issue by dreadlocked** [consul/consul#2329]
Hi, I've created a consul:consul user for test proposal on psql with CREATEDB premissions granted. I'm following the deploy mini-guide and having an issue with the second rake step `bin/rake db:migrate` (First step finish correctly).

It seems there is an error with the default database definition.

`ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "proposals" does not exist
LINE 5:                WHERE a.attrelid = '"proposals"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"proposals"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
`

**Comment by bertocq** [comment]
Hey @dreadlocked does this same error happen to you at your local machine as well?

**Comment by dreadlocked** [comment]
Sorry, it's soilved. I was using master branch, using v0.12 branch doesn't happend.

**Comment by bertocq** [comment]
@dreadlocked still worries me that master branch has that problem ... 🤔  maybe you where on master branch but not 100% up to date? I can't reproduce the problem either and asked about localhost test just in case it was truly related with the operative system (Ubuntu 14.04) 

Anyway as you have notice... master is no longer "stable" and we may endup renaming it somehow to make it even clearer :D. Nowadays we're finally in a stable release schedule (every 2-4 weeks is our desire) so being up to date with latest release should always be 👌  :)

Thanks for your report anyway ❤️ 🤗
