### ISSUE TITLE
Improve upload documents feature

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2334]
Background
==

Recently we added to CONSUL the upload documents feature. The alert when reach the max documents allowed is a little confusing regarding the UX and we want to improve it.

What we need
==

When a user clicks on "Add new document" and is the last document of `max_documents_allowed` the alert warning `You have reached the maximum number of documents allowed! You have to delete one before you can upload another` appears

1. This alert **should appear only** when user clicks on "Add new document" and we've passed the `max_documents_allowed`  e.g. for `(max_documents_allowed == 3)`:

- _Click "Add new document" --> Appears form for **document 1**_
- _Click "Add new document" --> Appears form for **document 2**_
- _Click "Add new document" --> Appears form for **document 3**_  
- _Click "Add new document" --> **Alert appears**_  

Also change on alert class `warning` to `primary` (indicates better information instead of an error)

2. When the form appears empty show `Cancel` if there is no document and `Remove document` if its already upload.

Screeshots
==
### 1
![docs_1](https://user-images.githubusercontent.com/631897/35039516-64b2e414-fb7e-11e7-801a-6163bbad0c7e.png)

![docs_2](https://user-images.githubusercontent.com/631897/35039521-6631b676-fb7e-11e7-82e1-f51f0f2558a9.png)

### 2
![docs_cancel](https://user-images.githubusercontent.com/631897/35040107-41375f5e-fb80-11e7-878e-26796d16d966.png)

**Comment by vicentemendozam** [comment]
I'll take this one.

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2374
