### ISSUE TITLE
Allow Admins to edit new Budget's Phases

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2339]
# What & Current status
Admins should be able to edit new Budget::Phase models at the admin panel when the enter a Budget. But right now they can only edit old and deprecated `description_*` attributes.

# Expected behaviour

### Budget's Phases table listing
When admins edit a Budget, the should see a table with all (currently 9) Budget Phases. 

Budget::Phases are [auto-generated when the Budget is created](https://github.com/consul/consul/blob/master/app/models/budget.rb#L21-L22) and should NOT be deleted.... so we only need to allow the edit action over them.

### Budget's phases edit form
Each phase should have this fields:
- Name (filled automatically with internal name) CANNOT be edited.
- Start date (optional, but if present it will pass some validations at the Budget::Phase model)
- End date (optional, but if present it will pass some validations at the Budget::Phase model)
- Description (optional, but will get html_safe'd on save)
- Summary (optional)
- Enabled (boolean flag that is defaulted to true). If changed from true to false (disabled) we won't validate dates on save, but if set to true from false (enabled) dates will get validated, and for sure errors can appear.

About dates validations... enabled phases must have consecutive dates, that means whenever a phase ends, the next enabled phase will start at that very moment (same date, yes same day, not the following... the same one).

Some notes that will contradict what you'll see at screenshot/mockup:
- First textarea will be the `summary` attribute obviously, nexxt one is description
- The "Enable description for phase" and "Show this description to users on budget timeline phases" should be changed for `Enabled phase` & `This phase will be public in the Budget's phases timeline, as well as active for any other purpose`

### Budget's edit form:

Also we'll need to change on the budget's edit form:

- Move "Phase" and "Currency" selects to top (after budget name).

- Change button "Update Participatory budget" to "Update budget"

Screenshots
==

### Admin panel
![budgets_phases_admin_4](https://user-images.githubusercontent.com/631897/34781382-f8660cee-f625-11e7-9ebf-ba8918df566e.jpg)

![budgets_phases_admin_4b](https://user-images.githubusercontent.com/631897/34781385-fb4d3f68-f625-11e7-9848-845558063dd3.jpg)

**Comment by MariaCheca** [comment]
Closed here: https://github.com/consul/consul/pull/2353
