### ISSUE TITLE
Create groups of users for valuations

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2362]
What
==
Add the possibility to create groups of users with valuator role, so we can assign the group to the valuation of projects only one time.

- Create valuators groups and assign valuator users to them.
- Allow groups to be created without associated valuators. So groups can be assigned to investments firstly, and afterwards fill the groups with valuators.
- On the admin panel, at the investment page, we need to show the list of  Valuators Groups with a checkbox for each of them (along with the existing valuators list, but without mixing both lists neither relating valuators with groups), to let admins assign either a group or individual valuators (or both). (Think that a valuator may end up assigned to an Investment both directly (individually) and through a group.)

Screenshots
==
**`VALUATORS INDEX`**
![1_valuators_list](https://user-images.githubusercontent.com/631897/35344794-3fb57518-012e-11e8-86a5-ea40b7770b38.jpg)

**`VALUATOR NEW`**
![2_valuators_search](https://user-images.githubusercontent.com/631897/35988621-44c20080-0cff-11e8-9e2c-78af0f5aa2a4.jpg)

**`VALUATOR EDIT`**
![valuators_edit](https://user-images.githubusercontent.com/631897/35986774-4539b1fc-0cfa-11e8-9715-9771ec75e9d5.jpg)

**`VALUATORS GROUPS INDEX`**
![3_valuators_group_list](https://user-images.githubusercontent.com/631897/35344804-4697802e-012e-11e8-8525-ac3877139a99.jpg)

**`VALUATORS GROUPS SHOW`**
![3b_valuators_group_show](https://user-images.githubusercontent.com/631897/35991650-2005ef1e-0d08-11e8-89de-5ce1ae536f04.jpg)

**`VALUATORS GROUPS NEW`**
![4_valuators_group_new](https://user-images.githubusercontent.com/631897/35344809-492c2358-012e-11e8-9787-52ba055a3037.jpg)

**`VALUATORS ADMIN ASSIGN`**
![5b_valuators_assign](https://user-images.githubusercontent.com/631897/35990257-c2dd6b22-0d03-11e8-8afb-50eb3523b985.png)

**Comment by bertocq** [comment]
My initial approach was wrong (asking about User Groups) as I didn't realize that `Valuators` aren't just users or the same as `Users` but more like "User Profiles" as Administrators or Moderators. Those models store additional info & logic about a role/profile that an user may have for a period of time and even when the user is removed from the platform the relevant historic info will be kept (but as anonymized as possible)

So with the implementation I had in mind and @voodoorai2000 started at https://github.com/consul/consul/compare/valuator-groups?expand=1 we would have a very generic & reusable User Group, but the logic to decide which users could be added to a Group would be something like "users that have a profile associated of type `self.kind`" ... making it not as reusable as I thought (for any scenario where you don't need to limit group members by profile but by other logic) ... and now I'm seeing the big red *YAGNI* sign and thinking the amount of effort is not going to be worth it as we're really not allowing any future changes to be easier. 🙇 sensei Raimond!

I think Valuator::Group & Valuator::Group::Member may be the way to go, and I'm only concerned about the way to add Valuators to Groups... as the mockup https://user-images.githubusercontent.com/631897/35344797-4117a9c6-012e-11e8-9d3a-e149f3ad8f2f.jpg assumes we'll be adding valuators to groups as we assign a valuator profile to an user... what about existing valuators? 

Maybe just adding an "Edit" button at the Valuators list to select the group could be the best as we've already there the search box. Adding a "Filter by group" selector on that list would make things easier as well, and we could link to that list filtered by group directly from the Valuators Groups list with a "see valuators list" link. @decabeza what do you think about it?

**Comment by bertocq** [comment]
We'll need additional backports after #2510 is done:

- https://github.com/AyuntamientoMadrid/consul/pull/1358
- https://github.com/AyuntamientoMadrid/consul/pull/1357
- https://github.com/AyuntamientoMadrid/consul/pull/1359
