### ISSUE TITLE
Undefined method `legislation_proposal_path' in comments#show

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2364]
Find out what could make this error appear coming from `/notifications` area: 
```
NoMethodError: undefined method `legislation_proposal_path' for #<#<Class:0x0000000acf5558>:0x0000000ca4f6a8>
File "[...]/app/helpers/application_helper.rb" line 44 in back_link_to
File "[...]/app/views/comments/show.html.erb" line 3 in _app_views_comments_show.html.erb
```

**Comment by aitbw** [comment]
Fixed in AyuntamientoMadrid#1189, backport PR is pending

**Comment by bertocq** [comment]
Yes @aitbw we've a ongoing backport at https://github.com/consul/consul/pull/2464/commits/d6385c0c855762db4b5c982a6d8db6696bed04c9 but its going to take a while to review and merge

**Comment by aitbw** [comment]
Don't worry, @bertocq; the comment was just to keep track of what's done :D

**Comment by MariaCheca** [comment]
Same issue duplicated here: https://github.com/AyuntamientoMadrid/consul/issues/1189
