### ISSUE TITLE
Show investment links only on balloting or later

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2377]
Show [List of all investment projects](https://github.com/consul/consul/blob/master/app/views/budgets/index.html.erb#L93) and [List of all investment projects not selected for balloting](https://github.com/consul/consul/blob/master/app/views/budgets/index.html.erb#L99) links if the current budget is on Balloting phase or later (reviewing_ballots or finished)

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2386
