### ISSUE TITLE
Backport Budgets homepage map fixes

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2389]
We need to backport the fixes for the budgets homepage map from https://github.com/AyuntamientoMadrid/consul/pull/1162 back to Consul 😁

**Comment by vicentemendozam** [comment]
I'll take this one!

**Comment by aitbw** [comment]
I'm gonna go with this one :)

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2654
