### ISSUE TITLE
Filter investments by feasibility aggregating results

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2396]
What
===
- Aggregate results when filtering by feasibility
For example, if you mark "unfeasible" and "undecided" investments, both unfeasible and undecided investments should appear in the results

Screenshots
===
![filter by feasibility](https://user-images.githubusercontent.com/4169/35530390-384ad174-0534-11e8-9a9e-b9568e16ee9a.gif)

**Comment by aitbw** [comment]
I'll do this one, @voodoorai2000. Just one question: Is there a limit on how many filters an user can apply? Or should it work for all combinations?

**Comment by voodoorai2000** [comment]
Appreciate it @aitbw! 🎉  
All combinations 👌
