### ISSUE TITLE
Combine free text search and filters

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2400]
Related PRs
===
https://github.com/consul/consul/pull/2378
https://github.com/consul/consul/pull/2344

What
===
- Allow combining free text search with the other filters

GIF
===
![combine filters](https://user-images.githubusercontent.com/4169/35565337-75b0edbc-05bd-11e8-9db8-1118757d39c6.gif)

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by raul-fuentes** [comment]
after a few days hunting flakies I return to this task

**Comment by raul-fuentes** [comment]
after a few days hunting flakies I return to this task

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1276
