### ISSUE TITLE
Fix /admin/comments internal error

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2412]
If you open `http://localhost:3000/admin/comments` you'll get a internal server error:

![screen shot 2018-01-31 at 18 13 04](https://user-images.githubusercontent.com/983242/35636879-d2beff12-06b2-11e8-8800-f5e007531255.jpg)

## We need:
- [ ] A feature spec that covers that page (and fails without the fix)
- [ ] Changes in the code to fix both the new test failure and the error on page access

**Comment by aitbw** [comment]
I'm on it.

**Comment by bertocq** [comment]
Seems we fixed it without knowing it :) Nice one @aitbw  😅
