### ISSUE TITLE
Trim down duplicated strings from translation files

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2418]
We should be using more and more shared strings on translations to avoid having tens of "Email" or "User" or some common words repeated across multiple yml files. That would improve translators work.

Since some words may not have same meaning depending of the context... we should be conservative on this one and go step by step from the most universal ones like "Email".

Feel free to send a PR that just solves some of them, better than a massive one that tries to clean everything at once (it will may get into debates/comments that will slow down approval and merge conflicts may appear)

**Comment by javierm** [comment]
Closing in favor of #2093, which is a bit more specific. Maybe after we do that one we can look at what remains to be done, but I think the main problems would be addressed with #2093 :thinking:.
