### ISSUE TITLE
Generate RSS feeds for created contents

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2426]
- https://ruby-doc.org/stdlib-2.3.2/libdoc/rss/rdoc/RSS.html#module-RSS-label-Producing+RSS or a gem?
 - xml/atom feed for proposals/debates/investments/polls

Maybe I'm the only one that still uses RSS reader (http://newsblur.com/ from https://github.com/samuelclay/NewsBlur in particular) to filter and funnel all the info/news I'm interested in (even twitter)

**Comment by javierm** [comment]
Closing since this issues hasn't had any activity for almost 2 years and there are no plans to add it in the near future.
