### ISSUE TITLE
Integrated translating service for user generated content

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2437]
Even if we allow users to create content in multiple languages once we have https://github.com/consul/consul/issues/2436 implemented.... many of the won't speak all languages offered at an installation. So we need to offer users a way to translate user-generated-content in place.

Integrating Google Translator (or explore other alternatives) at the view pages of Proposals/Debates/Process/Investments/Comments...

We can start by having a prototype PR  that just adds this to a single element (Comment could be easy enough, but any would do), and after that we can move on adding it to all possible resources.

**Comment by javierm** [comment]
Closed via #3359.
