### ISSUE TITLE
Allow Budget Groups edit

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2438]
Currently Budget Groups can only be created at `/admin/budgets/:budget_id` but there is no admin UI to modify the name afterwards. This issue will enable future work at https://github.com/consul/consul/issues/2320

## What we need
- Edit button for each Group
- Inline form that allows changing & saving Group's name

## How
- Tests, check how we're already covering Budget Group Heading inline edit form on that page
- Code that satisfies those tests

## Screenshots

![edit_group](https://user-images.githubusercontent.com/631897/35821249-a6a96152-0aa8-11e8-8c78-8c4baf3bbb58.png)

![edit_group_2](https://user-images.githubusercontent.com/631897/35821250-a6d798c4-0aa8-11e8-8578-46a8a8afeabe.png)

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2504
