### ISSUE TITLE
Use user locale to format currency

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2442]
## Current behaviour
All currencies are formatted using the default locale language (I18n.default_locale) instead of the user selected language:

![screen shot 2018-02-06 at 11 11 07](https://user-images.githubusercontent.com/983242/35853900-1f12df3e-0b2f-11e8-8264-84e837e1714e.jpg)

## Expected behaviour

Use the user language to format currencies 
![screen shot 2018-02-06 at 11 20 15](https://user-images.githubusercontent.com/983242/35854108-bb59d870-0b2f-11e8-81b3-68a858d6b30c.jpg)

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by bertocq** [comment]
@raul-fuentes there's a PR open already that only has pending tests to be completed

**Comment by raul-fuentes** [comment]
I'm blind

**Comment by bertocq** [comment]
Closed by #2443
