### ISSUE TITLE
statusCode=500, statusMessage='Internal Server Error'

### ISSUE THREAD

**Issue by kissdragon-z** [consul/consul#2457]
when i use spring-cloud-consul , i found one exception as 
Error watching Consul CatalogServices com.ecwid.consul.v1.OperationException: OperationException(statusCode=500, statusMessage='Internal Server Error', statusContent='rpc error: EOF') at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:122) at com.ecwid.consul.v1.catalog.CatalogConsulClient.getCatalogServices(CatalogConsulClient.java:108) at com.ecwid.consul.v1.ConsulClient.getCatalogServices(ConsulClient.java:320) at org.springframework.cloud.consul.discovery.ConsulCatalogWatch.catalogServicesWatch(ConsulCatalogWatch.java:65)

the resource is :
RawResponse rawResponse = this.rawClient.makeGetRequest("/v1/catalog/services", new UrlParameters[]{queryParams});

the client was written by Java . but [statusCode=500] means when query something from consul, the server has something wrong.

i don't know about go. i want to konw stability about consul when 1000+ Apps run. (we have 5 servers)
and how to solve this problem

**Comment by bertocq** [comment]
Wrong repo @kissdragon-z you'r looking for https://github.com/hashicorp/consul
