### ISSUE TITLE
ERB Linting tool

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2467]
I've tried https://github.com/katgironpe/rails-erb-lint over the codebase and got:
> 600 files, no invalid files :clap:
But that one seems to just check erb file format... 

After checking https://github.com/bbatsov/rubocop/issues/1113 seems like best option would be: https://github.com/ericqweinstein/ruumba but as mentioned there is not very efficient in performance

But for now it may be good enough to findout many issues like:
- Trailing whitespaces
- Inconsistent indentations
- Unused block arguments
- etc... that rubocop offers

We may need to do some extra research for a better tool.. if not just start making small PR's to cleanup files or rules one by one

**Comment by bertocq** [comment]
Two issues to talk about when deciding rules for erb files:
-  https://github.com/consul/consul/pull/2462#discussion_r167923222
- https://github.com/consul/consul/pull/2465#discussion_r168513974

**Comment by javierm** [comment]
Closed via #3379 and #3629.
