### ISSUE TITLE
Admin Budgets investment search filters not working

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2471]
In the admin section for Budget investments, combining the above selects (Select administrators, valuators, headings, etc) with the advanced filters is not possible.

It should be able to use them at the same time.

**Comment by aitbw** [comment]
I'm on it.

**Comment by raul-fuentes** [comment]
is already resolved in the pr https://github.com/AyuntamientoMadrid/consul/pull/1276 (as we are told, we should resolve the issues on AyuntamientoMadrid/consul/ and then backport here)
