### ISSUE TITLE
Include valuators group in admin budgets "Download current selection"

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2472]
In the Budgets admin section, add the valuators group in the data generated when the administrator uses the "Download current selection" button, currently it only shows the individual valuator.

**Comment by raul-fuentes** [comment]
I'll do this one

**Comment by bertocq** [comment]
We've to wait for @voodoorai2000 to backport Valuator Groups PR https://github.com/AyuntamientoMadrid/consul/pull/1248 to finish https://github.com/consul/consul/issues/2362 before the PR that solves this (https://github.com/AyuntamientoMadrid/consul/pull/1287) can be backported to Consul

**Comment by raul-fuentes** [comment]
So I'll wait until that happens :)

**Comment by voodoorai2000** [comment]
Good to go @raul-fuentes https://github.com/consul/consul/pull/2510

**Comment by raul-fuentes** [comment]
There is currently a valuation_group in the csv, related with the model through valuator_group_assignments. Isn't it the requested data? . The other solution that I can think is showing all the groups related to any valuator to the investment, but I don't known if it's make sense.

**Comment by bertocq** [comment]
Don't worry about this @raul-fuentes it was already done & refactored at https://github.com/consul/consul/pull/2592 but forgot to link this issue
