### ISSUE TITLE
Admin newsletters: send a maximum number of emails at a time

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2473]
This issue is related to https://github.com/consul/consul/issues/2318 **and must be performed after it's done.**

Let the newsletters mailer send a maximum number of emails at a time to prevent being identified as spam in case there are too much emails being sent at the same time.

**Comment by bertocq** [comment]
Do some research around the idea behind https://stackoverflow.com/questions/42366391/how-to-send-mails-to-5-user-per-minute-using-delayed-job/42367624#42367624

**Comment by javierm** [comment]
Issue #2623, which was closed via #2802, was a duplicate of this one, so I'm closing this one too.
