### ISSUE TITLE
Let users mark Notifications as read

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2478]
What we need
==
Allow users to mark their notifications as read individually. 

Also, include two new tabs to separate "Unread" notifications and "All notifications" (with notifications read)

Screenshots
==
![1_new_notifications_tabs](https://user-images.githubusercontent.com/631897/36542053-0ed4d998-17e0-11e8-8418-51b1176b33bd.png)

![2_new_notifications_tabs](https://user-images.githubusercontent.com/631897/36542054-0ef14592-17e0-11e8-9149-be43bc857385.png)

![3_new_notifications_tabs](https://user-images.githubusercontent.com/631897/36542237-8f6d7c9a-17e0-11e8-9b54-a498b7b56d85.png)

![4_new_notifications_tabs](https://user-images.githubusercontent.com/631897/36542181-60fe66da-17e0-11e8-9e09-9b3f2accdcea.png)

**Comment by bertocq** [comment]
We need a backport of the PR AyuntamientoMadrid#1304 from madrid's fork to include this functionality and close the issue

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2549
