### ISSUE TITLE
Remove from emails list those with email digest disabled

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2480]
For the user segments used to download emails lists from admin, those users who have disabled any email notification must be excluded.

**Comment by bertocq** [comment]
Apart from `newsletter` we've the following flags:
```
email_on_comment
email_on_comment_reply
email_on_proposal_notification
email_digest
email_on_direct_message
```

Does it mean an user with everything to `false` should not be included?

**Comment by bertocq** [comment]
no longer needed
