### ISSUE TITLE
Let managers reset user's password

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2500]
What we need
==
The manager should have a button to "reset password" for user:

![1_reset_password](https://user-images.githubusercontent.com/631897/37405115-1e989bb2-2794-11e8-9917-ae9c14f495d0.png)

There are two options:

1. *If the user has an email present (and its one that he controls)* 
Show a form with the button "Send reset password email" So the user will get a link that he can use to stablish a new password. This is useful when the user didn't have an email or not one that he controls... and the manager just fixed it for him (this is already described at issue https://github.com/consul/consul/issues/2499)

![2_reset_password](https://user-images.githubusercontent.com/631897/37405116-1eb2a084-2794-11e8-8274-7c8ec2c430ae.png)

2. *If the user doesn't have an email (or doesn't control/use it)*
This would show the Manager a form with:
- A "Password" input that shows in plain text the password and lets him type a new one by request of the user or his own will. There should be a "help text" next to it explaining that after saving it we'll offer him to "Print password" so there's no need to write it down right now.
- A "Generate random password" next to the input would be great, in the case the citizen doesn't need to have a "memorable" or "human readable" password.
- A "Save button"

![3_reset_password](https://user-images.githubusercontent.com/631897/37405117-1ed2af6e-2794-11e8-9fc4-f049e69e669b.png)

After hitting "Save" the Manager should have a "Print password" button that allows the manager to easily print the new password (we're not storing it in plain text... so somehow "store" it in session or somewhere) as an empty html page or pdf or... whatever its easier!

![4_reset_password](https://user-images.githubusercontent.com/631897/37405118-1eed220e-2794-11e8-80ef-b517799f84b4.png)

**Comment by iagirre** [comment]
I'll do it

**Comment by iagirre** [comment]
@decabeza I have two doubts regarding the UI:
1. Where should I put the buttons for reseting the password and showing the password form? Should I follow the same style as described in #2499 (both in the rigth side of the square)?
2. If the buttons are placed in the grey square, they must appear every time or only when the user is in `management/account`?

**Comment by decabeza** [comment]
Hi @iagirre! I updated the issue and included some mockups 😉

**Comment by bertocq** [comment]
Another "automagically closed" that shouldn't :( 

Please @iagirre a backport to consul whenever you have the time to entirely close this issue 😃

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2548

**Comment by KrzysztofMadejski** [comment]
Where was this implemented? Can't find this feature..

**Comment by decabeza** [comment]
Hi @KrzysztofMadejski this feature was implemented on https://github.com/consul/consul/pull/2548 (you can see some attached gifs of how it works). 

The URL to access to **Management** section is `/management` you can access with an admin user or a user with manager role.
