### ISSUE TITLE
Fix user email address change

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2511]
As we discovered at madrid's fork (https://github.com/AyuntamientoMadrid/consul/issues/1320) user has problems updating his email address.

This has already been resolved and we'll need a backport of the fix https://github.com/AyuntamientoMadrid/consul/pull/1324

**Comment by aitbw** [comment]
Don't forget to close this one up, guys!

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2569
