### ISSUE TITLE
Backport `visible_to_valuators` feature from madrid's fork

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2514]
[Madrid's fork](https://github.com/AyuntamientoMadrid/consul) has a feature that allows admins to set if a valuator should be able (or not) to see an investment. Just search `visible_to_valuators` in that codebase and you'll find all related code.

**Comment by javierm** [comment]
It seems to be a duplicate of #2328, which was closed by #2342. This issue was created before the latter was merged.
