### ISSUE TITLE
Flaky spec: Emails Budgets Unselected investment

### ISSUE THREAD

**Issue by aitbw** [consul/consul#2519]
# What

Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 60023

**Travis failed build:** [Travis CI build 20248, job 2](https://travis-ci.org/consul/consul/jobs/349988228)

**Failure:**

```
  1) Emails Budgets Unselected investment
     Failure/Error: expect(email).to have_subject("Your investment project '#{investment.code}' has not been selected")
       expected the subject to be "Your investment project '2018-9' has not been selected" but was "Your investment project '2018-8' has not been selected"
     # ./spec/features/emails_spec.rb:454:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- [How to Deal With and Eliminate Flaky Tests - Semaphore](https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests)

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

**Comment by MariaCheca** [comment]
Closed via https://github.com/consul/consul/pull/2695
