### ISSUE TITLE
Flaky spec: Officing Results Edit result

### ISSUE THREAD

**Issue by aitbw** [consul/consul#2520]
# What

Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 5891

**Travis failed build:** [Travis CI build 824, job 2](https://travis-ci.org/wairbut-m2c/consul/jobs/350063830)

**Failure:**

```
  1) Officing Results Edit result
     Failure/Error: select booth_name, from: 'officer_assignment_id'
     
     Capybara::ElementNotFound:
       Unable to find visible select box "officer_assignment_id" that is not disabled
     # ./spec/features/officing/results_spec.rb:100:in `block (2 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- [How to Deal With and Eliminate Flaky Tests - Semaphore](https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests)

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

**Comment by javierv** [comment]
I can confirm this test fails when executed right before midnight, as it happened on issues like AyuntamientoMadrid#1195. It's possible to reproduce it locally using [Timecop](https://github.com/travisjeffery/timecop), like so:
```ruby
feature 'Officing Results' do

  background do
    Timecop.freeze(Date.current.at_end_of_day) # Today at 23:59:59
    @poll_officer = create(:poll_officer)
    # ...
   end

  scenario 'Add results' do
    Timecop.freeze(Time.now + 1.second) # Tomorrow at 00:00:00; makes the test fail
    visit officing_root_path
    # ...
  end

  after do
    Timecop.return
  end
```
To fix it, one option would be freezing time with Timecop and another option would be stubbing `Date` and `Time` methods, like done in AyuntamientoMadrid#1342

**Comment by MariaCheca** [comment]
Closed via https://github.com/consul/consul/pull/2712
