### ISSUE TITLE
Improve test suite, move away from PhantomJS

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2523]
PhantomJS is dying or near to https://github.com/ariya/phantomjs/issues/15344

Headless Chrome is here to stay

We should do the swap, and maybe in the process we'll get rid of many random failing specs because of JS and phantomjs & flaws

**Comment by aitbw** [comment]
I'll get on it :)

**Comment by bertocq** [comment]
@aitbw  this is just an idea for improvement, not an urgency! We still have a ton of flaky failures at https://github.com/ayuntamientomadrid/consul/issues?q=is%3Aissue+is%3Aopen+label%3A%22Flaky+spec%22+sort%3Aupdated-desc that will improve development in the short term, and have a bigger impact in the test suite
