### ISSUE TITLE
Add timestamps Budget Headings & Groups tables

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2541]
Budget::Heading & Budget::Group tables need timestamps (created_at & updated_at columns)

**Comment by aitbw** [comment]
I'll do this one. Quick question: Should I develop this issue [here](https://github.com/AyuntamientoMadrid/consul) first, am I right?

**Comment by Shaun-Schwartz** [comment]
Created a pull request for this here: https://github.com/consul/consul/pull/2594
