### ISSUE TITLE
Remove hardcoded madrid's fork reference

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2544]
At https://github.com/consul/consul/blob/af1ce339c75b58ae71916fe6cb5bb5f1197bf6ba/app/views/budgets/investments/index.html.erb#L43 we have a harcoded url from madrid's fork, possibly from a bad backport from a feature that was done there. 

We need to figure what url should be showing the on a generic consul site (if any) and replace it

**Comment by javierm** [comment]
Closed via #2567.
