### ISSUE TITLE
Allow voting investments on more than one heading per group

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2547]
Following issue https://github.com/consul/consul/issues/2320 completion

We'll need the same functionallity but for Votes instead of Supports. Prior to this we should complete https://github.com/consul/consul/issues/2498 with a better implementation than https://github.com/consul/consul/pull/2503 that follows existing pattern like Budget::Ballot::Lines that is currently used for supports

**Comment by javierm** [comment]
Closed by #2546.
