### ISSUE TITLE
Enable Rubocop's Security/Open cop & fix issue

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2571]
After [upgrading rubocop up to 0.53.0](https://github.com/consul/consul/pull/2524) there is a new [Security/Open](https://github.com/bbatsov/rubocop/blob/master/manual/cops_security.md#securityopen) cop that should be enabled explicitly and the only issue/offense fixed.

It was done at https://github.com/consul/consul/pull/2524/commits/0fe99d1dfeff51f1357bbc21d549a6571013129d and you can just cherry-pick that commit to start the work. But its not 100% clear that the fix at lib/sms_api.rb is the right way to solve the issue/offense... this should be manually tested (the sms api) in a fork that has the feature running in preproduction to be sure.

**Comment by javierm** [comment]
Reopening since there's an active pull request that implements this issue.
