### ISSUE TITLE
Setting for disable upload documents feature

### ISSUE THREAD

**Issue by rzido** [consul/consul#2579]
# Background

Recently it was added to CONSUL the upload and view documents feature in budget investments. In admin/settings section it is possible to disable upload images feature but it is not possible to disable upload documents feature.

# What we need

Create a setting to disable upload documents feature in budget investments or to establish maximum number or size of documents to be upload.

**Comment by bertocq** [comment]
@rzido enable/disable document setting has been done & merged in consul, but the second part of the issue (as I explained) has been extracted on to https://github.com/AyuntamientoMadrid/consul/issues/1417

**Comment by bertocq** [comment]
The second part of the issue has been extracted to https://github.com/consul/consul/issues/2584,

**Comment by bertocq** [comment]
@rzido enable/disable document upload has been added to consul https://github.com/consul/consul/pull/2585

**Comment by rzido** [comment]
@bertocq Thank you for resolving this issue so fast.  You all are doing a great work with Consul.
