### ISSUE TITLE
How to archive a proposal?

### ISSUE THREAD

**Issue by orlyco** [consul/consul#2582]
How am I as a manager can archive a proposal?

**Comment by voodoorai2000** [comment]
Hey @orlyco!

Proposals are archived automatically after a certain period
You can setup this period in the url /admin/settings within the option _Months to archive Proposals_

The best places to ask for functional questions are [Gitter](https://gitter.im/consul/consul?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or the [Community](https://community.consulproject.org/) 👌
