### ISSUE TITLE
Improve admin settings with help texts

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2587]
Many values at the Admin settings panel sections `Configuration settings` and `Features` would be easier to understand with the addition of an optional "help text" displayed under the item name. 

For example at `Allow upload and show of attached documents` a text underneath "This only affects final users creating Budget Investments or Proposals. Admins will still be able to attach documents to Milestones and Legislation Processes"

**Comment by decabeza** [comment]
Done on https://github.com/consul/consul/pull/2821 🎉
