### ISSUE TITLE
Fix `max_per_heading` filter in admin budget investments list

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2588]
The advanced filter "Max supports per heading" of the Investments list `max_per_heading` is not working properly. 
![screen shot 2018-04-10 at 18 47 40](https://user-images.githubusercontent.com/983242/38571069-c2ed2b7c-3cef-11e8-9c35-779a59092053.jpg)

The expected behaviour for the filter is: The list should only display investments with an number of supports equal or greater than the value introduced at the "Max supports per heading" input.

We also have to change it's name to "Minimum supports".

**Comment by aitbw** [comment]
Closed via #2799

**Comment by decabeza** [comment]
Closed via #2799
