### ISSUE TITLE
Update CKEditor to version 5

### ISSUE THREAD

**Issue by MariaCheca** [consul/consul#2591]
Currently CONSUL is using the `4.7.1` version of CKEditor, but the [v5 has many improvements and new features](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/whats-new.html).

It would be interesting to update to this new version and write more complete and prettier texts!

**Comment by decabeza** [comment]
Duplicated with https://github.com/consul/consul/issues/2495, already in progress! 🎉
