### ISSUE TITLE
Password strength adviser

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2596]
Not sure about what rules to enforce... (i.e minimum length, inclusion of numbers and letters, etc...) because it should be configurable (at least via code...) the amount of rules and the types (optional or mandatory to be met)

A nice addition could be the usage of https://github.com/philnash/pwned

**Comment by aitbw** [comment]
Further reading regarding this topic can be found on [this article](https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/) by Dropbox —quite lengthy but extremely worth it
