### ISSUE TITLE
Fix rspec-mocks deprecation warning

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2597]
When running the test suite a deprecation warning is prompted:
```
Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /spec/shared/models/document_validations.rb:36:in `block (2 levels) in <top (required)>'.
```

**Comment by aitbw** [comment]
This deprecation warning is already fixed in AyuntamientoMadrid/consul#1362. I'm waiting for the PR to be reviewed and merged in order to backport it here :smile:

**Comment by bertocq** [comment]
Yes! You're right Angel, sorry I kept forgetting about that PR! I remembered I had somewhere a reference to this deprecation warning but I was searching for PR's instead of issues :( its a duplicated of https://github.com/AyuntamientoMadrid/consul/issues/1120 but we'll keep it open just to remember to create the backport for that great PR.

**Comment by decabeza** [comment]
Done on https://github.com/consul/consul/pull/2888 🎉
