### ISSUE TITLE
Add button on admin to see budget results

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2603]
Background
==
Once the voting phase for a budget has finished, admins can click a button to calculate the winner investments

What
==
Once the winners have been calculated we would like to have a button linking to public results

How
===
- Sign in as an admin
- Go to the /admin section
- Click on Participatory Budgets
- Click on Edit budget
- Change the budget phase to 'Reviewing Ballots'
- Click on 'Calculate winner investments'
- Go back to editing a budget (/admin/budgets/2/edit)
- Add the button to see public results (/budgets/2/results)

Screenshots
===
![screen shot 2018-05-09 at 16 05 44](https://user-images.githubusercontent.com/631897/39819147-fb59561a-53a2-11e8-9016-914fadba868b.png)

Notes
===
Check out the [contributing guidelines](https://github.com/consul/consul/blob/master/CONTRIBUTING.md) 😉

**Comment by atzorvas** [comment]
I'll do this :)

**Comment by atzorvas** [comment]
Some questions,

* we may hit calculate, but we may not have a winner, what do we do in that case?
* is it necessary to have a winner? or can we simplify this by saying "if it's in balloting or in finished phase, then show the button"? This eliminates the headache in the first bullet

**Comment by atzorvas** [comment]
How is this any different from what #2620 implements?

**Comment by decabeza** [comment]
Hi @atzorvas,

> we may hit calculate, but we may not have a winner, what do we do in that case?

You can show an alert with "There are no investment projects with votes and winner can't be calculated."

> is it necessary to have a winner? or can we simplify this by saying "if it's in balloting or in finished phase, then show the button"? This eliminates the headache in the first bullet

No. But if there are no projects with votes you can show the alert. The button "Calculate winner investment" should appear only if the budget is on `reviewing_ballots` or `finished` phase (I think this is already done).

> How is this any different from what #2620 implements?

On #2620  the "See results" button always appears, the idea of this issue is show this "See results" button only if the results has been calculated.

**Comment by atzorvas** [comment]
@decabeza you can assign me then :)
