### ISSUE TITLE
Add a message to unselected and unfeasible budget investments

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2604]
What we need
==

From "Reviewing projects" phase add a message to unselected and unfeasible budget investments show `/budgets/N/investments/X` indicating to users that this budget investment doesn't go to balloting phase.

Screenshots
==
![ballot](https://user-images.githubusercontent.com/631897/39239907-9af1811a-4882-11e8-8091-c3e82699f13a.jpg)

![select](https://user-images.githubusercontent.com/631897/39239910-9c88abd4-4882-11e8-8494-7f1561eeee82.jpg)

**Comment by microweb10** [comment]
I can work on this one. 
I wonder if you already have the message strings somewhere or if you leave the messages up to me

**Comment by decabeza** [comment]
@microweb10 @bertocq mockups updated with the correct texts 😉

**Comment by microweb10** [comment]
@decabeza I have this ready for PR for a while now, but I have a question about the translations (config/locales)
I haven't contributed for more than a year now, and before you only had 2 translations (EN & SP), but I see a lot of them now.
Do I have to add manually all translations?

**Comment by bertocq** [comment]
@microweb10 don't worry, only English translations are enforced [and required by specs](https://github.com/consul/consul/blob/master/spec/i18n_spec.rb#L1) (we should make this more explicity on a Pull Request checklist 🤔 )

Translations for additional languages will be added by translators at https://crwd.in/consul, so don't worry about languages you aren't fluent on ;) English (+ Spanish) its more than 👌 🙇

**Comment by microweb10** [comment]
@decabeza probably you shouldn't make that more explicitly, probably I should read a little bit more. Sorry about that.

Anyway I wanted to let you know that I have only added the English messages cause I don't really know how you want to make it in Spanish, but if you let me know the messages in here I can add them to the PR https://github.com/consul/consul/pull/2614

**Comment by decabeza** [comment]
Hi @microweb10 the texts in Spanish:

`Este proyecto de inversión ha sido marcado como inviable y no pasará a la fase de votación.`

`Este proyecto de inversión no ha sido seleccionado para la fase de votación.`

😉

**Comment by microweb10** [comment]
Done! Gracias!!!!

**Comment by atzorvas** [comment]
@decabeza should we close this issue since the respective PR is merged?

**Comment by decabeza** [comment]
Thanks! @atzorvas 😉 

For next PR's it's nice to use the text `This PR closes N` and the issue is closed automatically when merged ☺️
