### ISSUE TITLE
Replaces icons of expand/collapse comments

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2605]
Background
==

Now on all item with comments we use an arrow to expand/collapse comments.

Background
==

Replaces arrow icon with plus/minus icons to expand/collapse comments.

Screenshots
==

**Actual icons**
![screen shot 2018-04-18 at 13 29 15](https://user-images.githubusercontent.com/631897/38929486-c080c66e-430c-11e8-9daa-4cb2aaf42e11.png)

![screen shot 2018-04-18 at 13 29 18](https://user-images.githubusercontent.com/631897/38929487-c09f2b2c-430c-11e8-9305-cc7387df7bb5.png)

**Replace to this ones**
![screen shot 2018-04-18 at 13 28 47](https://user-images.githubusercontent.com/631897/38929506-ce2650cc-430c-11e8-84fd-58d028fdf2e0.png)
![screen shot 2018-04-18 at 13 28 59](https://user-images.githubusercontent.com/631897/38929508-ce4294f8-430c-11e8-9623-f615df36b664.png)

**Comment by jesushp** [comment]
It would be useful to reflect all that kind of decisions on a common place, as to speak, a Design System.
