### ISSUE TITLE
Adds help to draft version of legislation processes

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2606]
What we need
==

Including some help to indicates to users they can comment the text of legislation process
`/legislation/processes/N/draft_versions/X`.

Screenshot
==

We can use something similar to (it would be nice create a gif for each locale):

![annotator_help](https://user-images.githubusercontent.com/631897/38929640-4d4c45b4-430d-11e8-9580-63f5af36234e.gif)

**Comment by bhack** [comment]
https://web.hypothes.is
https://web.hypothes.is/about/

**Comment by bhack** [comment]
Also if a discussion need to be organized over a modification proposal/comment check:
https://words.democracy.earth/thecaseforcanonicaldebate-34811166bbb0

**Comment by bhack** [comment]
Check also https://github.com/opengovfoundation/madison/blob/master/docs/README.md

**Comment by decabeza** [comment]
Closed by https://github.com/consul/consul/pull/2732.
