### ISSUE TITLE
Move search forms to sidebar

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2607]
Background
==

Now each section has a search form, always show on the sub-navigation bar and makes the UI a little messy.

What we need
==

Moves these searches forms to the sidebar (repositioning the "mode view" selector and the "advanced search link").

Screenshot
==

![search_sidebar](https://user-images.githubusercontent.com/631897/38930190-4e621e4a-430f-11e8-9215-ba16e922892c.jpg)

**Comment by javierm** [comment]
Closing since implementing this issue causes problems on mobile phones, and it's harder to find the search field in the sidebar.
