### ISSUE TITLE
consul_test not found

### ISSUE THREAD

**Issue by jcbcmpsmt** [consul/consul#2609]
Hi.
I'm installing consul with many problems but now I'm having no error messages, however the http connection is no working at all (no response) . Backinp up the installation proccess, I'm having problems with "RAILS_ENV=test bin/rake db:setup" command and I obtain this error message
"/usr/local/rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize': FATAL:  no existe la base de datos «consul_test»
".
I have created consul_test from PostgreSQL client and then the message is "Called from /usr/local/rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.5.1/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:457:in `load': /usr/local/rvm/gems/ruby-2.5.1/gems/devise-3.5.10/app/controllers/devise/sessions_controller.rb:5: syntax error, unexpected '{', expecting keyword_end".
Which file(s) must I trace to understand what it's happening with this service?

**Comment by bertocq** [comment]
Hi @jcbcmpsmt is there any public consul fork we can check to help you?

Anyway if you follow the installation steps one by one you shouldn't have any issues https://consul_docs.gitbooks.io/docs/content/es/getting_started/local_installation.html

Please start over and when mention on which step you stopped and which error the app gave you. Normally the error message is pretty descriptive as the one you've pasted... The second error message pasted makes me think there was a change in your consul codebase that broke it but can't debug what I can't see

**Comment by voodoorai2000** [comment]
This is probably due to using Ruby 2.5, which is not yet fully supported. 
Please make sure you are using Ruby 2.3 for now 🙏
