### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2611]
What
===
Make CONSUL Multitenant

How
===
We suggest using the [apartment gem](https://github.com/influitive/apartment)

Here are a [couple](https://medium.freecodecamp.org/building-a-multi-tenant-app-is-easy-if-you-have-an-apartment-3465f6eda85b) of [articles](http://dev.edenspiekermann.com/2016/09/09/rails-multitenant-site/) and a [screencast](https://gorails.com/episodes/multitenancy-with-apartment) on how to set it all up

Basic things to take care of per tenant:
- [ ] Separate database
- [ ] Subdomain
- [ ] Settings
- [ ] Logo and styles
- [ ] Postal Codes
- [ ] Census

Screenshots
==

![1_tenant_select](https://user-images.githubusercontent.com/631897/39259065-d787ae00-48b5-11e8-9873-75865d8187b1.png)

![2_tenant_select](https://user-images.githubusercontent.com/631897/39259067-d7a51260-48b5-11e8-9082-26addd4b3248.png)

![3_tenant_select](https://user-images.githubusercontent.com/631897/39259068-d7c02898-48b5-11e8-8276-53f0cc4ca257.png)

<img width="1670" alt="4_tenant_admin" src="https://user-images.githubusercontent.com/631897/39259070-d7f1ee96-48b5-11e8-86ab-90eac8bf9dec.png">

**Comment by sbernhard** [comment]
Another possibility instead of having a "full multi-tenant" implementation would be, to have something like groups for each category (polls, content, ...). A user can then be assigned to a group (or many). Means, same database, but divided through user access rights together with groups.
