### ISSUE TITLE
Add Imagemagick to Docker configuration

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2612]
References
===
**Related PR:** https://github.com/consul/consul/pull/2127

What
===
Install ImageMagick in initial Docker configuration script

Why
===
It is required for the upload image functionalities

**Comment by iagirre** [comment]
I'll do this.

**Comment by aamarill** [comment]
Hello,

I am looking to make my first open source contribution. Is this a good issue to take on?
If not, feel free to point me other issues that might be good for someone that's new to open source.
Thanks!

**Comment by voodoorai2000** [comment]
Hello @aamarill!

Thank you very much for wanting to contribute to CONSUL 😌 
And welcome to the marvellous world of open source 🎉 

This issues is already been worked on by @iagirre 
Would you like to do this one https://github.com/consul/consul/issues/2603? 👍

**Comment by aamarill** [comment]
@voodoorai2000 thanks! I'll have a look ASAP.

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1473

**Comment by voodoorai2000** [comment]
Pending Backport

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2655
