### ISSUE TITLE
Display only selected budget investments in publishing prices phase

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2617]
References
===
Backport: https://github.com/AyuntamientoMadrid/consul/pull/1454

What
===
During the publishing prices phase only selected investments should be displayed by default

**Comment by aitbw** [comment]
I'll get on it

**Comment by aitbw** [comment]
Don't forget to close this one

**Comment by voodoorai2000** [comment]
Thank you @aitbw ;)
Closed via https://github.com/consul/consul/pull/2657
