### ISSUE TITLE
Allow author notifications to be moderated

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2618]
Context
===
Authors of proposals can create notifications[1] for their supporters.

What
===
Allow this notifications to be moderated[2] by admins and moderators.

How
===
Something similar to how comments and proposals are moderated:
- There should be a link to 'hide notification' from the user interface.
- Once a notification has been hidden, it should be visible in the moderation section like the other moderated content.

[1] http://localhost:3000/proposals/1#tab-notifications
[2] http://localhost:3000/moderation

Screenshots
==

### Screenshot 1 (user interface)
<img width="1235" alt="notifications_front" src="https://user-images.githubusercontent.com/631897/39997170-3eebe31a-5782-11e8-95e2-370cfe042ed3.png">

### Screenshot 2 (moderation interface)
<img width="1673" alt="moderation" src="https://user-images.githubusercontent.com/631897/39997168-3c19ba04-5782-11e8-9195-6e371d5562d9.png">

**Comment by iagirre** [comment]
I'll do this one.
