### ISSUE TITLE
Admin forms improvements

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2624]
Background
==

Some forms on Admin panel need minor changes to make easier to understand.

Notes
==

⚠️ Wait to https://github.com/AyuntamientoMadrid/consul/pull/1451 is merged and backported to this repo.

What we need
==

1. Move "Show results and stats" form from `/admin/polls/N/edit` to `/admin/polls/N/results`. _[screenshot_1]_

2. Remove "Link to external video" from `/admin/questions/new` (now the admin can include a video on each answer). _[screenshot_2]_

3. Change "physical booth" checkbox on `/admin/booths/new` to a select with following options:
 _[screenshot_3]_
    - Physical booth (ballot boxes)
    - Digital booth (voting directly in a tablet or computer)

4. Sort alphabetically the booth list on `/admin/polls/N/booth_assignments/manage` and include pagination if the list is greater than 300.  _[screenshot_4]_

5. Remove "information header" field on `/admin/legislation/processes/N/proposals`. _[screenshot_5]_

6. When create a new budget on `/admin/budgets/new` select by default "Draft" phase instead of  "Accepting projects". _[screenshot_6]_

Screenshots
==
**Screenshot 1**
![sc1](https://user-images.githubusercontent.com/631897/39935593-d1df7c44-5549-11e8-8078-a7ae640265b5.png)

**Screenshot 2**
![sc2](https://user-images.githubusercontent.com/631897/39935589-d1541636-5549-11e8-9438-3328a644bbeb.png)

**Screenshot 3**
![sc3](https://user-images.githubusercontent.com/631897/39935588-d131353a-5549-11e8-858d-3aef8578e661.png)

**Screenshot 4**
![sc4](https://user-images.githubusercontent.com/631897/39935590-d1757d30-5549-11e8-95c7-b6daacdfc1bc.png)

**Screenshot 5**
![sc5](https://user-images.githubusercontent.com/631897/39935591-d18f5f8e-5549-11e8-8841-6eca46c4beb8.png)

**Screenshot 6**
![sc6](https://user-images.githubusercontent.com/631897/39935592-d1b071ce-5549-11e8-88eb-dcf908d70592.png)

**Comment by aitbw** [comment]
Just to be entirely sure: the 4th point of this issue says pagination should start after having over 300 booths —that seems a little excessive. Is this correct or a typo?

**Comment by decabeza** [comment]
Yes @aitbw, 300 it's correct! 😉 (This allow see all available booths without use pagination)

**Comment by aitbw** [comment]
Great, @decabeza. I'll make the PR in a moment :relaxed:

**Comment by dlddld** [comment]
Hi

¿"PHYSICAL BOOTH" check finally exists? I see that it's referenced on documentation, but I can't find it on app. 
Thanks

**Comment by Senen** [comment]
Hi @dlddld, that checkbox you have seen at screenshots is something specific to DecideMadrid fork and does not exist in Consul, it seems that this part of the documentation is not accurate since all the booths are physical booths associated with an address.

**Comment by dlddld** [comment]
aah ok ok, thank you
