### ISSUE TITLE
Basic content for i18n on admin

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2625]
Background
==

Recently we include the possibility of include translatable content for budget milestones from admin panel.

- Reference issue: https://github.com/consul/consul/issues/2436
- Refrence PR: https://github.com/consul/consul/pull/2619

What we need
== 

Include some basic content i18n to allow admin include the necessary customization or language from admin panel.

For this first implementation we need to include on Admin panel the following keys:

### budgets.yml
```shell
budgets.index.section_footer.description
budgets.index.section_footer.help_text_1
budgets.index.section_footer.help_text_2
budgets.index.section_footer.help_text_3
budgets.index.section_footer.help_text_4
```

### community.yml
```shell
community.topic.sidebar.recommendation_one
community.topic.sidebar.recommendation_two
community.topic.sidebar.recommendation_three
```

### devise.yml
```shell
devise.registrations.destroyed
```

### devise_views.yml
```shell
devise_views.mailer.confirmation_instructions.title
```

### general.yml
```shell
debates.index.section_footer.description
debates.index.section_footer.help_text_1
debates.index.section_footer.help_text_2
debates.index.section_footer.help_text_3

debates.new.recommendation_one
debates.new.recommendation_two
debates.new.recommendation_three
debates.new.recommendation_four

layouts.footer.accessibility
layouts.footer.conditions
layouts.footer.privacy

proposals.index.section_footer.description
proposals.index.section_footer.help_text_1
proposals.index.section_footer.help_text_2
proposals.index.section_footer.help_text_3
proposals.new.form.submit_button
proposals.new.more_info
proposals.new.recommendation_one
proposals.new.recommendation_two
proposals.new.recommendation_three

proposals.proposal.reason_for_supports_necessary

polls.index.section_footer.description
polls.index.section_footer.help_text_1
polls.index.section_footer.help_text_2

```

### guides.yml
```shell
- All keys
```

### legislation.yml
```shell
legislation.processes.index.section_footer.description
legislation.processes.index.section_footer.help_text_1
legislation.processes.index.section_footer.help_text_2
legislation.processes.index.section_footer.help_text_3
```

### mailers.yml
```shell
- All keys
```

### management.yml
```shell
management.print.proposals_info
management.print.proposals_note
management.print.proposals_title
management.print.budget_investments_info
management.print.budget_investments_note
```

Screenshots
==
![admin_translate](https://user-images.githubusercontent.com/631897/40110069-5916fab2-58ff-11e8-8f86-9c400064029d.png)

**Comment by iagirre** [comment]
This issue only requires adding the I18n keys, or it's also needed to create the admin page that appears in the mockup?

**Comment by decabeza** [comment]
Hi @iagirre, the i18n keys already exist, the idea is to move them and create this new page to allow admins to manage these translations through admin interface without the need of change yml files.

😌

**Comment by iagirre** [comment]
Oh! OK, I got it.
I'll got with it :)

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2809
