### ISSUE TITLE
[Backport] Add admin budget stats

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2630]
References
===
- Backport: https://github.com/AyuntamientoMadrid/consul/pull/789
- Related: https://github.com/AyuntamientoMadrid/consul/issues/1472

What
===
- Add an admin section displaying number of votes per heading in the support and balloting phases

Screenshots
===
![admin budget stats](https://user-images.githubusercontent.com/4169/40076291-d083f068-587e-11e8-8b1e-6cfd66775ebc.png)
![admin single budget stats](https://user-images.githubusercontent.com/4169/40076290-d06361c2-587e-11e8-9538-994fa14a48b3.png)
![admin budget more stats](https://user-images.githubusercontent.com/4169/40076289-d0422340-587e-11e8-99a8-f5b0135640ad.png)

**Comment by javierm** [comment]
Closed via #3499.
