### ISSUE TITLE
Custom pages doesn't show the links

### ISSUE THREAD

**Issue by Cheomm88** [consul/consul#2636]
# Steps to reproduce

1- Create a custom site with links, titles, etc 
2- Check in database that links and style is saved.
3- Open the new site custom from your bowser.
4- Links and style doesn't appear.

# Expected behaviour

1- Create a custom site with links, titles, etc 
2- Check in database that links and style is saved.
3- Open the new site custom from your bowser.
4- Links and style appears

# Current Behaviour

The style from the site custom doesn't appear.

# Possible fix:

Modify when the description text is shown in https://github.com/AyuntamientoMadrid/consul/blob/e906402cdffa61e79f1a5665d7b1eeb156c6d26e/app/views/pages/custom_page.html.erb#L11 to raw

**Comment by decabeza** [comment]
This issue is related with https://github.com/consul/consul/issues/2495

**Comment by javierm** [comment]
Closed via #2876.
