### ISSUE TITLE
Docker says "Error installing bundler"

### ISSUE THREAD

**Issue by KrzysztofMadejski** [consul/consul#2646]
Stacktrace:
```
/home/consul # docker-compose build
database uses an image, skipping
Building consul
Step 1/12 : FROM coreapps/ruby2.3
 ---> 3074051e1ce0
Step 2/12 : RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client nodejs
 ---> Using cache
 ---> 7e32bfa14b6c
Step 3/12 : ENV RAILS_ROOT /var/www/consul
 ---> Using cache
 ---> 345c75317173
Step 4/12 : RUN mkdir -p $RAILS_ROOT/tmp/pids
 ---> Using cache
 ---> 72389cdb1d78
Step 5/12 : WORKDIR $RAILS_ROOT
 ---> Using cache
 ---> c73d7e323535
Step 6/12 : COPY Gemfile Gemfile
 ---> Using cache
 ---> fbfe2e51d3ef
Step 7/12 : COPY Gemfile.lock Gemfile.lock
 ---> Using cache
 ---> d4022feff47f
Step 8/12 : COPY Gemfile_custom Gemfile_custom
 ---> Using cache
 ---> aa7a76eb8c1b
Step 9/12 : RUN gem install bundler
 ---> Running in ca514423ee5d
ERROR:  Error installing bundler:
    "bundle" from bundler conflicts with /usr/local/bin/bundle
ERROR: Service 'consul' failed to build: The command '/bin/sh -c gem install bundler' returned a non-zero code: 1
```

**Comment by KrzysztofMadejski** [comment]
Deleting `RUN gem install bundler` helped, but the question is, is it the right way to go?

**Comment by aitbw** [comment]
Hey @KrzysztofMadejski, thanks for this issue. Came across the exact same problem a few weeks ago but thought it was only me —I too solved it by removing the `RUN gem install bundler` line

Could you please tell us a little bit about the system you're trying to create the Docker image?

For now, we'll be needing:

* OS and its version
* Docker version
* Docker Compose version

I'll take care of this as soon as possible but if you happen to find a solution first, feel free to submit a PR :smile_cat:

**Comment by KrzysztofMadejski** [comment]
Ubuntu 16.04 Server 
Docker Version: 18.02.0-ce 
docker-compose version 1.18.0, build 8dd22a9

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2661
