### ISSUE TITLE
Not possible to delete or rename a heading group for a participatory budget

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#2651]
![capture d ecran 2018-05-25 a 11 55 16](https://user-images.githubusercontent.com/7223028/40538663-9596a9be-6012-11e8-8094-8a54ab6918b8.png)

Title is self explanatory, there is no button to edit or delete a heading group for a participatory budget.

**Comment by decabeza** [comment]
Hi @PierreMesure we included this feature in the last release (0.15.0), you can see in our [Changelog](https://github.com/consul/consul/blob/master/CHANGELOG.md) .

Also you can see the PR: [Allow Budget Group names to be edited](https://github.com/consul/consul/pull/2504) 😉 

Now the new Admin interface is:

![1](https://user-images.githubusercontent.com/631897/40624002-51767238-62aa-11e8-9262-b825ae715788.png)

![2](https://user-images.githubusercontent.com/631897/40624003-51a3efec-62aa-11e8-8d27-8b49b811bdb8.png)

**Comment by PierreMesure** [comment]
This is fixed since 0.15
