### ISSUE TITLE
Moves static pages content to site customization

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2656]
Background
===

Now in CONSUL, there are some static example pages: 

```
help   
  faq
    index.html.erb
  how_to_use
    index.html.erb
accessibility.html.erb 
census_terms.html.erb 
conditions.html.erb 
general_terms.html.erb
privacy.html.erb
```

What we need
===

⚠️ Wait to https://github.com/consul/consul/issues/2495 is merged to start this issue.

Move these pages to Admin Panel site customization pages to allow admin users edit this pages easily.

- Maintain `pages/custom_page.html.erb` file for static text pages.
- Delete the rest of these pages of the list.
- Moves the content of these pages to pages created with "admin/site_customization/pages".
- Generate this content from `dev_seeds.rb`.
- Remove unused keys of `locales/*/pages.yml`.
- Remove unnecesary content of `config/routes.rb`.

Screenshots
==

![custom_pages](https://user-images.githubusercontent.com/631897/40657376-edcb11e6-6347-11e8-8715-d9f93346ae33.png)

**Comment by javierm** [comment]
Closed via #3353.
