### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by jsperezg** [consul/consul#2660]
I'm trying to execute a dockerized image without any success. When I try to build the images it fails with the following error

```bash
docker-compose build
...
ERROR:  Error installing bundler:
	"bundle" from bundler conflicts with /usr/local/bin/bundle
```

**Comment by jsperezg** [comment]
I've changed the image used to:

FROM ruby:2.3.6

and it works like a charm. If there is no objectioin about changing the image I will commit a PR in order to fix it.

**Comment by aitbw** [comment]
Hey @jsperezg, thanks for opening your very first issue in CONSUL :tada:

This was already reported by @KrzysztofMadejski over #2646 

Your suggested patch sounds good but we have #2631 pending review which includes Ruby 2.4.1 :-(

Nevertheless, I encourage you to research for a fix and submit your PR :smile_cat:

**Comment by jsperezg** [comment]
@aitbw I contrubuted to Decidim as well  and helped them to improve their docker/docker-compose support. I've created a PR with lots of  enhancements/improvevents.
