### ISSUE TITLE
Unable to open settings page

### ISSUE THREAD

**Issue by MarcEwert** [consul/consul#2664]
I checked out the v0.15 tag and running it using docker-compose, but i am not able to reach the admin settings page under `http://<consul_url>/admin/settings`. It only shows following error:

> Showing /var/www/consul/app/views/admin/settings/index.html.erb where line #5 raised:
> `undefined method 'each' for nil:NilClass`

It is an almost fresh consul instance.

Any ideas how to fix this?

**Comment by voodoorai2000** [comment]
Hey @MarcEwert,

If you are running docker compose I assume you are running this instance in a development environment. Try regenerating the settings with `bin/rake db:dev_seed`

**Comment by MarcEwert** [comment]
Thanks @voodoorai2000 for your help!

`bin/rake db:dev_seed` does the trick. But i would use like to use docker-compose for a production environment as well. Is there any chance to get dockered Consul running with a clean environment?

**Comment by voodoorai2000** [comment]
Great! 🎉My pleasure 😌 

Sure maybe one day we will have full support for Docker in production environments, for now we recommend using the [installer](https://github.com/consul/installer) 👌

**Comment by MarcEwert** [comment]
Allright, thanks for the hint! :+1:
