### ISSUE TITLE
Create dev seeds to homepage

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2667]
Background
==

Now on admin section is possible to configure the homepage content in `/admin/homepage`.

What we need
==

Include the following content on `dev_seeds` as an example of the homepage.

**Header card**
Label (optional): Welcome to
Title: CONSUL
Description: Free software for citizen participation.
Link text: More information
Link URL: help_path

**Cards**
Label: Debates
Title: How do debates work?
Description: Anyone can open threads on any subject, creating separate spaces where people can discuss the proposed topic. Debates are valued by everybody, to highlight the most important issues.
Link text: More about debates
Link URL: https://youtu.be/zU_0UN4VajY

Label: Citizen proposals 
Title: How do citizen proposals work?
Description: A space for everyone to create a citizens' proposal and seek supports. Proposals which reach to enough supports will be voted and so, together we can decide the issues that matter to us.
Link text: More about proposals
Link URL: https://youtu.be/ZHqBpT4uCoM

Label: Participatory budgets
Title: How do participatory budgets work?
Description: Participatory budgets allow citizens to propose and decide directly how to spend part of the budget, with monitoring and rigorous evaluation of proposals by the institution. Maximum effectiveness and control with satisfaction for everyone.
Link text: More about Participatory budgets
Link URL: https://youtu.be/igQ8KGZdk9c

**Note**: for image cards, you can use any of https://unsplash.com/ with size `800x400`.

**Comment by PierreMesure** [comment]
Can I take this one? Seems easy enough, even for me!

**Comment by decabeza** [comment]
Yes @PierreMesure all yours! 🙏 ☺️

**Comment by PierreMesure** [comment]
Not done yet but writing down some notes for later:
- the title and the label of a card don't appear if there's no picture
- the text of the 'Save card' button changes to `<span class=&quot;translation_missing&quot; title=&quot;translation missing: en.admin.homepage.update.submit_card&quot;>Submit Card</span>`when there is an error in the card form
- in the card for, the image is displayed cropped and enlarged for no reason
- (design) the card description is underlined on hover, which makes it less readable. Wouldn't it be better to design a hover state for the whole card if it is meant to be clickable?

**Comment by PierreMesure** [comment]
This issue can be closed.

**Comment by voodoorai2000** [comment]
Indeed! Thanks @PierreMesure 🎉 

Closed via https://github.com/consul/consul/pull/2679
