### ISSUE TITLE
Make homepage content translatable 

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2668]
Background
==

Now on admin section is possible to configure the homepage content in `/admin/homepage`.

What we need
==

Make translatable the homepage content created from admin panel. 

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619). And try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

Screenshots
==

![translate_homepage](https://user-images.githubusercontent.com/631897/41243639-f584ddf8-6da2-11e8-8f5a-d80c06b25f22.jpg)

**Comment by mlovic** [comment]
I'm starting work on this one.

@decabeza To confirm, from the homepage section of the admin, we need to make cards and headers translatable right?

**Comment by decabeza** [comment]
Yes @mlovic! both (but really header is a card with attribute `header` with "true" value) 😌
