### ISSUE TITLE
Add winner proposals for legislation processes

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2670]
Context
===
The collaborative legislation module has a section where proposals for a legislation can be submitted and voted

What
===
In the admin section of a legislation:
- Add a 'select' button for each legislation proposal to mark them as winner proposals (similar to winner budget investments)

In the public section of a legislation:
- Display the winner legislation proposals

**Comment by decabeza** [comment]
Closed in favor to https://github.com/consul/consul/issues/2739
