### ISSUE TITLE
Add moderation of budget investments

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2673]
Context
===
Users can create investments for a budget
Some of these investments are inappropriate and must be moderated

Moderation has two parts:
- A user with a moderator role or an admin, can hide a resource
- Admins can view this hidden resource and display it again publicly

What
===
Allow moderation of budget investments

How
===
Similar to how other resources are moderated
consul#2618

Note
===
Proposals and debates can already be moderated

**Comment by aitbw** [comment]
I'm on it

**Comment by aitbw** [comment]
I'm on it

**Comment by aitbw** [comment]
Closed via #2778

**Comment by decabeza** [comment]
Closed via #2778
