### ISSUE TITLE
Admin toggle side menu not working

### ISSUE THREAD

**Issue by SergioBonet** [consul/consul#2682]
# Steps to reproduce
 1. Login as admin
 2. Go to administration in any small screen device
 3. Try to open the "toggle side menu"

![captura de pantalla de 2018-06-15 09-39-46](https://user-images.githubusercontent.com/15011675/41456448-c4ac915e-7080-11e8-8fe1-6c82edc0126a.png)

# Expected behaviour
 - This icon should show the user items like: "my activity", "sign out", "notifications"... present in the side menu

# Current Behaviour
 - This icon doesn't do any action and the menu doesn't show up

**Comment by decabeza** [comment]
Hi @SergioBonet! Thanks for the issue. 🙏 

The [PR to fix this](https://github.com/consul/consul/pull/2692) is ready! 😌

**Comment by SergioBonet** [comment]
An absolute pleasure contribute with you :smile:
