### ISSUE TITLE
Some features appear twice in the feature activation admin panel 

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#2683]
What happens
==========

- There are some unexpected feature flags in the admin panel. For example, Debates and Proposals are duplicated and Processes, which isn't really a feature in itself, appears.

See below:

![screenshot-2018-6-15 admin](https://user-images.githubusercontent.com/7223028/41478438-f7b60ae8-70c7-11e8-8bd0-825bb2b0df9e.png)

It seems that this comes from the new keys in the settings table whose name start with 'feature'.

![capture d ecran 2018-06-15 a 18 20 10](https://user-images.githubusercontent.com/7223028/41478635-c7b89b34-70c8-11e8-9894-460133e6694c.png)

It doesn't seem that they should be here as there is already a button in the homepage admin page to enable/disable them. If they can stay here, they should at least be renamed to avoid any confusion.

How can we fix it?
===

- Rename the keys?
- make the feature_flag concern a bit smarter so that it doesn't pick all the keys starting with 'feature.'?

**Comment by PierreMesure** [comment]
@voodoorai2000, you were the one to add these keys in the settings table. What do you think?

**Comment by voodoorai2000** [comment]
Well spotted @PierreMesure 😌

+1 to make the feature_flag concern a bit smarter so that it doesn't pick all the keys starting with 'feature.' 👌

**Comment by PierreMesure** [comment]
It's tough because there's no common pattern in the names to have an easy filter.

Maybe creating the list manually would be a better solution in the long run?

**Comment by PierreMesure** [comment]
This is fixed as of v1.0.0.
