### ISSUE TITLE
Proposal's dashboard

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2688]
Proposal's dashboard
==

We are working in a new section for improving proposals management by authors. 

A proposal's dashboard that contains:

- [ ] **Chart** with the ideal number of supports, and the actual reached.
- [ ] List of **goals** (these goals unlock different resources).
- [ ] List of **recommended actions** to get more support for your proposal.
- [ ] List of  **available resources**

Notes
==

This functionality is being developed on [this repo](https://github.com/medialab-prado/consul) and you can see the [roadmap](https://github.com/medialab-prado/consul/projects/2).

Screenshots
==

A first mockup version (more in progress)

![proposal_dashboard](https://user-images.githubusercontent.com/631897/41592297-681229f6-73bc-11e8-92e3-1eed9ea598e8.jpg)

**Comment by javierm** [comment]
Closed via #3412.
