### ISSUE TITLE
Add homepage content to production seeds

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2703]
Context
===
Seeds are used to populate the database with basic settings and content

There are two types of seed files:
- [Development seeds](https://github.com/consul/consul/blob/master/db/dev_seeds.rb)
- [Production seeds](https://github.com/consul/consul/blob/master/db/seeds.rb)

The development seeds have [nice content](https://github.com/consul/consul/pull/2679) for the homepage

What
===
Add this homepage content to the production seeds

**Comment by javierm** [comment]
I'm closing this one. While it would be nice to add some demo settings when we setup a demo, for real production environments it would only generate false content that needs to be deleted, particularly considering widgets are now translatable and dev seeds generate content in English and Spanish, which might or might not be the languages the production server is supposed to use :thinking:.
