### ISSUE TITLE
Proposal notifications texts

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2709]
Background
===

Now the proposal's author can send a notification to users that supported the proposal on `/proposal_notifications/new?proposal_id=N`

We are working in a new feature to "send a message" to all members of a proposal's community and maybe be a little confusing.

What we need
===

Changes all the the texts with "message" to "notification" to avoid confusions.

Screenshots
==
![message](https://user-images.githubusercontent.com/631897/42089704-c687a3b4-7b9e-11e8-82d4-240781e8643d.png)

**Comment by decabeza** [comment]
Of course @liamelliott! All yours! 😉 🎉

**Comment by andyjdavis** [comment]
Hi. I have raised a PR that I believe resolves this. https://github.com/consul/consul/pull/4538
