### ISSUE TITLE
Flaky spec: Votes Debates Single debate Update

### ISSUE THREAD

**Issue by javierv** [consul/consul#2713]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** <del>3315</del> 57656

**Travis failed build:** <del>[Travis build 24008, job 1](https://travis-ci.org/consul/consul/jobs/398882809)</del> [Forked repo Travis build](https://travis-ci.org/javierv/consul/jobs/399449443)

**Failure:**

```
2) Votes Debates Single debate Update
     Failure/Error: expect(page).to have_css("a.no-voted")
       expected to find visible css "a.no-voted" within #<Capybara::Node::Element tag="div" path="/html/body/div[1]/div[1]/div/aside/div[2]/div/div[1]"> but there were no matches
     # ./spec/features/votes_spec.rb:90:in `block (5 levels) in <top (required)>'
     # ./spec/features/votes_spec.rb:88:in `block (4 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

### Final thoughts
The true objective of this issue is not "to fix" a flaky spec, but to change a spec that randomly fails into one that we can trust when it passes (or fails). 

That means you've to think "What are we testing here?" and "Can we test the same thing in another way?" or "Are we already testing this somewhere else at least partially?".

Sometimes the fix is to re-write the entire tests with a different approach, or to extend an existing spec. Tests are sometimes written without taking a look at other tests files neither near scenarios.

**Comment by javierv** [comment]
Here's a screenshot taken using `save_and_open_screenshot` when the test fails:

![![both in favor and against are selected]](https://user-images.githubusercontent.com/348557/42139639-650e7ff6-7d81-11e8-86d9-4dc278e0a03b.png)

And here's a screenshot when the test passes (expected behaviour):

![in favor is not selected](https://user-images.githubusercontent.com/348557/42139610-f0928ce4-7d80-11e8-8ba4-1776379217e9.png)

It fails sometimes on my machine on master. The best chance I've found to reproduce so far is running

```
bundle exec rspec spec/features/votes_spec.rb --seed 32962
```

With those tests and that seed, on my macine it fails about 15%. Running the failing test by itself I've only seen the test pass so far (but every machine is different, so...)

**Comment by javierv** [comment]
I'll have a look at this one.

**Comment by MariaCheca** [comment]
Closed via https://github.com/consul/consul/pull/2734
