### ISSUE TITLE
Improve rendering performance for resources with many comments

### ISSUE THREAD

**Issue by bertocq** [consul/consul#2730]
When a resource (proposal/debate/investment) has many comments, it takes a lot of time to completely load the page.

A nice improvement, proposed by @kikito, would be to load the comments in a secondary request. That way the resource could be visible for the user in less time, meanwhile the comments would start be loaded. This would make a huge impact while using a mobile device (usually with have slower internet connection)

Another way of improvement commented by @xuanxu was to load asynchronously comment threads (comments that are childs of a main-level-comment). That way first 10 comments would be loaded along the resource, but the nested ones would take some more time... or even be unvisible until the user clicks a "See responses" link that would load them via ajax "on demand", like facebook does:

![screen shot 2018-07-04 at 18 39 22](https://user-images.githubusercontent.com/983242/42288090-9b684c3c-7fb9-11e8-9ce1-542c51f3cd49.jpg)

**Comment by javierm** [comment]
I'm closing this one and merging its contents with #946, which is very similar.
