### ISSUE TITLE
Make polls translatable

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2735]
Background
==

Now on admin is possible to create content in some languages. You can try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

What we need
==

Make translatable the **polls** section (including questions and answers) created from admin panel on:

- `/admin/polls/new` 
- `/admin/questions/new` 
- `/admin/questions/N/answers/new` 

Screenshots
==

<img width="1241" alt="translate_poll" src="https://user-images.githubusercontent.com/631897/42386224-2980318e-813f-11e8-81b6-62ba77dd3274.png">
<img width="1245" alt="translate_question" src="https://user-images.githubusercontent.com/631897/42386225-299e98ae-813f-11e8-93ec-1a0b7b2068d4.png">
<img width="1251" alt="translate_answer" src="https://user-images.githubusercontent.com/631897/42386226-29b7b3ac-813f-11e8-9e0e-9dcae92f82dc.png">

Notes
==

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619).

**Comment by microweb10** [comment]
I can work on this one

**Comment by microweb10** [comment]
@voodoorai2000 I was going to use [this PR](https://github.com/consul/consul/pull/2619) as a reference, as the description says. But I will also have a look at the one you mentioned. What's the difference? As I understood the PR in this repo is a backport from AyuntamientoMadrid repo.

**Comment by voodoorai2000** [comment]
Yes 😌

The originally referenced [PR](https://github.com/consul/consul/pull/2619) is the one that introduced into CONSUL Globalization: gems, javascript, views, etc

This other [PR](https://github.com/AyuntamientoMadrid/consul/pull/1585) uses the Globalization implementation and just applies it to a new section 👌

**Comment by microweb10** [comment]
Oh, yeah! No worries 😉
I realized about that when I had a look at the PR. The rest was very helpful to "understand" what it does BTW 😊

**Comment by voodoorai2000** [comment]
Glad to hear 😊👍

**Comment by microweb10** [comment]
@voodoorai2000 I have a couple of questions:

- I see that Spanish translation for polls is currently "Votaciones". Shouldn't it be "Encuestas"?

- In the mockups in the description and also in the PRs I see that the only changes are made in the forms, but what about the rest of the places where polls/questions/answers are shown? like the list of polls in `/admin/polls/`, the list of questions in `/admin/questions`, or the places in the public website. Should I also take care of that? Or you're maybe planning to do it in different Issues/PRs?

**Comment by microweb10** [comment]
@voodoorai2000 Never mind about the last question. I just realized it's already implemented 😓
