### ISSUE TITLE
Make collaborative legislation translatable

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2736]
Background
==

Now on admin is possible to create content in some languages. You can try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

What we need
==

Make translatable the **collaborative legislation** section (including all phases) created from admin panel on:

- `/admin/legislation/processes/new` 
- `/admin/legislation/processes/N/questions/new` 
- `/admin/legislation/processes/N/proposals` 
- `/admin/legislation/processes/N/draft_versions/new` 

Screenshots
==
<img width="1188" alt="translate_process" src="https://user-images.githubusercontent.com/631897/42386712-88267e9a-8140-11e8-8f5b-3e82d5185d24.png">
<img width="1203" alt="translate_question" src="https://user-images.githubusercontent.com/631897/42386715-88764fba-8140-11e8-8df0-3d22be493e09.png">
<img width="1208" alt="translate_proposal" src="https://user-images.githubusercontent.com/631897/42386713-88470322-8140-11e8-9207-60d2690c6d82.png">
<img width="1215" alt="translate_drafting" src="https://user-images.githubusercontent.com/631897/42386716-88a7691a-8140-11e8-83df-f03a07d27e42.png">

Notes
==

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619).

**Comment by mlovic** [comment]
I'm not sure what to do about proposals here. If I understand correctly, those are created by users (not admins). There is a form at `/legislation/processes/:id/proposals/new`, but I don't think we're ready to introduce multi-language support to user-generated content are we? 

From what I can tell, the only thing an admin can do with proposals (shown in the screenshot) is to choose "Categories that users can select creating the proposal". The only input here is tag names, which I understand should not be translated. Is that right?

**Comment by decabeza** [comment]
Hi @mlovic! (sorry for the late response, I was on holidays 🏖)

Effectively we are not yet ready to translate user-generated content. 😅 

But **the categories (tag names) added by admin should be translatable**. 😉

**Comment by javierm** [comment]
Closed via #2912.
