### ISSUE TITLE
Make participatory budgets translatable

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2737]
Background
==

Now on admin is possible to create content in some languages. You can try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

What we need
==

Make translatable the **participatory budget** section (including budget phases and group/headings) created from admin panel on:

- `/admin/budgets/new` 
- `/admin/budgets/X/budget_phases/N/edit` 
- `/admin/budgets/X`

Screenshots
==
<img width="1224" alt="translate_budget" src="https://user-images.githubusercontent.com/631897/42388530-148cee96-8146-11e8-916c-008ed8f539f7.png">
<img width="1237" alt="translate_budget_phase" src="https://user-images.githubusercontent.com/631897/42388531-14a84c72-8146-11e8-826e-67b37165644f.png">
<img width="1243" alt="translate_budget_heading" src="https://user-images.githubusercontent.com/631897/42389085-d5568014-8147-11e8-95b1-d206ee549ca6.png">

Notes
==

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619).

**Comment by mlovic** [comment]
I'll do this one

**Comment by devinbalkind** [comment]
Hi - what's the status of this? Will it be in the .17 release?

**Comment by mlovic** [comment]
@devinbalkind This particular issue (involving participatory budgets) is on hold right now, but most of the foundational work to make admin-generated content translatable is done. I'm assuming this part will follow soon. 

I'm not on the core team, but my guess is that it will be in the .17 release (not much is happening until September though).

**Comment by mlovic** [comment]
@devinbalkind You might be interested in following this issue https://github.com/AyuntamientoMadrid/consul/issues/1612 which tracks progress of the whole "make admin-generated content translatable" project (changes to the Madrid fork are regularly backported to this repo).

**Comment by devinbalkind** [comment]
Thanks for the info. I guess this is the code powering decide.madrid.es --> https://github.com/AyuntamientoMadrid/consul?

**Comment by mlovic** [comment]
@devinbalkind That's right. Right now, most of the development is done on that fork and then backported here.

**Comment by devinbalkind** [comment]
Gotcha. Thanks for the intel.
