### ISSUE TITLE
Make banners translatable

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2738]
Background
==

Now on admin is possible to create content in some languages. You can try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

What we need
==

Make translatable the **banners** section created from admin panel on `/admin/banners/new`

Screenshots
==
<img width="1224" alt="translate_banners" src="https://user-images.githubusercontent.com/631897/42389165-1d75a3de-8148-11e8-8400-23ff0228f5fd.png">

Notes
==

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619).

**Comment by MariaCheca** [comment]
Closed in https://github.com/AyuntamientoMadrid/consul/pull/1585
