### ISSUE TITLE
Updates translatable custom pages

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2741]
Background
==

Now on admin section is possible to create custom pages in `/admin/site_customization/pages/new`.

What we need
==

Update translatable feature for custom pages created from admin panel. 

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619). And try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

Screenshots
==

**Actual**
<img width="1218" alt="actual" src="https://user-images.githubusercontent.com/631897/42449329-867de44c-8380-11e8-841e-669948361e41.png">

**After changes**
<img width="1220" alt="after" src="https://user-images.githubusercontent.com/631897/42449332-8b980732-8380-11e8-924d-6f5cfcb7e085.png">

**Comment by papayalabs** [comment]
Working on this issue

**Comment by javierm** [comment]
Closed via #2913.
