### ISSUE TITLE
Make admin notifications translatable

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2742]
⚠️ **Backport needed from AyuntamientoMadrid#1289 before to start this issue**

Background
==

Now on admin section is possible to send notifications to users in `/admin/admin_notifications/new`.

What we need
==

Make translatable the notifications created from admin panel. 

You can use as reference the PR [Allow admin generated content to be translatable](https://github.com/consul/consul/pull/2619). And try this feature on `/admin/budgets/N/budget_investments/N/budget_investment_milestones/new`.

Screenshots
==

![translate_admin_notifications](https://user-images.githubusercontent.com/631897/42458271-da5f18e2-8399-11e8-810d-f9c7a4ad5934.png)

**Comment by mlovic** [comment]
Starting this one.

**Comment by javierm** [comment]
Closed via #2910
