### ISSUE TITLE
Cannot login into Consul instance

### ISSUE THREAD

**Issue by KrzysztofMadejski** [consul/consul#2745]
### User Story

As I user I want to login into the portal.

### Current Behavior
I'm working on my own Consul instance.

1. I've registered.
2. Got email with validation token.
3. Clicked the link and got response "Your account has been confirmed."
4. Trying to login and I'm getting "To continue, please click on the confirmation link that we have sent you via email"
5. No more email in my inbox - I'm stuck.

### Expected Behavior
Ideally activation link should log me into the site without the need to provide a password.

### Steps to reproduce
Clean docker instance + see Current Behaviour

**Comment by KrzysztofMadejski** [comment]
BTW: All my issues reported today concerns instance deployed at commit 63213a0e4d8b44231c28741f74c6b25fcf3e5964

**Comment by KrzysztofMadejski** [comment]
PS. My colleague has managed to login successfully now, seems like a hard to catch bug.

**Comment by javierm** [comment]
@KrzysztofMadejski Were you and your colleague able solve this issue?

**Comment by KrzysztofMadejski** [comment]
It might have been a question of configuration, if I remember right we did solve it. I'll close this issue, thanks for a reminder.
