### ISSUE TITLE
confirmation_token should work only once

### ISSUE THREAD

**Issue by KrzysztofMadejski** [consul/consul#2746]
### User Story

As a security person I want the confirmation_token to activate account to work only once.

### Why is this Needed?

For security reasons, email eaves-dropping, etc.

### Description

After registering and gettign activation link, clicking on activation link doesn't invalidate the token. This "bug" may shadowed by other, see #2745 

### Current Behavior

1. I've registered.
2. Got email with validation token.
3. Clicked the link and got response "Your account has been confirmed."
3. Clicked the again the link and got response "Your account has been confirmed."

### Expected Behavior

Second link should result in "Confirmation token has been already used."

**Comment by iraline** [comment]
I can work on a fix for this
