### ISSUE TITLE
Move "configuration settings"

### ISSUE THREAD

**Issue by KrzysztofMadejski** [consul/consul#2748]
In my opinion it would be more intuitive if "Configuration settings" link visible as "gear" icon in top horizontal menu on /admin would be moved to the left menu that lists verbally admin options. 

I would do the same with statistics.

**Comment by decabeza** [comment]
Hi @KrzysztofMadejski! 

Right now these options: "Statistics" and "Settings" are duplicated. On the sidebar and the header (as shortcuts) 🙂

![consul_admin](https://user-images.githubusercontent.com/631897/42519466-69658c22-8464-11e8-9209-e8e795c06648.jpg)

Remember you can create any custom layout to change it. For example for this case you can create a new file `custom/layouts/_admin_header.html.erb` and remove L31 `<%= render "admin/shared/admin_shortcuts" %>` 😌 

Regards!

**Comment by KrzysztofMadejski** [comment]
I've missed that or it was recently added. Thanks!
