### ISSUE TITLE
Adds proposals images on dev_seeds

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2756]
Background
==
The user can upload an image when creates a proposal and this image is shown on the index list in `/proposals`. 

What we need
==

Include some random images on proposals created on `dev_seeds/proposals`

Notes
==

You can use any random image from https://unsplash.com/ (please avoid using photos of people faces or any inappropriate image)

Screenshots
==
![proposals_image](https://user-images.githubusercontent.com/631897/42566743-dac4bc1e-8507-11e8-8edd-dd62222dc680.png)

**Comment by nando** [comment]
@decabeza i'll take this issue, is that ok?

**Comment by voodoorai2000** [comment]
Awesome @nando!
All yours! 👍

**Comment by decabeza** [comment]
Closed by https://github.com/consul/consul/pull/2768
