### ISSUE TITLE
Configurable Top Right and Main Navigation Menus

### ISSUE THREAD

**Issue by devinbalkind** [consul/consul#2781]
### User Story

As an admin user I want to be able to control which menu items appear on the top_right menu and in the main_navigation.

### Why is this Needed?

Currently, the top_right menu automatically generates links to Open Data and Transparency, and it appears only Blog links can be editted via the front end. I want to be able to place whatever items I deem appropriate in that menu.

The main_navigation menu is automatically generated depending on the enabled features. I want to place items before and after those auto-generated feature links. 

### Description

*Type*: Feature

We'll use the existing "content blocks" feature to achieve our objective by doing the following:
* Make the top_links content block control the entire top right menu
* Add two new content block areas: main_navigation_menu_left, which will create items to the left of the auto-generated menu items and main_navigation_menu_right to the same to the right side of the menu.

### Current Behavior

Currently, the top_right menu automatically generates links to Open Data and Transparency, and it appears only Blog links can be editted via the front end. I want to be able to place whatever items I deem appropriate in that menu.

The main_navigation menu is automatically generated depending on the enabled features.

### Expected Behavior
 I want to be able to edit top_right and main_navigation menus by creating and editing use content_blocks.

### Steps to reproduce
NA

### Definition of Done
* Go to /admin/site_customization/content_blocks
* Create a content block for top_links and items there appear as top right menu
* Create a content block for main_navigation_menu_left and items there will appear to the left of the auto-generated menu items 
* Create a content block for main_navigation_menu_left and items there will appear to the left of the auto-generated menu items 

@ziyan-junaideen is working on this and will submit a PR for this feature shortly.

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2785
