### ISSUE TITLE
Adds polls list description

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2784]
Background
==

Admins users can create polls on `/admin/polls`. Sometimes they create a group of polls and need to include a short description to give some context to users.

What we need
==

- Adds a "Edit polls list" on `/admin/polls`. _[Image_1]_
- New "Edit polls list" page with a description CKEditor textarea. _[Image_2]_
- If this field is filled show the content on `/polls` front view. _[Image_3]_

Screenshots
==

**[Image_1]**
![index](https://user-images.githubusercontent.com/631897/43134084-25e334bc-8f41-11e8-8318-35078ea7e1ec.png)

**[Image_2]**
![edit](https://user-images.githubusercontent.com/631897/43134087-279a60b4-8f41-11e8-8623-74e304957a38.png)

**[Image_3]**
![front](https://user-images.githubusercontent.com/631897/43134091-2acd3fb8-8f41-11e8-95bf-ec933e110585.png)

**Comment by microweb10** [comment]
I can work on this one.

**Comment by decabeza** [comment]
All Yours @microweb10! 🙏 😌

**Comment by microweb10** [comment]
@decabeza I have a question. Where do you want to store that description content?
