### ISSUE TITLE
Add homepage for legislation processes

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2791]
⚠️ **Wait to https://github.com/consul/consul/issues/2495 is merged before to start this issue.**

Background
==
Admins can create new processes on `/admin/legislation/processes`. Sometimes the processes are complex and need to give more context to users with texts, images...

What we need
==
- Add a new "Homepage" tab on admin legislation processes `/admin/legislation/processes/N/edit`.
- Include a checkbox to enable/disable this homepage.
- A CKEditor textarea (wait to https://github.com/consul/consul/issues/2495 for use last version).
- Now the process index URL redirects to the active phase, but if **homepage is enabled** redirect always to this page (independent of the current phase).

Screenshots
==

**Admin form**
![processes_homepage_admin](https://user-images.githubusercontent.com/631897/43212172-8e17eda0-9033-11e8-8c30-5b09dce2ee89.jpg)

**Front view of process index**
![processes_homepage](https://user-images.githubusercontent.com/631897/43212180-90826426-9033-11e8-9407-b5d5588b98d0.jpg)

**Comment by dpgigorro** [comment]
maybe this resolves it: https://github.com/dpgigorro/consul/tree/2791-homepage-for-legislation-process

**Comment by javierm** [comment]
@dpgigorro Thank you very much! Would you mind opening a pull request with the relevant changes against our `master` branch so we can easily check those changes and make comments about them? Thanks again :wink:!

**Comment by javierm** [comment]
Closed via #3091.
