### ISSUE TITLE
Admin menu doesn't show up for some admins

### ISSUE THREAD

**Issue by javierv** [consul/consul#2812]
## Steps to reproduce

1. Create a user with an ID higher than 10.
2. Log in with that user.
3. Go to the "Management" section.

## Expected behaviour

There should be a menu showing links to sections like "My activity" or "My account":

![expected](https://user-images.githubusercontent.com/348557/43359933-e611b012-929b-11e8-8f0b-02c083b7aea4.png)

## Actual behaviour

The menu doesn't show up:

![actual](https://user-images.githubusercontent.com/348557/43359934-ea89cdfa-929b-11e8-924b-338d88802c9f.png)

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2813
