### ISSUE TITLE
Translate accesibility page

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2820]
Background
===

We have some static pages with text, for example, the **accessibility** page in `/accessibility` and we need translate it. 

What we need
===

- Move the actual texts to i18n keys to `/config/locales/es/pages.yml`.
- Adds the English translations on `/config/locales/en/pages.yml`.

Screenshot
==

**The actual accessibility page it's only on Spanish**
![a11y](https://user-images.githubusercontent.com/631897/43453168-a6ae9dc0-94b9-11e8-8a41-e83c34995854.png)

**Comment by juan-fdz-hawa** [comment]
Hola, you do mind if I tackle this one?

**Comment by aitbw** [comment]
Hey @juan-fdz-hawa, feel free to do so! All contributions are welcome :smile:

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2834
