### ISSUE TITLE
Add options to display results for online polls

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2824]
### Context

When a Poll is finished, an admin can decide to [show the results publicly](https://github.com/consul/consul/pull/2095)

However this option is only allowed if there are counted Booth Votes(`PartialResults`) for a Poll 

### What is needed?

Make available the options to display results, when there are only Web Votes(`Question::Answers`) for a Poll

### How
Probably the simplest implementation is to check if there are `Voters` for a Poll, as Voters are stored for both Booth Votes and Web Votes, in that case display the options 👍

Also take into account that in the admin section where these options are displayed(`admin/polls/1/results`) other data is also included, like Booth Votes per Question.
This data should still be displayed and the options to display results should be independent and available for both Booth Votes and Web Votes

### Screenshots
<img width="1049" alt="screen shot 2017-10-20 at 18 44 19" src="https://user-images.githubusercontent.com/2141690/31832434-4960ce8a-b5c7-11e7-96df-12365e5aeead.png">

**Comment by aitbw** [comment]
I'm on it

**Comment by voodoorai2000** [comment]
@aitbw are you still up for working on this one? 😃

**Comment by jaflutz** [comment]
Can I try this one (if @aitbw  isn't working on it anymore, of course)?

**Comment by microweb10** [comment]
Sure! @jaflutz go for it! 👍

**Comment by microweb10** [comment]
Done in PR https://github.com/consul/consul/pull/3155
