### ISSUE TITLE
Add a form to submit CONSUL installations

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2828]
Context
===
In an effort to sync all the CONSUL forks around the world, we've created [consulproject](https://github.com/consul/consulproject) a repo that is meant to substitute one day the current [consulproject](http://consulproject.org/en/) website

For now we have Github integration to see the [differences between a fork and upstream](https://consulproject.herokuapp.com/).
And many other ideas are being suggested to make an awesome site of CONSUL installations around the World

What
===
Add a public form to submit a CONSUL installation with the following fields
- Name of fork
- Repo url
- Website url
- Contact name
- Conact Email
- Location (city/country)
- Organization type (Government, ONG, University, School, Other)
- Status (Installation in progress, In production)
- Notes

How
===
- Extending the current [Installations](https://github.com/consul/consulproject/blob/master/app/models/installation.rb) model to include these columns
- Creating the corresponding views and controller actions to submit an installation
- Writing some specs to make sure everything is working nicely

**Comment by embasbm** [comment]
Hi, can I take this one?

**Comment by javierm** [comment]
Closing in favor of consul/consulproject#3, so we've got the issue in the same repository where the pull request is open.
