### ISSUE TITLE
Upgrade Gems

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2829]
Context
===
Code keeps moving forward and we must stay up to date

What
===
Find a [gem](https://github.com/consul/consul/blob/master/Gemfile) that is [obsolete](https://rubygems.org/) and [upgrade it](https://bundler.io/v1.16/guides/updating_gems.html)

Why
===
For security, quality and maintainability

How
===
Check out the [release notes](https://github.com/thoughtbot/factory_bot_rails/releases) of that gem version and apply, if any, the changes required for the upgrade

Here is an example template to submit a PR:

_Title_
Upgrade gem _name_ to version _x_

_Description_
Previous version X (link to changelog of version X)
New version Y (link to changelog of version Y)

_Upgrade Changes_
None, or description of changes applied

_Notes_
None, or anything special to take into account
  
Notes
===
This is a forever-opened issue 😌

Just go ahead and send a PR 👍

**Comment by greysteil** [comment]
@voodoorai2000 - out of interest, it looks like you used to use Depfu for this, but don't any more. They're a competitor of mine (I built Dependabot and have been full time on it for a year). Out of interest, what made you stop?

**Comment by PierreMesure** [comment]
@greysteil Great job! I've always been super impressed by GOV.UK and how they update the dependencies of their 1000+ repos so fast! I checked again and your bot submitted 6000 pull requests to them.

**Comment by greysteil** [comment]
Thanks! It’s been amazing to see Dependabot get adopted by more and more teams there 😊

**Comment by greysteil** [comment]
@viren140290 go for it! Upgrading Nokogiri from 1.8.2 to 1.8.4 would be a good move - there's a security vulnerability in the current version.

**Comment by PierreMesure** [comment]
@viren140290, @greysteil I'd wait for feedback from @bertocq, @raul-fuentes, @aitbw or @voodoorai2000 if I were you.

It seems that a lot of dependencies have been updated in this [PR](https://github.com/consul/consul/pull/2631), most importantly Ruby and Rails but also nokogiri and some for which I created PRs.

**Comment by voodoorai2000** [comment]
Hi guys!

@greysteil sure, we stopped using Depfu because it does not automatically update the Gemfile with the specific version for minor gem upgrades. We prefer to have the exact version specified in the Gemfile, not only in the Gemfile.lock

@PierreMesure thanks for all those PRs, merging 🎉 

@viren140290 right, there is a big PR coming with Rails 5 and many gem dependency updates, but we still got quite a bit of real life testing to do before merging. Feel free to update any gem in the meantime 👍

**Comment by greysteil** [comment]
@voodoorai2000 - ah cool, I'm the same. It's configurable in Dependabot, but keeping the Gemfile in line with the Gemfile.lock is the default.

Just running it on my fork to make sure everything works as expected - I'll ping you a link to the PRs once it's generated some.

**Comment by greysteil** [comment]
@voodoorai2000 - alright, running nicely on my fork and you can see the PRs [here](https://github.com/greysteil/consul/pulls). Would love you to switch it on on this repo!

**Comment by voodoorai2000** [comment]
Awesome, thanks for trying it out @greysteil 😌
I see the Gemfile is updated for minor versions 🎉 
Can Dependabot be configured to update the Gemfile for patch versions too?

**Comment by greysteil** [comment]
Yeah, it'll do that for you automatically - it's the way I keep my Gemfiles, too. 🙂

**Comment by voodoorai2000** [comment]
That is magnificent 😌
Alright, we'll give it a shot 👍

**Comment by greysteil** [comment]
@voodoorai2000 - a couple of patch-level updates there now, including [this one](https://github.com/greysteil/consul/pull/6/files), so you can see exactly what they look like - just in case you doubted me. :trollface:

It caps out at 10 PRs open (and opens a max of 5 per update run) so won't overwhelm you.

**Comment by voodoorai2000** [comment]
Appreciate it @greysteil, I didn't 😌
Oh the cap feature is very considerate 🙏🎉

**Comment by voodoorai2000** [comment]
Things seem to be working very nicely with @greysteil's Dependabot! 🎉 
Putting this issue on hold for now

**Comment by voodoorai2000** [comment]
Don't think we need this issue open any longer 😌 
Dependabot is awesome, it works great and has everything that we wanted 😍

Thanks @greysteil great job building it! 👏

**Comment by greysteil** [comment]
That's awesome to hear - thanks @voodoorai2000!
