### ISSUE TITLE
Add configuration to setup a staging environment

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2830]
Context
===
We have an [automated installer](https://github.com/consul/installer) to setup CONSUL in a remote server

Currently the installer is hardcoded to setup CONSUL for a production environment

What
===
Add an option to the installer to [setup CONSUL for a staging environment](https://github.com/consul/installer/issues/23)

Notes
===
This issue requires learning a little [Ansible](https://www.ansible.com/)
And a thorough understanding of the components needed to deploy a Rails app

**Comment by javierm** [comment]
Closed via consul/installer#98
