### ISSUE TITLE
Missing translations for seed notifications

### ISSUE THREAD

**Issue by aitbw** [consul/consul#2836]
### Current behavior:

![screenshot_2018-08-06 consul](https://user-images.githubusercontent.com/9470839/43726287-c17c022a-996c-11e8-8942-32b67ccbbac9.png)

### Expected behavior:

* Translations should not be missing

### Steps to reproduce

* Login into CONSUL
* Click the 'Notifications' button

### Notes

* The translations were available until PR #2792

**Comment by aitbw** [comment]
Yes, you're correct @mlovic, sorry about that :bowing_man:

**Comment by javierm** [comment]
Closed via #2910.
