### ISSUE TITLE
Add "Approval Voting" as Option in Participatory Budgeting Module

### ISSUE THREAD

**Issue by devinbalkind** [consul/consul#2841]
### User Story

As an admin, I want to create participatory budgets using the "approval voting" style instead of the knapsack/shopping cart style currently supported by Consul.

If I select Approval Voting for the budget, then the user can pick a maximum number of projects on every heading on which they can vote. I would also be able to select the amount of projects a user can vote for on each Heading Group.

### Why is this Needed?

Participatory Budgeting the United States, and specifically in New York City, uses an "Approval Voting" style, not a "knapsack" style that Consul currently supports.

### Description

Specification is available here: https://docs.google.com/presentation/d/1ev1sJG3gu9ylZHi1143-hLu27oezySyD-Zqf4p8Nnss/edit?usp=sharing

Feel free to add comments directly to the Specification.

*Type*: Feature

### Current Behavior

Currently the only voting option for participatory budgets in Knapsack-style where a user can vote on as many projects as they like until the aggregate cost of those projects exceeds an administrator-defined maximum.

### Expected Behavior

Administrator should be able to select, on a budget by budget basis, the style of voting for that budget. The current style is defined as Knapsack and should remain an option. The additional style they should be able to select is called "Approval Voting".

If the administrator selects "Knapsack" then everything remains the same.

If the administrator selects "Approval Voting" then a field will appear under each Group asking how many projects a user can select under each heading. 

More specific instructions are in the specification posted in the description section of this issue. 

### Steps to reproduce
NA

### Definition of Done
See Specification: https://docs.google.com/presentation/d/1ev1sJG3gu9ylZHi1143-hLu27oezySyD-Zqf4p8Nnss/edit?usp=sharing

Feel free to either comment on this issue or directly on the specification. 

Thank you!

**Comment by juan-fdz-hawa** [comment]
Done in https://github.com/consul/consul/pull/2845
