### ISSUE TITLE
Facebook share link in poll doesn´t work

### ISSUE THREAD

**Issue by tiagozini** [consul/consul#2848]
Steps to reproduce
1- Enter in any pool.
2- In the share with social networks click in facebook
3- The facebook popup returns an error and user can't share the element with Facebook

Expected behaviour
The popup should show the Facebook UI and allow the user to share the item.
Current Behaviour
The popup's URL have the "quote" empty if it gets the descreption of the item it will work. This was fixed in the website from Madrid and added to the consul 0.14 but it stills happens.

**Comment by tiagozini** [comment]
I solved this issue at our fork of Consul changing the file "consul/app/views/shared/_social_share.html.erb" with the adition of ```desc``` parameter to ```social_share_button_tag``` and creating a custom view. The code of custom view is at the commit bellow ```https://github.com/Procempa/consul/commit/f63ec1ffc61530dc1499f00273ce11a01c881ae4```

**Comment by decabeza** [comment]
Closed by https://github.com/consul/consul/pull/2852
