### ISSUE TITLE
icon_home.png is not used anymore but still present in the custom image panel

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#2853]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

In the admin panel, you can set a custom image for **icon_home** *(330x240)* but this image doesn't seem to be used anywhere.

![capture d ecran 2018-08-16 a 10 04 59](https://user-images.githubusercontent.com/7223028/44196865-6d157580-a13d-11e8-8f82-c1ba7a99fbd8.png)

### Current Behavior
[comment]: # (Describe what actually happened.)

The image is uploaded but I haven't found where it's used and the code doesn't mention it anywhere.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Let's remove it from the admin panel?

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

Irrelevant

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Remove the possibility to customize *icon_home*
- Fix the specs

**Comment by PierreMesure** [comment]
I might be wrong about that. Please feel free to correct me!

**Comment by decabeza** [comment]
Hi, @PierreMesure! indeed this is a logo that is no longer used.

Feel free to send a PR to remove it! 🙏 😌

**Comment by PierreMesure** [comment]
This is fixed.
