### ISSUE TITLE
500 error when we created a budget investment from management panel

### ISSUE THREAD

**Issue by sturpin** [consul/consul#2855]
### Description
When we try to create a budget investment from the management panel with a user, who has either registered in the portal or we manually, we receive a 500 error.

*Type*: Bug

### Steps to reproduce
1. We select user from the management panel
![step_1](https://user-images.githubusercontent.com/16426243/44199392-49096280-a144-11e8-89c3-7969bd19d23b.png)

2. The user is verified
![step_2](https://user-images.githubusercontent.com/16426243/44199423-62121380-a144-11e8-8311-df73fa2cc844.png)

3. We create a budget investment from management panel with user identification
![step_3](https://user-images.githubusercontent.com/16426243/44204358-84ab2900-a152-11e8-89a6-46668f7cc1b5.png)

### Definition of Done
We always receive the 500 error, fill in or not the form and even if you do not accept the privacy policy.

### Traceback Rollbar
NoMethodError: undefined method `each' for nil:NilClass
``File "/consul/app/views/budgets/investments/_form.html.erb" line 62 in block in _app_views_budgets_investments__form_html_erb___2841398156537415368_33401000``

``File "/consul/app/views/budgets/investments/_form.html.erb" line 1 in _app_views_budgets_investments__form_html_erb___2841398156537415368_33401000``

``File "/consul/app/views/management/budgets/investments/new.html.erb" line 10 in _app_views_management_budgets_investments_new_html_erb__2031065292089547621_33642880``

``File "/consul/app/controllers/management/budgets/investments_controller.rb" line 26 in create``

**Comment by 16yuki0702** [comment]
I can fix it.

**Comment by sturpin** [comment]
Fantastic @16yuki0702 !!
That error has been solved, but even if you put a location on the map, it gives you an error and does not allow you to save the investment.

### Images 
1. Map location can't be blank ??
![pic_01](https://user-images.githubusercontent.com/16426243/44271731-30c83f00-a23b-11e8-877c-394b1b6770a9.png)

2. I put the location on the map
![pic_02](https://user-images.githubusercontent.com/16426243/44271818-72f18080-a23b-11e8-99de-062348ce5185.png)

If you delete the geolocation, it keeps giving you the same error.

**Comment by 16yuki0702** [comment]
thank you for your checking !!
oh, that's strange.
I'll check it.

**Comment by 16yuki0702** [comment]
I fixed so that you can store map location.

**Comment by sturpin** [comment]
Amazing @16yuki0702 !! running perfectly, I'm so proud of you!! :+1:

**Comment by 16yuki0702** [comment]
Thank you very much for your checking.
I think this issue should be kept opening until it's pr is merged.
Would you reopen this issue please ??

**Comment by sturpin** [comment]
@16yuki0702 you are right!! I got excited ha ha ha 
thanks!! :+1:

**Comment by javierm** [comment]
Closed via #4448.
