### ISSUE TITLE
Show Active Tab in Custom Information Texts

### ISSUE THREAD

**Issue by devinbalkind** [consul/consul#2889]
### User Story

As an admin, I want to be able to tell which "Information Texts" is currently displayed through the standard visual cue for active tabs.

### Why is this Needed?

Makes administration easier

### Description

*Type*: Bug

Make the active tab's title blue and underlined.

### Current Behavior
![image](https://user-images.githubusercontent.com/444311/45330133-8d143b00-b529-11e8-97b6-d5a45dc16f38.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/444311/45330253-2cd1c900-b52a-11e8-8902-62751e5ccc76.png)

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
Go to: /admin/site_customization/information_texts?tab=proposals

### Definition of Done
Active Tabs in Custom Information Texts are displayed following the same convention as the rest of the admin area.

**Comment by papayalabs** [comment]
Working on this issue

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/2898
