### ISSUE TITLE
Integrate Ckeditor with Amazon S3 uploads

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#2904]
### User Story

As an admin, I want to upload images using CKeditor, so that custom pages look awesome

### Why is this Needed?

Right now [images can be upload using CKeditor](https://github.com/consul/consul/pull/2876) but it assumes that we can store images in the hosted server. That is not always the case with providers such as Heroku, were you need an external storage provider such as Amazon S3.

Integrate Ckeditor image upload feature with Amazon S3 uploads

**Comment by PierreMesure** [comment]
Cool that you opened the issue @voodoorai2000! I don't know if you tested it but if you haven't, it might be that the current integration works without any problem with S3. My concern was just that we don't know.
For anyone looking into it, use the [Paperclip & S3 guide](https://github.com/PierreMesure/docs/blob/d439e66702e424ccf75cfb1d8301a358b8dbd7e1/en/getting_started/using-aws-s3-as-storage.md) in the Consul docs. @voodoorai2000, don't forget to build Gitbook when you have the time so it appears there as well.
