### ISSUE TITLE
CRUD for budget groups and headings

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2918]
## Background

Now the admin users can create a budget and assign **group and headings** on `/admin/budgets/N`. This is a little confusing and uses some extra JS to expand/hide the form.

## What we need

Change this "all-in-one" form to a CRUD for **groups** and **headings** to improve this section and add consistency with the rest of admin panel.

### Notes
Keep in mind a lot of forks have already used this budgets feature and need to **keep the data** already created (maybe a rake task is necessary).

The **group show** (`/admin/budgets/N/group/N`) and the **heading show** 
(`/admin/budgets/N/group/N/heading/N`) views are not necessary, don't provide too much information and is something we do not usually have in admin views.

## Screenshots

**[BEFORE]**
![before](https://user-images.githubusercontent.com/631897/45957709-f14cf980-c015-11e8-8ff9-9a405dbbe2bb.png)

**[AFTER]**

**Groups index** 
`/admin/budgets/N/groups`
![1_group_index](https://user-images.githubusercontent.com/631897/45959935-59eaa500-c01b-11e8-9736-0a6d7c4a5103.png)

**Group new/edit** 
`/admin/budgets/N/groups/new` and `/admin/budgets/N/groups/edit`
![2_group_new](https://user-images.githubusercontent.com/631897/45959950-60791c80-c01b-11e8-9e9a-541c698b13c2.png)

**Headings index** 
`/admin/budgets/N/groups/N/headings`
![4_headings_index](https://user-images.githubusercontent.com/631897/45959976-6c64de80-c01b-11e8-96f2-e77d1650e590.png)

**Heading new/edit** 
`/admin/budgets/N/groups/N/heading/new` and `/admin/budgets/N/groups/N/headings/edit`
![5_headings_new](https://user-images.githubusercontent.com/631897/45959972-6a9b1b00-c01b-11e8-8b36-fd8b89d17e33.png)

**Comment by microweb10** [comment]
I'll work on this one!
