### ISSUE TITLE
Images and documents settings

### ISSUE THREAD

**Issue by decabeza** [consul/consul#2934]
## Background

Users and admins can upload images and documents to proposals, investments, processes... but the settings only can be changed on code `/models/image.rb` and `/models/document.rb`.

## What we need

Move all this images and documents settings to admin panel on `/admin/settings`.

## Notes

These are the texts I use for the mockup. Feel free to change and improve them! ☺️ 

```
Image title min lenght 
When a user upload an image write a title to describe it (used as alt)  


Image title max lenght 
When a user upload an image write a title to describe it (used as alt)  

Image min width 
No description  

Image min height 
No description  

Image max size 
On MB (Megabytes) 

Accepted content type for images  
JPG JPEG PNG 
GIF SVG

Maximum number of documents 
The maximum number that one user can attach to the same item (proposal, investment...)  

Document max size 
On MB (Megabytes) 

Accepted content type for documents 
PDF DOC DOCX XLS 
XLSX CSV  ZIP
```

## Screenshots
![images_documents_settings](https://user-images.githubusercontent.com/631897/46147649-5bf47400-c266-11e8-8fd5-073601b9d41d.png)

**Comment by kreopelle** [comment]
I'd like to try my hand at this issue (also it's my first time)!

**Comment by decabeza** [comment]
Hi @kreopelle! Sure! All yours 😉

**Comment by decabeza** [comment]
Hi @kreopelle! How are you? any news with this issue? 

Tell us if you need some help. Many thanks! 🙏 😌

**Comment by microweb10** [comment]
Hi @jebediahelliott ! Sure! All yours 😉

**Comment by microweb10** [comment]
Hi @jebediahelliott! How are you? any news with this issue? ☺️

**Comment by jebediahelliott** [comment]
Hi @microweb10! I'm good thanks! My apologies for being inactive on this. I will set aside time in my calendar to get it taken care of and have some results for you in the next week.

**Comment by microweb10** [comment]
Hi @jebediahelliott, 

Sorry to say that, but this has become kind or urgent, so we have decided to start the development from the core team ☺️ 

Thanks anyway for your interest and please feel free to pick up any other open issue if you wish ❤️

**Comment by jebediahelliott** [comment]
Hey @microweb10 I totally understand. I apologize for not getting anything done with this. I tried to take on too many projects at once and unfortunately, I just didn't get to this one. I will make a contribution as soon as I have the time to dedicate to it.
