### ISSUE TITLE
Ability to catch and forward emails

### ISSUE THREAD

**Issue by ziyan-junaideen** [consul/consul#2954]
### Background

We are required to migrate the production database to a another instance of the app for testing purposes . This raises the possibility of blasting our users with unintended emails. It would be good to be able to on config prevent emails been sent to users.

### Description

*Type*: Feature

To be able to configure the application to catch and forward emails to a specified email address.

### Current Behavior

There exists no configurable option to prevent / forward emails unless by updating the code base.

### Expected Behavior

- Add key `email_interceptor_recipients: user@example.com`
- Reboot the app
- Generated emails delivered to the forwarded to the specified emails

### Notes

- This is work in progress
- Uses https://github.com/croaky/recipient_interceptor
- Following discussion with @voodoorai2000 in Slack

**Comment by microweb10** [comment]
Hi @ziyan-junaideen 

We have created a new [PR](https://github.com/consul/consul/pull/3251) using your code, added some tests, and it will be merged shortly. ☺️ 

Thank you very much for your contribution! 🎉
