### ISSUE TITLE
Local installation of consul : Your bundle is locked to i18n (0.9.5)

### ISSUE THREAD

**Issue by kiwis2** [consul/consul#2988]
### User Story
I just landed and discovered consul, and decided to discover the app as I'm PhD student working on Participatory Governance. 
I'm trying to install it on localhost.

### Why is this Needed?

[comment]: #
 to install Consul on a localhost

### Description

[comment]: # 
*Type*: Trouble shooting

### Current Behavior
The issue that blocked me from even locally exploring consul came after i ran out the command bundle install.

> $ bundle install
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Resolving dependencies......
> Your bundle is locked to i18n (0.9.5), but that version could not be found in
> any of the sources listed in your Gemfile. If you haven't changed sources, that
> means the author of i18n (0.9.5) has removed it. You'll need to update your
> bundle to a version other than i18n (0.9.5) that hasn't been removed in order to
> install.
> 

**also when i try bundle update i get :** 

> $ bundle update
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Fetching gem metadata from http://insecure.rails-assets.org/..
> Could not find gem 'rails (= 4.2.10)' in any of the gem sources listed in your
> Gemfile.

I was following the steps from the documentation for installing consul locally. 

could anyone please help out?

Screenshot
![s_s](https://user-images.githubusercontent.com/44402753/47622938-5ad79080-db0b-11e8-9701-adc888cc3299.jpg)

Thanks

### Expected Behavior
[comment]: # running smoothly

**Comment by kiwis2** [comment]
Merci Pierre! 
I still could not install it :( 
![s_s](https://user-images.githubusercontent.com/44402753/47886026-15330480-de38-11e8-854d-c044d95e1127.jpg)

here's what i got 

thank you a lot for your support!

**Comment by PierreMesure** [comment]
Another possibility would be to check your gem sources. I don't use `insecure.rails-assets.org`, I have the following sources when I install/update:
```
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/.
```
In general, maybe uninstalling ruby and reinstalling would solve the issue.

**Comment by kiwis2** [comment]
Actually, If i use https it would rise up an error. 
I re-installed ruby already. 
I noticed that i have to install the version of the gem that is asking for. 
so for example i had "browser" gem but a newer version than 2.5.3, so i when i ran gem install -v 2.5.3 then it would ask for another gem because it's locked to certain version and so on...

**Comment by javierm** [comment]
Thanks for your interest in CONSUL! :smile:

I'm afraid we don't support CONSUL installations on windows systems, and we don't support using insecure connections to retrieve gems either.
