### ISSUE TITLE
Custom documents

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3009]
## Background

Sometimes admin users want to upload some document and have to use some external tool or include the document in the repo.

## What we need

Create a new admin **Custom documents** section inside "Side content" menu to allow 

## Notes

It would nice include some settings like: 

- Accepted documents type.
- Max size of each file.
- Path where documents will be uploaded.

You can use as reference described on issue [Images and documents settings](https://github.com/consul/consul/issues/2934).

## Screenshots
<img width="1679" alt="custom_documents_index" src="https://user-images.githubusercontent.com/631897/48077790-6cdec080-e1e8-11e8-84b5-6fc41969ed77.png">

<img width="1676" alt="custom_documents_form" src="https://user-images.githubusercontent.com/631897/48077789-6cdec080-e1e8-11e8-9ecd-d0e409b17d84.png">

**Comment by voodoorai2000** [comment]
Closed via https://github.com/AyuntamientoMadrid/consul/pull/1733
