### ISSUE TITLE
Add Content Block to Heading Sidebar

### ISSUE THREAD

**Issue by devinbalkind** [consul/consul#3022]
### User Story

As an admin I want to be able to post custom content and links on heading pages.

### Why is this Needed?

People are often asking for more information about a heading. Headings are often "districts" so they want to know things like:
* Who is leading the district?
* What projects have been voted on in the past?
* What are the characteristics of this district?

By providing a flexible content box in the heading area, administrators can provide their users with whatever types of information and links that are requested by the community.

### Description

We make it possible for the admin to activate the content block on a heading by clicking a checkbox under the heading.

![expanding consul - media lab prado 2018 4](https://user-images.githubusercontent.com/444311/48144849-ea223800-e2b1-11e8-8af2-292ae02197f5.png)

When the checkbox is clicked and saved, a new content block area is automatically generated and made available as a location in the custom content block section.

![expanding consul - media lab prado 2018 5](https://user-images.githubusercontent.com/444311/48144936-0de57e00-e2b2-11e8-8deb-fb854b829786.png)

The content block is displayed on the top right of the heading's sidebar.

![expanding consul - media lab prado 2018 6](https://user-images.githubusercontent.com/444311/48144847-ea223800-e2b1-11e8-9c25-782f3022ea2a.png)

*Type*: Feature

**Comment by devinbalkind** [comment]
@milber @nicodiazm will be tackling this at the MediaLab Prado event.

**Comment by voodoorai2000** [comment]
Thanks @devinbalkind, @milber, @nicodiazm! 🎉 
Closed via https://github.com/consul/consul/pull/3043
