### ISSUE TITLE
Improve aspect of homepage customization in admin panel

### ISSUE THREAD

**Issue by microweb10** [consul/consul#3024]
### Description
In `/admin/homepage` the button for dissabling recommendations is not nicely shown when you don't have a high resolution on your screen. I suggest using the same aspect than **Debates**, **Proposals** and **Processes**.

I can work on this one if you accept my suggestion 😊

### Current Behavior
![captura de pantalla 2018-11-08 a las 11 40 39](https://user-images.githubusercontent.com/942995/48194453-5bfb8f80-e34d-11e8-8528-26ca252ab192.png)

### Expected Behavior
![captura de pantalla 2018-11-08 a las 11 40 07](https://user-images.githubusercontent.com/942995/48194474-687fe800-e34d-11e8-80b4-b8ab6a4c19f4.png)

**Comment by decabeza** [comment]
Of course @microweb10 all yours! 😌
