### ISSUE TITLE
Improve aspect of homepage customization in admin panel (table buttons)

### ISSUE THREAD

**Issue by microweb10** [consul/consul#3026]
### Description
In `/admin/homepage` the action buttons on the tables are not nicely shown when you don't have a high resolution on your screen. I suggest splitting the buttons into different cells, so the new aspect will the one in the screenshots.

I can work on this one if you accept my suggestion 😊

### Current Behavior
![captura de pantalla 2018-11-08 a las 12 58 30](https://user-images.githubusercontent.com/942995/48197925-83575a00-e357-11e8-8b1d-79d96547bf80.png)

### Expected Behavior
![captura de pantalla 2018-11-08 a las 13 03 45](https://user-images.githubusercontent.com/942995/48197941-8e11ef00-e357-11e8-9c1f-4bfd4ffb8ce5.png)

### However this will be the new aspect for high resolution screens
![captura de pantalla 2018-11-08 a las 13 02 15](https://user-images.githubusercontent.com/942995/48197952-9702c080-e357-11e8-9cf0-6ca212d21352.png)

Let me know if you want to proceed with the change.

**Comment by decabeza** [comment]
Hi @microweb10! I think better than split the buttons into different cells, is adding a CSS class in their parent `<th>` to keep a min width, and keep consistency with the rest of admin sections. 😉 

You have an example of this on `admin/debates/index.html.erb:13`

`<th scope="col" class="small-4"><%= t("admin.shared.actions") %></th>`

**Comment by decabeza** [comment]
For me it's ok! the important is buttons don't break in two lines. Moreover, the common for users is use a small resolution 😅

**Comment by microweb10** [comment]
Cool! I will have a look at the rest of the admin section to check if the issue appears in more places. Then send a PR for all of them.
