### ISSUE TITLE
Flaky spec: Budget Investments - Balloting Phase - Confirm

### ISSUE THREAD

**Issue by microweb10** [consul/consul#3035]
## Failure

**Travis failed build**: [Travis build 29543, job 3](https://travis-ci.org/consul/consul/jobs/536654919)

```
1) Budget Investments Balloting Phase Confirm
     Failure/Error: expect(page).to have_content "Remove"
       expected to find text "Remove" in "Budget Investment 338 title 2019-05-24 • Manuela1296 • Global Heading Spend money on this €1 Vote"
     # ./spec/support/common_actions/budgets.rb:10:in `block in add_to_ballot'
     # ./spec/support/common_actions/budgets.rb:8:in `add_to_ballot'
     # ./spec/features/budgets/investments_spec.rb:1559:in `block (3 levels) in <top (required)>'
```

## Cause

We don't know the cause yet. It might be related to issues with turbolinks when an element with an AJAX callback has been removed from the DOM, but that's only a wild guess.

**Comment by javierm** [comment]
It hasn't failed for months, so it might be fixed by #3113 or by another change.
