### ISSUE TITLE
Añadir buscador en admin/users

### ISSUE THREAD

**Issue by decabeza** [consul/consul#307]
Añadir un buscador en **Admin** para **usuarios ocultos**.

Puede ser igual que el de `admin/officials`

**Comment by javimbk** [comment]
Buenas,

sólo comentar que estoy haciendo esto actualmente, para no pisarnos las PRs y así poder abarcar más!
Enhorabuena por el proyecto, y encantado de conoceros!

**Comment by decabeza** [comment]
Ey @javimbk! ¿cómo llevas esto? ¡Gracias por echar una mano! :wink:

**Comment by nachogomez** [comment]
Buenas...podemos colaborar'

**Comment by decabeza** [comment]
Continue on #655
