### ISSUE TITLE
Missing translation for date.order

### ISSUE THREAD

**Issue by alerodrom** [consul/consul#3078]
### User Story

As a user, I want to be able to verify my residence.

### Why is this Needed?

When I try to access the page to be able to verify my residence, without this the users will not be able to vote on proposals. I want the application to show the form so that users can verify their residence, but now the application returns a 500 error.

### Description

*Type*: Bug

### Current Behavior

The application returns an error 500, and in the logs of the application it returns the following error:
```
ActionView::Template::Error (undefined method `map' for "translation missing: es.date.order":String
Did you mean?  tap):
    59: 
    60:       <div class="date-of-birth small-12 medium-6 clear">
    61:       <%= f.label t("verification.residence.new.date_of_birth") %>
    62:       <%= f.date_select :date_of_birth,
    63:                         prompt: true,
    64:                         start_year: 1900, end_year: 16.years.ago.year,
    65:                         label: false %>
  app/views/custom/verification/residence/new.html.erb:62:in `block in _app_views_custom_verification_residence_new_html_erb___1756775254094863727_66747460'
  app/views/custom/verification/residence/new.html.erb:30:in `_app_views_custom_verification_residence_new_html_erb___1756775254094863727_66747460'

```

### Expected Behavior

I expected the form to be opened in order to verify the residence of the user who is trying.

### Steps to reproduce

1. Log in to the platform as a user who has not verified residency.
2. Accessing to my account (my-domain/account)
3. Accessing to Verify my account (my-domain/residence/new)

### Definition of Done

The version of CONSUL that is being used is the latest version of the master branch. The last commit is [https://github.com/consul/consul/commit/a89e00b7b8fa0cdc838ae67f0c23530436713c48](url).

I have seen that there is a [pull request](https://github.com/consul/consul/pull/3007) where the translations that are failing me are deleted. As a possible solution it occurs to me to go back to add them again or change the helper (date_select) to string and using javascript to generate the date selector.

**Comment by javierm** [comment]
@alerodrom Thank you for opening this issue. It will be fixed before our next release :wink:.
