### ISSUE TITLE
syntax error, unexpected '{'

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3114]
### User Story

[comment]: # Running a development server locally, I should be able to login to test translations. 

### Why is this Needed?

[comment]: # To test translation locally before updating

### Description

[comment]: # 
*Type*: Bug

### Current Behavior
[comment]: # I follow the instructions in README.md to set up a development environment. The application runs. On the first page I clicks `Sign in` a Ruby error message opens.

![image](https://user-images.githubusercontent.com/106038/50156291-bc77d800-02ce-11e9-9e70-e94456610575.png)

### Expected Behavior
[comment]: # Should be able to log in with the default credentials as described in README.md

### Steps to reproduce
[comment]: # Set up a development environment, go to homepage, go to `Sign in`

### Definition of Done
[comment]: # A login page should show that allows me to log in with the default credentials.

**Comment by javierm** [comment]
@milovanderlinden Thank you for reporting this issue. We don't support Ruby 2.5 (yet), and it seems the Devise gem would need to be updated before upgrading to Ruby 2.5.

Until we offer support for Ruby 2.5, we recommend using the supported version 2.3.2 :wink:.
