### ISSUE TITLE
Translations for proposals, debates, budget investments and comments

### ISSUE THREAD

**Issue by Senen** [consul/consul#3130]
### User Story
As a citizen, i want to read proposals, debates, budget investments and their comments in my preferred language.

### Why is this Needed?
Consul interface is available in 17 languages actually and growing but proposals, debates, budget::investments and comments are only available in default application language. 

### Description
*Type*: Feature

The purpose of this issue is to make these models translatable. So we will need to provide users an optional interface to add language translations if they like.

1. Add globalizable concern and migrations to add database translations to Proposals,Debates, BudgetInsvestments and Comments 
2. Add globalizable behavior to frontend forms
3. Add feature setting to allow administrators to enable/disable translation interface at frontend
4. Create new feature setting to enable/disable translation interface at frontend
5. Add translation interface to frontend translatable forms
6. Enhance translation interface for frontend views. There are so many language tabs active at the same time

### Current Behavior
Proposals, Debates, BudgetInvestments and Comments are not translatable and only readable in default application language.

### Expected Behavior
Proposals, Debates, BudgetInvestments and Comments are translatable and readable in all application available locales.

### Definition of Done
* Users are able to read Proposals, Debates, BudgetInvestments and Comments in their preferred language when desired translations exists
* Users can introduce Proposals, Debates, BudgetInvestments and Comments(🤔) in all languages if they like and only when feature setting is enabled.

**Comment by javierm** [comment]
Closed via #3359.
