### ISSUE TITLE
Remove proposals form fields

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3182]
### Background

When a user create a proposal on `/proposals/new` there are a couple of unnecessary form fields.

### What we need

Remove:

- **Proposal question** (if a proposal go to voting can use their own title).
- **Link to additional documentation** (now the users can attach documents to the proposals).

**Note** it would be nice **create a rake task** to move all previous data on the field `Link to additional documentation` to the end of the field **Proposal text**

e.g.
**Description**: "some text"
**Link to additional documentation**: www.link.com
Will become
**Description**: "some text www.link.com"

### Screenshot
![remove_proposal_fields](https://user-images.githubusercontent.com/631897/51176281-d05a2e00-18bc-11e9-93e3-fcccb0d026f1.png)

**Comment by bear-my-wrath** [comment]
Hello, I'm new to open source and I'd like to try solving this bug.

**Comment by microweb10** [comment]
Hi @bear-my-wrath! Thank you so much! 👏. All yours 😉.

**Comment by decabeza** [comment]
Hi @bear-my-wrath,

I just updated the issue description:

`Note it would be nice create a rake task to move Link to additional documentation if exists to the end of Proposal text`

It's not necessary move content of "Proposal question".

Thanks! 🙏 😌

**Comment by microweb10** [comment]
Hi @bear-my-wrath! How are you? I hope you are fine. 😄 

How is it going with this issue?

Please let us know if you need any help. Thank you! 🙏 😌
