### ISSUE TITLE
Search form on admin moderated content

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3183]
### Background

On Admin panel there is a section to show all **Moderated content** (content hidden by admins).

### What we need

1. Include a search form on all **Moderated content** sections. (You can found an example of search form on `/admin/proposals`)

2. Review all **Moderated content** admin sections to ensure are showing the correct content (only elements hidden by admins, not another content like proposals or budget investments retired by their authors):

- Hidden proposals `/admin/hidden_proposals`
- Hidden debates `/admin/debates`
- Hidden budget investments `/admin/hidden_budget_investments`
- Hidden comments `/admin/comments`
- Hidden proposal notifications `/admin/proposal_notifications`
- Hidden users `/admin/hidden_users`
- Moderator activity `/admin/activity`

3. Fix `Hidden proposal notifications` active menu on sidebar (now when select this section the sidebar menu disappear)

### Screenshots

![search_form](https://user-images.githubusercontent.com/631897/51177022-cb967980-18be-11e9-83fa-2ec33e2c743e.png)

![sections](https://user-images.githubusercontent.com/631897/51177024-cb967980-18be-11e9-8915-84bc41c19e59.png)

**Comment by Jacek-202** [comment]
Hi
Can i take this one?

**Comment by decabeza** [comment]
Of course @Jacek-202! All yours! 🎉 👏 

Don't hesitate to ask any questions you may have. 😌
