### ISSUE TITLE
ERROR 500 | Creating new budget investment proposal

### ISSUE THREAD

**Issue by kevieman** [consul/consul#3192]
Hey!,

Regarding [issue 70 of the installer](https://github.com/consul/installer/issues/70) I have SSL working now but when creating a new proposal for a budget investment I receive a 500 error in browser. The new proposal is created anyway.

This is what I found in the log file:
```
W, [2019-01-17T09:42:28.265116 #23197]  WARN -- : [ActiveJob] [Rollbar] Got unexpected status code from Rollbar api: 400
W, [2019-01-17T09:42:28.484569 #23197]  WARN -- : [Rollbar] Got unexpected status code from Rollbar api: 400
F, [2019-01-17T09:42:28.488860 #23197] FATAL -- :
SocketError (getaddrinfo: Name or service not known):
  app/controllers/budgets/investments_controller.rb:62:in `create'
```
It refrences to [this line](https://github.com/consul/consul/blob/7724f9421ff79521d11b4dfe5798fcd7d493d588/app/controllers/budgets/investments_controller.rb#L62)

**Comment by sturpin** [comment]
Hi @kevieman !!
What hostname do you've to connect to psql?

**Comment by kevieman** [comment]
Hey @sturpin, thank you for helping out again!
Im not shure what you mean with hostname, but this is what i found in the connection settings:
```
listen_addresses = 'localhost'
port = 5432
```

**Comment by sturpin** [comment]
Hi friend!! :)
set listen_addresses to 127.0.0.1 and try again.

**Comment by kevieman** [comment]
I restarted postgresql but got the same result.

**Comment by sturpin** [comment]
OK.
What value do you've in host of `consul/config/database.yml`

**Comment by kevieman** [comment]
Aswell `localhost`

**Comment by milovanderlinden** [comment]
I think that you need to change localhost to 127.0.0.1 there too.

**Comment by javierm** [comment]
It looks like a crash sending the email, probably related to SMTP not being configured.

Closing this one for now, since we've got more issues related to SMTP which could be considered duplicates of this one, like #3391.
