### ISSUE TITLE
Página de notificaciones

### ISSUE THREAD

**Issue by kikito** [consul/consul#32]
¿Queremos que la gente sepa que les han respondido a un comentario de forma visual? Y de ser así, ¿cómo lo mostramos? Ejemplos: Con un "inbox arriba", tipo facebook ("5 respuestas a tus comentarios", pulsa aquí para desplegar y verlos), o con un numerito en cada debate ("2 respuestas en este debate").

@decabeza, te invoco.

**Comment by decabeza** [comment]
Yo soy fan de la campanita, aunque también un punto (a lo github) en la foto del usuario podría funcionar. Creo que es mejor agruparlos en un solo sitio (notificaciones) que no en cada uno de ellos (lo que obliga a estar navegando para ver lo nuevo :)

![screen shot 2015-07-23 at 22 06 39](https://cloud.githubusercontent.com/assets/631897/8860936/5ac3bc8a-3187-11e5-83c4-2516daabddbc.png)
![screen shot 2015-07-23 at 22 06 46](https://cloud.githubusercontent.com/assets/631897/8860937/5ac83bca-3187-11e5-9d38-1728fb2db3b8.png)
![screen shot 2015-07-23 at 22 06 56](https://cloud.githubusercontent.com/assets/631897/8860938/5acb099a-3187-11e5-8f07-129f3a161b99.png)

**Comment by kikito** [comment]
Relacionado con el envío de emails (#23)

**Comment by voodoorai2000** [comment]
Sugerencias: 

De momento habría dos tipos de actividades: alguien ha comentado en tu debate y alguien a respondido a tu comentario. 

Podríamos utilizar la gema public_activity o casi mejor una implementación a mano como hace Ryan [aquí] (http://railscasts.com/episodes/407-activity-feed-from-scratch)

Aparte de las actividades, deberíamos contemplar el concepto de notificaciones, para tener en cuenta a los usuarios que deberían ser notificados de los 2 tipos de actividades que pueden ocurrir. (notification belongs_to :activity)

**Comment by decabeza** [comment]
Para esto hace falta crear:

* Una página de notificaciones (/notifications)

* En ella se mostrará un listado con dos tipos de actividad:
  * Alguien **ha comentado** en tu debate: "Usuario" ha comentado en tu debate "Título de debate"
  * Alguien **ha respondido** a tu comentario: "Usuario" ha respondido a tu comentario en "Título de debate"

* Ambas actividades deben **mostrar el "Timestamp"** (mismo formato que en los comentarios).

* Un enlace en `/devise/menu/_login_items.html.erb` a esta página. El enlace debe de tener dos clases: "sin notificaciones" y "con notificaciones". Puede ser un texto y no hace falta que esté en los ficheros de texto ya que lo sustituiré por un icono.

Una vez hecho asignarme esta issue para añadirle estilos. :tada:

**Comment by microweb10** [comment]
Hay alguien trabajando en esta issue? Si no hay nadie, como puedo asignarme el ticket para trabajar en el y la gente sepa que yo estoy trabajando en el? Gracias

**Comment by decabeza** [comment]
No hay nadie con esta issue, así que @microweb10 le quito la etiqueta de PRs-welcome ¡y toda tuya! ;)

**Comment by microweb10** [comment]
:+1: 
Gracias.
No prometo que pueda hacerlo rapido porque no tengo mucho tiempo, la verdad. Pero trabajare en ella, he cogido esta simplemente porque era la mas vieja, voy a intentar darle un impulso a la plataforma en mis ratos libres :)

**Comment by microweb10** [comment]
Nadie coge esto? :(

**Comment by xuanxu** [comment]
Perdona por no haberte respondido antes, @microweb10. Antes de nada, gracias por la pull request, nos gusta y tenemos en mente aceptarla. Pero la tenemos un poco congelada porque ahora mismo está muy por detrás de master y hay muchos conflictos al mergearla. Uno de los principales es que paralelamente a tu PR creamos en su día un modelo `Activity` para otro uso no relacionado con este issue (log de actividad de moderadores) y habría que decidir modificar y renombrar uno de los dos. El caso es que por temas de carga de trabajo se nos ha quedado un poco abandonada la PR pero nuestra intención es que entre a master, probablemente en cuanto tengamos tiempo la mergeemos a una rama desde la que arreglar los conflictos y aprovechar todo lo que podamos para luego meterlo a master.

**Comment by microweb10** [comment]
OK, me alegra que el proyecto no este muerto, la verdad es que estaba buscando algun proyecto Rails para trabajar en el y darme un poco de visibilidad en github, pero al ver que nadie ni contestaba, ni hacia el merge, ni nada, pense que el proyecto estaba muerto, y me desanime. Todos tenemos poco tiempo libre y a nadie le gusta trabajar para nada, como minimo que alguien se beneficie de tu trabajo. 

Simplemente cogi esa issue porque pense que los que estaban los ultimos quedarian olvidados y alguien tendria que hacerlos. Entonces me sugieres que coja issues que tengan la etiqueta hi-priority mejor??

**Comment by xuanxu** [comment]
@microweb10 Las `high-priority` creo que están ahora mismo todas asignadas. Un buen lugar donde mirar son las issues marcadas con la [etiqueta PR-welcome](https://github.com/consul/consul/labels/PRs-welcome), ahí vamos añadiendo las cosas que creemos que pueden ser útiles y están suficientemente bien definidas como para que no haga falta saber mucho contexto para ponerse manos a la obra. Cualquiera que veas libre te la puedes asignar. Por ejemplo esta: #679.

**Comment by microweb10** [comment]
OK, y la rama que tengo que checkear para obtener el codigo mas reciente y que eso no pase otra vez, es la rama master, verdad? Gracias!

**Comment by kikito** [comment]
@microweb10 sí, las ramas nuevas (y las actualizaciones de ramas viejas) siempre se hacen contra master.

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/811
