### ISSUE TITLE
Seguimiento de secuencia de eventos importantes con Ahoy

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#320]
Para saber si los usuarios se quedan por el camino al realizar una acción, debemos hacer un seguimiento desde el principio hasta el final de la acción. 

- [ ] Registro (New/Create)
- [ ] Verificar cuenta (Padrón/SMS/Carta)
- [ ] Crear un debate (New/Create)

**Comment by xuanxu** [comment]
deprecated
