### ISSUE TITLE
Why are pull requests not handled?

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3227]
Hello,

I can see that this project has 111 open pull requests. May I be so impolite to ask why they do not get pulled? Some date back to 2017. It is my opinion that they either need to be declined with a reason, or pulled.

**Comment by voodoorai2000** [comment]
Hey @milovanderlinden!

Thank you very much for concern 😌
We are simply ~a bit~ overloaded with everything that requires our attention in this fantastic and huge project.

If you would like to help us with reviews, closing issues, tidying things up, answering questions, all help is welcome! ❤️

**Comment by milovanderlinden** [comment]
I do, I have started helping on the website and access to gitter or slack has been requested via netdem. Hope to be able to help soon!
