### ISSUE TITLE
Allow multiple answers for poll questions with minimum and maximum limits

### ISSUE THREAD

**Issue by tiagozini** [consul/consul#3232]
**User Story**
As a user
I want to have a way to select more than just one answer by question in a poll considering optionally a minimum of answers as mandatory and optionally a maximum limit too. Also a error message must appear when the minimun number of answers chosen was not achivied. The miminum and maximum limit must appear between brackets at right side of the related question.

**Why is this Needed?**
The problem is that some questions could have more than one answer as the user answer. In these cases, limit the user to select only one answer will result in an unrealistic idea of what people really think about the subject.

**Description**
Feature: Allow a poll to have more than one answers as chosen. Optianally the poll question creator will have the option to obligate a minimal number of choices and a maximum too. It should be possible to configured this in the poll question manage. A button for confirm the votes in the and of poll is also necessary and the vote code for future check needs to be showed only after button have been clicked and all questions have been answered considering the minimum and maximum especifications.

**Comment by milovanderlinden** [comment]
As a work-around; make sure questions can only have boolean answers "yes/no". It will take some effort to rewrite them, but that way the system will be usable.

I also think that allowing non-boolean answers will be a big effort for the developers as it also requires changes to the vote-analyses.

**Comment by javierm** [comment]
It looks like issue #3475 includes this one :thinking:. @tiagozini If you don't feel this is correct, feel free to reopen this issue :wink:.
