### ISSUE TITLE
invalid mode: delegated using Docker

### ISSUE THREAD

**Issue by uribes78** [consul/consul#3262]
Trying to install using Docker is going well until it start, y showing the next message:

`consul_database_1 is up-to-date
Creating consul_app_1      ... error

ERROR: for consul_app_1  Cannot create container for service app: invalid bind mount spec "consul_bundle:/usr/local/bundle:delegated": invalid mode: delegated

ERROR: for app  Cannot create container for service app: invalid bind mount spec "consul_bundle:/usr/local/bundle:delegated": invalid mode: delegated
ERROR: Encountered errors while bringing up the project.`

I'm trying to installed on CentOS 7, I can not be able to initialize the container. Any suggest? Thanks

**Comment by milovanderlinden** [comment]
Assuming you are running docker compose from the root directory of the clone or download of this repository;
1. Can you first try to create a `bundle` directory (in the consul dir on the host system)? or, as your error suggests; a `consul_bundle` directory?
2. If that doesn't work, open the file  `docker-compose.yml`
and on lines 36 and 37, remove the `:delegated` annotation on the volume declarations.

**Comment by milovanderlinden** [comment]
It can also have to do with the version of your docker-compose and docker binaries. If the previous suggestions doesn't work, could you please output the result of the commands 
```bash
docker --version
docker-compose -v
```
These are my results:
```bash
[me@mypc consul]$ docker --version
Docker version 18.09.1-ce, build 4c52b901c6
[me@mypc consul]$ docker-compose -v
docker-compose version 1.23.2, build unknown
```

**Comment by uribes78** [comment]
@milovanderlinden  thanks to answer. I have already solved the issue, at the end only remove the `delegated` and it's working now. Any way this is the version I have:

Docker version 1.13.1, build 07f3374/1.13.1
docker-compose version 1.18.0, build 8dd22a9

Regards
