### ISSUE TITLE
Not sending confirmation email

### ISSUE THREAD

**Issue by uribes78** [consul/consul#3270]
it's my again. I configured the email (gmail smtp service) to send confirmation register email, but it's not sending at all. 

I try changing the development.rb file with no tabs and now it's showing me this message:

![consul-email-message](https://user-images.githubusercontent.com/18754899/52315577-be782200-2974-11e9-853e-0a276336a9f5.png)

Do I need to have installed any browser to send emails in the platform? or Am I missing something? I'm using the docker version, and can I see in the Dockerfile the installation of the chromium, but I guess is necesary to define and enviroment variable to use chromium, Am I right? Please, any help is welcome. thanks

**Comment by javierm** [comment]
@uribes78 I think it's because, by default, in the development environment, emails are not sent, but opened in a browser.

Feel free to reopen this issue if this comment didn't help you :wink:.
