### ISSUE TITLE
Run migration from page

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3279]
### User Story

As a system administrator, when I install a new instance, I want to be able to run migrations from a page instead of from the command line.

### Why is this Needed?

Running migrations is the first step after the installation that currently throws an error and tells you to go run bin/rake db:migrate RAILS_ENV=development. I think this error page could be replaced with a page with a simple button where you can actually run the migration directly without having to go to your system

![image](https://user-images.githubusercontent.com/106038/52466786-be9a3c80-2b83-11e9-9691-44c2bb549ef8.png)

### Description

*Type*: Feature

### Current Behavior
Shows error page

### Expected Behavior
Should show page asking something like "The system is not operating correctly, do you want me to try and fix this?"

### Steps to reproduce
- Install fresh instance of consul
- Make database available
- Start consul

**Comment by javierm** [comment]
This looks like an issue affecting Rails internals; not much we can do in CONSUL :thinking:.

Feel free to reopen this issue if there's a gem adding this functionality which we can add to CONSUL. You can also try opening an issue on the [rails repository](https://github.com/rails/rails/).
