### ISSUE TITLE
Allow configuration from the web-interface when no seed has ran

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3282]
### User Story

As administrator, I want to be able to configure consul from the web-interface from scratch

### Why is this Needed?

I want to have a consul instance that only has a admin user. The admin user can then use the web-interface to configure consul. This way, we can set up consul and hand over to an administrator who can then configure consul to fit his/her needs.

### Description

*Type*: Bug

### Current Behavior
Rails/Ruby errors are shown at various places in the web interface

### Expected Behavior
Dialogs should be presented where an administrator can configure consul in the broadest way.

### Steps to reproduce
1. Install consul
2. Run the `rake db:migrate` task
3. Add a superuser

For this I added a rake task:
```ruby
namespace :users do
    desc "Create superuser"
    task superuser: :environment do
        email = Faker::Internet.email
        password = Faker::Internet.password
        puts "Superuser created. You can log in with \"#{email}\" using \"#{password}\" as password"

        silence_stream(STDOUT) do
            admin = create_user(email, password)
            admin.create_administrator
            admin.update(residence_verified_at: Time.current,
                confirmed_phone: Faker::PhoneNumber.phone_number, document_type: "1",
                verified_at: Time.current, document_number: Faker::Code.npi)
        end
    end

    def create_user(email, password)
        User.create!(
          username:               Faker::Name.name,
          email:                  email,
          password:               password,
          password_confirmation:  password,
          confirmed_at:           Time.current,
          terms_of_service:       "1",
          gender:                 ['Male', 'Female'].sample,
          date_of_birth:          rand((Time.current - 80.years)..(Time.current - 16.years)),
          public_activity:        (rand(1..100) > 30)
        )
    end
  end
```
The task will generate a admin user with a random name, email and password. The task will output the login credentials.
```bash
rake users:superuser

Superuser created. You can log in with "emerald@murphy.info" using "MjVpF8McRq3nI7X" as password
```
4. I now login with the newly created superuser and go to http://localhost:3000/admin/settings it generates an error.
![image](https://user-images.githubusercontent.com/106038/52519714-4190c500-2c60-11e9-831b-b2a448bf56e5.png)

### Definition of Done
No errors show up browsing through the consul web interface when no seed has been run.

**Comment by javierm** [comment]
It looks like there are no settings created :thinking:. I'm afraid there are no plans to support installations which don't run `db:seed`, which creates the settings.
