### ISSUE TITLE
Ruby Sass is Deprecated

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3284]
http://sass.logdown.com/posts/7081811

**Comment by PierreMesure** [comment]
I replaced the gem by the new one, as [advised](https://github.com/rails/sass-rails/issues/420). No problem noticed so far, let's see what the tests say.

**Comment by PierreMesure** [comment]
The tests passed so I guess we can merge and close this and update the gem when upgrading to Rails 5 and Ruby 2.5.
