### ISSUE TITLE
Capistrano deployment requires ed25519 gem

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#3285]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

Not sure why but I started to get the following error message when trying to deploy using capistrano:

```
00:00 rvm1:hook
      01 mkdir -p /home/deploy/consul/rvm1scripts/
(Backtrace restricted to imported tasks)
cap aborted!
NotImplementedError: OpenSSH keys only supported if ED25519 is available
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "Could not find 'ed25519' (~> 1.2) among 234 total gem(s)
Checked in 'GEM_PATH=/Users/admin/.gem/ruby/2.3.0:/Users/admin/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0', execute `gem env` for more information"

Tasks: TOP => rvm1:hook
```

Adding the two gems fixes it:
```
gem 'ed25519', '~> 1.2'
gem 'bcrypt_pbkdf', '~> 1'
```

And then I get the following error message:
```
00:00 rvm1:hook
      01 mkdir -p /home/deploy/consul/rvm1scripts/
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@188.166.38.114: expected 64-byte String, got 3


Caused by:
ArgumentError: expected 64-byte String, got 3

Tasks: TOP => rvm1:hook
```

Which I fix by updating net-ssh to 5.1.0 (by default, it's at 5.0.2).

It's the first time I get this while using Capistrano to deploy to a Ubuntu 16.04 machine. I've always been using OpenSSH until now, without an issue.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

Follow the Capistrano deployment guide until you reach the command `cap production deploy`

Anyone has encountered this before? It seems to be a [common issue](https://github.com/net-ssh/net-ssh/issues/565).

**Comment by PierreMesure** [comment]
I don't know why but this one seems fixed with v1.0.0.

**Comment by lucasocon** [comment]
On Mac OS, you need to run: 
`ssh-add [yourkey] `

**Comment by JohnSmall** [comment]
Very strange this error came up for me after I'd been happily deploying from an Ubuntu 20.04 system to an Ubuntu 20.04 system. It worked just fine a couple of days ago and now suddenly 'Gem::LoadError : "Could not find 'ed25519' (~> 1.2) etc'

If things had been working before, why would I suddenly get this error?

**Comment by javierm** [comment]
Hi, @JohnSmall :smile:.

Could you provide a link to the repository and branch with the code where you're getting this error?
