### ISSUE TITLE
precompile will not generate static assets without hashes

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3289]
When I run `bin/rake assets:precompile`, I get assets with hashes. I set all the parameters to try and make the task mentioned generate `application.js` and `application.css` and all the assets *without* hashes, but it just won't generate them.
Can anybody tell me how the `public/stylesheets/`, `public/javascripts/`, `public/help/` and all the other "static" directories are created and filled?

**Comment by voodoorai2000** [comment]
This is not a CONSUL issue, it's how assets work in Rails for production environments. 

Please refer to the Rails documentation on assets: https://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark

**Comment by milovanderlinden** [comment]
Can you explain to me then why my consul instance running with RAILS_ENV=production generates a page at view-source:https://midden-groningen.consulproject.nl/ that generates asset urls that look like:

```html
<!DOCTYPE html>
<html lang="en" data-current-user-id="">
  <head>
    <meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>CONSUL</title>
<link rel="stylesheet" media="screen" href="/stylesheets/application.css" />
<script src="/javascripts/application.js" data-turbolinks-track="true"></script>
```
As this rendered code clearly looks for assets in the wrong place.
