### ISSUE TITLE
consul contains vulnerabilities

### ISSUE THREAD

**Issue by milovanderlinden** [consul/consul#3306]
I ran 
```bash
docker run -v "$(pwd)":/code presidentbeef/brakeman -f markdown
```
and this is the result: https://gist.github.com/milovanderlinden/d3ec4f2a0c3a8547ce8b5da6f1f38926

I suggest setting up a strategy to fix these vulnerabilities.

**Comment by voodoorai2000** [comment]
Thank you @milovanderlinden we'll review it 👍 

If you find other security issues, please do not post them in Github, instead send us an email at extension.institucional@madrid.es.
