### ISSUE TITLE
New language - Danish

### ISSUE THREAD

**Issue by natasakvinfo** [consul/consul#3320]
Hi, I work in Kvinfo, www.kvinfo.dk and we want to implement Consul in our organization. We would like to make Danish translation for Consul. How can we do that?

**Comment by decabeza** [comment]
Hi @natasakvinfo,

For manage translations we use [Crowdin](https://crowdin.com/project/consul). Feel free to sign up to complete danish translations. 😉

You have a little more of information in our [Translations documentation](https://consul_docs.gitbooks.io/docs/content/en/customization/translations.html).

Thank you very much for the help! 🙏🏻😌
