### ISSUE TITLE
New language (danish)

### ISSUE THREAD

**Issue by Jakobasmussen** [consul/consul#3322]
Hello I would like to have my language danish added to CONSUL

**Comment by decabeza** [comment]
Hi @Jakobasmussen,

For manage translations we use [Crowdin](https://crowdin.com/project/consul). Feel free to sign up to complete danish translations. 😉

You have a little more of information in our [Translations documentation](https://consul_docs.gitbooks.io/docs/content/en/customization/translations.html).

Thank you very much for the help! 🙏🏻😌

**Comment by decabeza** [comment]
Closed because is duplicated with https://github.com/consul/consul/issues/3320.
