### ISSUE TITLE
Rename debate and comment controller to hidden controller in admin

### ISSUE THREAD

**Issue by germangaliadigital55** [consul/consul#3350]
In the admin panel the controllers of debates and comments are for the moderated content section (hidden comments and hidden debates). Now the debates_controller and comments_controller are needed for the new Debates and Comments sections in the admin panel menu.

They should be refactored from debates_controller and comment_controller to hidden_debate_controller and hidden_comment_controller.

**Comment by javierm** [comment]
Closed via #3376.
