### ISSUE TITLE
Show the price of investments in its own column on the administration index page

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3355]
### User Story

As a admin user, I want to see the price of investments in its own column instead of associated to feasibility so that will make it easier to understand the investment information.

### Why is this Needed?

Now the price of the investments is shown as feasibility information only if the investment has a feasible status.
Adding the "Price" column, that information will be displayed for all investments and users without navigating to the detailed page

### Description

*Type*:Feature

### Current Behavior

Price of the investments is shown as feasibility information only if the investment has a feasible status.
![image](https://user-images.githubusercontent.com/1029265/54264296-0f31fa80-4573-11e9-9156-1b8cb99cff65.png)

### Expected Behavior

Price of the investments will have its own column.
![image](https://user-images.githubusercontent.com/1029265/54264401-561ff000-4573-11e9-8553-001c425f6642.png)

**Comment by javierm** [comment]
Closed via #3356.
