### ISSUE TITLE
Add new max support advanced_filter for admin investments

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3357]
### User Story

As a admin, I want to filter investments by max support field

### Why is this Needed?

We can filter investments by min support value and we want to filter by max support number too

### Description

On admin investments page, add new text input field on advanced filter area for filter by max support number value 

*Type*: Feature

### Current Behavior

This filter not exists

### Expected Behavior

- New filter field has to be display inside advanced filters component
- If input text is empty, this filter will not apply
- Input text allow integer values
- If input text has value, only investments which match with filter will be display after click on filter button
- After filtering, input text has to keep value

### Definition of Done
go to admin/budgets/:budget_id/budget_investments
After apply max support filter, only investments which match with filter will be display
Placeholder will have translations

**Comment by javierm** [comment]
Closed via #3364.
