### ISSUE TITLE
Main fonts have only latin letters

### ISSUE THREAD

**Issue by ppeczek** [consul/consul#3372]
Any nonlatin letter language needs to override fonts right now with the same font families containing their native letters. This could be easily fixed by loading multi-language asset.

**Comment by javierm** [comment]
@ppeczek I can't reproduce this issue. Chinese looks fine on my machine :thinking:.

![CONSUL in Chinese, with Chinese characters](https://user-images.githubusercontent.com/35156/67136182-0bf69f80-f223-11e9-90fe-e044fff978f6.png)

**Comment by javierm** [comment]
@ppeczek I think I'd need some help to reproduce it. Could you add more information, like which system you're using, a screenshot of what you see, ...? Thanks! :pray:

**Comment by javierm** [comment]
Closing since I can't reproduce the issue and no further information was provided.
