### ISSUE TITLE
City map bug

### ISSUE THREAD

**Issue by ppeczek** [consul/consul#3374]
Updating map at URL: `admin/site_customization/images` doesn't update it at: `proposals/map`

**Comment by PierreMesure** [comment]
Hey Piotr, I don't see any setting to update the map at the address you mention. You can change the map by adding the file named `map.jpg` at `app/assets/images/custom`.

This is what is recommended in the [docs](https://github.com/consul/docs/blob/master/en/customization/images.md).

If you want to use a PNG (which makes more sense sometimes), you'll need to modify the reference to the map directly on the page templates.

**Comment by Dr4u95** [comment]
Hi, I did the same step  ppeczek and have the same issue ( The map appears in /proposals but in /proposals/map still is the default). 
  - I added an image in the file app/assets/images/custom/map.jpg , no works.
  - I modify the file map.jpg in app/assets/images/ and nothing too.

**Comment by PierreMesure** [comment]
Not sure what to tell you besides making sure that you deployed the code and restarted the server. It might be that the assets haven't been precompiled correctly.

See our [demo instance](https://consul.demokratiskastader.se/proposals/map) and our [source code](https://github.com/digidemlab/consul/tree/master/app/assets/images/custom) for comparison.

**Comment by Dr4u95** [comment]
First of all, i only install the Production Server. I did the step in the other post and compile the assets using :

   1. RAILS_ENV=production bundle exec rake assets:clobber 
   2. RAILS_ENV=production bundle exec rake assets:precompile

All the files that I touch, they modified, while the map (districts) disappears and does not show any.

**Comment by decabeza** [comment]
Hi @ppeczek @PierreMesure @Dr4u95!

Admin users can change **map image** on `/admin/site_customization/images`:
![site_customization_images](https://user-images.githubusercontent.com/631897/57291838-86da5c80-70c0-11e9-87a3-3405fee61769.png)

But this custom image is not rendering in all pages with the map 😅. 

I create a PR https://github.com/consul/consul/pull/3472 to fix it! 🙏

**Comment by Dr4u95** [comment]
@decabeza Ty, that works 💯  ... only forget close the ("map.jpg") in the second file 👍 .

@PierreMesure Ty for let me see your demo, I check a fault that had with the coordinates, should insert only the coordinates and not the entire label 👍 .
