### ISSUE TITLE
Change username display for administrators in "Valuation comments"

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3393]
### User Story

As a evaluator or admin user, I want to see administrator or evaluator name in "Valuation comments" so that will make it easier to identify the user who has commented

### Why is this Needed?

Now, on comments component, if a comment was made as administrator, we display "Administrator {id}" as commenter
For public part this funtionality is fine, but in admin and evaluator layouts we want to display user name(or alias https://github.com/consul/consul/issues/3375) to make easy to identify which user made the comment 

### Description

Change comments partial to display administrator name or alias only in admin and evaluator layouts

*Type*: Feature

### Current Behavior

When user comments as administrator, "Administrator #{id}" will be display as name
![image](https://user-images.githubusercontent.com/1029265/54675404-c8a64800-4afe-11e9-9e68-bf89468d743f.png)

### Expected Behavior

Public site keeps the same functionality
Valuation comments will display admin name or alias instead of "Administrator #{id}"
![image](https://user-images.githubusercontent.com/1029265/54675884-bc6eba80-4aff-11e9-8f0a-612fedc4faee.png)

### Steps to reproduce
Go to admin budget investment page `/admin/budgets/:budget_id/budget_investments/:investment_id` and make a valuation comment as administrator

### Definition of Done
Public comments will keep the same funtionality
Administrators and evaluators will see administrator name for comments done as administrator

### Notes
Related with https://github.com/consul/consul/issues/3375

**Comment by javierm** [comment]
Closed via #3389.
