### ISSUE TITLE
New language - Macedonian

### ISSUE THREAD

**Issue by jovanovski** [consul/consul#3394]
Hey guys, can you open up the Macedonian language on Crowdin so we can add localization for it? :D

**Comment by decabeza** [comment]
Hi @jovanovski!

Macedonian language included on [Crowdin](https://crowdin.com/project/consul/mk) 🎉 

<img width="125" alt="Screenshot 2019-03-20 at 15 22 19" src="https://user-images.githubusercontent.com/631897/54691781-2305cf80-4b24-11e9-9737-0438ddb807a8.png">
