### ISSUE TITLE
Send email to admin and evaluators after valuation comment was created

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3395]
### User Story

As an admin or evaluator user, I want to receive an email every time a new valuation comment 
is created about an investment which I am related with so that makes the workflow more productive

### Why is this Needed?

With that feature, admin and evaluator users will be notify directly with every new comment 

### Description

We will add a new feature flag to enable/disable this new functionality, given to each implementation decide if they want it

If feature flag is enable, every time a "valuation comment" is created for an investment, an email with comment information will be sent to each user related to the investment. For evaluator groups, the email will be sent to any evaluator user within the group

*Type*: Feature

### Current Behavior

No notification is sent

### Expected Behavior

New feature flag will be created inside admin settings section
![image](https://user-images.githubusercontent.com/1029265/54752805-a6d0c200-4bdf-11e9-88d2-e956d1b6619f.png)

Feature flag default value will be enabled

If feature flag is disabled when valuation comment is created everything will work as it does now

If feature flag is enabled when valuation comment is created an email have to be sent to all users(admin and valuators) related to the investment
- Email must contain relevant information about valuation comment( user alias / Administrador #{id}, comment date, comment body..) 
- Email will be sent for each valuator user inside a group if that group is associated to the commented investment 

New email template will be added to "system emails" page

### Steps to reproduce
Create a new valuation comment into a budget investment

**Comment by javierm** [comment]
Closed via #3413.
