### ISSUE TITLE
Add Tags to Milestones

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3411]
### User Story

As a user, I want to filter investments by milestone tags so that makes easier find investments

### Why is this Needed?

It will help users to find investments by their milestones 

### Description

*Type*: Feature

### Current Behavior
N/A

### Expected Behavior

Add a new field on /admin/budgets/:budget_id/budget_investments/:investment_id/edit to add milestone tags as a string list split by commas

Display on /admin/budgets/:budget_id/budget_investments/:investment_id inside Milestone section the tag list

Add new select filter on /budgets/:id/executions to filter investments

**Comment by javierm** [comment]
Closed via #3419.
