### ISSUE TITLE
Add public investment information into admin and valuator investment pages

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3422]
### User Story

As a admin or valuator user, I want to see budget investment public page on my admin pages so that help me to have a preview or information about it

### Why is this Needed?

Now, if a admin user wants to see some public information about an investment, he have to go to public page(maps, docs, image...). Displaying public page components inside admin pages will help admin user to work better. Same for evaluators

### Description

*Type*: Feature

### Current Behavior

An admin page is shown for admin users with data information, but not visual information, and in some cases like maps, without any information 
Same for valuators

### Expected Behavior
See on admin budget investment show page all public information
See on valuator budget investment show page all public information
See on valuator budget investment edit page all public information

**Comment by javierm** [comment]
Closed via #3427.
