### ISSUE TITLE
Investment Vote - Cache - Cache not re-rendered on vote

### ISSUE THREAD

**Issue by ziyan-junaideen** [consul/consul#3423]
### Description

*Type*: Bug

A possible bug was encountered in [NYC](http://pbnyc.participatorybudgeting.org) installation while in voting. Affects only in production environment with caching.

Consider a user visiting a budget investment to vote. When voting, as expected, the voted info shows in the sidebar. How ever if you refresh the page, the the vote link shows up. You click on vote, nothing happens, you cant vote what is already voted.

Upon inspection, I noticed that the `cache` in the `budget/investments/_investment_show.html.erb` using an instance variable `@investment_votes` as an input to generate a cache key. Even if voted, this variable remains an empty hash `{}`. This explains why we see the 'Vote' link as nothing else has changed to generate a new cache key.

![Screenshot from 2019-04-05 11-26-11](https://user-images.githubusercontent.com/762159/55606243-a9154d80-5795-11e9-940b-f3bfdc1fdfd9.png)

I noticed that the vote process doesn't make a record in the `votes` table. But the instance variable is populated using the `votes` table.

If you can confirm, i can work on a fix.

### Current Behavior
In an app running in production environment, voting on a budget investment shoes the vote button after page reload / refresh.

### Expected Behavior

Following the voting process, the budget investment page cache should be invalidated and re-rendered. For this a new cache key should be generated to re-render the view.

### Steps to reproduce

- A consul installation using the installer (with cache and booted in production mode) v0.19
- Budget investment in voting
- Vote on selected project
- Refresh page - vote link shows

**Comment by javierm** [comment]
Closed via #4504.
