### ISSUE TITLE
Create a new subset of valuators that can only comment but not evaluate

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3428]
### User Story

As a budget investment reviewer, I want to only have the ability of create evaluation comments so that make dossier data more secure

### Why is this Needed?

We need a new kind of user profile at the level of a valuator that can create evaluation comments but can not edit dossier information.  

### Description

*Type*: Feature

### Current Behavior

We only have valuator user role which allow user to edit dossier information and create evaluation comments

### Expected Behavior

We will have the possibility of create valuator users by choosing the actions that the user can do.
Valuator user actions:
- Show budget investment
- Edit dossier
- Show evaluation comments
- Create evaluation comments

### Definition of Done

Administrator could manage valuator user to enable or disable to
- edit budget investment dossier information
- create evaluation comments

**Comment by javierm** [comment]
Closed via #3437.
