### ISSUE TITLE
Let administrator user choose display columns for investments table

### ISSUE THREAD

**Issue by abelardogilm** [consul/consul#3429]
### User Story

As an administrator, I want to select visible columns for budget investments table so that let me see useful information

### Why is this Needed?

A budget information resource has a lot of information which will be useful in some cases, but we cannot display all on current table. Let administrator user hide or show columns will help them to see only useful information for each user

### Description

*Type*: Feature

### Current Behavior

Budget investments table have some columns hardcoded
![image](https://user-images.githubusercontent.com/1029265/55709528-cc840680-59e8-11e9-85cf-e1b357f411ee.png)

### Expected Behavior

A new columns selector component will be added to allow administrator user choose visible columns
The current fields will be the set of columns visible by default.
Selected columns will be stored as cookie, to avoid extra http calls to the server.

**Comment by javierm** [comment]
Closed via #3439.
