### ISSUE TITLE
Usuarios de @madrid.es

### ISSUE THREAD

**Issue by kikito** [consul/consul#343]
Es deseable que los usuarios registrados con un email de @madrid.es (este dominio debería ser configurable en el admin) sean automáticamente nombrados como cargos públicos de nivel 1 ("Empleado público").

Sugerencias:

* Hacer una tarea rake para "reconvertir usuarios existentes"
* Hacer un campo en las settings para "dominio(s?) de email para cargos públicos"

**Comment by voodoorai2000** [comment]
Movido al repositorio de Madrid https://github.com/AyuntamientoMadrid/consul/issues/1
