### ISSUE TITLE
Create new history section in each project of participatory budget

### ISSUE THREAD

**Issue by Germangalia** [consul/consul#3433]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As administrator, I want to be able to see the changes made in the project of a participatory budget.

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

We need to know which changes has been made, by who, when and which was the original and new value.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

Changes made in projects are not recorded.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Administrators can check who modified the project, when and what.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Change log section appears in projects view.
- Changes are recorded in the change log table.
- Changes have a simple view.

**Comment by javierm** [comment]
Closed via #3456.
