### ISSUE TITLE
Greek

### ISSUE THREAD

**Issue by leftvla13** [consul/consul#3444]
Hello I would like to have my language Greek added to CONSUL

**Comment by voodoorai2000** [comment]
Thank you so much @leftvla13!

[Greek added to Crowdin](https://crowdin.com/project/consul/el#) 👍 

You have a little more information on translations [here](https://docs.consulproject.org/docs/english-documentation/customization/translations#translations).

Cheers!

**Comment by leftvla13** [comment]
Hello again!I finished tranlation in Greek [https://crowdin.com/project/consul/el#](url). How can i get it applied in the application;

**Comment by xrkolovos** [comment]
same with #3445.
Greek translations completed
