### ISSUE TITLE
Create "Traker" rol

### ISSUE THREAD

**Issue by Germangalia** [consul/consul#3461]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a traker I want to manage the milestones of Projects Investments in a panel like the valuator panel.

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

Only administrators can manage the milestones of Projects Investments. Creating a new rol "Traker" will allow this user to manage milestones but it will not have the same privileges that the administrator rol.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)

Milestones of Project Investments are only managable by administrators.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

New user rol "Traker" with a panel for managing milestones of Project Investments.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- A user with rol "Traker" can log into the Traking panel.
- A administrator can add the "Traker" role to a user.
- A "Traker" can manage milestones of Project Investments.

**Comment by javierm** [comment]
Closed via #3480.
