### ISSUE TITLE
Download collaborative legislation summary in Excel.

### ISSUE THREAD

**Issue by Germangalia** [consul/consul#3463]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a user I want to be able to view and download the resume of the more relevant data.

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)
There's no section that as a users permit to see nor download a summary of the results at the process and it's interesting to have such feature for analysis and statistics functions.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
There's no section that allows the user to see the summary of the data nor download it.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
Have a section that allows users to see a structured and concise summary of the most relevant process data and a button that download an Excel file with this data.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Tab "Results" appear in view of finished process in collaborative legislation section.

- Button that allow downloading the data into an Excel file.

**Comment by javierm** [comment]
Closed via #3473.
