### ISSUE TITLE
Getting 500 - Internal Server Error when registering

### ISSUE THREAD

**Issue by leftvla13** [consul/consul#3469]
### User Story

As a user, I want to be able to register into the application that i installed for production environment.

### Description

Type: Bug

### Current Behavior

When i try to register , I'm getting 500 Internal Server Error.When i retry putting the same credentials, it says that the username is already in use although i haven't finished the process of registering before.

**Comment by Dr4u95** [comment]
Check this https://github.com/consul/installer, in the part of  email configuration.  
And you can get more information of the fail in your server in home/user/consul/log/production.log

**Comment by javierm** [comment]
It definitely looks like a crash when sending the confirmation email, due to SMTP not being configured. Closing this one for now, since we've got more issues related to SMTP, like #3391.
