### ISSUE TITLE
Allow admins to manage LocalCensusRecords

### ISSUE THREAD

**Issue by Senen** [consul/consul#3478]
### User Story
As an administrator user i want to be able to manipulate LocalCensusRecords from the administration panel.

### Why is this Needed?
To provide to administrator users a way to manage the local census database through the administration panel. Currently the only way to manipulate this table records is through the rails console.

Allow adiministrators users to manage this table in two different ways:
1. Manually, one by one through a CRUD interface
2. Automatically through an importation process

### Description
- Create a new section under admin settings menu entry called "Manage Local Census" to manage local_census_records manually.
- Allow to import spreadsheet files and create records on database
- Only administrators users should be able to manipulate LocalCensusRecords

### Current Behavior
Currently administrators need the support of IT to manage the census database manually as rails console is the only way to access it.

### Expected Behavior
![Captura de pantalla 2019-04-03 a las 18 29 00](https://user-images.githubusercontent.com/16189/55496005-642ad300-563e-11e9-86a9-bdff4bd8ab09.png)

**Comment by javierm** [comment]
Closed via #3500 and #3646.
