### ISSUE TITLE
Add historic settings to participatory budget

### ISSUE THREAD

**Issue by Germangalia** [consul/consul#3481]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As a Administrator I want to be able to edit budgets so they are independent between years. I want to assign Tags, Administrators, Validators and Trackers that are available for the budget investments.

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)
Administrators, Validators and Trackers are available for all budgets investment in all budgets. This will allow to restrict Administrators, Validators and Trackers to only on budget.

Some settings may change between years.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Feature

### Current Behavior
[comment]: # (Describe what actually happened.)
Administrators, Validators and Trackers are available for all budgets investment in all budgets. 

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
To be able to set the Administrators, Validators and Trackers that are available to assign to the investment.

You only can assign Administrators, Validators and Trackers to investments that are assigned to the budget.

Set settings that change between years.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Be able to assign Administrators, Validators and Trackers to budgets.
- Be able to set the classification tags to budgets .
- Be able to set the help link to budgets.
- Only be able to assign Administrators, Validators and Trackers that are assigned to the budget.

**Comment by javierm** [comment]
Closed by #3514.
