### ISSUE TITLE
Connect "Follow citizen proposals" with author notifications

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3550]
## Background
The author of a proposal can create a notification that is sent (through the "Proposal notification digest"  included in the System Emails menu `/admin/system_emails`) to all users supporting the proposal. 

The proposals have an independent "Follow citizen proposal" button in its show page.

## What we need
When a user supports a proposal, it will automatically active also the "Follow citizen proposal" option. The proposal notifications will be sent not to all users supporting the proposal but to the users who have activated the "Follow citizen proposal" option. In the notification digest, under each notification it will appear also the link to unfollow that particular proposal.

**Comment by andrewcameronsims** [comment]
I can take this, if nobody else is working on it?

**Comment by javierm** [comment]
@andrewcameronsims Thanks! All yours! :smile: Feel free to ask any questions about the desired behaviour :wink:.

**Comment by andrewcameronsims** [comment]
@javierm Hi, I've created a PR for this issue which has been sitting there for a while now, thought it might have been overlooked, but can withdraw the PR if it is no longer relevant. 🙂

**Comment by javierm** [comment]
@andrewcameronsims Thanks a lot! :smile: We'll have a look at the pull request after we release version 1.1. Sorry for the late reply! :pray:
