### ISSUE TITLE
Restore blocked users content

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3551]
## Background
Users can be blocked through the Moderation interface `/moderation/users` hiding also all their content

## What we need
When a blocked user is restored by an administrator through `/admin/hidden_users` all his/her previously hidden content should be also unhidden.

**Comment by carlosiniesta** [comment]
👋 

I make something here https://github.com/consul/consul/pull/3770

Hope, you like it

**Comment by carlosiniesta** [comment]
After one year... I'm back and this time 
I added some specs, hopefully is useful.
