### ISSUE TITLE
Soft blocking for users

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3552]
## Background
Users can be blocked through the Moderation interface `/moderation/users` hiding also all their content.

## What we need
Create a "Soft block" option in the moderation interface that hide the user and block him for accessing the website, but doesn't hide all his/her content.

**Comment by Rytis-Lebedys** [comment]
I would like to work on this issue if its not taken yet

**Comment by javierm** [comment]
@Rytis-Lebedys Sure. Go ahead! :smile:

**Comment by carlosiniesta** [comment]
Hopefully is not rude to add this PR. I was working on a previous one related to this one and can't resist...
