### ISSUE TITLE
Bug when flagging as inappropriate collaborative legislation proposals

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3554]
## Description

It doesn't work the "Flag as inappropriate" option of proposals of the "proposals phase" of a collaborative legislation process.

**Comment by volcov** [comment]
i can work on this issue, if nobody picked yet ;)

**Comment by javierm** [comment]
@volcov All yours! :smile:

**Comment by javierm** [comment]
Huge thanks to @volcov for his work investigating this issue and adding the initial fix :pray: :tada:.
