### ISSUE TITLE
Add a name field for the signature sheets

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3557]
## Background
Proposals can be supported by signatures, and those supports can be included in the system through the "Signature sheets" menu in `/admin/signature_sheets`.

## What we need
Include an optional new field "name" in `/admin/signature_sheets/new` that will be shown in the list of sheets `/admin/signature_sheets` to facilitate differentiating between them.

**Comment by andrewcameronsims** [comment]
@javierm Hi, I saw that this PR was defunct but this issue is still open so I took the half finished branch and made the requested changes. Hope it's helpful.
