### ISSUE TITLE
Keep categories being shown when change proposal phase date on colaborative legislation processes

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3558]
## Background
When a proposal phase of a collaborative legislation process is active, in the sidebar are shown the categories of the process. 

When the admin change the date of the proposals phase the categories disappear from the sidebar.

## What we need
Keep showing the categories in the sidebar although the proposal phase date is changed.

## Screenshots

When the admin change the date of the proposals phase on `/admin/legislation/processes/N/edit`

![Screenshot 2019-11-04 at 13 05 56](https://user-images.githubusercontent.com/631897/68119768-db418600-ff03-11e9-94e7-6b82817a55c2.png)

The categories disappear of `/admin/legislation/processes/N/proposals` this causes also are disappearing on the front view.

![Screenshot 2019-11-03 at 19 00 36](https://user-images.githubusercontent.com/631897/68119774-ded50d00-ff03-11e9-858e-fd307fd9fd04.png)

![Screenshot 2019-11-03 at 18 59 10](https://user-images.githubusercontent.com/631897/68119780-e2689400-ff03-11e9-863a-dc8b369ce27b.png)

**Comment by andrewcameronsims** [comment]
Hi, I'd like to take this issue if nobody is working on it?

**Comment by javierm** [comment]
@andrewcameronsims All your! Thanks!

**Comment by andrewcameronsims** [comment]
Hello,

I've been attempting to recreate the issue described on my local machine and was hoping I could ask for some clarification. The background of this issue describes the application as failing to show the categories of the process when the proposals phase is active (i.e., when the date-range of that phase includes the current date). However, I am unable to replicate this situation; on my machine, these categories are shown in the sidebar even when the proposals phase has already passed. 

![categories_active](https://user-images.githubusercontent.com/40895962/67627753-1e6d7a80-f8ae-11e9-9758-3d25bbd496f4.png)

I guess that I must be making some false assumption about this issue. Either, i) the sidebar which I am looking at here is not the same sidebar which is indicated in the background; or ii) the proposals phase is active even after the end date of that phase has passed. I was hoping that you could let me know what I am getting wrong here. This is my first attempt to contribute to a project of this kind so perhaps I am not seeing something that is obvious. Any clarification you could give would be very helpful.

Thanks so much :)

**Comment by javierm** [comment]
Hi @andrewcameronsims!

> this issue describes the application as failing to show the categories of the process when the proposals phase is active

Just to clarify: is there a typo in this sentence? :thinking:

> on my machine, these categories are shown in the sidebar even when the proposals phase has already passed

Maybe @decabeza can comment on this behavior :wink:.

**Comment by andrewcameronsims** [comment]
Yes, sorry, that is a typo! Edited.

**Comment by andrewcameronsims** [comment]
@decabeza Gentle ping. :) Do you have any guidance on how to replicate the issue you have described above?

**Comment by decabeza** [comment]
Hi @andrewcameronsims,

Researching about this behaviour I found the real cause why the categories were disappearing. I updated the issue with more information. 😉

**Comment by andrewcameronsims** [comment]
Fantastic, thank you.
