### ISSUE TITLE
Hide related content proposals when these proposals are retired by their authors

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3559]
## Background
The debates and proposals have a "related content" section where users can add related proposals and other content. Proposals can be retired by the proposal author through the "Edit my proposal" menu in the author's proposal dashboard.

## What we need
If a proposal is retired by his/her author, it should disappear from all "related content" sections where it appears.

**Comment by nileshkumar** [comment]
@decabeza : I will start working on it..

**Comment by jaredholdcroft** [comment]
Hi. I'd like to take this if no-one else is working on it?

**Comment by javierm** [comment]
@jaredholdcroft Thanks! Go ahead :smile:.

**Comment by karunya-tota** [comment]
@javierm @jaredholdcroft Is this issue still up for grabs? First-time contributor here!

**Comment by jaredholdcroft** [comment]
@karunya-tota Yeah, I didn't get chance to do anything here :(

**Comment by javierm** [comment]
@karunya-tota Sorry for the late reply!

If you'd like to take this issue, you're more than welcome! Thanks a lot! :pray:

**Comment by karunya-tota** [comment]
Thank you! I hope to start taking a look today!

**Comment by matisnape** [comment]
@javierm Hi, is this is still up for grabs? 

And are you joining Hacktoberfest with the new rules? It's now opt-in for open source projects, you just need to add hacktoberfest topic https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by javierm** [comment]
@karunya-tota Are you still working on this issue? If not, @matisnape, sure, go ahead :wink:.

**Comment by matisnape** [comment]
@javierm done, although dunno if that's the good way to do it :)

**Comment by javierm** [comment]
> On another note - when I run Rubocop locally, there's much more warnings than from Hound here - how come? It's mostly too long lines in specs.

Hound only barks when there are offenses in the changes you make; it doesn't say anything about code which this pull request doesn't touch. Otherwise all contributors would get hundreds of comments about long lines whenever they open a pull request, which would be really annoying.

Also note the long lines Rubocop rule uses the "refactor" severity, meaning we aren't very strict about that rule, although it's usually better to follow it.
