### ISSUE TITLE
Docker - problema con la instalación

### ISSUE THREAD

**Issue by torresfabian** [consul/consul#3588]
Al tratar de iniciar la app con docker da el siguiente error

```
root@fabian-All-Series:/media/disco-g/consul-2019/consul# docker-compose up
WARNING: The SSH_AUTH_SOCK variable is not set. Defaulting to a blank string.
Creating network "consul_default" with the default driver
Creating volume "consul_docker-example-postgres" with default driver
Creating volume "consul_bundle" with default driver
Creating consul_database_1 ... 
Creating consul_database_1 ... done
Creating consul_app_1 ... 
Creating consul_app_1 ... error

ERROR: for consul_app_1  Cannot create container for service app: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for app  Cannot create container for service app: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

**Comment by javierm** [comment]
@torresfabian ¿Tenías ya creado el contenedor con `docker build -t consul .` como se menciona en la [documentación de CONSUL](https://docs.consulproject.org/docs/spanish-documentation/introduction/servers/docker#macos-and-linux)?

En caso afirmativo, acabamos de cambiar la imagen de Docker. ¿Podrías comprobar si sigues teniendo el mismo problema?

**Comment by asolera** [comment]
I had the same problem here! Solved by changing the `app/volume` section of `docker-compose.yml` file to this:
```
 volumes:
      - "$PWD:/var/www/consul"
```

**Comment by javierm** [comment]
Closing in favor of #4436. Even if this issue was created first, #4436 is in English and has more information.
