### ISSUE TITLE
Captcha no accesible

### ISSUE THREAD

**Issue by kikito** [consul/consul#360]
El captcha actual no es accesible. Necesitamos encontrar una solución anti-SPAM que lo sea.

Opciones:

* Usar un captcha que sea accesible
* Hacer nuestro captcha accesible (necesitaríamos hacer [síntesis de voz]([https://github.com/dejan/espeak-ruby]) en el servidor)
* Utilizar algo que no sea un captcha. Algunas opciones:
  * Flag "no soy un robot"
  * [timestamping](http://blog.gingerlime.com/2012/simple-detection-of-comment-spam-in-rails/)
  * [honeypotting](http://nomethoderror.com/blog/2014/02/26/simple-rails-form-honeypot/)
  * Una mezcla de los anteriores

**Comment by dgilperez** [comment]
Yo he montado timestamping en alguna ocasión. No es infalible pero sirve para quitar una buena cantidad de spam. Puede usarse en combinación con otras técnicas. Si queréis un PR decidme.

**Comment by markets** [comment]
Saludos a todos y felicidades por el proyecto! :+1: para una solución "honeypot" escribí hace un tiempo un sencillo plugin para Rails: https://github.com/markets/invisible_captcha. Para sites con tráfico bajo/medio me está funcionando realmente bien. 

Actualmente, también le estoy añadiendo la funcionalidad de "timestamps" (espero poder lanzar un release en las siguientes semanas, lo quiero testar bien en producción).

Siento la auto-promo :stuck_out_tongue_winking_eye:, pero he visto el proyecto por Twitter y revisando los issues he caído aquí...

**Comment by voodoorai2000** [comment]
Como ha ejemplificado @xkill https://github.com/xkill/participa_baypass los captchas de imagen no son seguros. 

También hemos de sopesar lo que explica @xuanxu que nos piden internamente: 
"@h3ku entendemos tu cuestión, si ves el histórico del repo verás que nuestra primera versión usaba recaptcha, pero eso es un tema institucional de independencia tecnológica, siendo una web del ayuntamiento no podemos utilizar herramientas externas para ciertas cosas. En concreto si ponemos recaptcha, Google tendría registro de cada vez que un madrileño participa e incluso podría potencialmente (aunque no lo hiciera) interrumpir el proceso de participación."

**Comment by bertocq** [comment]
Parece que [NegativeCaptcha](https://github.com/subwindow/negative-captcha) usa honeypotting, timestamping y varias más, pero lleva tiempo sin actualizarse.

Por otro lado [visualCaptcha](https://github.com/emotionLoop/visualCaptcha) usa iconos y audio, pero tiene pinta de ser trivial incorporar la [gema de Ruby](https://github.com/emotionLoop/visualCaptcha-rubyGem) a una app rails, aunque hace años alguien lo [intentó](https://github.com/kimenye/visualcaptcha)

**Comment by markets** [comment]
hola @bertocq, `invisible_captcha` ahora tiene también timestamps (además de honeypots). El feature se mergeó hace unos pocos días https://github.com/markets/invisible_captcha/pull/7. Hay un screencast aquí: https://www.driftingruby.com/episodes/invisible-captcha. 

Saludos!

**Comment by kikito** [comment]
Hemos implementado `invisible_captcha` en consul. Un saludo!
