### ISSUE TITLE
Search form on admin booths

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3607]
### What we need

Include a search form on `/admin/booths`. 

**Note**: you can found an example of search form on `/admin/proposals`.

### Screenshots

![search_booths](https://user-images.githubusercontent.com/631897/59283792-6bd4ac80-8c6b-11e9-9c10-764191c2749c.png)

**Comment by mmachado95** [comment]
Hey @decabeza , I'm fairly new in contributing to open source.
If anyone hasn't picked this up in the meanwhile, can I give it a go?

**Comment by DenisNikolski** [comment]
Hi @decabeza, is this issue actual?
I can take it :)
