### ISSUE TITLE
Upgrading to v1.0.0 crashes the settings page

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#3610]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

When trying to access the settings page, an error 500 is thrown because some settings are missing in the table, resulting in `@uploads_settings` being nil.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

- The new upgrade task should make sure that all the new settings are created.

- Moreover, the whole settings management should be more robust. It should take the hardcoded list present in [models/setting.rb](https://github.com/consul/consul/blob/22787151f55529cefa0ea23418ffc356b5d49c21/app/models/setting.rb#L79) as a primary source of information so that any missing or corrupted key in the table doesn't lead to an error 500 or to a missing key in the interface. If a key or its value is missing, it could be recreated from the default value on the fly.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

- Install v1.0.0.beta or v0.19 with dev seeds
- Upgrade to v1.0.0
- Go to `admin/settings` and enjoy an error 500.
- To fix it, just run the `settings:add_new_settings` task.

### Definition of Done

I'm shipping a PR to fix the first point. The second needs to be done too to close this task but more discussion is probably needed with the developers of the new system.

**Comment by voodoorai2000** [comment]
Hi @PierreMesure!,

Thank you so much for letting us know about this. We’re looking into it. :pray:

Just to make sure, you did use Capistrano to deploy version 1.0.0 from 1.0.0-beta right?. That should have executed the first task `add_new_settings` 
https://github.com/consul/consul/blob/master/config/deploy.rb#L48

And you upgraded from 0.19 to 1.0.0-beta and then to 1.0.0 right? When upgrading from 0.19 to 1.0.0-beta the `rename_setting_keys` task should  have already been executed.
https://github.com/consul/consul/releases/tag/1.0.0-beta

**Comment by PierreMesure** [comment]
Hey @voodoorai2000,

Yes, the upgrade went smoothly when using Capistrano. But if you are just upgrading a local test machine or Heroku instances, `add_new_settings` will never be run. It's great that it's in the Capistrano  deployment flow but in my opinion, it should also be present in the upgrade script. It doesn't hurt to run it several times and it covers all cases.

**Comment by voodoorai2000** [comment]
Hey @PierreMesure,

Indeed, we did not take into account deploys with Heroku, thanks for bringing that up.
We can definitely add the `add_new_settings` task to the tasks to be executed after a release upgrade.

However a release has been created, it's not a good idea to edit it in case other forks have already pulled it. But we will make sure it's fixed for the next release. 🙏 

Regarding the second point, yes it's a great idea! 🎉 We can make it work _on the fly_ for new settings. It's not as trivial as the first solution, but it's probably an even better one. 👌

Thank you Pierre 🙌

**Comment by PierreMesure** [comment]
I agree, maybe we could just add the commands to the release tasks on this [page](https://github.com/consul/consul/releases/tag/1.0.0)? This way, no change to the release itself.

**Comment by javierm** [comment]
Certainly :+1:. Done :smile:.

**Comment by PierreMesure** [comment]
Great, let's close it then!
