### ISSUE TITLE
Check for Drupal vulnerability 

### ISSUE THREAD

**Issue by jonvargas** [consul/consul#3638]
Drupal announced a Critical vulnerability and just wanted to know if this affects Consul and if it needs to be addressed, just in case:

https://www.drupal.org/sa-contrib-2019-053?utm_source=dlvr.it&utm_medium=twitter

**Comment by javierm** [comment]
@jonvargas Thank your for reporting. However, we don't use Drupal (nor PHP), so I don't think this vulnerability will affect CONSUL :ok_hand:.
