### ISSUE TITLE
New language (Sinhala)

### ISSUE THREAD

**Issue by akuruADMIN** [consul/consul#3672]
Hello I would like to have my language `Sinhala (si_LK)` added to CONSUL

cc @thinkholic @ruwanego

**Comment by decabeza** [comment]
Hi @akuruADMIN,

For manage translations we use [Crowdin](https://crowdin.com/project/consul). Feel free to sign up to complete Sinhala translations and we will be happy to include them in CONSUL. 😉

[Sinhala added to Crowdin](https://crowdin.com/project/consul/si-LK#) 👍 

You have a little more information in our [Translations documentation](https://consul_docs.gitbooks.io/docs/content/en/customization/translations.html).

Thank you very much! 🙏🏻😌
