### ISSUE TITLE
Can't assign map location to a budget investment from the management console

### ISSUE THREAD

**Issue by amiedes** [consul/consul#3681]
### Steps to reproduce

1. Login as an admin
2. Go to the management console and try to create a spending proposal as a user
3. If you assign a location to the budget investment it's not saved an an error is raised

### Current Behavior

A validation error appears saying that the map location is not valid

### Expected Behavior

The map location should be saved and no errors displayed

### Possible solution

Add `map_location_attributes: [:latitude, :longitude, :zoom])` to `investment_params` in `Management::Budgets::InvestmentsController`

**Comment by javierm** [comment]
Closed by #4448.
