### ISSUE TITLE
Duplicated records when filtering budget investments by tag

### ISSUE THREAD

**Issue by amiedes** [consul/consul#3682]
### Steps to reproduce

1. Create a budget investment and assign a user tag and admin tag with the same name
2. When listing the projects in http://localhost:3000/admin/budgets/<id>/budget_investments filtering by that tag, the project appears twice:

![Captura de pantalla 2019-09-02 a las 16 04 09](https://user-images.githubusercontent.com/9287468/64120064-8ebeba80-cd9b-11e9-97d5-03e036e13100.png)

I think the problem is the `by_tag` scope:

```ruby
scope :by_tag, ->(tag_name) { tagged_with(tag_name) }
```

which uses the undlerlying ActsAsTaggableOnMethod `tagged_with` which makes the query against the taggings table, which has two entries in this case.

**Comment by javierm** [comment]
@amiedes Thanks for reporting! :smile: Would it be possible for you to open a pull request with a fix and a test? :pray:

**Comment by amiedes** [comment]
@javierm currently this is not a priority for us, but if at the end we implement a fix I'll share it 👍
