### ISSUE TITLE
Let the users edit his budget investment proposals only during the acceptance phase

### ISSUE THREAD

**Issue by denialtorres** [consul/consul#3691]
### User Story
Hello, im Daniel from Mexico and I worked in the project of implementing consul in the city of San Pedro in Monterrey
https://decide.sanpedro.gob.mx

### Why is this Needed?
During the process of generating proposals we get complaints from many people who said they could not edit their proposals because they had a spelling error or forgot to upload an image.
and they didn't like the idea of erasing everything and starting from scratch

### Description

The idea is that the user can only edit their proposals during the acceptance phase, during the following phases, access to this will be limited

### Current Behavior

We already have a fix for this, so I would like to do a PR for this based on what we implement in San Pedro

**Comment by PierreMesure** [comment]
We also got demands for this, it's great if you can share it! I'll be happy to help and review the PR!
