### ISSUE TITLE
Can't verify users using only the local census

### ISSUE THREAD

**Issue by participacioncr** [consul/consul#3742]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
Hello, we are trying to implement Consul from scratch, for the city of Ciudad Real in Spain.

[comment]: # (Describe the problem and why this task is needed. P### Why is this Needed?
rovide a description of the current state, what you would like to happen, and what actually happened)

We are heading multiple problems, there are some features that work perfectly in the development environment, but not in production. Some of them are really basic ones.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

Our main two problems are:

- When trying to sign out, Consul crashes with the following trace:
`W, [2019-10-02T18:08:22.937421 #12693] WARN – : [c1c6fd44-1e76-4507-9613-24c9d6d0e551] [Rollbar] Got unexpected status code from Rollbar api: 400
F, [2019-10-02T18:08:22.941364 #12693] FATAL – : [c1c6fd44-1e76-4507-9613-24c9d6d0e551]
F, [2019-10-02T18:08:22.941475 #12693] FATAL – : [c1c6fd44-1e76-4507-9613-24c9d6d0e551] ActiveRecord::RecordNotFound (Couldn’t find User with ‘id’=sign_out [WHERE “users”.“hidden_at” IS NULL
]):
F, [2019-10-02T18:08:22.941551 #12693] FATAL – : [c1c6fd44-1e76-4507-9613-24c9d6d0e551]
F, [2019-10-02T18:08:22.941673 #12693] FATAL – : [c1c6fd44-1e76-4507-9613-24c9d6d0e551] activerecord (5.0.7.2) lib/active_record/relation/finder_methods.rb:353:in raise_record_not_found_exc eption!' [c1c6fd44-1e76-4507-9613-24c9d6d0e551] activerecord (5.0.7.2) lib/active_record/relation/finder_methods.rb:479:infind_one’
[c1c6fd44-1e76-4507-9613-24c9d6d0e551] activerecord (5.0.7.2) lib/active_record/relation/finder_methods.rb:458:in find_with_ids' [c1c6fd44-1e76-4507-9613-24c9d6d0e551] activerecord (5.0.7.2) lib/active_record/relation/finder_methods.rb:66:infind’
[c1c6fd44-1e76-4507-9613-24c9d6d0e551] activerecord (5.0.7.2) lib/active_record/querying.rb:3:in find' [c1c6fd44-1e76-4507-9613-24c9d6d0e551] activerecord (5.0.7.2) lib/active_record/core.rb:151:infind’
[c1c6fd44-1e76-4507-9613-24c9d6d0e551] cancancan (2.3.0) lib/cancan/model_adapters/abstract_adapter.rb:20:in find' [c1c6fd44-1e76-4507-9613-24c9d6d0e551] cancancan (2.3.0) lib/cancan/controller_resource_finder.rb:11:infind_resource’`

- When trying to validate a new user, if we search the user with its DNI, we get another crash and the following error in the production log:
`W, [2019-10-02T13:54:42.020252 #12696] WARN – : [8c6935e3-8ea0-4739-948d-c9e7e83e7389] [Rollbar] Got unexpected status code from Rollbar api: 400
F, [2019-10-02T13:54:42.022170 #12696] FATAL – : [8c6935e3-8ea0-4739-948d-c9e7e83e7389]
F, [2019-10-02T13:54:42.022336 #12696] FATAL – : [8c6935e3-8ea0-4739-948d-c9e7e83e7389] Errno::ENOENT (No such file or directory @ rb_sysopen - ):
F, [2019-10-02T13:54:42.022432 #12696] FATAL – : [8c6935e3-8ea0-4739-948d-c9e7e83e7389]
F, [2019-10-02T13:54:42.022529 #12696] FATAL – : [8c6935e3-8ea0-4739-948d-c9e7e83e7389] lib/census_api.rb:61:in get_response_body' [8c6935e3-8ea0-4739-948d-c9e7e83e7389] lib/census_api.rb:7:inblock in call’
[8c6935e3-8ea0-4739-948d-c9e7e83e7389] lib/census_api.rb:6:in each' [8c6935e3-8ea0-4739-948d-c9e7e83e7389] lib/census_api.rb:6:incall’
[8c6935e3-8ea0-4739-948d-c9e7e83e7389] lib/census_caller.rb:7:in call' [8c6935e3-8ea0-4739-948d-c9e7e83e7389] app/models/verification/residence.rb:74:inretrieve_census_data’
[8c6935e3-8ea0-4739-948d-c9e7e83e7389] app/models/verification/residence.rb:28:in save' [8c6935e3-8ea0-4739-948d-c9e7e83e7389] app/controllers/verification/residence_controller.rb:13:increate’`

We can provide full traces, logs and PostgreSQL query logs, if needed. Again, this works OK in development.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

Install Consul from scratch (v1.0.0) and deploy to production with Capistrano, with some minor changes (some CSS, images and banners).

**Comment by javierm** [comment]
@participacioncr Great that you're trying CONSUL! :tada:

The first error doesn't sound familiar :thinking:. Could you post a link to your git repository? A full application trace would alo be great.

The second one seems to be related to calls to the census API and could be tricky :thinking:. Have you configured the census API in `config/secrets.yml`?

**Comment by participacioncr** [comment]
@javierm Thank you very much for your quick reply! Of course we can provide all information you need. Our git repository is [https://github.com/Ayuntamiento-CR/consul](url)

We haven't configured the census API. Attached here are our secrets.yml and production.log. We don't know if "secret_key_base" set to "change_me" in production has anything to do with this error. The production log shows only an access to Consul with the admin user, trying to validate a user and then trying to log out, for not making it too long.

[production.log](https://github.com/consul/consul/files/3689364/production.log)
[secrets.yml.txt](https://github.com/consul/consul/files/3689367/secrets.yml.txt)

**Comment by javierm** [comment]
Replace "change_me" with a content generated by running `bin/rake secret`. After you do that, restart the application. It is highly recommended you don't share the `secrets.yml` file, since knowing this secret key could help a hacker take control of your application, and the file will potentially contain passwords.

I see you're using a version which is more recent than 1.0.0. If you're going to verify user accounts using the local census, have a look at: https://docs.consulproject.org/docs/spanish-documentation/features/census_configuration

Regarding the exception logging out, for that link to work JavaScript needs to be activated; clicking it without JavaScript or opening it in a new tab will result in a exception. Are you getting the exception when you open the link in the current tab with JavaScript activated?

**Comment by participacioncr** [comment]
Ok, regarding the error in the sign out, it was our fault. Now it works ok... It was due to activating debug mode, we saw this affected CSS output but didn't knew it would affect JavaScript too.

We are not using remote census by now, although we'll need to use it in the future. By now we are using only local census, with only one user as an example. Same settings that in development. The exact functionality that gives us this error is "search by document_number", as shown in [https://docs.consulproject.org/docs/english-documentation/features/local_census](url)

¿Could this be because we are not using version 1.0.0?

**Comment by javierm** [comment]
Let's check if I'm getting it correctly :smile:. So, as shown in the page you mention, you log in as an administrator, in the administration area you click on Settings->Manage local census, and when you enter a document number and click on "search", the application crashes. Correct? If so, could you send be a full application trace of the exception you're getting?

Note the "search" functionallity on that page uses JavaScript too, although it should work without JavaScript as well :thinking:.

**Comment by participacioncr** [comment]
Hi again, not exactly. The error raises while logged in as administrator, clicking on Menu -> Management and clicking in the option "Select User" in the left menu. Then, we select "DNI" as "document type" and, when searching with any value (existing in the database or not), we get the exception. As shown before, the only output in production.log is:

`W, [2019-10-08T08:41:56.463338 #10624]  WARN -- : [bbb92632-aed7-4e97-8ce7-684b2a002d2b] [Rollbar] Got unexpected status code from Rollbar api: 400
F, [2019-10-08T08:41:56.465293 #10624] FATAL -- : [bbb92632-aed7-4e97-8ce7-684b2a002d2b]   
F, [2019-10-08T08:41:56.465404 #10624] FATAL -- : [bbb92632-aed7-4e97-8ce7-684b2a002d2b] Errno::ENOENT (No such file or directory @ rb_sysopen - ):
F, [2019-10-08T08:41:56.465498 #10624] FATAL -- : [bbb92632-aed7-4e97-8ce7-684b2a002d2b]   
F, [2019-10-08T08:41:56.465629 #10624] FATAL -- : [bbb92632-aed7-4e97-8ce7-684b2a002d2b] lib/census_api.rb:61:in `get_response_body'
[bbb92632-aed7-4e97-8ce7-684b2a002d2b] lib/census_api.rb:7:in `block in call'
[bbb92632-aed7-4e97-8ce7-684b2a002d2b] lib/census_api.rb:6:in `each'
[bbb92632-aed7-4e97-8ce7-684b2a002d2b] lib/census_api.rb:6:in `call'
[bbb92632-aed7-4e97-8ce7-684b2a002d2b] lib/census_caller.rb:7:in `call'
[bbb92632-aed7-4e97-8ce7-684b2a002d2b] app/models/verification/management/document.rb:28:in `in_census?'
[bbb92632-aed7-4e97-8ce7-684b2a002d2b] app/controllers/management/document_verifications_controller.rb:18:in `check'
`
As we activated "config.consider_all_requests_local" in the configuration file, we are seeing the full trace in the browser window. I'm attaching it as a text file:
[trace.20191008.txt](https://github.com/consul/consul/files/3701087/trace.20191008.txt)

We are getting also this error if, while logged in as an unverified user, we try to verify the account clicking on "My account" and then in the button "Verify my account". As before, selecting "DNI" as "Document Type" and then searching for any document number. The full trace seems the same as before, only changing request parameters. I'm attaching also the full trace here anyway:
[trace2.20191008.txt](https://github.com/consul/consul/files/3701106/trace2.20191008.txt)

As said before, what we can't understand is why this works perfectly in development environment, with the same data in the database...

**Comment by javierm** [comment]
@participacioncr I've updated the title of this issue.

We recommend you try the following patch:

```diff
diff --git a/lib/census_caller.rb b/lib/census_caller.rb
index 71b3404..9cf64a2 100644
--- a/lib/census_caller.rb
+++ b/lib/census_caller.rb
@@ -1,12 +1,13 @@
 class CensusCaller
 
   def call(document_type, document_number, date_of_birth, postal_code)
-    if Setting["feature.remote_census"].present?
-      response = RemoteCensusApi.new.call(document_type, document_number, date_of_birth, postal_code)
-    else
-      response = CensusApi.new.call(document_type, document_number)
-    end
-    response = LocalCensus.new.call(document_type, document_number) unless response.valid?
+    response = if Setting["feature.remote_census"].present?
+                 RemoteCensusApi.new.call(document_type, document_number, date_of_birth, postal_code)
+               elsif Setting["feature.legacy_remote_census"].present?
+                 CensusApi.new.call(document_type, document_number)
+               end
+
+    response = LocalCensus.new.call(document_type, document_number) unless response&.valid?
 
     response
   end
```

> what we can't understand is why this works perfectly in development environment, with the same data in the database...

That's because in the development and test environments calls to the census API are disabled :wink:.

**Comment by participacioncr** [comment]
@javierm we've applied your patch and now Consul doesn't crashes anymore! You've really made our day, thank you very much! Now we are waiting for the remote census to be available for more testing, but by now it works ok and we can go on... Thank you again!

**Comment by javierm** [comment]
Great! :tada: Thanks @Senen and @taitus for suggesting the patch! :pray:

**Comment by participacioncr** [comment]
Hi again, sorry for coming back to this... Since your patch, we are not having "error 500" anymore, but we realised that verifying users isn't working properly. The steps for getting the error are:
- Login with a unverified user account
- Go to "My account" and push the green button "Verify my account"
- Select "DNI" as Document Type, write the DNI in Document Number, filling Date of Birth and Postcode
- Accept terms and conditions and push "Verify residence"

Then, Consul returns back to the same page saying "1 error prevented the verification of your residence" and in the postcode field, it says "In order to be verified, you must be registered."

In the local census, an user with all those data (DNI, date of birth and postcode) exists. In fact, if we login as admin and go to Menu->Management and then click on "Select user", that user exists and we can send the verification email and create a new account.

Consul is not dumping any error in production.log in this case. If you can tell us how we can get a trace of this, we would gladly send you any information you need.

**Comment by Senen** [comment]
Hi @participacioncr,

I was able  to reproduce the error following your instruccions. I guess you probably entered a record into the local census record with `Document type` field set to "DNI". Current verification process only accepts integer values, the same ones shown at verification form document_type select ["DNI" => 1 , "Passport" => 2, "Residence card" => 3].

Try to update your LocalCensusRecords with following Document type values:

* 1 for DNI
* 2 for Passport
* 3 for residence card

An example of a working LocalCensusRecord could be the following:
`LocalCensusRecord.create(document_type: 1, document_number: "#documentnumber", date_of_birth: Date, postal_code: "28080")`

Let mew know if this works for you too.

**Comment by participacioncr** [comment]
Hi @ Senen, and thank you for your reply!

We did that some time ago. In fact, before we changed "DNI" for "1" in the local census, we couldn't select the user from Menu->Management neither...

**Comment by Senen** [comment]
Hi again @participacioncr ,

I think i finally found the problem. Right now residence verification process do a postalcode validation and forces it to be a Madrid valid postal code, we only need to change validation method to check that the provided postal code Ciudad Real valid. I think Ciudad Real postal codes should start with **13**.

Please, change the file https://github.com/Ayuntamiento-CR/consul/blob/master/app/models/custom/verification/residence.rb#L26 and modify the postal_code validation method to something like:

```
    def valid_postal_code?
      postal_code =~ /^13/
    end
```

**Comment by participacioncr** [comment]
Hi again, sorry, couldn't test until today... That made the trick! Thank you very much @Senen

**Comment by Senen** [comment]
> Hi again, sorry, couldn't test until today... That made the trick! Thank you very much @Senen

Glad to help @participacioncr!
