### ISSUE TITLE
Contador en la nube de temas

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#376]
Cuando generamos el [tag_cloud](https://github.com/AyuntamientoMadrid/participacion/blob/master/app/controllers/debates_controller.rb#L14) se cuentan también los debates ocultos, con lo que luego al filtrar por tema pueden aparecer menos de los que se indicaban en el la nube de temas.

![tag_cloud](https://cloud.githubusercontent.com/assets/6528/9704270/65ab1242-54a0-11e5-8783-e8897a92f698.png)

Habría que añadir condiciones al método `tag_counts` de ActsAsTaggableOn o rehacerlo para que filtrara al hacer el count.

**Comment by decabeza** [comment]
Ya está solucionado. Ahora al filtrar por una etiqueta se muestra el mismo número de resultados. :tada:
