### ISSUE TITLE
Consul sends newsletters to unconfirmed accounts

### ISSUE THREAD

**Issue by PierreMesure** [consul/consul#3761]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

I checked the logs of my e-mail server and one of the bounces is due to an incorrect e-mail address (it ends with "@vmail.com" instead of "@gmail.com". What happened is the person created a first account with a typo in the e-mail, never got the confirmation mail and then created a new one with the correct e-mail.

### Current Behavior
[comment]: # (Describe what actually happened.)

To my surprise, sending a newsletter to all the users of the platform also sends it to this incorrect address (hence the bounce).

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Mails should never be sent to users that haven't even confirmed their e-mail address. It's creating bounces, ineffective and even if the address was correct, someone who didn't bother to finish creating their account probably doesn't want to be bothered by e-mails later on.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

- Sign up but don't confirm your account.
- Send a newsletter to all users as an admin.
- You should receive an e-mail to your unconfirmed address.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Unconfirmed accounts don't receive anything
- Check for other places where unconfirmed users might be included when they shouldn't.

**Comment by mohsinkhansymc** [comment]
@PierreMesure I can work on this if not taken up yet

**Comment by katafrakt** [comment]
> It's creating bounces, ineffective and even if the address was correct, someone who didn't bother to finish creating their account probably doesn't want to be bothered by e-mails later on.

I think what is even more important is that it's illegal, at least in most of Europe, so I think this shall get quite high priority.

**Comment by PierreMesure** [comment]
Of course @mohsinkhansymc! Don't hesitate to ask if you need help or a review!

Really good point @katafrakt! Although I think the e-mail address is saved only after they tick the box for user conditions so I guess they consented to some form of data storage if the platform administrators wrote it there.

![Capture d’écran 2019-10-16 à 11 35 13](https://user-images.githubusercontent.com/7223028/66907090-10477080-f009-11e9-880a-9aa0c8d1a262.png)

**Comment by katafrakt** [comment]
We dealt a lot with issues like that at my previous company. I'm not a lawyer, but these were main takeaways:

* I can easily put your email there and tick the box. It does not mean you (as a person) agreed. Email confirmation is a way to ensure it was really email owner who agreed.
* TOC are one thing, but under GDPR you can't just use one checkbox to handle both general terms and specific consents for email marketing. Maybe I misinterpreted "newsletters" but it sounds a lot like marketing (i.e. non-service emails) to me.

**Comment by mohsinkhansymc** [comment]
thanks @PierreMesure and @katafrakt  for the input. I will do this over the weekend
