### ISSUE TITLE
Adaptación modelo datos versión 0.7 a  versión 1.0

### ISSUE THREAD

**Issue by elreydeoros** [consul/consul#3762]
Hola a tod@s,
Me encuentro sumergido en un proyecto en el que deseo realizar una migración limpia desde la versión 0.7 a la ultima versión disponible.
Revisando he encontrado que el modelo de datos de la versión 0.7 (esquema de bbdd) es muy distinto al de la última versión.

Por ejemplo, hay tablas y campos que no existen en la versión 0.7 y por otro lado, algunos de los campos / tablas no tienen correspondencia en la versión 1.0.

He estado revisando la documentación publicada y no he encontrado nada a cerca de los cambios en el modelo de datos y me gustaría saber si existe tal documentación y donde puedo encontrarla.

Cualquier ayuda será bienvenida.

Un saludo,

**Comment by javierm** [comment]
@elreydeoros ¡Muy buenas!

Ahora mismo actualizar desde la versión 0.7 de golpe efectivamente ocasionaría con total seguridad pérdida de información de la base de datos. Me temo que el único método que garantiza la integridad de los datos es actualizar versión a versión, ejecutando en cada versión las tareas de migración de datos correspondientes.

A partir de la versión 0.10, verás que en cada una de las versiones hay una sección "Updating your fork", con instrucciones de qué hacer para actualizar. Por ejemplo, para actualizar de la versión 0.12 a 0.13, tienes instrucciones en: https://github.com/consul/consul/releases/tag/v0.13

```
git checkout master
git pull
git checkout -b upstream
git fetch upstream
git merge v0.13
```

Y después tendrás que ejecutar unas tareas extra, que varían en cada versión. En las instrucciones para actualizar a la 0.13 aparece por ejemplo:
```
bin/rake budgets:phases:generate_missing
bin/rake investments:internal_comments:migrate_to_thread
```

Para actualizar a las versiones 0.8 y 0.9 no parece que haya que ejecutar tareas extra, con lo que valdría con ejecutar la primera parte del código (cambiando v0.13 por v0.8).

Con la versión 1.0.0 y siguientes hemos facilitado un poco el proceso de ejecutar estas tareas extra que aseguran que no habrá pérdida de datos, pero por desgracia es imposible aplicar este sistema de forma retroactiva a versiones que salieron hace años.

P.D. Solo por curiosidad, ¿podrías mandar un enlace al código fuente del proyecto que mencionas?

**Comment by elreydeoros** [comment]
Hola @javierm ! :)

Creo que lo primero que voy a hacer es agradecerte la rápida respuesta, no es lo común y muchas veces las dudas se quedan en el limbo, con la desconfianza que eso genera.

Dicho esto, comentarte que lo que tengo entre manos es algo complicado puesto que hemos "heredado" una instalación de Consul muy anticuada (v0.7 ahí es ná) montado sobre un sistema igualmente anticuado.
El planteamiento es extraer la información de la instancia de bbdd de la versión 0.7, revisar su modelo de datos, hacer lo mismo con la versión 1.0 y adaptarlo todo para que simplemente se "monte" un sistema operativo con una versión mas moderna y actualizada para posteriormente, una vez instalada la última versión de Consul, solo sea cuestión de volcar la bbdd ya adaptada.
Obviamente esto lleva mucho trabajo de analisis, razón por la cual abrí está issue.

En tanto al codigo, no disponemos del repo desde el que se creó esta instalación y aún no he creado el fork que posteriormente utilizaremos.

En cualquier caso, muchas gracias por la información.

Un saludo,
@elreydeoros

**Comment by javierm** [comment]
> El planteamiento es extraer la información de la instancia de bbdd de la versión 0.7, revisar su modelo de datos, hacer lo mismo con la versión 1.0 y adaptarlo todo

En eso me temo que no podemos ayudaros. Yo le daría una oportunidad primero a ir actualizando versión por versión (previa copia de seguridad de la base de datos, por supuesto), que sí, es cierto que son unas 15 versiones a actualizar, pero por otro lado no tendríais que hacer análisis comparativo de modelos de datos sino que podríais seguir las instrucciones de cada versión, que se encargan de ir migrando datos de una versión a otra.

> En tanto al codigo, no disponemos del repo desde el que se creó esta instalación

En teoría según la licencia AGPL que utiliza CONSUL, el código tiene que estar disponible para todo aquel que visita la web, si bien desconozco las circunstancias concretas de este caso en particular :thinking:.

**Comment by elreydeoros** [comment]
Hola de nuevo @javierm !

Como bien indicas, creo que la mejor opción va a ser realizar todas las actualizaciones necesarias hasta llegar a la última y desde alli extraer un backup de la bbdd para posteriormente realizar una restauración en la máquina en la que se va a desplegar.
Tengo una pregunta que muy posiblemente sea de las más tontas pero... como sé con seguridad en que versión está actualmente consul? pues al tener que actualizarlo quiero hacerlo en orden para así evitar problemas.

Por otro lado, efectivamente la web tiene el repositorio publico pues asi me han confirmado cuando lo he consultado pero yo estoy partiendo desde una versión en desarrollo que no está publicada ni accesible.

P.D: De verdad, muchas gracias por el apoyo, es un placer sentirse "escuchado".

**Comment by javierm** [comment]
¡Muy buenas @elreydeoros!

Tienes una lista de versiones en: https://github.com/consul/consul/releases
