### ISSUE TITLE
Spring Cloud service does not register with Consul

### ISSUE THREAD

**Issue by xBentu** [consul/consul#3774]
### User Story

[comment]: # (As a dev, I want to register a service so that it shows on Consul on localhost:8500.)

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

`
spring:
  application:
    name: card
  consul:
    discovery:
      preferAgentAddress: true
      tags: cardService
      healthCheckPath: /management/health
      healthCheckInterval: 5s
`

`   
    <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.M5</version>
		<relativePath/>
	</parent>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud-function.version>3.0.0.M2</spring-cloud-function.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-consul-dependencies</artifactId>
				<version>1.1.2.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-discovery</artifactId>
		</dependency>
`

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Spring cloud service registers with consul.

![image](https://user-images.githubusercontent.com/56086690/67036472-b79bd480-f0e9-11e9-8466-c6d27e3249ab.png)

![image](https://user-images.githubusercontent.com/56086690/67036587-e154fb80-f0e9-11e9-8801-35444305ac7d.png)

**Comment by javierm** [comment]
@xBentu I think you got the wrong project :thinking:. You probably meant [Hashicorp's project](https://github.com/hashicorp/consul).

**Comment by xBentu** [comment]
@javierm Oh.  Sorry.

**Comment by javierm** [comment]
No problem :wink:.
