### ISSUE TITLE
Twitter auth not working

### ISSUE THREAD

**Issue by sbolleddula** [consul/consul#3777]
Type: Bug

Signin/Signup using twitter fails.

**Current behaviour**
User clicks on Twitter icon and sees a 502 error.

**Steps to reproduce**
I see the same behavior on the demo.cosnulproject.org as well. For Facebook and Google you will see an error whereas for twitter you ended upon error page.

**Expected Behaviour**
Would like to signin/signup without any issues.

**Definition of Done**
If we were able to signin/login using twitter without any issues.

**Comment by javierm** [comment]
@sbolleddula Thanks for reporting. Have you [configured the secrets](https://docs.consulproject.org/docs/english-documentation/features/oauth#3-set-key-and-secret-values) for twitter? :thinking:

**Comment by javierm** [comment]
@sbolleddula Thanks for reporting. Have you [configured the secrets](https://docs.consulproject.org/docs/english-documentation/features/oauth#3-set-key-and-secret-values) for twitter? :thinking:

@taitus I think we need to update the documentation and mention we've got to restart the application after changing the `config.secrets.yml` file :thinking:. Could you take care of it? :pray:

**Comment by sbolleddula** [comment]
@javierm Thanks for your response. This got resolved after I restarted the application.
