### ISSUE TITLE
Upgrade jQuery

### ISSUE THREAD

**Issue by microweb10** [consul/consul#3847]
### Why is this Needed?

It would be nice to keep jQuery up to date ☺️ 

### Description

Upgrade the version of jQuery.
Note that we also use foundation and some extra adjustments might need to be done.
Note that other gems, like `cocoon` and `annotator` also depend on jQuery, so please review everything related to jQuery and make sure everything is properly working after upgrading 🙏

**Comment by m-pereira** [comment]
Can I try to do this one?

**Comment by microweb10** [comment]
Sure! Please. Go ahead! 😍

**Comment by m-pereira** [comment]
@microweb10 I checked your jquery gems and they are up to date. In that case you want to upgrade the rails version to 5.1, and then install jquery via yarn?

**Comment by javierm** [comment]
Hi, @m-pereira. In order to upgrade, we need to change `app/assets/javascripts/application.js` and replace `//= require jquery` with `//= require jquery3`. AFAIK there's no need to use yarn :wink:.

The tricky part is testing everything keeps working properly after the change :thinking:.
