### ISSUE TITLE
Dashboard emailing feature not working

### ISSUE THREAD

**Issue by sbolleddula** [consul/consul#3852]
Type: Bug

On the proposal dashboard the emailing feature under Email section seems not working.

Current behaviour
User clicks on "Send to <email>" button, message arrives but no email has been received.

Steps to reproduce
I see the same behavior on the demo.cosnulproject.org as well. You can create a new proposal, then visit E-mail under resources of the dashboard section. Please click on "Send to <email>"

Expected Behaviour
Would like to receive emails when author clicks on the button

Definition of Done
If we were able to receive emails when author clicks on the button.

**Comment by javierm** [comment]
@sbolleddula Thanks for reportig! :smile:

I can confirm this bug. It looks like we disabled dashboard emails a few months ago, but we didn't hide the menu to send emails.

Before releasing version 1.1, we'll either hide the menu or enable this feature.
