### ISSUE TITLE
Proposal supporting users list & Poll voting users list

### ISSUE THREAD

**Issue by sbolleddula** [consul/consul#3863]
Type: Bug

Is there a way that we can get the list of users who supported the proposal?
Is there a way that we can get the list of users who voted with the option they voted?

Current behavior
There's no way for admin to get the list of users who supported the proposal.
There's no way for admin to get the list of users who voted with the option they voted.

Expected Behavior
Admin should have a way to download all the supporters list for a proposal
Admin should have a way to download all the participants list for a poll with their option of vote.

Definition of Done
If Admin have a way to download all the supporters list for a proposal
If Admin have a way to download all the participants list for a poll with their option of vote.

**Comment by javierm** [comment]
Hi @sbolleddula :smile:. I'm afraid this feature would go against the secret ballot right :thinking:. We'd actually like to take the opposite route and implement a [secure vote system](https://github.com/consul/consul/issues/2135), which would guarantee it's impossible for anyone to check which option a user voted.
