### ISSUE TITLE
Remote census verification not working

### ISSUE THREAD

**Issue by participacioncr** [consul/consul#3869]
Hi all again, we are trying to use remote census with no success. First of all, our remote census provider doesn't support the query/request format that Consul requires, so we had to write a "intermediate service" to translate this between Consul and the web service itself. We see that it works mostly ok. I mean, Consul sends the request to our intermediate service, our service translates it to the actual webservice, that sends the reply back and translates it to Consul. The problem is that Consul doesn't seem to understand the request, and keeps saying that the person requested is not in the census.

We have designed the service so the requests follow the guidelines in  https://docs.consulproject.org/docs/spanish-documentation/features/census_configuration#configuracion
An example of the request our service sends to Consul (sensible data masked):

`<SOAP-ENV:Envelope SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:producto" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/">
   <SOAP-ENV:Body>
      <ns1:comprobarDatosResponse>
         <return xsi:type="xsd:string">get_habita_datos_response: {
          get_habita_datos_return: {
            datos_habitante: {
              item: {
                fecha_nacimiento_string: "11/01/1979",
                identificador_documento: "XXXXXXXXX",
                descripcion_sexo: "X",
                nombre: "XXXXXXXX",
                apellidos: "YYYYYYYY"
              }
            },
            datos_vivienda: {
              item: {
                codigo_postal: "13005",
                codigo_distrito: ""
              }
            }
          }
        }</return>
      </ns1:comprobarDatosResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

Here is a screenshot of our remote census configuration in Consul:
![remote-census-config](https://user-images.githubusercontent.com/55405402/69638061-3e818c80-105a-11ea-84d2-41a5894e00d0.png)

We don't know how to debug this, please feel free of asking for anything you need. Any help will be greatly appreciated...

**Comment by taitus** [comment]
Hi @participacioncr ,

Reviewing the screenshot of your remote census configuration, it seems that it is not well filled.

In the screenshot you can see the text "datoshabitante" and "datosvivienda", while in the answer you have sent the fields are called "datos_habitante" and "datos_vivienda".

Replace on you remote census configuration:
"datoshabitante" --> "datos_habitante"
"datosvivienda" --> "datos_vivienda"

Please keep me informed if the problem with this change has been resolved.

Regards!

**Comment by participacioncr** [comment]
Hi @taitus, and thank you for your quick answer!

We have tried that, with no luck. The answer sent to Consul has the following format (again, data is masked):

`#<RemoteCensusApi::Response:0x0056432bae9c18 @body={:comprobar_datos_response=>{:return=>"get_habita_datos_response: {get_habita_datos_return: {datos_habitante: {item: {fecha_nacimiento: 'XX/XX/XXXX',identificador_documento: 'XXXXXXXX',descripcion_sexo: 'Hombre',nombre: 'XXXXXXXXX XXXXXX',apellidos: 'XXXXXX XXXXXXXX'}},datos_vivienda: {item: {codigo_postal: '13001',codigo_distrito: '22'}}}}"`

We have made another change in the configuration, for testing. Where it was:
`get_habita_datos_response.get_habita_datos_return.datos_habitante.item`
Now it's:
`comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item`

We now have Consul returning a 500 error. We see the following in the log:
`TypeError (Nori::StringWithAttributes does not have #dig method)`

We really don't know if the answer format is wrong. ¿Is there any debug option we can activate in order to trace this?

**Comment by taitus** [comment]
Hi @participacioncr 

With this 500 error, it seems that the problem is that it cannot parse the answer, does not find the field path and returns an error.
The specific line that is failing you is the following:
https://github.com/consul/consul/blob/master/lib/remote_census_api.rb#L21

Right now it seems that the fields that have been filled in the data of the answer, are not well informed.

Could you send me exactly all the values you have entered in the "Remote Census Configuration" section?
On the other hand, if you have any more logs of the error, it could help to detect the problem.

**Comment by participacioncr** [comment]
Hi again, of course, here you have our remote census configuration:

![config_census](https://user-images.githubusercontent.com/55405402/69723718-97b0f500-111a-11ea-940f-f568af9ed08d.png)

This is the full trace in the log:

W, [2019-11-27T13:29:33.188868 #26395]  WARN -- : [72d26861-639f-4878-a2a3-47cbb5d09596] [Rollbar] Got unexpected status code from Rollbar api: 400
F, [2019-11-27T13:29:33.190825 #26395] FATAL -- : [72d26861-639f-4878-a2a3-47cbb5d09596]
F, [2019-11-27T13:29:33.190944 #26395] FATAL -- : [72d26861-639f-4878-a2a3-47cbb5d09596] TypeError (Nori::StringWithAttributes does not have #dig method):
F, [2019-11-27T13:29:33.191046 #26395] FATAL -- : [72d26861-639f-4878-a2a3-47cbb5d09596]
F, [2019-11-27T13:29:33.191202 #26395] FATAL -- : [72d26861-639f-4878-a2a3-47cbb5d09596] lib/remote_census_api.rb:22:in `dig'
[72d26861-639f-4878-a2a3-47cbb5d09596] lib/remote_census_api.rb:22:in `extract_value'
[72d26861-639f-4878-a2a3-47cbb5d09596] lib/remote_census_api.rb:27:in `valid?'
[72d26861-639f-4878-a2a3-47cbb5d09596] lib/remote_census_api.rb:9:in `block in call'
[72d26861-639f-4878-a2a3-47cbb5d09596] lib/remote_census_api.rb:7:in `each'
[72d26861-639f-4878-a2a3-47cbb5d09596] lib/remote_census_api.rb:7:in `call'
[72d26861-639f-4878-a2a3-47cbb5d09596] lib/census_caller.rb:15:in `call'
[72d26861-639f-4878-a2a3-47cbb5d09596] app/models/verification/management/document.rb:28:in `in_census?'
[72d26861-639f-4878-a2a3-47cbb5d09596] app/controllers/management/document_verifications_controller.rb:18:in `check'

**Comment by javierm** [comment]
@participacioncr Thanks for the info! Would it be possible for you to open a rails console on the server and send us the value of `Setting["remote_census"]`? That'll will give us the same information as shown in the screenshot, but in plain text :smile:.

**Comment by javierm** [comment]
Sorry, I meant these values:
```
        Setting["remote_census.general.endpoint"]
        Setting["remote_census.request.method_name"]
        Setting["remote_census.request.structure"]
        Setting["remote_census.request.document_type"]
        Setting["remote_census.request.document_number"]
        Setting["remote_census.request.date_of_birth"]
        Setting["remote_census.request.postal_code"]
        Setting["remote_census.response.date_of_birth"]
        Setting["remote_census.response.postal_code"]
        Setting["remote_census.response.district"]
        Setting["remote_census.response.gender"]
        Setting["remote_census.response.name"]
        Setting["remote_census.response.surname"]
        Setting["remote_census.response.valid]
```

**Comment by cdiaz23** [comment]
Hola!

Soy el compañero de @participacioncr, sigo con la conversión, pongo los valores pedidos:

2.3.2 :001 > Setting["remote_census.general.endpoint"]
 => "https://wwsspadron.ciudadreal.es/server.php?wsdl"

2.3.2 :003 > Setting["remote_census.request.method_name"]
 => "comprobar_datos"

2.3.2 :005 > Setting["remote_census.request.structure"]
 => "{\r\n request: {\r\n   tipo:  '',   \r\n   fecha: '',\r\n   documento:  '', \r\n   cp:  ''\r\n }\r\n}"

2.3.2 :008 > Setting["remote_census.request.document_type"]
 => "request.tipo"

2.3.2 :011 > Setting["remote_census.request.document_number"]
 => "request.documento"

2.3.2 :014 > Setting["remote_census.request.date_of_birth"]
 => "request.fecha"

2.3.2 :015 > Setting["remote_census.response.postal_code"]
 => "comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_vivienda.item.codigo_postal"

2.3.2 :018 > Setting["remote_census.response.date_of_birth"]
 => "comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.fecha_nacimiento"

2.3.2 :021 > Setting["remote_census.response.district"]
 => "comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_vivienda.item.codigo_distrito"

2.3.2 :022 > Setting["remote_census.response.gender"]
 => "comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.descripcion_sexo"

2.3.2 :025 > Setting["remote_census.response.name"]
 => "comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.nombre"

2.3.2 :028 > Setting["remote_census.response.surname"]
 => "comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.apellidos"

2.3.2 :038"> Setting["remote_census.response.valid"]
2.3.2 :039">

Esta última variable no devuelve ningún valor a pesar de estar puesta en las opciones ... 

Gracias!

**Comment by cdiaz23** [comment]
Pasa algo extraño con esta variable ... estoy mirando los valores directamente en la base de datos, si hago esta consulta, el "remote_census.response.valid" no aparece por ningún lado:

select * from settings where key like '%remote%';

id |                  key                  |                                                          value                                                    
----+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------
 16 | feature.remote_translations           |
 87 | remote_census.request.document_type   | request.tipo
 84 | remote_census.general.endpoint        | https://wwsspadron.ciudadreal.es/server.php?wsdl
 88 | remote_census.request.document_number | request.documento
 85 | remote_census.request.method_name     | comprobar_datos
 94 | remote_census.response.gender         | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.descripcion_sexo
 93 | remote_census.response.district       | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_vivienda.item.codigo_distrito
 96 | remote_census.response.surname        | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.apellidos
 18 | feature.remote_census                 | active
 92 | remote_census.response.postal_code    | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_vivienda.item.codigo_postal

Sin embargo, buscando por "value" sí que me aparece (id 97)

select * from settings where value like '%comprobar_datos%';

id |                 key                  |                                                          value                                                     
----+--------------------------------------+-------------------------------------------------------------------------------------------------------------------------
 85 | remote_census.request.method_name    | comprobar_datos
 94 | remote_census.response.gender        | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.descripcion_sexo
 93 | remote_census.response.district      | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_vivienda.item.codigo_distrito
 96 | remote_census.response.surname       | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.apellidos
 92 | remote_census.response.postal_code   | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_vivienda.item.codigo_postal
 97 | remote_census.response.valid         | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item
 95 | remote_census.response.name          | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.nombre
 91 | remote_census.response.date_of_birth | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.fecha_nacimi:

**Comment by cdiaz23** [comment]
en la base de datos el valor está correcto:

select * from settings where key='remote_census.response.valid';

 id |             key              |                                                 value
----+------------------------------+--------------------------------------------------------------------------------------------------------
 97 | remote_census.response.valid | comprobar_datos_response.return.get_habita_datos_response.get_habita_datos_return.datos_habitante.item

**Comment by taitus** [comment]
Hola @cdiaz23 

La verdad que es extraño que estando el valor en bbdd, al ejecutar en consola `Setting["remote_census.response.valid]` no te de ningún valor. Al menos debería devolverte `nil`.

Viendo tu log

> 2.3.2 :038"> Setting["remote_census.response.valid"]
2.3.2 :039">

Parece que se ha colado una comilla mal cerrada y por eso no te esta dando ni `nil`, ni ningún valor.
Creo que si repites el proceso, abriendo la consola y ejecutando directamente:
`Setting["remote_census.response.valid"]` va a devolverte el valor.

Por otro lado, el error parece que vuestra respuesta está devolviendo un "string", cuando lo que espera es un "hash". De ahí el error en el método:

> TypeError (Nori::StringWithAttributes does not have #dig method)

```
    def extract_value(path_value)
      path = parse_response_path(path_value)
      return nil unless path.present?

      @body.dig(*path)
    end
```

**Comment by javierm** [comment]
Sí, al pegar se me saltó una comilla doble :sweat_smile:.

**Comment by cdiaz23** [comment]
Gracias @taitus y @javierm! Efectivamente, parece que los tiros van por ahí, estoy trabajando en ello. El mensaje que me da ahora es este:

_No tienes edad suficiente para verificar tu cuenta._

Entiendo que la llamada al censo ya la hace correctamente y me detecta que el usuario está empadronado, pero no se si coge bien la fecha. En la configuración tengo establecido 16 como el valor de la edad mínima. La fecha se devuelve en formato dd/mm/yyyy, ¿es correcto?

Gracias!

**Comment by cdiaz23** [comment]
Hola!

El mensaje de la edad suficiente no era real, era consecuencia de que no se mandaba bien la respuesta, y se daba por empadronado, pero no había dato de la fecha de nacimiento. Creo que ya lo tengo resuelto, muchas gracias a todos!

**Comment by javierm** [comment]
Estupendo :smile:.

**Comment by dlddld** [comment]
Hola!
estamos intentado implantar CONSUL en nuestra Entidad. Estamos algo atascados con la conexión de padrón. 
Para conectarlo con el mismo, nos ha parecido muy interesante este hilo y nos ha esperanzado bastante. 
Vemos que las respuesta es un JSON, es decir, un servicio web que devuelva un String con el JSON dentro.
Hemos hecho eso, pero aunque recibimos la llamada, no parece que Consul interprete la respuesta. El production.log no dice nada, y no se si habrá otro log para mirar.

El mensaje devuelto es como este (son los datos de ejemplo del **remote_census_api.rb**):

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <s:Body>
    <datos_padron_consulResponse xmlns="http://tempuri.org/">
      <datos_padron_consulResult>get_habita_datos_response: { get_habita_datos_return: {datos_habitante: { item: { fecha_nacimiento_string: "11/01/1979", identificador_documento: "XXXXXXXXX" , descripcion_sexo: "Varón", nombre: "José", apellidos: "García" } },datos_vivienda: {item: {codigo_postal: "28013",codigo_distrito: "01" }}}}</datos_padron_consulResult>
    </datos_padron_consulResponse>
  </s:Body>
</s:Envelope>
```

En la configuración de Consul, los valores aluden a los nodos de este modo:
`**datos_padron_consulResponse**.datos_padron_consulResult.get_habita_datos_response.get_habita_datos_return.datos_habitante.item.apellidos`

Hemos probado con y si lo que está entre ** 

¿Nos podríais dar una pista? Muchas gracias de antemando
