### ISSUE TITLE
Remote translations from other languages not working as expected.

### ISSUE THREAD

**Issue by sbolleddula** [consul/consul#3872]
Type: Bug

Remote translations from other languages not working as expected for ex: Greek to English.

Current behavior
Whenever we tried Remote translate/Microsoft Translations from Greek to English, we get unexpected text. We tried manually translating the same text using Microsoft Translator which worked. We get the below text when tried to translate 

> Οι αρχαίοι Έλληνες προσπάθησαν να εξηγήσουν όλα τα φυσικά φαινόμενα με μύθους. Παρακάτω είναι η εξήγησή τους για την δημιουργία του κόσμου.

  Στην αρχή υπήρχε το χάος (chaos), ένα άδειο διάστημα. Από το χάος γεννήθηκαν η Γη (earth), η νύχτα (night) και η μέρα (day). Από την Γη γεννήθηκαν τα βουνά, η θάλασσα, και ο Ουρανός (sky-Uranus), ο πρώτος θεός.   Από τον Ουρανό και την Γη γεννήθηκαν 13 παιδιά, οι τιτάνες (titans). Ο Ουρανός φοβόταν πως μια μέρα, ένα από τα παιδιά του θα του πάρει τον θρόνο.   Κάθε ένα από τα παιδιά του, μόλις γεννιόταν, ο Ουρανός, τα έριχνε σε μια βαθιά σπηλιά. Ένα από τα παιδιά του ο Κρόνος (Saturn), ο νεώτερος, ήταν πολύ έξυπνος και αποφασιστικός. Δραπέτευσε και με την βοήθεια της μητέρας του πήρε τον θρόνο από τον Ουρανό. Μετά ελευθέρωσε τους αδελφούς του και τις αδελφές του και με την βοήθειά τους έγινε ο κυρίαρχος του κόσμου.

> Ο ι α ρ χ α the ο ι a λ λ, η, ν, ε ς π ρ ο σ π, θ η σ α ν ν α ε ξ η γ σ ο υ ν λ α τ α φ υ σ. Π α ρ α κ τ ω ε i ν α ι η ε ξ, γ η, σ, τ ο υ ς γ ι α τ η ν δ η μ ι ο υ ρ γ α τ.  Σ τ η ν α ρ χ or υ π or ρ χ ε τ ο χ a ο ς (Chaos), E ν α a δ ε ι ο δ ι σ τ η μ α. Α π τ ο χ ο ς, γ ε ν, ν θ η κ α ν η (Night) Γ η (Earth η ν χ (day) τ. Α π τ η ν Γ η γ ε ν ν or θ η κ Uranus α ν τ α β ο υ ν, η θ, λ α σ σ, α κ α ι ο Ο υ, ρ. < br/h α   Α π τ ο ν Ο υ ρ α ν, κ α the ι τ η ν Γ η γ ε ν ν, θ, η Titans κ α ν π α ι. Ο Ο υ ρ α ν the ς φ a ο β the τ α of ν π ω ς μ ι α μ ρ α ν, α α π τ α π α ι δ ι τ ο υ to the θ, α.   Κ θ ε e ν α α π the τ α the π α ι δ ι a τ ο, υ, μ λ ι ς γ ε ν ν ι the τ α, ν ο Ο υ ρ α ν ς τ α ρ ι χ ν a ε σ ε μ ι α β α, θ a ι to the σ π, η the λ ι. ν τ ο υ ο Κ ρ the ν ο (Saturn), ς ο ν i ε τ, ε, ρ, or ο ς τ α ν π, ο λ ξ υ π ν ο ς κ α ι α π ο φ α σ ι. Δ ρ α π, τ ε υ, σ ε κ α ι μ ε τ η ν β ο, θ ε ι α τ η ς μ η τ ρ α ς τ ο υ π ρ ε the τ ο ν θ ρ ν, ο α π τ ο ν Ο υ ρ α ν τ ο υ ς α δ ε λ φ ο a ς τ ο υ κ α ι τ ι ς α δ ε λ φ ς τ ο υ κ α ι μ ε τ η ν β ο θ ε ι τ ο υ ς κ σ μ ο υ.

Steps to reproduce
After enabling Remote Translations in the backend. Try creating a proposal in Greek using the above Greek text then switch the language to English. You will see the above output.

Expected Behavior
The remote translations should work regardless of the original source language. 

Definition of Done
If I am able to use Remote Translation feature to reflect the proper translations regardless of original source of the language.
![microsoft_translator](https://user-images.githubusercontent.com/53448133/69959876-18faf400-152e-11ea-82a5-9ed58e5ecea7.jpg)
![remote_translations](https://user-images.githubusercontent.com/53448133/69959879-19938a80-152e-11ea-9afd-6440b1eed359.jpg)

**Comment by taitus** [comment]
Hi @sbolleddula,

I just tested the functionality in my repository with the languages you tell me about and it works correctly.
I have cloned your repository https://github.com/sbolleddula/consul and with the master branch also works.
I have created 3 proposals in your environment https://pusularqa.worldbank.org/ and what you say happens to me. The title and short description are translated well, but the long description is not translated well.
Is wb-dev the branch you have uploaded on https://pusularqa.worldbank.org/?
Tomorrow I will try to reproduce it locally with the branch wb-dev and I'll try to detect what's going on.

Greetings!

**Comment by sbolleddula** [comment]
Thanks for looking into it @taitus 

Yes,  https://pusularqa.worldbank.org/ has wb-dev branch. Master branch hasn't updated yet with the latest code.

**Comment by taitus** [comment]
Hi @sbolleddula ,

Looks like I've already found the problem.
The error only affects the Wysiwyg fields, as is the description of your example.
In this WIP PR you can see how it is solved https://github.com/consul/consul/pull/3874

I'll let you know as soon as it's reviewed, ensuring that everything continues to work properly and is merged into master.

**Comment by sbolleddula** [comment]
Hi @taitus When can we expect the review process to complete?

**Comment by taitus** [comment]
Hi @sbolleddula 

PR #3874 has been merged!
