### ISSUE TITLE
db:migrate error in local machine window

### ISSUE THREAD

**Issue by giturra** [consul/consul#3878]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

I want to install the project on my local machine.

### Description

I follow the installation according to this [guide](https://github.com/consul/consul) in the _Configuration for development and test environments_.

### Current Behavior
[comment]: # (Describe what actually happened.)

When I type `rake db:migrate` I got this error:

(in D:/railsprojects/consul)
[dry-types] Dry::Types.module is deprecated and will be removed in the next major version
Use Dry.Types() instead. Beware, it exports strict types by default, for old behavior use Dry.Types(default: :nominal). See more options in the changelog
<path/to>/consul/config/application.rb:7:in `<top (required)>'
rake aborted!
NoMethodError: undefined method `member_types' for #<Dry::Types::Hash::Constructor:0x0000000006748550>
<path/to>/consul/config/application.rb:7:in `<top (required)>'
<path/to>/consul/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

And I don't know how to fix it...

**Comment by javierm** [comment]
Hi @giturra,

Do you still get the error when you run `bin/rake db:migrate` instead of `rake db:migrate`? If so, can you paste the output you get when  running `bin/rake db:migrate --trace`?

**Comment by giturra** [comment]
Hi @javierm 

Well, I'm using window 10 when I tried to run `bin/rake db:migrate`, the terminal said;

`not recognized as an internal or external command operable program or batch file`

intead of that I change de directory to `consul/bin` and run the command `rake db:migrate`

I got this when I type `rake db:migrate --trace`:

(in D:/railsprojects/consul)
[dry-types] Dry::Types.module is deprecated and will be removed in the next major version
Use Dry.Types() instead. Beware, it exports strict types by default, for old behavior use Dry.Types(default: :nominal). See more options in the changelog
D:/railsprojects/consul/config/application.rb:7:in `<top (required)>'
rake aborted!
NoMethodError: undefined method `member_types' for #<Dry::Types::Hash::Constructor:0x000000000a681280>
D:/Ruby/lib/ruby/gems/2.4.0/gems/dry-types-0.15.0/lib/dry/types/constructor.rb:147:in `method_missing'
D:/Ruby/lib/ruby/gems/2.4.0/gems/dry-struct-0.5.1/lib/dry/struct/class_interface.rb:306:in `schema'
D:/Ruby/lib/ruby/gems/2.4.0/gems/dry-struct-0.5.1/lib/dry/struct/class_interface.rb:193:in `check_schema_duplication'
D:/Ruby/lib/ruby/gems/2.4.0/gems/dry-struct-0.5.1/lib/dry/struct/class_interface.rb:133:in `attributes'
D:/Ruby/lib/ruby/gems/2.4.0/gems/dry-struct-0.5.1/lib/dry/struct/class_interface.rb:113:in `attribute'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator_text/types/sentence.rb:8:in `<class:Sentence>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator_text/types/sentence.rb:3:in `<module:Types>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator_text/types/sentence.rb:2:in `<module:TranslatorText>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator_text/types/sentence.rb:1:in `<top (required)>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator_text/types.rb:30:in `require_relative'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator_text/types.rb:30:in `<top (required)>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator-text.rb:4:in `require_relative'
D:/Ruby/lib/ruby/gems/2.4.0/gems/translator-text-0.1.0/lib/translator-text.rb:4:in `<top (required)>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
D:/Ruby/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
D:/railsprojects/consul/config/application.rb:7:in `<top (required)>'
D:/Ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
D:/Ruby/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
D:/railsprojects/consul/Rakefile:4:in `<top (required)>'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:82:in `block in run'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
D:/Ruby/lib/ruby/gems/2.4.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
D:/Ruby/bin/rake:23:in `load'
D:/Ruby/bin/rake:23:in `<main>'

**Comment by javierm** [comment]
Note windows is not supported at all. We'll try to help you but cannot guarantee you'll get it to work.

> intead of that I change de directory to consul/bin and run the command rake db:migrate

I'm not sure it's the same thing; the output mentions `D:/Ruby/bin/rake` but not `consul/bin/rake`  :thinking:.

 Do you get the same result when running `bin\rake db:migrate --trace` or `bundle exec rake db:migrate --trace`?

**Comment by javierm** [comment]
> D:/Ruby/lib/ruby/gems/2.4.0/gems/dry-types-0.15.0

Closing this one since it seems you're using dry-types-0.15.0, while in our Gemfile.lock we've defined version 0.13.3.

You can try uninstalling dry-types, check you're using the right version in the Gemfile.lock, and run `bundle install` again. Hope that helps! :smile:
