### ISSUE TITLE
bug of navigation when try to go back

### ISSUE THREAD

**Issue by gabrielbaldao** [consul/consul#3885]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
In some pages, when the user try to go back in your navigation this happen this bug.

### Why is this Needed?

To improve the user experience

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
One example is when I, as admin, access `http://localhost:3000/admin/budgets`, after I click in some `Manage project` and try to go back this bug happen.
`http://localhost:3000/admin/budgets`
![Screenshot_20191216_140637](https://user-images.githubusercontent.com/20587352/70928365-a8fd6b00-200f-11ea-8c39-b1fe5cc034a0.png)

`After click in "to go back" in my browse`
![Screenshot_20191216_140552](https://user-images.githubusercontent.com/20587352/70928364-a864d480-200f-11ea-89e7-c734e31f8082.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
To go back for `http://localhost:3000/admin/budgets`, but this is happening in most pages.

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
- Access `http://localhost:3000/admin/budgets`
- Click in some `Manage project`
- Click to go back in your browser

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
@gabrielbaldao Thanks for reporting! It will be fixed when we merge pull request #3778, before releasing version 1.1.

**Comment by gabrielbaldao** [comment]
perfect, thanks
