### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by gpetrov-bg** [consul/consul#3937]
Hello I would like to have Bulgarian language added to CONSUL

**Comment by javierm** [comment]
Hi, @gpetrov-bg!

Thank you very much for your interest in translating CONSUL! :smile:

We manage translations through [Crowdin](https://crowdin.com/project/consul). Feel free to sign up and add [translations for Bulgarian](https://crowdin.com/project/consul/bg)

You might also want to check out our [documentation about translations](https://docs.consulproject.org/docs/english-documentation/customization/translations).

Cheers!

**Comment by gpetrov-bg** [comment]
Thank you!
