### ISSUE TITLE
Error en verificación de residencia

### ISSUE THREAD

**Issue by aaznar** [consul/consul#3947]
Estoy intentando verificar mi cuenta como administrador, para enviar mensajes privados y demás acciones de administración, pero por más que meto uns datos supuestamente válidos, siempre sale el error "Para verificarte debes estar empadronado." y le estoy metiendo un Código Postal correcto, incluso con DNI real.
¿Bug o alguna forma especial de poder verificar los datos?

**Comment by Senen** [comment]
Hola @aaznar, Antes de comenzar a indagar unas preguntas:

1. ¿Qué versión de consul tienes?
2. ¿Qué sistema de verificación estás usando? ¿Censo local o censo remoto?

**Comment by javierm** [comment]
@aaznar Hola :smile:. ¿Sigues teniendo este problema?

**Comment by javierm** [comment]
Closing this one due to lack of information. @aaznar Si sigues teniendo este problema, puedes reabrir la incidencia dando los detalles que pedía Senén :wink:.
