### ISSUE TITLE
Bug when change custom text with variables from admin panel 

### ISSUE THREAD

**Issue by decabeza** [consul/consul#3957]
### Description

There is a **bug** when an admin user tries to change a text on the "Custom information text" section `/admin/site_customization/information_texts` with the keys that include some `%{variable}` in the text.

It seems the custom text it's converted to a String and the interpolation it's not working correctly.

### Steps to reproduce
1. Visit `/admin/site_customization/information_texts?tab=mailers`
2. Change key `mailers.budget_investment_created.intro` keeping the variable, for example `Custom hi for the awesome <strong>%{author}</strong>,`
3. Visit `/admin/system_emails/budget_investment_created/view` to check the wrong interpolation.

This bug happens in any key with a variable.

### Expected Behavior
The custom text should show the interpolation correctly.

### Screenshot
![interpolation](https://user-images.githubusercontent.com/631897/77913301-4e251200-7294-11ea-8c58-3cfb45640d65.png)

**Comment by javierm** [comment]
Is this issue the same as issue #3676? :thinking:

**Comment by decabeza** [comment]
Duplicated with #3676.
