### ISSUE TITLE
broken orbit slider on voting 

### ISSUE THREAD

**Issue by smarques** [consul/consul#3961]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
As an admin I want to add multiple images to possible replies to one voting question and see them in the corresponding orbit slider

### Why is this Needed?

https://github.com/consul/consul/pull/3886 has broken something
see also: https://github.com/foundation/foundation-rails/issues/289

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

- images do not appear for a css inconsistency (it appears connected to this: https://github.com/consul/consul/blob/master/app/assets/stylesheets/participation.scss#L1775) 
- the looping of the slides work only once (see https://github.com/foundation/foundation-rails/issues/289)

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
You add images to a reply option for one question in a voting set, the slider shows but the orbit container has height: 0, this seems to be due to a css problem on orbit-container
If you force the container height by disabling `height: 100% !important` in the inspector than images show, but there remains a problem with the loop of the slides as referenced above.

If I comment this line: https://github.com/consul/consul/blob/master/app/assets/stylesheets/participation.scss#L1775,
add `data-use-m-u-i="false"` to the orbit element
and revert foundation rails to` 6.4.3.0 `things work again (but no transitions on slides)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
I expected images to show and slides to loop

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
Create a voting , create a question, add one answer, add two images to the answer,

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
Hi, @smarques :smile:.

Thanks for reporting! We've just opened pull request #4077, which we think solves the issue (although we had to disable the animation effect, which makes it harder to use when images have different heights :relieved:), and it will be included in our next release.
