### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by raoulkramer** [consul/consul#3962]
Hello I would like to have my language Georgian added to CONSUL

**Comment by javierm** [comment]
Hi, @raoulkramer :smile:.

I've just added Georgian to the list of available languages in [Crowdin](https://crowdin.com/project/consul). Feel free to sign up and add [translations for Georgian](https://crowdin.com/project/consul/ka) and we'll be glad to add them to CONSUL :wink:.

You might also want to check out our [documentation about translations](https://docs.consulproject.org/docs/english-documentation/customization/translations).

Cheers!

**Comment by raoulkramer** [comment]
Thanks @javierm we will follow your instructions (งツ)ว . Great!
