### ISSUE TITLE
Docker image unable to build

### ISSUE THREAD

**Issue by RuBiCK** [consul/consul#3991]
### User Story

As a developer, I want to run consul in container so I followed the guide to run consul in local

### Why is this Needed?

Docker image is not built due to an error with gems

### Description

*Type*: BUG

### Current Behavior
 `docker build` thrown an error:
```
user_agent_parser-2.6.0 requires ruby version >= 2.4, which is incompatible with
the current version, ruby 2.3.8p459
The command '/bin/sh -c bundle install --full-index' returned a non-zero code: 5
```

### Expected Behavior
to build the docker image without error

### Steps to reproduce
just trying to build the docker image as describedin the guide: https://docs.consulproject.org/docs/english-documentation/introduction/servers/docker

Downloaded the latest master version: d3fa00b1e60bc391d15306a3e5109b520fa13deb (HEAD -> master, origin/master, origin/HEAD)

See full output here https://gist.github.com/RuBiCK/c0cbaa674a6311aeb9546b921e513bf2

**Comment by raoulkramer** [comment]
Hi, did you run the prerequisites https://docs.consulproject.org/docs/english-documentation/introduction/local_installation/prerequisites ? Installing prerequisites and gems outside the docker commands messed up a lot for me in my experience. Docker(-compose) deals with it all and I think it get confused when you have ruby stuff running outside your container.

**Comment by javierm** [comment]
It looks like we need to upgrade the Ruby version usend in the Docker image, as suggested in pull request #3960 :thinking:.

**Comment by raoulkramer** [comment]
@abihas could you comment on this?

**Comment by RuBiCK** [comment]
I'm trying to perform the production installation in a brand new ubuntu 16.04 and same issue executing `bundle` while I'm following all steps described in docs
Sorry but I don't have ruby knowledge so If you tell me which file I need to update the version, I could try it

**Comment by abihas** [comment]
@RuBiCK me neither 😜. Change the first
line in the Dockerfile to: 
FROM ruby:2.4

I could also send you our docker-compose
file if that helps.

**Comment by RuBiCK** [comment]
Upgrading the base image to 2.4 builds sucessfully as @abihas suggested

**Comment by javierm** [comment]
Thank you very much @abihas and @raoulkramer for your help with this issue :pray:.

Thanks to @luchiago, we've just merged a pull request fixing this issue :tada:.
