### ISSUE TITLE
Review length validations in ckeditor fields

### ISSUE THREAD

**Issue by taitus** [consul/consul#4013]
### Description
*Type*: Bug

Minimum length validation is not being correctly applied in the fields of the forms where the ckeditor is used. 
If we fill in the ckeditor with a simple "a", the string that reaches the validation is: `<p>a</p>\r\n` 
Then it exceeds the minimum length and does not skip validation 🤔 

### Steps to reproduce
1. Start a debate
1. Fill in title, Fill in the description with less than 10 characters and  Accept privacy policy and terms
1. Submit

We will see that the debate is created correctly, and the following validation does not apply: `is too short (minimum is 10 characters)`

### Notes
Review specs and replace `fill_in` with `fill_in_ckeditor` where necessary, and identify similar cases.

**Comment by efgalvao** [comment]
So the limit should be higher or there is a way to apply the validation before converting ?

**Comment by javierm** [comment]
Hi, @efgalvao :smile:. That's a great question!

Ideally we would change the minimum length validation rule so it doesn't take tags into account :thinking:.

**Comment by efgalvao** [comment]
I think that too. What length you think would be good ? 30 ? 50 ? I can change that for you if you wish.

**Comment by javierm** [comment]
Thanks for your collaboration! :tada:

Just to clarify: what I mean is keeping the minimum length at 10 characters, but changing the validation rule so instead of checking the whole string (`<p>a</p>\r\n` in the example), it checks the string after removing the HTML tags and trailing spaces/newline chatracters (`a` in our case).

**Comment by efgalvao** [comment]
Ok.

**Comment by efgalvao** [comment]
Hi @javierm , I'm having a bit of difficulty validating the length of the Description translations. I can check the string after removing the HTML tags and everything else with no problem. Do you have any advice ? I'm not used to globalize gem.

**Comment by javierm** [comment]
@efgalvao Could you paste (or link to) the code you've written so far?

**Comment by efgalvao** [comment]
@javierm 
I've tried some approaches
Custom method:
```
validates_translation :description, presence: true
validate :description_sanitized

...

  def description_sanitized
    real_description_length = ActionView::Base.full_sanitizer.sanitize("#{description}").squish.length
    if real_description_length < 10
      errors.add(:description,  I18n.t("errors.messages.too_short.other", count: Debate.description_min_length))
    end
    if real_description_length > 6000
      errors.add(:description, I18n.t("errors.messages.too_long", count: Debate.description_max_length))
    end
  end
```
I've tried with a custom validator and with virtual attributes too.


![9](https://user-images.githubusercontent.com/61836657/109689622-3f11a880-7b64-11eb-972b-da021bdb7583.png)
![ok](https://user-images.githubusercontent.com/61836657/109689634-42a52f80-7b64-11eb-92fd-d65f5f51ddb2.png)
![too_long](https://user-images.githubusercontent.com/61836657/109689640-446ef300-7b64-11eb-821f-85997ce991c3.png)

**Comment by javierm** [comment]
Maybe I'm not following what's going on :thinking:. Since you mentioned you were having difficulties, I thought the code wasn't working, but in the screenshots things seem to be fine :thinking:.

By the way, could you add some test cases for what you're implementing? :pray: This way it's much easier to check whether the code is working :smile:.

**Comment by efgalvao** [comment]
The code is working, but it works differently from the validation with: `  validates_translation :description, presence: true, length: { in: 10..Debate.description_max_length }
`
My code verify the description which was written before anything else. But with the ` validates translation` he checks the length in a different way. I'm working on it.
