### ISSUE TITLE
Detailed confirmation texts

### ISSUE THREAD

**Issue by Michael1337** [consul/consul#4015]
### Description
The confirmation alert for any action should specify what the action does in detail. If it just asks "Are you sure?", I will always click yes, because I have no reason to change my mind so suddenly, unless I misclicked. But I would not be able to realize a misclick, because the alert does not tell me what I clicked.

### Current Behavior
Currently, all confirmation alerts just ask "Are you sure?".

### Expected Behavior
Each confirmation alert should have a detailed description about what is going to happen upon confirmation.

### Steps to reproduce
Click on "Hide" and "Hide author" on a comment on a discussion.

**Comment by javierm** [comment]
@Michael1337 Thanks for reporting! :pray:

> If it just asks "Are you sure?", I will always click yes, because I have no reason to change my mind so suddenly, unless I misclicked. But I would not be able to realize a misclick, because the alert does not tell me what I clicked.

Couldn't agree more :smile:.

Ideally we'd remove this alert completely and offer ways to undo actions instead, but I'm afraid the "undo" feature won't be implemented soon :thinking:.

**Comment by rhian-cs** [comment]
Hello, may I give this issue a try?
