### ISSUE TITLE
Redirect on GET /residence

### ISSUE THREAD

**Issue by Michael1337** [consul/consul#4016]
### Description
GET /residence does not lead to any page.

### Current Behavior
When you send invalid data during the verification process at GET /residence/new, you get redirected to POST /residence. When you logout or refresh the site at this point, the resulting GET /residence request leads to a non-existing page.

### Expected Behavior
Invalid POSTs at /residence/new should also end up on /residence/new or GET /residence should redirect to GET /residence/new

### Steps to reproduce
Click on "Verify residence" with an empty form. Then sign out of your user account.

**Comment by javierm** [comment]
@Michael1337 Correct me I'm wrong; refreshing the page does *not* result in a non-existing page :thinking: but the browser asks whether you want to re-send the form :thinking:.

Logging out and getting redirected to a blank page can be annoying, though :relieved:, so I'm leaving this issue open.

**Comment by Michael1337** [comment]
> @Michael1337 Correct me I'm wrong; refreshing the page does _not_ result in a non-existing page 🤔 but the browser asks whether you want to re-send the form 🤔.

You are right, my terminology is not precise here. By "refreshing" I mean reloading the page as a GET, like clicking into the address bar of the browser and hitting Enter.
