### ISSUE TITLE
PLEASE NOTE THAT THE SOFTWARE MAY NOT BE USED, DEPLOYED OR INSTALLED IN THE PEOPLE’S REPUBLIC OF CHINA.

### ISSUE THREAD

**Issue by dyhack** [consul/consul#4029]
### User Story

PLEASE NOTE THAT THE SOFTWARE MAY NOT BE USED, DEPLOYED OR INSTALLED IN THE PEOPLE’S REPUBLIC OF CHINA.

### Why is ?

AGPLv3 protocol, that is to say, no matter how you modify or use the code, you need to open source unless you get commercial authorization.

### Description

https://help.github.com/en/github/site-policy/github-and-trade-controls

### FIinally
Your company is regulated by American law. GitHub also updated its export instructions last year. This is the upgrade of trade war!!!

Here's a message for you. Abandon your illusions and prepare for battle

**Comment by javierm** [comment]
@dyhack Thank for your interest in CONSUL.

For legal questions, please [contact the CONSUL project staff](https://consulproject.org/en/#contact) :wink:.

Cheers!
