### ISSUE TITLE
Problema con oauth2 de google

### ISSUE THREAD

**Issue by bjmkavak** [consul/consul#4074]
### User Story

[comment]: # Estamos intentando implementar Oauth con Google para nuestra organización y estamos teniendo problemas con la autenticación de google, he validado en varias ocasiones la documentación y no logro encontrar donde se origina el error.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:Bug?

[comment]: # Al agregar el clientID y secret nos permite acceder al login pero al usuario dar autorización de usar el correo de google nos manda error de credenciales invalidas:
![image](https://user-images.githubusercontent.com/55755847/89469529-3e847100-d73f-11ea-814f-cd67da6e79dd.png)

### Current Behavior
[comment]: # 
- Se crea la aplicacion web en la consola de google y se generan las credenciales.
- Se agregan los uris se configura el archivo en el servidor de producción
- Se reinicia el servicio via capistrano 
- Al querer hacer login con google manda error de credenciales invalidas

![image](https://user-images.githubusercontent.com/55755847/89469646-80151c00-d73f-11ea-9253-d349d54f07e6.png)
![image](https://user-images.githubusercontent.com/55755847/89469697-9e7b1780-d73f-11ea-95f6-3c7c93997e73.png)
![image](https://user-images.githubusercontent.com/55755847/89469744-b9e62280-d73f-11ea-83c6-39c8a443d123.png)

### Expected Behavior
[comment]: # El login con Google debería funcionar, a menos que no se este especificando algo de nuestro lado, se utilizó el installer para el despliegue y todas las actualizaciones se han hecho vía capistrano,
También se habilito la api de contactos y google+ como lo menciona la documentación,
¿Estamos omitiendo algún paso?
¿Hacia donde me puedo dirigir para resolver este tema?

De antemano muchas gracias.

**Comment by javierm** [comment]
Buenas @bjmkavak.

Gracias por el aviso :smile:. Otro usuario nos ha comentado lo mismo también esta misma semana. ¿Podrías probar esto?

1. En el fichero "Gemfile", cambia la línea `gem "omniauth-google-oauth2", "~> 0.4.0"` por `gem "omniauth-google-oauth2", "~> 0.8.0"`
2. Ejecuta `bundle update omniauth-google-oauth2`
3. Sube estos cambios a vuestro repositorio y luego actualiza usando capistrano

**Comment by bjmkavak** [comment]
Muchas gracias, eso soluciono el issue.

Saludos y gracias por el excelente trabajo que hacen

**Comment by javierm** [comment]
Me alegro que funcionase :smile:. Si no te importa, reabro la incidencia hasta que el código que lo resuelve esté en CONSUL :wink:.
