### ISSUE TITLE
add new language to repo

### ISSUE THREAD

**Issue by raoulkramer** [consul/consul#4120]
Hello  @javierm would it be possible to Georgian add to the CONSUL repo? :thumbsup: Translation is 98% now and done by professional translators. Ps the the automatic way of joining words to compose sentences does not always work well in Georgian [e.g. Follow citizens proposal ].  thanks!

**Comment by Senen** [comment]
Hi @raoulkramer, we are working right now on a PR with all new translations including Georgian, as it translation ratio is very high we will enable it by default bu adding it to available _locales. Lot of thanks to the professional translators! :clap
