### ISSUE TITLE
Validación de usuarios via SMS

### ISSUE THREAD

**Issue by kuenka123** [consul/consul#4124]
Buenas,

Estamos tratando de implementar esta genial solución en un ayuntamiento español y hemos logrado salvar todos los pasos de configuración excepto la verificación de cuentas via SMS. Tenemos contratado actualmente el envio de SMS mediante la mensajería de negocios de Movistar cuyo wsdl puede verse aquí:

https://www.mensajerianegocios.movistar.es/ISServer/services/MI-InterfazSimplificado-Port?wsdl

He modificado código en la librería /lib/sms_api.rb pero entre que desconozco el lenguaje y que la documentación de movistar no está salvo en php y java no sé muy bien como avanzar.

Mi primera pregunta sería ¿alguien ha modificado esta librería para conectar con el servicio de Movistar? ¿Hay alguna alternativa a Movistar para poder hacer pruebas sin necesidad de modificar el código?

Si esto no fuera posible... ¿Existe la posibilidad de omitir esta validación? He visto en el código que si la propiedad endpoint no está definida debería pasar la validación cogiendo la respuesta predefinida; pero me da error 500 en el servidor. ¿Estoy obviando algo?

Muchísimas gracias por todo

**Comment by javierm** [comment]
@kuenka123 Muy buenas.

Me temo que los desarrolladores nunca hemos usado el servicio de Movistar que mencionas. Si quieres, puedes probar a poner tu pregunta en nuestro canal de slack o en [nuestra comunidad](https://community.consulproject.org/), ya que ahí habrá más gente que pueda haber estado en tu situación (esta página solo la leen los desarrolladores de CONSUL). Y, por favor, si lo consigues, mándanos un enlace a los cambios que has tenido que hacer. Así podremos incluirlo en [la documentación](https://docs.consulproject.org/) y otros usuarios en esta situación encontrarán una solución más facilmente :wink:.

Si al final prefieres saltarte esta validación, prueba a crear un archivo en `app/models/custom/user.rb` con este contenido:

```ruby
require_dependency Rails.root.join("app/models/user").to_s

class User
  def verification_sms_sent?
    true
  end

  def sms_verified?
    true
  end
end
```

In English:

I'm afraid we haven't used the Movistar WSDL. You might want to post in our slack channel or [our community](https://community.consulproject.org/), where more CONSUL users might read your question. By the way, if you find a solution, please send us a link to the changes you needed to do, so we can update [our documentation](https://docs.consulproject.org/) and the solution will be available for everyone :wink:.

Regarding skipping the SMS validation, try creating a file in `app/models/custom/user.rb` with the following content:

```ruby
require_dependency Rails.root.join("app/models/user").to_s

class User
  def verification_sms_sent?
    true
  end

  def sms_verified?
    true
  end
end
```

**Comment by javierm** [comment]
Closing due to lack of response.

In case this is still needed, concello-santiago-de-compostela#19 implements SMS using the Movistar API.
