### ISSUE TITLE
Error en comentarios ruta: management/proposals/43-successful-proposal-title-for-locale-en#comments

### ISSUE THREAD

**Issue by cfcastillol** [consul/consul#4137]
Hola, estoy entrando en este enlace y aparece el siguiente error

Enlace: http://localhost:3000/management/proposals/43-successful-proposal-title-for-locale-en#comments

Error: ActionView::MissingTemplate in Management::Proposals#show

**Comment by javierm** [comment]
@cfcastillol Gracias por el aviso :smile:; hemos abierto la #4138 para arreglar este fallo. / Thanks for the tip; we've opened pull request #4138 which should solve this issue.
