### ISSUE TITLE
Moderación activa del foro.

### ISSUE THREAD

**Issue by Poliuk** [consul/consul#420]
*Lo primero felicidades por el proyectazo. Sois todo un ejemplo para el resto de administraciones públicas, no quiero imaginar lo que hubiera costado esto y que churro hubiera salido en caso de haber sido colocado a la consultora de turno.*

Considero que es necesario que incorporéis un mecanismo activo de moderación del foro, de manera que los nuevos debates en lugar de publicarse automáticamente pasen por una validación. Con el tiempo se puede identificar a los usuarios más activos y dotarles de privilegios de administración.

Esto está relacionado con mi comentario en https://github.com/AyuntamientoMadrid/participacion/issues/415, lamentablemente ciertas comunidades de internet (Forocoches, seguidores del rubius, etc...) han decidido trolear el foro.

**Comment by damagedgoods** [comment]
Añadiría la posibilidad de consultar las propuestas que han sido moderadas / retiradas. En un portal de transparencia, la moderación también debería ser transparente.

Gracias por tan buen trabajo :-)

**Comment by bomberstudios** [comment]
+1 al comentario de @damagedgoods.

Por otra parte, molaría elegir la "Propuesta Troll del Mes" y premiarla con una beca para escribir noticias en El Mundo Today. ¡Algunas de las propuestas son muy graciosas! (Véase https://decide.madrid.es/debates/1598 : )

**Comment by andhillebrand** [comment]
Secundo lo dicho por @damagedgoods y @bomberstudios. Creo que es una grandísima propuesta, sumamente necesaria para el futuro de las ciudades y considero que el hecho de que haya personas que no se la toman tan en serio como otras, no debe achantar a nadie para mantener y continuar con un proyecto tan sumamente necesario.

**Comment by rosa2** [comment]
No creo que premiar a trolls sea una buena idea como sugieren damagedgoods y andhillebrand. Estaría bien una función que en vez de borrar, hiciese los posts invisibles por si más adelante se acusa poder mostrar. También por si se cuela un moderador troll.

**Comment by d4weed** [comment]
+1 a moderar solo cambiando la visibilidad. Eso haría la moderación transparente y permitiría a cualquiera recuperar las propuestas troll y hacer lo que quisiese con ellas sin añadir ruido a la herramienta

**Comment by d4weed** [comment]
También es posible una moderación orgánica basada en karma o algo similar

**Comment by JorgeGT** [comment]
+1 a @damagedgoods, la moderación sin transparencia es censura.
@d4weed el problema de tu propuesta es el "karma gaming" (p ej todo forocoches se pone de acuerdo para subir el karma a un miembro concreto).

La moderación de un foro abierto... no tiene una solución cerrada!

**Comment by voodoorai2000** [comment]
Holas! 

Muchas gracias por vuestras ideas cracks!

En efecto no hay nada borrado, sólo está oculto y nos estamos planteando seriamente abrir a todo el mundo los debates y comentarios moderados, pero aún no tenemos claro cual es la mejor manera de hacerlo.

**Comment by ManjiChiba** [comment]
Opino como Poliuk y Damage.
Veo que ya se le ha pasado por la cabeza antes a otras personas las mismas soluciones.
Aquí ponía yo lo mismo.
https://decide.madrid.es/proposals/5178
Lo de premiar a los trolls... lo veo contra-producente. Es lo que atraería a cada vez más trolls.
