### ISSUE TITLE
Follow proposal button not indicating actual follow state

### ISSUE THREAD

**Issue by Michael1337** [consul/consul#4224]
### Description

On Staging and Production, the "Follow citizen proposal" button seems to be bugged. When a user clicks the button and refreshes the page, the buttons shows as if the user is not following the proposal. The "follow" does get created and stored in the database, though, and the js refresh as well as the delete work properly. The same is true for the "Follow investment" button.
Also, this does not occur on my local development environment, even though the code is the same, so I assume the `def find_or_build_follow(user, followable)` method always searches the development database or something like that.

### Current Behavior
When a user follows a proposal and refreshes the page, the button looks like the user is not following the proposal.

### Expected Behavior
When a user follows a proposal and refreshes the page, the button should look like the user is following the proposal.

### Steps to reproduce
1. Go to any proposal or investment on a production environment, for example: https://demo.consulproject.org/proposals/5-prevent-supermarkets-from-wasting-food
2. Follow the proposal by clicking "Follow citizen proposal".
3. Refresh the page.

**Comment by javierm** [comment]
@Michael1337 Thanks for reporting! :smile: It looks like it's a cache issue. We'll have a look.
