### ISSUE TITLE
Table of contents not working properly

### ISSUE THREAD

**Issue by raoulkramer** [consul/consul#4231]
Hi,

It looks that with the update the **Table of contents** in /legislation/processes/1/draft_versions/1 is not working properly anymore since the current release. When I compare release 1.2 0 with 0.19 the latter has got the ability to scroll and have a proper overview. 
Thanks

See the screen shots attached.

Good:
![table_good](https://user-images.githubusercontent.com/47716558/98003586-2d570900-1def-11eb-8f46-2197891784fb.png)

Bad:
![table_bad](https://user-images.githubusercontent.com/47716558/98003593-2def9f80-1def-11eb-8dce-d055108f77e5.png)

**Comment by raoulkramer** [comment]
After refactoring (in vscode) consul/app/assets/javascripts/legislation_allegations.js the table layout improved. Only document scrolling should be separated from page scrolling as in "0.19"

**Comment by javierm** [comment]
Hi, @raoulkramer. Thanks for reporting!

I've tested in on version 0.19 and I get the exact same (buggy) behavior I get with version 1.2.0 :thinking:. No scroll in the table of contents, and the texts stay narrow until I start scrolling.

Can you link to a live version which is working as expected?

**Comment by raoulkramer** [comment]
Hi, @javierm , you can check it here https://ledenkamer.pvda.nl/legislation/processes/4/draft_versions/4 please be careful it is very live :smile: If I need I can give you access to the fork. Thanks again :+1:

**Comment by javierm** [comment]
Thanks for the link! I get the same behavior on that page. It looks this way if you open the contents and don't scroll:

![The table of content shows one word per line](https://user-images.githubusercontent.com/35156/98092955-95f1c480-1e87-11eb-9950-5538291d65de.png)

The problem with the width seems to be fixed with this patch:
[sticky.txt](https://github.com/consul/consul/files/5486831/sticky.txt). Scrolling is probably going to be a bit trickier.

**Comment by raoulkramer** [comment]
So strange.. :thinking: this does now happen for the first time with me too... in the Brave browser it looks still to work as it suppose to work... We will check further on our side.

![table](https://user-images.githubusercontent.com/47716558/98100155-c1c57800-1e90-11eb-8638-c200ab16f27b.GIF)
