### ISSUE TITLE
Commands to run after code update

### ISSUE THREAD

**Issue by jfoclpf** [consul/consul#4254]
Which exact commands should I run after changing the code, for example css files or config files?

I changed them and the site does not update. I tried to compile the assets or restart the server and nothing.

Thanks in advance

**Comment by javierm** [comment]
The recommended way is to change the code locally on your machine, upload it to the repository, and deploy with capistrano.

**Comment by jfoclpf** [comment]
Ok, I was trying to avoid Capistrano cause it is totally new for me, but I think I really have to study it :)
