### ISSUE TITLE
How does a admin change the profile of a user?

### ISSUE THREAD

**Issue by jfoclpf** [consul/consul#4259]
I have a colleague that registered and I want to make him also administrator.
Which file shall I edit?
Is it possible to upgrade an user to admin on the admin control panel?

**Comment by javierm** [comment]
@jfoclpf a look at this [comment on issue #3950](https://github.com/consul/consul/issues/3950#issuecomment-619910184). Hope that helps!

**Comment by jfoclpf** [comment]
Thanks a lot @javierm 
It's not very intuitive though
