### ISSUE TITLE
Consumer generates a copy when registering a service through the HTTP API

### ISSUE THREAD

**Issue by AEGEGE** [consul/consul#4317]
I deploy a consul cluster with three nodes, all in the role of server. After the deployment is completed, kv has achieved high availability, but when I register the service through one of the nodes, I found that the registered service cannot automatically generate a copy. Is there a way to register Does the service automatically generate a copy?

**Comment by javierm** [comment]
I'm sorry; I'm afraid I'm not following what you're trying to do.

Would it be possible that your issue is related to [Hashicorp's Consul](https://github.com/hashicorp/consul) (which is a different software)? :thinking:

**Comment by AEGEGE** [comment]
sorry,there's a mistake
