### ISSUE TITLE
Link Website in github

### ISSUE THREAD

**Issue by Nudin** [consul/consul#4319]
Is there a reason why the project homepage is not linked in the Github metatdata? This isnot only handy, since the link can be found always at the same position, it is also machine-readable and can therefore be checked/synced with other databases and knowledge graphs.

For better understanding, it about that there is no link to be seen here:
![Bildschirmfoto](https://user-images.githubusercontent.com/509205/104966752-fd78d400-59e1-11eb-8c4c-e92a6e3b4bb4.png)

**Comment by javierm** [comment]
Thanks for reporting! Fixed.
