### ISSUE TITLE
undefined method `title' for nil:NilClass

### ISSUE THREAD

**Issue by mchisnerman3** [consul/consul#4321]
Hola, me tira este error cuando quiero moderar comentarios.

undefined method `title' for nil:NilClass
![Sin título](https://user-images.githubusercontent.com/21108629/105050009-0e5e2f80-5a4c-11eb-938c-09d61ad037f1.png)

**Comment by javierm** [comment]
No sabría decir seguro, pero tiene pinta de que hay algún comentario que se ha quedado "huérfano". Es decir, se hizo un comentario en un debate/propuesta/etc. y dicho debate/propuesta/etc. fue eliminado :thinking:. ¿Es posible que hayas eliminado datos manualmente de la base de datos?

**Comment by javierm** [comment]
Closing due to lack of feedback.
