### ISSUE TITLE
Update Dockerfile to Ruby 2.6.6

### ISSUE THREAD

**Issue by raoulkramer** [consul/consul#4351]
Hi all!

It would be good to upgrade the Dockerfile following the prerequisites: Ruby 2.6.6, In production the builds are tested and work well. Thanks Raoul

**Comment by raoulkramer** [comment]
On advise of @javierm we should leave it on prerequisites: Ruby 2.5.8

**Comment by javierm** [comment]
Yes, that's correct for version 1.2.0. If you're using our current master branch (which can be considered a pre-1.3.0 version), use Ruby 2.6.6. I've opened pull request #4462, which will be included in version 1.3.0.
