### ISSUE TITLE
6

### ISSUE THREAD

**Issue by mrdocR** [consul/consul#4403]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
@mrdocR I guess this one was opened by mistake :thinking:. Feel free to reopen if that weren't the case.
