### ISSUE TITLE
Bloquear usuario vs ocultar usuario

### ISSUE THREAD

**Issue by kikito** [consul/consul#441]
Ha quedado claro que necesitamos dos acciones distintas para usuarios:

* Bloquear un usuario es que "desaparezca de la web": sus comentarios y debates se hacen invisibles.
* Ocultar un usuario es cuando alguien nos pide que le ocultemos porque no quiere aparecer más - por ejemplo por bullying. La idea es que en en lugar de ese usuario aparezca "usuario oculto", pero que sus debates y posts se sigan viendo.

Problemas:

* Actualmente en la web se confunden los dos conceptos. El menú, el código y los permisos se habla de "ocultar" cuando deberían ser "bloquear".
* Tenemos que plantearnos qué pasa con los votos de los usuarios bloqueados. ¿Deberían dejarse, o quitarse?
* Por otro lado, el escenario de "ocultar por bullying" todavía no se ha dado (aunque es pronto). Hay que plantearse la alternativa de hacer YAGNI: ocultar un usuario es bloquearlo y punto.

**Comment by xuanxu** [comment]
tema solucionado
