### ISSUE TITLE
Bundle install fails caused by mimemagic gem

### ISSUE THREAD

**Issue by jakrzus** [consul/consul#4468]
### User Story

As user runs `bundle instal` installation fails 

### Why is this Needed?

To install gems

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
gem _mimemagic_ yanked all versions prior to 4.0 to resolve its licensing issues. ActiveRecord depends on this gem. It causes all bundle installs to fail 
```

An error occurred while installing mimemagic (0.3.8), and Bundler cannot continue.
Make sure that `gem install mimemagic -v '0.3.8'` succeeds before bundling.
```
Updating only this gem could work but it causes licensing issues as well, as its license since 4.0 has changed from MIT to GPL2.
[Here link to great post explaining whole situation](https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1)

Rails adresses this issue in version 5.2.5 
Indeed after updating to 5.2.5 `bundle install` is successfull.

### Steps to reproduce
rails version 5.2.4.5
run `bundle install `

**Comment by javierm** [comment]
@jakrzus We addessed this issue in pull requests #4439 and #4444.

MImemagic yanked all 0.3.x versions but then released more versions and [version 0.3.8 seems to be up](https://rubygems.org/gems/mimemagic/versions/0.3.8) :thinking:.

Even if Rails doesn't depend on mimemagic anymore, we still depend on it because we use paperclip, so updating Rails would not solve the problem.

Could you paste the specific error you get when trying to install mimemagic? :pray: Maybe we can help you then :thinking:.

**Comment by jakrzus** [comment]
@javierm  thanks for replying.

 The error i get is:

```
Fetching mimemagic 0.3.8
Installing mimemagic 0.3.8 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jakubkrzus/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mimemagic-0.3.8/ext/mimemagic
/Users/jakubkrzus/.rbenv/versions/2.6.6/bin/ruby -rrubygems /Users/jakubkrzus/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rake-13.0.3/exe/rake
RUBYARCHDIR\=/Users/jakubkrzus/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/mimemagic-0.3.8
RUBYLIBDIR\=/Users/jakubkrzus/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/mimemagic-0.3.8
rake aborted!
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml",
"/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-types package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.

Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/jakubkrzus/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/mimemagic-0.3.8 for inspection.
Results logged to /Users/jakubkrzus/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/mimemagic-0.3.8/gem_make.out

An error occurred while installing mimemagic (0.3.8), and Bundler cannot continue.
Make sure that `gem install mimemagic -v '0.3.8'` succeeds before bundling.

In Gemfile:
  invisible_captcha was resolved to 1.1.0, which depends on
    rails was resolved to 5.2.4.5, which depends on
      activestorage was resolved to 5.2.4.5, which depends on
        marcel was resolved to 0.3.3, which depends on
          mimemagic
```
### Solution
My workaroud with current rails **5.2.4.5** was copying manually `freedesktop.org.xml` to  `usr/local/share/mime/packages/freedesktop.org.xml`

As I said before, with rails updated to **5.2.5** bundle install was successful without any workarounds

**Comment by javierm** [comment]
@jakrzus Does it work if you install `shared-mime-info` (installed by default in most GNU/Linux distributions)? That package provides `/usr/local/share/mime/packages/freedesktop.org.xml`.

> As I said before, with rails updated to 5.2.5 bundle install was successful without any workarounds

Both `paperclip` and `caxlsx` depend on `mimemagic`, so even if `bundle install` was successful (not sure why it was successful, though :thinking:) you'll still need the `freedesktop.org.xml` file.

**Comment by javierm** [comment]
@jakrzus We've updated the README to include the `shared-mime-info` dependency. Let us know if you still have this issue after installing it!

**Comment by jakrzus** [comment]
I use macOS Big Sur 11.2.3
I had to copy the `freedesktop.org.xml` file manually, because `brew install shared-mime-info` was failing.
After your suggestion i deleted the file and tried again with 
`HOMEBREW_NO_AUTO_UPDATE=1 brew install shared-mime-info` 
This time with `HOMEBREW_NO_AUTO_UPDATE=1` installation was successful, and the `bundle install` issue is gone. Thanks for addressing it in README.

**Comment by rpepe23** [comment]
sudo apt-get update
sudo apt-get install shared-mime-info  
gem install mimemagic -v '0.4.3' --source 'http...'

**Comment by javierm** [comment]
@rpepe23 Version 1.5.0 no longer depends on mimemagic (since commit 7212657c0), so installing it shouldn't be necessary anymore :thinking:.
