### ISSUE TITLE
postgresql version upgrade

### ISSUE THREAD

**Issue by raoulkramer** [consul/consul#4477]
Hi all,

I read on the website https://www.postgresql.org/

> Additionally, this is the final release of PostgreSQL 9.5. If you are running PostgreSQL 9.5 in a production environment, we suggest that you make plans to upgrade.

Would it be an idea to upgrade de postgres version?

### README.md
41. Prerequisites: install git, Ruby 2.6.6, CMake, pkg-config, shared-mime-info, Node.js and PostgreSQL **(>=9.4)**.

### docker-compose.yml
8.    image: **postgres:9.4.5**

Thanks!

**Comment by javierm** [comment]
@raoulkramer Thanks for reporting! I've opened #4478 to solve it.
