### ISSUE TITLE
systemctl start consul not success

### ISSUE THREAD

**Issue by edidada** [consul/consul#4485]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
centos 7 systemclt start consul

ExecStart=/usr/bin/consul agent -server -bootstrap-expect 1 -ui -bind 10.23.29.39 -config-dir=/etc/consul.d/  -client 0.0.0.0

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:
problem

### Current Behavior
[comment]: # (Describe what actually happened.)
sysstemctl start consul
not success

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
systemctl start consul
success

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
Hi, @edidada :smile:.

I think you're looking for the [Hashicorp's Consul repository](https://github.com/hashicorp/consul).

Cheers!
