### ISSUE TITLE
Error 422 when try to add existing related content

### ISSUE THREAD

**Issue by decabeza** [consul/consul#4498]
### Description

Error 422 when try to add existing related content.

### Steps to reproduce

1. Visit a relatable content, for example the [proposal one](https://demo.consulproject.org/proposals/1-strategic-plan-for-a-100-green-city).
2. Clic on "Add related content" and add other proposal URL, for example [proposal two](https://demo.consulproject.org/proposals/2-the-right-to-play-for-a-more-child-friendly-city).
3. Try to add the same link again.

The page generates a 422 Error.

### Expected behaviour

An alert message with "The related content you are adding already exists." or something similar. 😌

**Comment by javierm** [comment]
Thanks for reporting! :pray: It looks like this bug was introduced in commit 7ca55c44e04. Before that commit, a message saying "You added a new related content" was shown, but (as expected) the related content wasn't added twice.
