### ISSUE TITLE
Translation override can't be changed if done the second time

### ISSUE THREAD

**Issue by cmllr** [consul/consul#4540]
### Description

*Type*: Bug

The user defined text blocks (/admin/site_customization/information_texts) cannot be updated if there is already a text value saved in the database.

### Current Behavior

1. Adjust the value using the textboxes
2. Save
3. The value is changed
3. Try to adjust it again
4. Save
5. The value is not changed

### Expected Behavior

The value should be updated after the second save aswell.

### Steps to reproduce

1. Adjust the value using the backend textboxes
2. Save
3. Change text again
4. Save
5. The value is not changed

Version: 1.3.1

**Comment by javierm** [comment]
@cmllr Thanks for reporting :pray:.

I can confirm this bug, but only when the second time the translation is updated to its original value. Updating it to other values works properly. Could you confirm that's the behavior you're getting?

**Comment by cmllr** [comment]
hey @javierm thank you for responding! That is exactly the issue we faced!
