### ISSUE TITLE
How can I prevent the users from voting until they are on census?

### ISSUE THREAD

**Issue by alexbg** [consul/consul#4576]
Hello everyone.

I am trying a fresh new installation of consul and users are able to support proposals and participate in final voting even when they are not on census. According to the documentation, they shouldn't be able to do so: 
[https://consulproject.org/docs/consul_participatory_budgeting_es.pdf](https://consulproject.org/docs/consul_participatory_budgeting_es.pdf)

> 6.- FASE DE VOTACIÓN
• En la fase de votación final, todas las personas empadronadas en la ciudad
mayores de 16 años pueden votar proyectos para toda la ciudad y para un
distrito concreto a su elección. Se puede votar aunque no se haya
participado anteriormente y no es necesario ser residente en un distrito
para poder apoyar o votar los proyectos de ese distrito.

Thanks in advance.

**Comment by Senen** [comment]
Hi @alexbg, 

New CONSUL installations use a feature called "Skip user verification" by default. This feature is helpful for instances that do not have a census web service to connect. When this feature is enabled, users are not required to be verified to participate.
 
To enable the remote census integration, you will have to disable the feature "Skip user verification" and enable and configure the "Configure  connection to the remote census (SOAP)". You can change these settings through the Administration panel > Settings > Global settings > Features tab.

You can find technical documentation regarding this topic [here](https://docs.consulproject.org/docs/english-documentation/features/census_configuration). It's also available in [Spanish](https://docs.consulproject.org/docs/spanish-documentation/features/census_configuration).

I hope this helps!

**Comment by alexbg** [comment]
it is fixed, thank you so much.
