### ISSUE TITLE
can't modify translation text

### ISSUE THREAD

**Issue by Ourithi** [consul/consul#4584]
### User Story

I would like the french translation files to translate the "ahora no mismo..." displayed on the main page in case of no_item

### Why is this Needed?

This is needed because the translation is incomplete

### Current Behavior
Currently there is no translation for the case where no proposal/debate/process is active

I modified the /es/general.yml file, the /fr/general.yml file and added a /customs/es/general.yml file and despite that the main page still displays the spanish text instead of the french one. How do I fix that?

**Comment by javierm** [comment]
Hi, @Ourithi :smile:. Could you link to the code of the branch where you're trying to change these translations?

**Comment by Ourithi** [comment]
> Hi, @Ourithi 😄. Could you link to the code of the branch where you're trying to change these translations?

I'm not sure if that's what you want but here: https://github.com/consul/consul/blob/2b8330691cab319a50658dac82dc7060d39ff4ca/config/locales/es/general.yml
it's on lines 881-883

**Comment by javierm** [comment]
Hi, @Ourithi.

For this specific text, you can edit it in the admin section. You can try it out in [the official demo custom information texts section](https://demo.consulproject.org/admin/site_customization/information_texts?tab=welcome). The needed username and password appear at the top of the screen; feel free to sign in and experiment.

If at a certain point you'd like to change things which cannot be changed from there, check the [Deploys with Capistrano](https://github.com/consul/installer#deploys-with-capistrano) section in the installer's README (the screencast is a bit outdated; sorry for that! :pray:). Changing the code directly on the production server won't work.

Hope that helps!

**Comment by javierm** [comment]
Continuing the conversation in #4591.
