### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by Ourithi** [consul/consul#4591]
I'm trying to complete the french translation of consul but modifying the yml files does squat. Does anybody have a detailed solution as to how I can finish the translation AND implement it in my production server?

Thanks in advance

PS: I'm running on debian 10 buster

**Comment by javierm** [comment]
Hi, @Ourithi.

Did you try what I mentioned in issue #4584?

> check the  [Deploys with Capistrano](https://github.com/consul/installer#deploys-with-capistrano) in the installer's README (the screencast is a bit outdated; sorry for that! :pray:). Changing the code directly on the production server won't work.
>
> Hope that helps!

**Comment by javierm** [comment]
If you're interested in contributing your translations to the whole CONSUL community, you can add your translations the [CONSUL Crowdin project](https://crowdin.com/project/consul) and they will be included in the next CONSUL version :tada:.

**Comment by javierm** [comment]
Closing due to lack of response.
