### ISSUE TITLE
Read a Policy by Name failed

### ISSUE THREAD

**Issue by hhandy** [consul/consul#4644]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
when i query a policy by it's name, I want to get a 200 response from consul, but give me 500

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)
I want to update my policy, but I don't konw the policy, I am only have the name for the policy , so I need get the policy info by it's name. 
I do this through the following request： /acl/policy/name/:name

https://www.consul.io/api-docs/acl/policies

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
this is the error message:
![image](https://user-images.githubusercontent.com/44293767/129005835-396e493b-1b2a-49a4-8e4c-30998acc0742.png)

but i can find it in my policy list:
![image](https://user-images.githubusercontent.com/44293767/129006397-cbc62851-c92d-4448-bf0d-c7b7344b9fae.png)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
I can get the policy infomation by /acl/policy/name/:name api 

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
you can create a policy and read it by /acl/policy/name/:name api
1. create a pyload file in your pc
2. create a policy use this pyload file
3. read the policy by name

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
my consul version is 1.6.9
![image](https://user-images.githubusercontent.com/44293767/129008134-551abcca-c817-4672-8f97-e0228c560614.png)

**Comment by javierm** [comment]
@hhandy I think you're looking for the [Hashicorp's Consul](https://github.com/hashicorp/consul) repo :wink:, which is not related to this project (although unfortunately we share the same name).
