### ISSUE TITLE
Error when combining investments advanced search with filtering

### ISSUE THREAD

**Issue by microweb10** [consul/consul#4659]
### Description

An error is raised when combining advanced search and filtering for budget investments.

### Steps to reproduce

1. Visit the [list of investments](https://demo.consulproject.org/budgets/1/investments?heading_id=1) for a participatory budget.
2. Click on advanced search
3. Fill the field **With the text** with any text
4. Select **Last 24 hours** from the selector **By date**
5. Click button **Filter**
6. Select **Not unfeasible** from the selector **Filtering projects by**

### Screenshot
![Captura de pantalla 2021-08-13 a las 10 54 22](https://user-images.githubusercontent.com/942995/129302852-29ab0123-7e77-4f20-8d82-86820e058bfc.png)

**Comment by javierm** [comment]
Was wondering about how to get this exception when we saw it yesterday in the demo. Thanks for reporting! :pray:

**Comment by microweb10** [comment]
That was actually me testing in the demo 😛
