### ISSUE TITLE
Inject tags in SRV Records

### ISSUE THREAD

**Issue by ardichoke** [consul/consul#4700]
### User Story

As a Consul user, operating a service, I want to deploy a new cluster running an updated version of my software which clients discover using SRV records. Unfortunately, the client uses hardcoded names for the service (`_service._tcp`). By being able to add a version tag to a service, and having it injected into the SRV records, like what happens with A records, I'm able to do service discovery in a more granular way.

### Why is this Needed?

Currently, SRV records for a service can only be separated out by changing the service name. This is not possible in some cases (for instance, Puppet uses `_x-puppet._tcp.[srv_domain]` for service discovery, and there is no way to change anything other than the [srv_domain] portion). Consul already allows for getting A records in the form of <service><.tag>.service<.domain>, doing the same with automatic SRV records would bring this into parity with the A records and allow for services to separate clusters.

### Description

*Type*: Feature

### Current Behavior
Tags are completely ignored in the context of SRV records, making it impossible to separate out hosts with different tags for the same service.

### Definition of Done
Tags can be used to discover a specific tagged subset of hosts providing a service via SRV records.

**Comment by javierm** [comment]
@ardichoke Not sure what you're talking about :thinking:. Could it be you're looking for [Hashicorp's Consul](https://github.com/hashicorp/consul)?

**Comment by ardichoke** [comment]
... wow.... yeah, this is what happens when I try filing an issue while also debugging something. Sorry.
