### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by tisserapac** [consul/consul#4724]
Hello I would like to have my language Thai added to CONSUL

**Comment by Senen** [comment]
Hi @tisserapac 👋🏼 , I've just added [the Thai 🇹🇭 language to the Crowdin platform.](https://crowdin.com/project/consul/th). You can add translations there.

If you need help, feel free to ask.

**Comment by javierm** [comment]
@tisserapac Feel free to start using Crowdin to add translations and, as Senén said, feel free to ask if you need help.

Looking forward to adding the Thai language to CONSUL!
