### ISSUE TITLE
Umbrales de propuestas

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#473]
- [x] Cuando se llega la 2% (53.726) del Censo, a los 45 días empieza la votación final.
- [x] Si se ha llegado al 2%, ya no se pueden retirar apoyos
- [x] Durante los primeros 30 días, después de haber llegado al 2% de apoyos, si otra propuesta llega al 2% de apoyos, será votada el mismo día que la primera propuesta.
- [x] Pasados 12 meses la propuesta caduca y no puede recibir más apoyos - poner variable en Settings

**Comment by ManjiChiba** [comment]
Mi opinión es que las propuestas no deberían de caducar.
Por cierto, 2 semanas para el periodo de votaciones... me parece totalmente insuficiente, es más, no entiendo un periodo tan sumamente corto, precisamente, la gran ventaja de una Democracia Participativa es la deslocalización y atemporalidad del voto (si le quitamos una de esas ventajas....).

**Comment by voodoorai2000** [comment]
Un año para marcar una propuesta como caducada parece razonable, pero es una variable que podemos modificar en cualquier momento si las propuestas necesitan más tiempo para ser apoyadas.

El periodo de votación será sólo de una semana, porque también se hará simultáneamente de forma física (en urnas por toda la ciudad, ese es el plan) Pero, antes de esta votación final, habrá un proceso deliberativo específico para estas propuestas de 45 días. 

Aquí está la información detallada del proceso: https://decide.madrid.es/proposals_info#i

**Comment by ManjiChiba** [comment]
Ah, vale, no sabía lo de los 45 días entre que se llega al % exigido y el periodo de 1 semana para la votación, aunque... talvez sería una buena idea, que fueran 2 semanas para el periodo de votación, pero que SOLO se pueda hacer de forma física durante la 1ª semana, mientras que telemáticamente puedas hacerlo durante las 2 (sugerencia).
Daría más posibilidades a que puedan participar más ciudadanos (1 semana para la parte de votación física si me parece razonable y más tiempo, supondría muchos gastos).
Así, si alguien me pregunta le puedo informar adecuadamente.
Por otra parte... talvez se debería de replantear la exigencia del 2% para pasar a la fase de votación (menor incluso para propuestas municipales).
Lo vienen reclamando muchos ciudadanos en diferentes propuestas.
Si los ciudadanos ven que alguna propuesta se vota (e incluso, sale adelante), por insignificante que esta sea, seguro que se van animando a usar este novedoso sistema de Democracia Participativa, pero si sólo ven propuestas repetidas hasta el infinito y que ninguna prospera...
Llegar a que una propuesta actualmente, (no digo que en un futuro no se debieran de revisar al alza un límite de apoyos pre-establecido), llege tan siquiera a los 10.000 apoyos está resultando una odisea, no digamos ya los 50.000 y tantos mil.
Otra cosa sería exigir un quorum mínimo en la fase de votación (cosa que no vería mal).
En fin, sólo es una opinión, no se lo tomen a mal.

**Comment by unsegnor** [comment]
Yo también creo que lo del 2% es una barrera enorme, sobretodo al principio. Quizá salga alguna prouesta si se publicita en los mass media pero entonces serán éstos los que estarán decidiendo. ¿Por qué no usamos muestras para la primera fase? Por ejemplo: Se hace llegar la propuesta a 100 personas del censo elegidas al azar y si más de la mitad la apoyan entonces pasa a la siguiente fase.

**Comment by ManjiChiba** [comment]
Una alternativa es mejor que ninguna, pero le veo grandes inconvenientes a lo que comentas.
No tardarían ni 0,0 en saltar a la yugular los falangistas de turno a despotricar, de que si esas 100 personas no se han escogido realmente al azar y haber como demuestras lo contrario, no se, eso lo veo complicado.
Por otra parte, lo que comentas de los Mass Media... toda la razón, se les dotaría de más poder del que ya tienen (y no precisamente para tirar flores a Ahora Madrid o Podemos).
Sin embargo... si, se baja el umbral... bastaría con que una gran parte de los votantes informados de 2 o 3 grupos políticos apoyaran una propuesta para que se pudiera llevar a referendum, legitimando así propuesta que puedan hacer madrileños y que lleve a cabo el Ayto "porque se lo han ordenado los ciudadanos y no por gusto".
Es una buena forma de cubrirse las espaldas "hago lo que piden los madrileños, no lo que quiero".

**Comment by voodoorai2000** [comment]
Gracias @unsegnor, @ManjiChiba por vuestros comentarios.

Ha llegado el momento de empezar a archivar propuestas ya que llevan en la web un año y otras han conseguido superar el umbral y llegar a la siguiente fase. A ver que tal avanza el asunto.

Implementado en https://github.com/consul/consul/pull/1213 y https://github.com/consul/consul/pull/1206
