### ISSUE TITLE
Be able to see all budgets on the valuation page

### ISSUE THREAD

**Issue by microweb10** [consul/consul#4770]
Dear CONSUL developer team,

I think it would be interesting that you consider backporting this commit into CONSUL
https://github.com/democrateam/consul/commit/c916fb7906649fe064de0ddb7cd03a3cbd7aebbb

Cheers!

**Comment by Senen** [comment]
Hi @ microweb10, I'm closing this issue as it's solved via #5061, feel free to re-open it if I'm wrong!
