### ISSUE TITLE
Registration without E-Mail possible

### ISSUE THREAD

**Issue by janrakete** [consul/consul#4779]
### User Story
As an admin, I want to have email address on registration mandatory if no SMS verification is set.

### Why is this Needed?
Currently I can register without email address. This makes no sense, as long as SMS verification is not set up.

### Description
*Type*: Bug

### Current Behavior
If I do not enter an email address during registration, I can still submit the form. It then says: https://community.consulproject.org/uploads/default/optimized/1X/3d9c00fcf2cfd07bb657c62ef78f8999b3b43beb_2_690x283.png
which makes no sense. If I try registration without email again, “500 - internal server” error appears. I know that there is an SMS verification also. But if this is not configured I guess It would make sense that e-mail is mandatory.

### Expected Behavior
If I provide no email address and SMS verification is not set up, I can not submit the registration.

### Steps to reproduce
1. Open registration form
2. Leave email address input field free
3. Register

**Comment by iraline** [comment]
I can work on a fix for this
