### ISSUE TITLE
Reduce the number of SCSS files

### ISSUE THREAD

**Issue by decabeza** [consul/consul#4785]
### User Story

Recently 30 SCSS files divided into folders have been added:

```
app/assets/stylesheets/admin/budget_groups/form.scss
app/assets/stylesheets/admin/budget_headings/form.scss
app/assets/stylesheets/admin/budget_phases/form.scss
app/assets/stylesheets/admin/budget_phases/phases.scss
app/assets/stylesheets/admin/budgets/actions.scss
app/assets/stylesheets/admin/budgets/drafting.scss
app/assets/stylesheets/admin/budgets/form.scss
app/assets/stylesheets/admin/budgets/groups_and_headings.scss
app/assets/stylesheets/admin/budgets/heading_mode.scss
app/assets/stylesheets/admin/budgets/help.scss
app/assets/stylesheets/admin/budgets/index.scss
app/assets/stylesheets/admin/budgets/links.scss
app/assets/stylesheets/admin/budgets/show.scss
app/assets/stylesheets/admin/budgets_wizard/headings/group_switcher.scss
app/assets/stylesheets/admin/budgets_wizard/headings/index.scss
app/assets/stylesheets/admin/budgets_wizard/creation_step.scss
app/assets/stylesheets/admin/budgets_wizard/creation_timeline.scss
app/assets/stylesheets/admin/machine_learning/help.scss
app/assets/stylesheets/admin/machine_learning/scripts.scss
app/assets/stylesheets/admin/machine_learning/setting.scss
app/assets/stylesheets/admin/machine_learning/settings.scss
app/assets/stylesheets/admin/machine_learning/show.scss
app/assets/stylesheets/admin/poll/questions/filter.scss
app/assets/stylesheets/admin/settings/featured_settings_form.scss
app/assets/stylesheets/admin/settings/featured_settings_table.scss
app/assets/stylesheets/admin/stats/sdg/goal.scss
app/assets/stylesheets/admin/action.scss
app/assets/stylesheets/admin/menu.scss
app/assets/stylesheets/admin/search.scss
app/assets/stylesheets/admin/table_actions.scss
```

While I understand the organization, I think this becomes more difficult to manage, especially for looking up which class to overwrite when adding custom CSS.

I also see that there is a lot of repeated content and classes that could be merged, making it easier to customize. As an example:

Content of `app/assets/stylesheets/admin/budget_groups/form.scss`:

```
.admin .budget-groups-form {
  @include full-width-form;
}
```

Content of `app/assets/stylesheets/admin/budget_headings/form.scss`:

```
.admin .budget-headings-form {
  @include full-width-form;
}
```

These two could be merged in a single file:

```
.admin .budget-groups-form,
.admin .budget-headings-form {
  @include full-width-form;
}
```

Or even use the same class for both:
```
.admin .budget-form {
  @include full-width-form;
}
```

Anyway, does CONSUL need a separate file for three lines of code? I honestly think not.

### Why is this Needed?

Make it easier for forks to customize styles.

### Expected Behavior

Use fewer files while maintaining the organization, e.g.:

Merge:

```
app/assets/stylesheets/admin/machine_learning/help.scss
app/assets/stylesheets/admin/machine_learning/scripts.scss
app/assets/stylesheets/admin/machine_learning/setting.scss
app/assets/stylesheets/admin/machine_learning/settings.scss
app/assets/stylesheets/admin/machine_learning/show.scss
```

In to:

`app/assets/stylesheets/admin/machine_learning.scss`

**Comment by javierm** [comment]
Hi, @decabeza :smile:.

We're trying to have consistent criteria regarding when to create a new SCSS file and the contents it should have.

What we've come up with so far is: there's one SCSS file per Ruby view/component file, and the HTML class in the view/component file resembles the filename as much as possible.

Feel free to suggest any other consistent way to handle these files and we'll consider it.

Of course, in your custom files, you can organize the code as you'd like, for example, in the custom.scss file you could write:

```scss
.admin .budget-groups-form,
.admin .budget-headings-form {
  // Overwrite default styles here
}
```

This example could be solved if we used consistent structure and styles in all the admin forms :sweat_smile:, so we could write something like:

```scss
.admin main > form { // Or whatever selector
  @include full-width-form; // Or whatever rules
}
```

And then all sections would look the same way with little code :tada:. Pull requests making the administration more consistent so we can remove duplication in the HTML/SCSS code are welcome, although I know it's a lot of work :relieved:.

**Comment by javierm** [comment]
Closing since there was no response and, as mentioned earlier, we're aiming to have one SCSS file per Ruby view/component file, at least for the new code. Might change our minds in the future if at some point there are more disadvantages than advantages, but it hasn't been the case so far.
