### ISSUE TITLE
Full background images in Participatory Budgets

### ISSUE THREAD

**Issue by decabeza** [consul/consul#4786]
### User Story

It seems that after the changes introduced in https://github.com/consul/consul/commit/9cc4d5272356b4acef4f46b55345a1e0af3440c2 a margin is added to all elements, including those that should fill the entire background width.

I think CONSUL could keep the Foundation `.row` and `.row.expanded` classes that already allowed to do this.

_Foundation classes already allow this effect._

<img width="1680" alt="foundation" src="https://user-images.githubusercontent.com/631897/158222396-b5556f56-b583-480d-a4ad-4a82022e9423.png">

This change affects the Participatory Budget header, but also any other section that a fork wants to customize with this same full background image "effect".

### Why is this Needed?

Allow to use a full background image in Participatory Budgeting as before, and display it correctly.

### Steps to reproduce

1. Add a new image from https://demo.consulproject.org/admin/budgets/1/edit.
2. Visit https://demo.consulproject.org/budgets where image is duplicated, and not use full width.

### Current Behavior
<img width="1679" alt="before" src="https://user-images.githubusercontent.com/631897/158020246-1bbfdbc7-d7c6-4833-a8d9-45e9503883dd.png">

### Expected Behavior
<img width="1680" alt="after" src="https://user-images.githubusercontent.com/631897/158020249-679b0849-baed-4a28-8a21-6d707a1dbe7c.png">

**Comment by javierm** [comment]
Hi, @decabeza :smile:.

You say "as before", so I take it it worked at a certain point? :thinking: Do you know when it stopped working?

Thanks!

**Comment by decabeza** [comment]
I've updated the issue description.

**Comment by iraline** [comment]
I can work on this issue
