### ISSUE TITLE
HTML injection possible in search results. Vulnerability.

### ISSUE THREAD

**Issue by TomClive** [consul/consul#4793]
We have recently had a penetration test completed and it was raised as a medium severity issue that it was possible to inject HTML into search results throughout the site.

Having tested this on our site we have checked and note that this also happens on the ConsulProject demo site. Please see the link below:

https://demo.consulproject.org/debates?utf8=%E2%9C%93&search=%3Ca+href+%3D%22https%3A%2F%2Fgoogle.com%22%3E%3Ch1%3E%3Ci%3Einjection%3C%2Fi%3E%3C%2Fh1%3E%3C%2Fa%3E

Please see extract below from our penetration test.

> **1.HTML Injection**
> 
> Status Open MEDIUM
> 
> **Description**
> 
> Throughout  the  testing  window  it  was  possible  to  inject  HTML  code  into  the  search  function of  a project/process.  After  the  HTML  was  injected  ,  the  desired  output was  rendered.  As  such,  an opportunistic  attacker could trick end users into visiting a maliciously crafted link to view their HTML.As  mentioned  above,  an  injection  point  was  identified,  this  injection  point  was  within  the  search section of the application on the search parameter.
> 
> After this was sent  to the server, the code was rendered. Due to this, if an attacker were able to trick a user into clicking a maliciously crafted link, they would fall subject to the attacker’s desire.
> 
> HTML Injection, similar to  Cross Site-Scripting (XSS), is  the  presence of  injecting malicious code  into the application for a desired outcome.  Unlike XSS, JavaScript does  not execute, rather images can be rendered from outside  sources, new page elementscreated to  potentially phish  application users  or malicious content  could  be  injected  to  impact  the  brand  reputation.    Despite  the  code  rendering, throughout  the testing phase, it was not possible to get JavaScript executing.HTML injection, as mentioned previously, could be used to incorporate malicious components into the application. If successfully introduced,  it could  be possible for an attacker to phish  for credential sets or create divisions  to  negatively impact the  application logic. All of  the  previously  mentioned  could result in negative impact.
> 
> **Recommendation**
> 
> Appropriate input sanitisation should occur to ensure only expected characters are being inserted into the application. ( https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/11-Client-side_Testing/03-Testing_for_HTML_Injection )
> 
> Further, another good security practice would be to encode the data on output  so if an  attacker  were  able  to  bypass  the  input  restrictions,  the  data  would  not  render  or  behave  as intended.

**Comment by javierm** [comment]
@TomClive Thanks for reporting! The fix seems simple enough; we'll look into it.
