### ISSUE TITLE
Error 500 on Admin system emails

### ISSUE THREAD

**Issue by decabeza** [consul/consul#4812]
### Description

Error 500 `undefined method "name" for nil:NilClass` on Admin system emails.

### Steps to reproduce
1. Visit any investment and create a comment, for example: https://demo.consulproject.org/budgets/1/investments/5.
2. Visit https://demo.consulproject.org/admin/system_emails and click "View" on "New evaluation comment" email.
3. Error 500! 😱 

### Notes

These valuation example comment is created from `app/controllers/admin/system_emails_controller.rb`

```
when "evaluation_comment"
  load_sample_valuation_comment
end
```

```
def load_sample_valuation_comment
  comment = Comment.where(commentable_type: "Budget::Investment").last
  if comment
    @email = EvaluationCommentEmail.new(comment)
    @email_to = @email.to.first
   else
    redirect_to admin_system_emails_path, alert: t("admin.system_emails.alert.no_evaluation_comments")
  end
end
```

Although, I think the real problem is from the email view `app/views/mailer/evaluation_comment.html.erb` itself.

Is using `<%= t("mailers.evaluation_comment.hi") %> <strong><%= @email_to.name %></strong>` but I think there isn't any attribute `name` on database related with users. 🤔

**Comment by javierm** [comment]
@decabeza Thanks for reporting! :pray:

I think it crashes when the investment which received the last comment doesn't have valuators/valuator groups/administrator associated :thinking: (or only the one who made the comment). In that case, `@email.to` returns an empty array, `@email_to = @email.to.first` returns `nil` and so `@email_to.name` crashes.

So I guess we should make sure the sample comment would have recipients, or maybe consider that `@email_to` might be `nil` :thinking:.

By the way, the `name` method is defined in the `User` model:

```ruby
  def name
    organization? ? organization.name : username
  end
```
