### ISSUE TITLE
Error 422 when creating admin Tags

### ISSUE THREAD

**Issue by microweb10** [consul/consul#4829]
### Description
If trying to create a Tag from the admin panel without a name, an error 422 is raised.

### Current Behavior
Error 422 raised.

### Expected Behavior
Form validation saying the name cannot be blank 🤔 

### Steps to reproduce

1. Visit the [CONSUL demo](https://demo.consulproject.org/?locale=en)
2. [Log in](https://demo.consulproject.org/users/sign_in) with admin user
3. Visit the [admin Tags page](https://demo.consulproject.org/admin/tags)
4. Click button/link "Create topic"

**Comment by joaoGabriel55** [comment]
I can take a look @microweb10

**Comment by joaoGabriel55** [comment]
I got to simulate this error, I will develop a solution for it

**Comment by joaoGabriel55** [comment]
Waiting for review
