### ISSUE TITLE
Error uploading large dimensions images

### ISSUE THREAD

**Issue by decabeza** [consul/consul#4830]
### Description

There seems to be an error when uploading large images but no error message appears.

### Steps to reproduce

1. Login on [CONSUL demo](https://demo.consulproject.org/users/sign_in) page.
2. Change the [Image maximum size](https://demo.consulproject.org/admin/settings#tab-images-and-documents) setting to **5Mb** for example.
3. Try to [create a Poll](https://demo.consulproject.org/admin/polls/new) with a large dimensions image.

I've tested with several images with the same error like [this image](https://images.pexels.com/photos/670261/pexels-photo-670261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260) with a dimensions of **3938x3024** and a size of **4.04Mb**.

### Screenshots
![error_image](https://user-images.githubusercontent.com/631897/168915171-27633832-6362-4d0e-b8bf-b77cc983fd72.png)

**Comment by javierm** [comment]
It looks like the demo server was configured before we solved this issue in the installr.

I've updated the nginx configuration on the demo server.

Closed via consul/installer#111.

**Comment by decabeza** [comment]
Oh, I hadn't thought of that configuration. Thanks! 🙏
