### ISSUE TITLE
Group of evaluators doesn't work as expected

### ISSUE THREAD

**Issue by decabeza** [consul/consul#4860]
### Description

It's possible to group valuators to make it faster to assign investment projects to several valuators at the same time. The problem is that the investments assigned to a valuators group don't appear in the Valuation interface.

### Steps to reproduce
1. Create a new valuator group from https://demo.consulproject.org/admin/valuator_groups.
2. Add a new Valuator and include him inside the group https://demo.consulproject.org/admin/valuators/.
3. Change the Budget phase to "Valuating projects" https://demo.consulproject.org/admin/budgets/1/edit.
4. Assign any investment to the new valuator group https://demo.consulproject.org/admin/budgets/1/budget_investments/19/edit#classification.
5. Mark "Show to valuators" checkbox from admin https://demo.consulproject.org/admin/budgets/1/budget_investments.
6. Visit Valuation interface https://demo.consulproject.org/valuation and nothing appears.

### Definition of Done

The valuation interface should display all the investments that have been assigned to the evaluator individually, as well as those assigned to all the groups to which the evaluator belongs.

**Comment by joaoGabriel55** [comment]
Hi @decabeza! I can take a look at it.
