### ISSUE TITLE
Installation with docker in local ubuntu 20

### ISSUE THREAD

**Issue by johnfelipe** [consul/consul#4884]

**Comment by javierm** [comment]
@johnfelipe I'm afraid I don't understand the question :thinking:. Could you elaborate a bit?

Thanks!

**Comment by johnfelipe** [comment]
i want to install consul in ubuntu 20, in development and later in
production but using docker, where is readme.md or cheatsheet for to that
docker run or docker compose?

**Comment by johnfelipe** [comment]
i found this
https://github.com/consul/docs/blob/master/es/installation/docker.md
may be is that one?

**Comment by javierm** [comment]
@johnfelipe That's the document, yes.

That document is also available in the documentation page: https://docs.consulproject.org/docs/spanish-documentation/introduction/servers/docker

**Comment by johnfelipe** [comment]
```
root@ubuntu20:~/consul# POSTGRES_PASSWORD=123456789. docker-compose run app rake db:create db:migrate
Creating consul_app_run ... done
+ stat -c %u /var/www/consul/Gemfile
+ USER_UID=0
+ stat -c %g /var/www/consul/Gemfile
+ USER_GID=0
+ export USER_UID
+ export USER_GID
+ usermod -u 0 consul
+ groupmod -g 0 consul
+ usermod -g 0 consul
+ chown -R -h 0
chown: cannot access '': No such file or directory
+ chgrp -R -h 0
chgrp: cannot access '': No such file or directory
+ set -e
+ [ -f tmp/pids/server.pid ]
+ /usr/bin/sudo -EH -u consul rake db:create db:migrate
Rails Error: Unable to access log file. Please ensure that /var/www/consul/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /var/www/consul/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
rake aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /var/www/consul/log/delayed_job.log
/var/www/consul/config/initializers/delayed_job_config.rb:16:in `new'
/var/www/consul/config/initializers/delayed_job_config.rb:16:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:662:in `load_config_initializer'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:361:in `initialize!'
/var/www/consul/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/www/consul/log/delayed_job.log
/var/www/consul/config/initializers/delayed_job_config.rb:16:in `new'
/var/www/consul/config/initializers/delayed_job_config.rb:16:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:170:in `instrument'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:662:in `load_config_initializer'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `each'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `each'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:361:in `initialize!'
/var/www/consul/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
ERROR: 1

```

how solve that step?

**Comment by johnfelipe** [comment]
Anyone?

**Comment by johnfelipe** [comment]
> with this step
> 
> `POSTGRES_PASSWORD=123456789. docker-compose run app rake db:create db:migrate`
> 
> show this error
> 
> ```
> root@ubuntu20:~/consul# POSTGRES_PASSWORD=123456789. docker-compose run app rake db:create db:migrate
> Creating consul_app_run ... done
> + stat -c %u /var/www/consul/Gemfile
> + USER_UID=0
> + stat -c %g /var/www/consul/Gemfile
> + USER_GID=0
> + export USER_UID
> + export USER_GID
> + usermod -u 0 consul
> + groupmod -g 0 consul
> + usermod -g 0 consul
> + chown -R -h 0
> chown: cannot access '': No such file or directory
> + chgrp -R -h 0
> chgrp: cannot access '': No such file or directory
> + set -e
> + [ -f tmp/pids/server.pid ]
> + /usr/bin/sudo -EH -u consul rake db:create db:migrate
> Rails Error: Unable to access log file. Please ensure that /var/www/consul/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /var/www/consul/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
> rake aborted!
> Errno::EACCES: Permission denied @ rb_sysopen - /var/www/consul/log/delayed_job.log
> /var/www/consul/config/initializers/delayed_job_config.rb:16:in `new'
> /var/www/consul/config/initializers/delayed_job_config.rb:16:in `<top (required)>'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `block in load'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:170:in `instrument'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:662:in `load_config_initializer'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `each'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `instance_exec'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `run'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `each'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:60:in `run_initializers'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:361:in `initialize!'
> /var/www/consul/config/environment.rb:5:in `<top (required)>'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `block in require'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:337:in `require_environment!'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
> /usr/local/bundle/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
> /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> 
> Caused by:
> Errno::ENOENT: No such file or directory @ rb_sysopen - /var/www/consul/log/delayed_job.log
> /var/www/consul/config/initializers/delayed_job_config.rb:16:in `new'
> /var/www/consul/config/initializers/delayed_job_config.rb:16:in `<top (required)>'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `block in load'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:285:in `load'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/notifications.rb:170:in `instrument'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:662:in `load_config_initializer'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `each'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `instance_exec'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:32:in `run'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:61:in `block in run_initializers'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `each'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:50:in `tsort_each_child'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/initializable.rb:60:in `run_initializers'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:361:in `initialize!'
> /var/www/consul/config/environment.rb:5:in `<top (required)>'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `block in require'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:257:in `load_dependency'
> /usr/local/bundle/gems/activesupport-5.2.7.1/lib/active_support/dependencies.rb:291:in `require'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:337:in `require_environment!'
> /usr/local/bundle/gems/railties-5.2.7.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
> /usr/local/bundle/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
> /usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
> Tasks: TOP => db:create => db:load_config => environment
> (See full trace by running task with --trace)
> ERROR: 1
> ```
> 
> how solve that step?

i need help asap, for solve this and test your app

**Comment by johnfelipe** [comment]
Dear me again, tell me steps for solve latest reply, because I think is only remains for test your app

**Comment by javierm** [comment]
Hi, @johnfelipe.

Not sure it's related, but I see you're running the command as the root user :thinking:. Every step mentioned in the documentation should be run using a regular user.

**Comment by javierm** [comment]
By the way, I've just noticed you mentioned:

> i want to install consul in ubuntu 20, in development and later in production but using docker

Just wanted to let you know that currently Consul provides a Docker configuration meant mainly for development. People using it on production have had to change a few things (although we haven't received feedback about the specific changes they had to do).

**Comment by johnfelipe** [comment]
Can you share me markdown file with that configuration for production.
First I need to show this to stakeholders and later will be in production,
then I think will be important to know in this moment.

**Comment by johnfelipe** [comment]
> Hi, @johnfelipe.
> 
> Not sure it's related, but I see you're running the command as the root user 🤔. Every step mentioned in the documentation should be run using a regular user.

```
felipe@ubuntu20virgen:~/consul$ POSTGRES_PASSWORD=123456789. docker-compose run app rake db:create db:migrate
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[11086] Failed to execute script docker-compose

```

im using not root user and show me that permission warning
the how solve this?

**Comment by johnfelipe** [comment]
i update my stack docker for install with not root user and same issue like before:

```
felipe@ubuntu20virgen:~/consul$ POSTGRES_PASSWORD=123456789. docker-compose run app rake db:create db:migrate
Creating consul_app_run ... done
+ stat -c %u /var/www/consul/Gemfile
+ USER_UID=1000
+ stat -c %g /var/www/consul/Gemfile
+ USER_GID=1000
+ export USER_UID
+ export USER_GID
+ usermod -u 1000 consul
+ groupmod -g 1000 consul
+ usermod -g 1000 consul
+ chown -R -h 1000
chown: cannot access '': No such file or directory
+ chgrp -R -h 1000
chgrp: cannot access '': No such file or directory
+ set -e
+ [ -f tmp/pids/server.pid ]
+ /usr/bin/sudo -EH -u consul rake db:create db:migrate
FATAL:  password authentication failed for user "postgres"
Couldn't create 'consul_development' database. Please check your configuration.
rake aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "postgres"
/usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/connection_handling.rb:90:in `connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/database_tasks.rb:119:in `create'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/usr/local/bundle/gems/activerecord-5.2.8.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/airbrake-11.0.3/lib/airbrake/rake.rb:17:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
ERROR: 1

```

im in ubuntu 20, may be downgrade to 18?
or give me more steps for test

**Comment by javierm** [comment]
> i update my stack docker for install with not root user and same issue like before

Great! Note this is **not** the same issue you had before :wink:. Earlier it said `Unable to access log file`, while now it says `password authentication failed for user "postgres"`.

Not sure what's going on with the password :thinking:. Just in case, can you try running the command starting with `POSTGRES_PASSWORD=password` instead of `POSTGRES_PASSWORD=123456789.`?

**Comment by javierm** [comment]
> Can you share me markdown file with that configuration for production

Sorry, I'm afraid I've never used Docker on production. @muki @tonekk (sorry to bother you!) do you have any Docker configuration files for production which might be useful in this case?

**Comment by johnfelipe** [comment]
or link me another deployment documentation

**Comment by johnfelipe** [comment]
> > i update my stack docker for install with not root user and same issue like before
> 
> Great! Note this is **not** the same issue you had before 😉. Earlier it said `Unable to access log file`, while now it says `password authentication failed for user "postgres"`.
> 
> Not sure what's going on with the password 🤔. Just in case, can you try running the command starting with `POSTGRES_PASSWORD=password` instead of `POSTGRES_PASSWORD=123456789.`?

this is all my commands

```
git clone https://github.com/consul/consul.git

cd consul


cp config/secrets.yml.example config/secrets.yml


cp config/database-docker.yml.example config/database.yml


POSTGRES_PASSWORD=123456789. docker-compose build

POSTGRES_PASSWORD=123456789. docker-compose up -d database
```

all good until this command

`POSTGRES_PASSWORD=123456789. docker-compose run app rake db:create db:migrate`

then how can solve this for at least test and try your app
before i install democracyos, but i think that app is dead now

**Comment by johnfelipe** [comment]
ok i change pwd without dot at final and works
