### ISSUE TITLE
It will change the main page to '/debates' instead.

### ISSUE THREAD

**Issue by Chanachai-Pansailom** [consul/consul#4888]
It will change the main page to '/debates' instead.

**Comment by javierm** [comment]
Hi, @Chanachai-Pansailom :smile:.

I'm afraid we need a bit more context. Could you provide more details regarding when the main page will change to `/debates`?

**Comment by Chanachai-Pansailom** [comment]
I want to go to the website / and immediately go to the debate page. Because the first page will not be used, it will use the Debate page as the first page instead. By now I use javascript redirect url '../debates' I don't know if it's appropriate or not. I still don't see a way to change the routing.

**Comment by javierm** [comment]
Right now the easiest way is probably changing the line `root "welcome#index"` to `root "debates#index"` in the `config/routes.rb` file.

**Comment by javierm** [comment]
Closing since I think the question has been answered. @Chanachai-Pansailom Please, if I misunderstood, say so and reopen the issue :wink:.
