### ISSUE TITLE
Tratamiento de los teléfonos móviles

### ISSUE THREAD

**Issue by kikito** [consul/consul#489]
Esta issue tiene dos vertientes:

- [x] En la parte de interfaz, no se dice en ningún momento qué formato debe tener el teléfono móvil: 

¿Valen los espacios? ¿Guiones? ¿Paréntesis? ¿Hay que introducir el código de país?

- [x]  En el lado del servidor, tenemos que validar que nos ponen un teléfono válido, y mostrar un mensaje acorde si no lo hacen. También tenemos que quitarle los caracteres que consideremos que son válidos pero que no aportan (espacios, paréntesis, guiones), etc.

**Comment by decabeza** [comment]
Para el primero se añadió en la interfaz ***(Ejemplo: 612345678)***, se debería poder poner también un número internacional con su prefijo :wink:

**Comment by nachogomez** [comment]
Nos ponemos con ella.... @inobcr y @nachogomez

**Comment by inobCR** [comment]
¿Que hacemos para guardar los prefijos internacionales, creamos una tabla o utilizamos la tabla Tags creando una categoria en :kind que se llame prefijos?
