### ISSUE TITLE
How to new debates policy target="_blank"

### ISSUE THREAD

**Issue by Chanachai-Pansailom** [consul/consul#4892]
How to new debates policy target="_blank"  Unable to open a new page. (checkbox).
Ex.
<%= f.check_box :terms_of_service,
          title: t("form.accept_terms_title"),
          label: t("form.accept_terms",
                   policy: link_to(t("form.policy"), "URL", target: "_blank"),
                   conditions: link_to(t("form.conditions"), "URL", target: "_blank")
                  ) %>

**Comment by javierm** [comment]
Hi, @Chanachai-Pansailom :smile:.

Thanks for reporting. This is actually a known issue. Feel free to send a pull request to fix it!

Closing as duplicate of #4355
