### ISSUE TITLE
sendgrid API smtp is possible add like feature for send notifications?

### ISSUE THREAD

**Issue by johnfelipe** [consul/consul#4893]
sendgrid API smtp is possible add like feature for send notifications?

**Comment by javierm** [comment]
Hi, @johnfelipe :smile:.

Sorry, I'm afraid I don't understand the question :thinking:. Notifications are sent using the [admin notifications interface](https://demo.consulproject.org/admin/admin_notifications) and, yes, to do so on production, you need sendgrid or another SMTP provide and configure the application as mentioned in the [mail server configuration documentation](https://docs.consulproject.org/docs/english-documentation/introduction/servers/mail_server_configuration).

**Comment by johnfelipe** [comment]
Sendgrid use api
Then is only put there like same doc?

**Comment by javierm** [comment]
We've used sendgrid in the past by configuring the `smtp_settings` in the `secrets.yml` file, yes:

**Comment by johnfelipe** [comment]
```
  # mailer_delivery_method: :smtp
  # smtp_settings:
  #   :address: "smtp.example.com"
  #   :port: 25
  #   :domain: "your_domain.com"
  #   :user_name: "<username>"
  #   :password: "<password>"
  #   :authentication: "plain"
  #   :enable_starttls_auto: true
```

yes but wich will be settings for sendgrid?

You can connect via unencrypted or TLS on ports 25, 2525, and 587. You can also connect via SSL on port 465
smtp.sendgrid.net, 25

user will be me my user and password will be APIkey?

**Comment by javierm** [comment]
Hi, @johnfelipe.

I don't know; I don't use sendgrid :wink:. Maybe this can help :thinking:. [Configure ActionMailer to Use SendGrid](https://docs.sendgrid.com/for-developers/sending-email/rubyonrails#configure-actionmailer-to-use-sendgrid).

**Comment by javierm** [comment]
Closing since the question is answered in the SendGrid documention linked above. @johnfelipe Please reopen if that's not the case :wink:.
