### ISSUE TITLE
Creation of manuals for user, admin and develop

### ISSUE THREAD

**Issue by johnfelipe** [consul/consul#4895]
https://github.com/consul/consul/pull/4894

is an example, but can u share or create, i can contribute, with pdf or md files with recent screenshots and features?

**Comment by javierm** [comment]
Hi, @johnfelipe.

(Sorry, accidentally replied in the wrong page, so here's the same message again).

User manuals are part of the [webiste repository](https://github.com/consul/website). This website is publicly accessible through the [CONSUL project page](https://consulproject.org/); you can download these manuals from there.

I'm not sure whether the manuals you're looking for are already available. If they aren't, would you like to open an issue in the mentioned repository and close this one?

By the way, the team handling these manuals will be on holidays for the next 2-3 weeks, so it might be a while before they reply.

Hope this helps!

**Comment by johnfelipe** [comment]
sweet, can i translate them to spanish and share u?

**Comment by javierm** [comment]
I see you're already opening pull requests on the website repository :ok_hand:, so closing this one in favor of those ones.

By the way, if you're interested in keeping the user interface translated to Italian/French (we take care of English and Spanish, but of course we welcome reports regarding typos :smile:), you can join our [Crowdin project](https://crowdin.com/project/consul). The translations done there are later included in the source code of this repository.
