### ISSUE TITLE
how change title of webpage frontend

### ISSUE THREAD

**Issue by johnfelipe** [consul/consul#4898]
![SNAG-0103](https://user-images.githubusercontent.com/428820/183110974-3c23c740-4983-4ea2-8665-9bd52403e34d.png)

**Comment by javierm** [comment]
Hi, @johnfelipe.

The title of the page is taken from the name of the organization. You can edit this name in the "settings" section of the administration interface. The setting is called "site name".

**Comment by javierm** [comment]
Closing since I think the question has been answered :thinking:. @johnfelipe Feel free to reopen it that's not the case :wink:.
