### ISSUE TITLE
how change styles css and graphical design

### ISSUE THREAD

**Issue by johnfelipe** [consul/consul#4899]
can u link me md file or steps for change all sytles in consul
https://www.udea.edu.co/wps/portal/udea/web/inicio/institucional/planeacion/comunidad/encuestas-consultas
that will be example for colors and fonts, backgrounds, etc
Tnks

**Comment by javierm** [comment]
Hi, @johnfelipe.

You can add your own styles to the `app/assets/stylesheets/custom.scss` file or you can create new files in the `app/assets/stylesheets/custom/` folder.

**Comment by javierm** [comment]
Closing since I think the question has been answered in the previous comment. @johnfelipe If that's not the case, say so and reopen :wink:.

**Comment by Avi-ADAM** [comment]
> Hi, @johnfelipe.
> 
> You can add your own styles to the `app/assets/stylesheets/custom.scss` file or you can create new files in the `app/assets/stylesheets/custom/` folder.

for us its not working, we have problem in the new proposal page in hebrew, we put our custom style there which should sove it but not having any effect
those are the styles we put in "\consul\app\assets\stylesheets\custom.scss"
```
.proposal-new header::before {
    left: 100%;
    right: auto;
}

.proposal-form>fieldset>legend {
    float: none;
}
```

**Comment by javierm** [comment]
Hi, @Avi-ADAM :smile:.

Could you link to the repository where you're doing those changes? And maybe the website using them?

**Comment by Avi-ADAM** [comment]
> Hi, @Avi-ADAM 😄.
> 
> Could you link to the repository where you're doing those changes? And maybe the website using them?

https://decide.huka.co.il/proposals/new

we not working with repo for now but making changes inside our server
