### ISSUE TITLE
What is the relationship between "consulproject.org"  AND "consul.io"?

### ISSUE THREAD

**Issue by skycyan** [consul/consul#5015]
Thanks for answering. 

### 
What is the relationship between "consulproject.org"  AND "consul.io"?

###
Why are their version numbers different?

**Comment by Senen** [comment]
Hi @skycyan, they have no relation as they are different projects. While the Hashicorp Consul is a tool to manage networks, CONSUL is free software for citizen participation. It's usual people gets confused because of the name.
