### ISSUE TITLE
ca_file is not correct in generated agent-server-tls.hcl file

### ISSUE THREAD

**Issue by skyao** [consul/consul#5026]
### User Story

I need to setup two clusters on one machine for test, so I need to change the default settings of  CONSUL_CONFIG_DIR and CONSUL_DATA_DIR

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

CONSUL_CONFIG_DIR and CONSUL_DATA_DIR should be used for different clusters.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

I followed the document to setup consul in linux:

https://developer.hashicorp.com/consul/tutorials/get-started-vms/virtual-machine-gs-deploy

Because I need to setup two clusters on one machine for test, so I changed the default settings from 

```bash
 export DATACENTER="dc1" \
export DOMAIN="consul" \
export CONSUL_DATA_DIR="/etc/consul/data" \
export CONSUL_CONFIG_DIR="/etc/consul/config" \
```

to 

```bash
export DATACENTER="dc1" \
export DOMAIN="consul" \
export CONSUL_DATA_DIR="/home/sky/work/soft/consul/default/data" \
export CONSUL_CONFIG_DIR="/home/sky/work/soft/consul/default/config"
```

After I run `./generate_consul_server_config.sh` and `consul agent -node=consul -config-dir=${CONSUL_CONFIG_DIR}` to start consul:

```bash
==> Error loading from /etc/consul/config/consul-agent-ca.pem: open /etc/consul/config/consul-agent-ca.pem: no such file or directory
```

After I checked the generated hcl files, I found that in agent-server-tls.hcl file:

```bash
## TLS Encryption (requires cert files to be present on the server nodes)
ca_file   = "/etc/consul/config/consul-agent-ca.pem"
cert_file = "/home/sky/work/soft/consul/default/config/dc1-server-consul-0.pem"
key_file  = "/home/sky/work/soft/consul/default/config/dc1-server-consul-0-key.pem"
```

ca_file is not set correctly to follow CONSUL_CONFIG_DIR.

### Current Behavior
[comment]: # (Describe what actually happened.)

ca_file in generated agent-server-tls.hcl is not correct.

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

ca_file in generated agent-server-tls.hcl should use CONSUL_CONFIG_DIR

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

https://developer.hashicorp.com/consul/tutorials/get-started-vms/virtual-machine-gs-deploy

- step1: set CONSUL_CONFIG_DIR, don't use the default value "/etc/consul/config" 
- step2: run `./generate_consul_server_config.sh`
- step3: run `consul agent -node=consul -config-dir=${CONSUL_CONFIG_DIR}` 

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by javierm** [comment]
Hi, @skyao :smile:.

I'm afraid I've no idea what you're talking about. Is it possible that you're looking for [Hashicorp's Consul](https://github.com/hashicorp/consul/)? :thinking:

**Comment by skyao** [comment]
> Hashicorp's Consul

I'm sorry for this mistaken.
