### ISSUE TITLE
Hi, It would be great if we can add nepali language too in consul project. Can we add support for Nepali language too?

### ISSUE THREAD

**Issue by shrsundar** [consul/consul#5042]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*:

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

**Comment by Senen** [comment]
Hi @shrsundar, thank you very much! 🎉

We handle our translations through Crowdin. We've just enabled the [Nepali language in CONSUL](https://crowdin.com/project/consul/ne-NP).

Looking forward to adding the Nepali language to CONSUL!

**Comment by shrsundar** [comment]
Hi @Senen, 
Thank you very much for your resposne.
I have added Nepali language project in crowdin. (https://crowdin.com/project/np-nepali/ne-NP) Can I use same project to import in Consul. I have copied locale from consul to upload in crowdin and translate.

Can I used it ? It would be great if we can.



Thanking you again

**Comment by Senen** [comment]
Wow, I saw you already translated the 40%. That's impressive! 👏🏼 

> I have added Nepali language project in crowdin. (https://crowdin.com/project/np-nepali/ne-NP) Can I use same project to import in Consul. I have copied locale from consul to upload in crowdin and translate.I have added Nepali language project in crowdin. (https://crowdin.com/project/np-nepali/ne-NP) Can I use same project to import in Consul. I have copied locale from consul to upload in crowdin and translate.

I think you can run the `Export to XLIFF` in your Crowdin's repository and then run the `Upload translations` feature in the CONSUL one.

I hope this helps!

Thanks for your contribution! 🥇

**Comment by Senen** [comment]
cc @shrsundar 

Please ask if you find any trouble, and we will try to help you.

**Comment by shrsundar** [comment]
@Senen 

Thank you for your prompt response. I'll try as you said and let you know if any problem.

Thank  you again, for your efforts to make CONSUL, best multi-Lang open project for public participation.

Regards,
Sundar

**Comment by javierm** [comment]
Closing since the language has already been enabled on Crowdin.

@shrsundar Thanks a lot for adding Nepali to Consul! :tada:
