### ISSUE TITLE
View Investment page caching issue

### ISSUE THREAD

**Issue by coslajohn** [consul/consul#5075]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
Sorry - this one is quite difficult to describe

We have identifed some strange behaviour when viewing investments.  If you view an Investment, then when the Phase of a Participatory Budgeting process changes, the view of the Investment remains the same as the previous phase.  It does not show the correct Buttons on the right sidebar even though they are needed by the new phase.

This feels like caching but we have been unable to force a refresh in the browser to display the updated page

We think it might be on a per user basis but was reported to us as site wide

### Why is this Needed?

[comment]: # (Describe the problem and why this task is needed. Provide a description of the current state, what you would like to happen, and what actually happened)

This was reported to us by end users who were concerned that their investment was being disadvantaged in a vote because the Vote or Support button was not being displayed in the sidebar. We are still investigating and are not entirely clear whether this affects all users or just individual logged in users.

### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)

If you log in as an admin or author and view an investment page then change phase, the investment view remains the same as it was in the previous phase.

For example if you are in the Valuating Phase, view an Investment then change the Active Phase to Voting, the Investment View remains the same as before so does not have the Vote button.  If you view the list of investments they all display the Vote button in the summary list, but when you click in to the Investment, there is no Vote button.

Refreshing/Clearing the cache in the browser seems to have no effect.

Editing the Investment and saving by clicking Update Investment will force a refresh and the correct view for the phase will display

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
The view which corresponds to the Phase should be displayed

### Steps to reproduce
[comment]: # (Describe how we can replicate the bug step by step.)
We have been able to reproduce this in our own site and on the live Consul Demo site. View Investment, change phase, view investment once more.

https://dev.communitychoices.scot/budgets/44/investments?heading_id=71

**The process is in the support phase**

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/102246590/215744827-94cc58af-7335-4eb7-97c3-ce2706b50b1e.png)

**when I click into the Investment it doesn't show the Support button (this example shows Vote because that was the last phase I tested with)**

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/102246590/215746381-1e1b6e0a-f064-479d-81c7-9ea26b2ce402.png)

**but in a different session using different browser looking at same page I get the correct view**
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/102246590/215750088-664197a3-9964-478c-9cd4-c07b7f9dc2b7.png)

**Edit the page, click on Update Investment and I get the correct view. The view has been refreshed correctly.**

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/102246590/215746742-3dd30a41-9567-4dff-9a6b-485dd7a538be.png)

**Change phase to Voting and in my first session, the browser I changed the phase in and still showing support**  

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/102246590/215747248-4708a113-cd1a-4c0e-a969-494749a1e979.png)

In my second session it correctly shows Vote 

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/102246590/215747244-ade9cd01-9ee8-496e-8221-a9c446fea074.png)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

When Phase is changed all users can see updated page view

**Exactly the same behaviour occurs when using the Consul Demo site**

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/102246590/215749837-104cc0d2-0676-46a2-9c5e-6a7bb7d9968a.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/102246590/215749844-9f4655cd-08ed-4bc6-b26f-372f8653a7df.png)

**Comment by javierm** [comment]
@coslajohn Thanks for reporting! :pray:

This is at least the third caching issue we've had related to the investments sidebar, so we're considering our approach and only caching the contents of the investments (title, image, description, ...) but not the sidebar. Just opened #5077 with a possible implementation.
