### ISSUE TITLE
Budget image not shown if filename contains special characters

### ISSUE THREAD

**Issue by microweb10** [consul/consul#5079]
### Description

When uploading an image for a Participatory Budget, if the image filename contains special characters, the image is uploaded and shown correctly in the admin panel, but cannot be properly loaded by the browser in the public view.
In this example, the filename used is `Wijkbudget_Beijum_2(1)` which special characters are `(` and `)`

### Current Behavior

The image is not shown.

### Expected Behavior

The image is shown.

### Steps to reproduce

1. Login with the admin user into [the demo website](https://demo.consulproject.org/users/sign_in).
2. Edit [the current budget](https://demo.consulproject.org/admin/budgets/1/edit).
3. Upload an image with a filename containing a special character.
4. Visit [the public budget view.](https://demo.consulproject.org/budgets/1)

#### Admin view
![admin](https://user-images.githubusercontent.com/942995/217519506-0c36184f-3671-4e81-bfe2-15ca9b3198e0.png)

#### Public view
![public](https://user-images.githubusercontent.com/942995/217519890-75a0223b-48b9-41e9-bab4-0bef5cbcf3c1.png)

**Comment by javierm** [comment]
Hi, @microweb10 :smile:.

Is this the same issue as issue #5051? :thinking:

**Comment by microweb10** [comment]
Yep, sorry, I didn't know about that already opened issue. 😉
