### ISSUE TITLE
There  was an error saving your key,  the adapter operation was aborted

### ISSUE THREAD

**Issue by GITHUBTOXZ** [consul/consul#5081]
### Hello, consult saved key error
agent: grpc: addrConn.createTransport failed to connect to {gwms_dc-172.21.0.1:8300 0 consul_server_1.gwms_dc <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.21.0.1:0->172.21.0.1:8300: operation was canceled". Reconnecting...

![11893ea13ff99a3d8644b21cfbe570d](https://user-images.githubusercontent.com/40156185/218945912-acc20f66-cbc0-4d8e-9468-ea7a9b36771c.jpg)

**Comment by javierm** [comment]
Hi @GITHUBTOXZ :smile:.

Not sure what you're talking about :thinking:. Is it possible that you're looking for [Hashicorp's Consul](https://github.com/hashicorp/consul/)?

**Comment by javierm** [comment]
Closing due to lack of response.
