### ISSUE TITLE
cannot find custom images uploaded from admin

### ISSUE THREAD

**Issue by Avi-ADAM** [consul/consul#5088]
we start wihout capistrano and now we noving to use capistrano so we need first to update our local instaletion with all the changes and customizaton madfe by our team mosley fromn the admin panel.
for now i backup the db from the production and restor it on the development local instaletion.
i get an error 
```
` ActiveStorage::Attachment Load (1.9ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 46], ["record_type", "Image"], ["name", "attachment"], ["LIMIT", 1]]
  ↳ app/models/image.rb:44:in "variant"
  Rendered shared/_header.html.erb (Duration: 352.4ms | Allocations: 32262)
  Rendered welcome/index.html.erb within layouts/application (Duration: 621.6ms | Allocations: 65110)
Completed 500 Internal Server Error in 977ms (ActiveRecord: 73.4ms | Allocations: 107689)


  
ActionView::Template::Error (variant delegated to attachment, but attachment is nil):
    16:
    17:       <% if header.image.present? %>
    18:         <div class="small-12 medium-6 column">
    19:           <%= image_tag(header.image.variant(:large),
    20:                         class: "margin",
    21:                         alt: header.image.title) %>
    22:         </div>

app/models/image.rb:44:in `variant'
app/views/shared/_header.html.erb:19
app/views/welcome/index.html.erb:14
config/initializers/wicked_pdf.rb:10:in `render'
app/controllers/application_controller.rb:53:in `switch_locale'`
```
from what i understant it is our custom images missing on the dev server, where can i find them? they are not in "/home/deploy/consul/current/app/assets/images/custom" so where should i look for them? 
also other recomandetion for not loosing all the work done on the server when i deploy from capistrano 
thanks

**Comment by Senen** [comment]
Hi @Avi-ADAM, 

I think the `ActiveStorage` files live in the "storage" directory within the application root folder.

Not sure, but it's possible you need to use the same `secret_key_base` in both environments 🤔 .
