### ISSUE TITLE
No moderation on debates/comments in Collaborative Legislation

### ISSUE THREAD

**Issue by coslajohn** [consul/consul#5094]
### User Story

There is no moderation in the debates/comments within collaborative legislation. This is quite urgent for us as we hope to use collaborative legislation for some potentially controversial discussions and really need to be able to moderate comments

### Why is this Needed?

We need to be able to moderate discussions within collaborative legislation just as we do in Debates
In debates we have

![image](https://user-images.githubusercontent.com/102246590/226299400-3976168e-b6c2-4282-a51c-80fa09e71444.png)

but in collaborative legislation there is no moderation on comments -  no flag/block/hide functions as below

![image](https://user-images.githubusercontent.com/102246590/226298752-704eb927-9a25-49f8-8e3c-8ebe322e9c35.png)

**Comment by Senen** [comment]
Hi @coslajohn, 

AFAIK the legislation process debates section has those features 🤔. You can check it by login in as administrator in the CONSUL Democracy demo site and browsing any debate. Here is a [link ](https://demo.consulproject.org/legislation/processes/1/questions/1) to one of them. You will find the administrator credentials at the top of the page. 

In the screenshot, I can see you are logged in as an administrator that posted that comment. The application does not show the moderation features to the comment author.

**Comment by coslajohn** [comment]
You are correct !!!Sorry I missed this. Thanks for the response
