### ISSUE TITLE
Database seed returns error undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by jankeber** [consul/consul#5132]
Bug:

When i run bin/rake db:dev_seed i get the following error

bin/rake db:dev_seed
Creating Settings ✅
Creating Geozones ✅
Creating Users ✅
Creating Tags Categories ✅
Creating Debates ✅
Creating Proposalsrake aborted!
NoMethodError: undefined method `<' for nil:NilClass
/Users/jankeber/Documents/temp/consul/app/models/image.rb:73:in `validate_image_dimensions'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:181:in `block (2 levels) in halting_and_conditional'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:604:in `catch'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:182:in `block in halting_and_conditional'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:513:in `each'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:825:in `_run_validate_callbacks'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activemodel-6.0.6.1/lib/active_model/validations.rb:406:in `run_validations!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activemodel-6.0.6.1/lib/active_model/validations/callbacks.rb:117:in `block in run_validations!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activemodel-6.0.6.1/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activemodel-6.0.6.1/lib/active_model/validations.rb:337:in `valid?'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/validations.rb:68:in `valid?'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/validations.rb:84:in `perform_validations'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/validations.rb:53:in `save!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:318:in `block in save!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/transactions.rb:318:in `save!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/suppressor.rb:48:in `save!'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activerecord-6.0.6.1/lib/active_record/persistence.rb:55:in `create!'
/Users/jankeber/Documents/temp/consul/db/dev_seeds.rb:41:in `add_image_to'
/Users/jankeber/Documents/temp/consul/db/dev_seeds/proposals.rb:14:in `add_image_to_proposal'
/Users/jankeber/Documents/temp/consul/db/dev_seeds/proposals.rb:43:in `block (2 levels) in <top (required)>'
/Users/jankeber/Documents/temp/consul/db/dev_seeds/proposals.rb:19:in `times'
/Users/jankeber/Documents/temp/consul/db/dev_seeds/proposals.rb:19:in `block in <top (required)>'
/Users/jankeber/Documents/temp/consul/db/dev_seeds.rb:17:in `section'
/Users/jankeber/Documents/temp/consul/db/dev_seeds/proposals.rb:17:in `<top (required)>'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:318:in `load'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:318:in `block in load'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:318:in `load'
/Users/jankeber/Documents/temp/consul/db/dev_seeds.rb:12:in `load_dev_seeds'
/Users/jankeber/Documents/temp/consul/db/dev_seeds.rb:57:in `<top (required)>'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:318:in `load'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:318:in `block in load'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:318:in `load'
/Users/jankeber/Documents/temp/consul/lib/tasks/db.rake:5:in `block (3 levels) in <top (required)>'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/ros-apartment-2.11.0/lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
/Users/jankeber/Documents/temp/consul/app/models/tenant.rb:139:in `switch'
/Users/jankeber/Documents/temp/consul/lib/tasks/db.rake:5:in `block (2 levels) in <top (required)>'
/Users/jankeber/.rvm/gems/ruby-3.0.6/gems/airbrake-13.0.3/lib/airbrake/rake.rb:17:in `execute'
Tasks: TOP => db:dev_seed
(See full trace by running task with --trace)

**Comment by karim-semmoud** [comment]
@jankeber 
It looks like an issue with a missing dependencies.
Could you confirm that you went through all the [prerequisite](https://docs.consulproject.org/docs/english-documentation/introduction/local_installation/ubuntu) before running dev_seed
In your case, it seems that [Imagemagick:](https://docs.consulproject.org/docs/english-documentation/introduction/local_installation/ubuntu#imagemagick) is not installed
Could you try
`sudo apt install imagemagick`
And then run again
`bin/rake db:dev_seed`

**Comment by jankeber** [comment]
That was exactly the issue.

Since i'm running on MacOS i had to run

brew install imagemagick

Thank you for your help
