### ISSUE TITLE
Markdown not rendering correctly

### ISSUE THREAD

**Issue by coslajohn** [consul/consul#5135]
### Description

[comment]: # (Feature or Bug? eg. Type: Bug)
*Type*: Bug

### Current Behavior
[comment]: # (Describe what actually happened.)
When using the text editor in Collaborative Legislation the markdown for a table renders correctly in the preview part of the text editor.
![image](https://github.com/consul/consul/assets/102246590/4e9b7718-bc50-4672-a67b-5c05e52bd719)

When the process is published and viewed in the process the table doesn't render and the markdown commands are shown as text

![image](https://github.com/consul/consul/assets/102246590/8c2f356b-6826-4446-bb2b-49e80bea2045)

The opposite behaviour happens with the markdown code for header # It renders correctly in the process but doesn't render in the  text editor preview

![image](https://github.com/consul/consul/assets/102246590/fb63883f-81f2-4293-9816-00bbdc0e868f)
![image](https://github.com/consul/consul/assets/102246590/547d3b42-519d-40af-b3e2-bbf53e5cc691)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

Markdown elements to render consistently

**Comment by karim-semmoud** [comment]
Hi @coslajohn 
I hope you are doing great.

It looks like the gem [Redcarpet](https://github.com/vmg/redcarpet)  has `tables: false` by default

Can you try this changes 
in `lib/admin_legislation_sanitizer.rb` add `tr th td table thead tbody`
```
class AdminLegislationSanitizer < WYSIWYGSanitizer
  def allowed_tags
    super + %w[img h1 h4 h5 h6 tr th td table thead tbody]
  end

  def allowed_attributes
    super + %w[alt src id]
  end
end
```
in `app/models/legislation/draft_version.rb` add `tables: true`

```
  def body_html
    renderer = Redcarpet::Render::HTML.new(with_toc_data: true)

    Redcarpet::Markdown.new(renderer, tables: true).render(body)
  end
```

This this changes you can now see the tables
![Screenshot from 2023-06-21 10-27-01](https://github.com/consul/consul/assets/114252883/19c158db-7a6c-4c3a-b87c-da479ad5e5ac)
![Screenshot from 2023-06-21 10-26-30](https://github.com/consul/consul/assets/114252883/717e7c5a-f58b-401c-966e-ce3c250a88cf)

**Comment by coslajohn** [comment]
Thanks @karim-semmoud  that seems to work
