### ISSUE TITLE
Estadísticas de verificación y otras

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#571]
Visualizar los números de los pasos de verificación:
  - [ ] Cuanta gente llegar al formulario del padrón y cuanto gente lo rellena con éxito
  - [ ] Cuanta gente llegar al formulario de SMS y cuanto gente introduce el código correcto
  - [ ] Cuanta gente de "nivel 2" no ha apoyado ninguna propuesta

**Comment by palomahnhp** [comment]
Vamos a ir mirando este issue @MaiteHdezRivas  y yo

**Comment by decabeza** [comment]
Gracias @palomahnhp  y @MaiteHdezRivas :ok_hand:

**Comment by xuanxu** [comment]
hecho
