### ISSUE TITLE
Propuestas similares

### ISSUE THREAD

**Issue by decabeza** [consul/consul#588]
Las propuestas deben de tener un campo para añadir (por cualquier usuario) un enlace a otra propuesta similar. 

En el show de la propuesta se mostrará un listado de 5 propuestas similares (ordenadas por el número de apoyos), en caso de que haya más similares habrá un enlace a "Ver más propuestas similares" y aparecerán todas en formato listado (como /proposals/).

**Comment by decabeza** [comment]
![similar_proposals](https://cloud.githubusercontent.com/assets/631897/10365229/1862da3e-6dc2-11e5-82b5-35d02ed1742f.jpg)

![similar_proposals_list](https://cloud.githubusercontent.com/assets/631897/10365231/19cb1a12-6dc2-11e5-87b0-a2322e57e789.jpg)

**Comment by passcual** [comment]
Voy a intentarlo con ésta

**Comment by ManjiChiba** [comment]
Que tal alguna de estas ideas?
https://decide.madrid.es/debates/4363
https://decide.madrid.es/debates/4318
https://decide.madrid.es/proposals/6912
https://decide.madrid.es/proposals/6879
https://decide.madrid.es/proposals/6878
https://decide.madrid.es/proposals/5994
https://decide.madrid.es/proposals/5260
https://decide.madrid.es/proposals/5178

**Comment by passcual** [comment]
Lo siento, chicos. De momento no puedo atender esta issue.

**Comment by inobCR** [comment]
He hablado con Pascual y me pongo con esta

**Comment by ManjiChiba** [comment]
Gracias por la posibilidad de poder retirar propuestas realizadas, obsoletas, o repetidas.
Gran trabajo (aunque no sea nadie para decirlo).
Ahora falta que los autores de propuestas repetidas, respondan a mis peticiones para que las retiren (por desgracia, la mayoría de las propuestas parecen abandonas por su creadores 😡 y tampoco se puede "adoptar" por el momento).
Lo que es una lástima, es que todas aquellas propuestas que tanto el Ayto, como vosotros estáis haciendo y llevando a la práctica, no vayan a una sub-sección aparte de "Terminadas" o "Realizadas" para que dentro de 3,5 años, todo el mundo pueda ver TODO (y valorar) el trabajo y esfuerzo que se ha hecho tanto por parte del Ayto, como de los programadores encargados de la página.
Ya se que ese esfuerzo se haría igualmente sin ningún reconocimiento, por simple convicción, pero tampoco creo que estuviera de más poder verlo.
Tómenlo como una simple sugerencia (y no es mi intención meterme donde no me llaman).
Gracias igualmente, aunque sólo sea por mi parte.

**Comment by voodoorai2000** [comment]
👍  @inobCR 
Ánimo @ManjiChiba! Muchas gracias por tus esfuerzos, al final lo conseguiremos ;)

**Comment by ManjiChiba** [comment]
Gracias a vosotros por vuestro trabajo. 👍

**Comment by ManjiChiba** [comment]
De nuevo, mi enhorabuena por las nuevas opciones "Enviar notificación" y "Mensaje privado" (en el perfil particular de cada usuario).
La 1ª vendrá a solucionar parcialmente (y espero que mucho) la repetición de propuestas (a ver si se consigue una mayor limpieza y que se queden en pocas páginas).
La 2ª.... ya había pensado yo en hacer una propuesta al respecto, pero os habéis adelantado. 👍
Enhorabuena por el gran trabajo realizado.
He actualizado el hilo https://decide.madrid.es/proposals/8938-recopilacion-de-propuestas-relativas-a-mejora-de-la-administracion-de-la-web para que quede constancia del trabajo que estáis haciendo.

**Comment by decabeza** [comment]
Finalmente vamos a añadir un sistema de "Contenido relacionado" y no sólo de propuestas similares.

Continuamos en #1164
