### ISSUE TITLE
Sugerir debates/propuestas antes de crearlas

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#599]
Para evitar duplicidades, al darle al botón "Crear propuesta" mostrar una nueva página que te obligue a buscar. Si no encuentras lo que estás buscando, entonces te deja ir al formulario para crear un debate/propuesta.

**Comment by palomahnhp** [comment]
Nos ponemos con esta @MaiteHdezRivas  y yo

**Comment by decabeza** [comment]
¡Gracias @palomahnhp y @MaiteHdezRivas! 

Todavía no tengo diseños para esto, pero estábamos pensando a hacer algo similar a esto:

http://stackoverflow.com/questions/ask/advice?

:wink:

**Comment by ManjiChiba** [comment]
¿Talvez esta solución sea más rápida ante la urgencia de este tema en concreto?.
https://decide.madrid.es/proposals/6878

**Comment by voodoorai2000** [comment]
Gracias por la sugerencia @ManjiChiba!
Ya lo han resuelto @MaiteHdezRivas y @palomahnhp, gracias chicas!
