### ISSUE TITLE
Mejorar SEO para las urls de debates y propuestas

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#602]
Los links a los debates y propuestas deberían tener este formato:

https://decide.madrid.es/propuestas/9-billete-unico-para-el-transporte-público

Sugerencias de gemas:
https://github.com/enriclluelles/route_translator
https://github.com/norman/friendly_id

**Comment by dgilperez** [comment]
Y si el usuario cambia el idioma, también tiene que cambiar el idioma en la URL? Si es que no, me ahorraría el uso de route_translator y traduciría la ruta directamente en el routes.rb

**Comment by voodoorai2000** [comment]
Sí, podríamos empezar sin route_translator hasta que saquemos la web en inglés.

**Comment by microweb10** [comment]
Si no la tiene nadie, me cojo esta!

**Comment by voodoorai2000** [comment]
:+1: Muchas gracias @microweb10!

**Comment by microweb10** [comment]
https://github.com/consul/consul/pull/817
