### ISSUE TITLE
Arreglar traducciones plurales/singulares masculinos/femeninos

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#604]
Al crear una propuesta sale el mensaje "Proposal creado correctamente"
Debería ser "**Propuesta ciudadana** cread**a** correctamente"

También hay una inconsistencia entre plurales y singulares en locales/activerecord.es y locales/activerecord.en.

**Comment by Serabe** [comment]
¿No sería __Propuesta ciudadana__?

**Comment by voodoorai2000** [comment]
Correcto ;)

**Comment by pardoam** [comment]
Buenos días, Elena y Ana nos quedamos con esta Issue.

**Comment by decabeza** [comment]
¡Gracias Elena y Ana! :+1:

**Comment by voodoorai2000** [comment]
Closed via #828
