### ISSUE TITLE
Compartir enlace en los debates

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#642]
Se debería compartir un enlace como única de información de un debate. Sin necesidad de poner un texto, ni nada más.

Sugerencia: 
Añadir un enlace ó botón 'compartir enlace' adicional al de 'crear debate'.

Actualización:
Aparte del enlace también se añadiría un título.
Debería ser un formulario nuevo, independiente del de crear un debate.

**Comment by MaiteHdezRivas** [comment]
Nos quedamos esta Paloma y yo. Un saludo

**Comment by voodoorai2000** [comment]
Grande @MaiteHdezRivas y Paloma!

**Comment by decabeza** [comment]
¡Gracias @MaiteHdezRivas y Paloma! os adjunto un par de imágenes con la idea que teníamos en mente de esta parte. Cualquier duda me decís :wink: 

En la página principal añadir un botón de "Compartir un enlace" en el sidebar:

![share_link_button](https://cloud.githubusercontent.com/assets/631897/11243707/d0df7100-8e09-11e5-84c2-251fe5a0ec85.png)

Y un formulario al estilo de nuevo debate con solo dos campos de "Título" y "Enlace":

![share_link_page](https://cloud.githubusercontent.com/assets/631897/11243712/d5a6493e-8e09-11e5-928c-5a1ce546534f.png)

**Comment by MaiteHdezRivas** [comment]
OK. Perfecto.

**Comment by MaiteHdezRivas** [comment]
Según el diseño de @decabeza no se ven temas para etiquetar el debate. ¿no son necesarios?

**Comment by decabeza** [comment]
Hola @MaiteHdezRivas, después de consultarlo me comentan que lo ideal sería que apareciese el campo de etiquetas (que es opcional) separadas por temas / distritos. Es lo que están haciendo en #685 :wink:

**Comment by palomahnhp** [comment]
Pendiente hablar con vosotros sobre test

**Comment by decabeza** [comment]
Done on https://github.com/consul/consul/pull/742
