### ISSUE TITLE
Mostrar si el nombre de usuario está disponible al registrarse

### ISSUE THREAD

**Issue by xavs** [consul/consul#648]
Actualmente para registrarse se pide un nombre de usuario unico.
La disponibilidad solo se comprueba al enviar el formulario.
En caso de no disponibilidad, el usuario ha de introducir otro nombre, contraseña dos veces mas el captcha. Este proceso podria llegar a repetirse muchisimas veces, a la segunda o tercera la mayoria de usuarios desistira.
Hay varias opciones: 
Quiza un ajax para comprobar nombre de usuario antes de envio de formulario...

**Comment by voodoorai2000** [comment]
Gracias @xavs!

+1 a comprobar dinámicamente el nombre de usuario

**Comment by xavs** [comment]
De nada, gracias por la iniciativa, va por el buen camino :)

**Comment by microweb10** [comment]
Si no la tiene nadie, me cojo esta!

**Comment by decabeza** [comment]
¡Gracias @microweb10! :+1:

**Comment by microweb10** [comment]
https://github.com/consul/consul/pull/808

**Comment by microweb10** [comment]
https://github.com/consul/consul/pull/818

**Comment by voodoorai2000** [comment]
Closed via #818
