### ISSUE TITLE
Mejoras sección de administración

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#655]
- [ ] Añadir en la pestaña de admin un buscador de usuarios, que permita buscar por DNI, e-mail o nombre de usuario, y que luego muestre esos tres datos más la pestaña de actividad más un botón de bloquear/desbloquear.
- [x] Los admin deberían poder acceder a la pestaña de gestores.
- [x] Ordenar la lista de Organizaciones por orden de llegada de solicitud, no alfabética.
- [ ] Añadir buscador para las propuestas/debates/comentarios ocultos.

**Comment by GustavoCaso** [comment]
Buenas @voodoorai2000 No he contribuido todavía en el proyecto pero  me gustaría hacerlo. Pensé en empezar por esta pero si hay alguna de más prioridad o que prefieras que comience por otra, dímelo.

**Comment by voodoorai2000** [comment]
Buenas @GustavoCaso! Muchas gracias por querer colaborar, por favor estás en tu casa, trabaja en el issue que más te motive. Este en concreto, te lo agradecerán bastante los funcionarios en las oficinas de atención al ciudadano, así que adelante!

**Comment by GustavoCaso** [comment]
Ok @voodoorai2000 cualquier cosa te digo. Un saludo

**Comment by voodoorai2000** [comment]
Perfecto, saludos!

**Comment by GustavoCaso** [comment]
@voodoorai2000 Que tal ? Oye veo que en la sección de usuarios del panel de Admin solo hace mención a usuarios bloqueados, es aquí donde quieren el buscador de usuarios o hay algo que me haya perdido ?

Muchas gracias

**Comment by GustavoCaso** [comment]
@voodoorai2000 Leyendo mejor las especificaciones creo que no es la misma pagina, si no sería otra sección en el lateral del menu de admin. Me equivoco ?

**Comment by voodoorai2000** [comment]
Efectivamente @GustavoCaso lo suyo es crear una sección en Admin que se llama por ejemplo Usuarios, y ahí es donde podemos mostrar el buscador y las acciones a realizar sobre los usuarios.

**Comment by GustavoCaso** [comment]
Estupendo @voodoorai2000, ya empece con ello espero hacer el pull request lo antes posible

**Comment by voodoorai2000** [comment]
:+1: :+1: :+1:

**Comment by inobCR** [comment]
En las issue 307-Añadir buscador en admin/users  se crean tambien buscador en:

admin/comments
admin/debates
admin/proposals
admin/spending_proposals

**Comment by inobCR** [comment]
La tabla organizaciones no tiene un campo fecha de alta por el que ordenar, ¿lo conveniente sería crearlo? o ¿que la ordenación fuese por fecha de alta de usuario asociado?

**Comment by xuanxu** [comment]
por fecha de alta de usuario asociado estaría bien

**Comment by inobCR** [comment]
ok me pongo con ello

**Comment by voodoorai2000** [comment]
Closed in favor of https://github.com/consul/consul/issues/1489
