### ISSUE TITLE
Revisar orden de los comentarios

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#670]
Problema:
En el orden predeterminado (más votados) aparecen comentarios con votos negativos antes que comentarios sin votos. 
Aquí se pueden ver un ejemplo https://decide.madrid.es/debates/4230. El comentario de oASDF tiene 3 votos negativos pero aparece antes que comentarios sin votos.

Comportamiento esperado:
Deberíamos ordenar por votos positivos ó mejor aún por más apoyados (votos a favor- votos en contra. Teniendo en cuenta el número de votos para darle más peso a los comentarios que tengan más votos)

**Comment by microweb10** [comment]
Si no hay nadie con esta, me la cojo!

**Comment by voodoorai2000** [comment]
Vaya, esta también está empezada. https://github.com/consul/consul/pull/765
@danibaena ¿cómo vas de tiempo para finiquitar este issue?

**Comment by microweb10** [comment]
:+1:

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/765
