### ISSUE TITLE
Opción en "Mi cuenta" para recibir o no correos de información 

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#679]
Opción en "Mi cuenta" para recibir o no correos de información interesante sobre la web.

Además debe haber un link para desactivar esta opción que se pueda usar en los emails como link de desuscripción.

**Comment by microweb10** [comment]
Enga, quitadle la etiqueta the PRs-welcome, que me la cojo!

**Comment by decabeza** [comment]
¡Gracias @microweb10! :+1:

**Comment by kikito** [comment]
Closed by #771
