### ISSUE TITLE
Filtros redux

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#680]
Cambiar el "Estás viendo las propuestas" con el select, por tres enlaces "activas hoy / más apoyadas / nuevas" resaltando en cuál se está en ese momento. Lo mismo en debates. 

A la derecha de estos, otro enlace de "Más filtros". Este debería llevar a opciones más complejas (a poder ser en la misma página), incluyendo todas las opciones "activas hoy / más apoyadas / nuevas / más comentadas / aleatorias" y también permitiendo limitar por fechas "de las últimas 24 horas / última semana / último mes / siempre / intervalo personalizado"

**Comment by gitmarcia** [comment]
Me quedo con esta. Un saludo

**Comment by voodoorai2000** [comment]
Muy bien @gitmarcia :+1: Saludos!

**Comment by nachogomez** [comment]
Nos lo pasa Marcia este...

**Comment by nachogomez** [comment]
es decir, que nos ponemos los tres , Marcia, Boni y yo

**Comment by decabeza** [comment]
He cambiado un poco la descripción de esta issue con algunos cambios de texto, y añado varias imágenes con la idea que tenemos de esto :wink: 

**Cambiar el select por menús** (sin título, ya que el menú superior indica que ya estamos en Propuestas. Aunque para mejorar la accesibilidad se puede añadir un `<h1>` con la clase `"sr-only"`, que se mostrará sólo para los lectores de pantalla). Los filtros que ya había siguen funcionando de la misma manera y se añade un menú nuevo "Más filtros" :

![proposal_filters](https://cloud.githubusercontent.com/assets/631897/11271451/1d1d55f2-8ec6-11e5-826f-a00d4a174525.jpg)

Al pulsar en **"Más filtros"** se mostraría el resto de filtros, y permitiría también seleccionar el intervalo de fechas:

![proposal_filters_2](https://cloud.githubusercontent.com/assets/631897/11271496/612f2c16-8ec6-11e5-9b14-5b1ce23aa5bf.jpg)

Al seleccionar **"Intervalo personalizado"** aparecería el formulario de "Fecha inicio" y "Fecha fin". Para seleccionar la fecha se podría usar algo como http://getuikit.com/docs/datepicker.html o https://jqueryui.com/datepicker/

![proposal_filters_3](https://cloud.githubusercontent.com/assets/631897/11271523/a56d1f78-8ec6-11e5-8641-594f92f01ca1.jpg)

**Comment by inobCR** [comment]
ok muchas gracias

**Comment by kikito** [comment]
Hola! Nos han pedido con bastante urgencia que hagamos lo de transformar los selects en enlaces, así que lo voy a hacer yo en una PR independiente - solamente lo de transformar los selects en links.

**Comment by gitmarcia** [comment]
Hola. De acuerdo.
Un saludo

El 5 ene 2016, a las 15:22, Enrique García <notifications@github.com<mailto:notifications@github.com>> escribió:


Hola! Nos han pedido con bastante urgencia que hagamos lo de transformar los selects en enlaces, así que lo voy a hacer yo en una PR independiente - solamente lo de transformar los selects en links.

**Comment by voodoorai2000** [comment]
Closed via #822
