### ISSUE TITLE
Página de búsqueda avanzada

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#681]
Hay que añadir un link al buscador para búsqueda avanzada. Lleva a nueva página con opciones avanzadas de búsqueda:

 - por fecha (últimas 24 horas / última semana / último mes / último año / intervalo personalizado)
 - buscar por nombre/username del autor
 - buscar por categoría del autor (concejal, cargo directivo, etc). 

Y que también permita ordenar el resultado de la búsqueda con los criterios de ordenación anteriores (apoyadas, comentadas, nuevas, activas, aleatorias). 

Las búsquedas deberían poder ser combinables (ej: en "la última semana", usuarios tipo "concejal" y con el texto "economía"). 

También deberíamos poder hacer una búsqueda vacía de cualquiera de esos filtros (ej: "mostrar todas las propuestas del último mes", o "todas las creadas por cargos directivos"), que además nos serviría para poner en algún otro lado enlaces directos a esas búsquedas (por ejemplo la anterior de propuestas o intervenciones de concejales o cargos directivos).

**Comment by Ana06** [comment]
I'll do it!

**Comment by decabeza** [comment]
¡Gracias @Ana06! :wink:

**Comment by Ana06** [comment]
En lugar de que lleve a una página nueva, lo estoy haciendo en la misma página aunque por defecto aparece oculto:

![busquedas1](https://cloud.githubusercontent.com/assets/16052290/12070852/7fa549d0-b08d-11e5-8754-87f115563405.png)

![busquedas2](https://cloud.githubusercontent.com/assets/16052290/12070855/ab3fdf06-b08d-11e5-9811-2cd79aa4a1b2.png)

Me parece que es más lógico así, ¿Os parece bien?

¿La categoría del autor debe ser un selector con opciones prefijadas como está en la imagen o un cuadro de texto? En caso de que las opciones sean fijas, ¿cuáles son?

**Comment by Ana06** [comment]
Me parece que las opciones deberían ser fijas y en concreto serían: Empleado público, Organización Municipal, Directores general, Concejal y Alcaldesa
De menor a mayor valor de official_level
¿No?
