### ISSUE TITLE
Añadir estructura temática y por distritos

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#685]
Al crear propuestas o debates, mostrar las etiquetas en dos secciones: 
-Etiquetas temáticas, 
-Etiquetas de distrito. 

Relacionado con #686

**Comment by nachogomez** [comment]
Boni y yo nos quedamos con esta...

**Comment by voodoorai2000** [comment]
Grande @nachogomez y Boni!!!

**Comment by decabeza** [comment]
¡Gracias @nachogomez y Boni! os adjunto una imagen con la idea que teníamos de esta parte. Cualquier duda me decís :wink:

![proposal_tags](https://cloud.githubusercontent.com/assets/631897/11244017/c33811b8-8e0b-11e5-8f82-9da5b0dd0e50.png)

**Comment by ManjiChiba** [comment]
¿Qué tal esta sugerencia mia?
https://decide.madrid.es/proposals/5994

**Comment by voodoorai2000** [comment]
Gracias @ManjiChiba ya lo tienes online :)

Closed via #855
