### ISSUE TITLE
Navegación temática y por distritos

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#686]
Limitar el menú Tendencias a sólo 5 elementos. 

Además añadir dos menús más en la barra lateral por debajo de Tendencias: Categorías y Distritos. 
El primero, Categorías, tiene un enlace por cada etiqueta temática (pero que el enlace realmente lleve a una búsqueda con la palabra de la etiqueta, así arreglamos el que "Economía/economía/Economia/" aparezcan en la misma lista). 

El segundo, Distritos, tiene un pequeño mapa de Madrid. Al hacer click en el mapa lleva a una nueva página con un mapa grande de madrid, con cada distrito clickable. Al hacer click lleva a una búsqueda con el nombre del distrito. Debajo del mapa también está una lista con los nombres de los distritos, por si se prefiere a hacer click en el mapa (y para poder ahorrarse el mapa en el móvil si hace falta). 

También poner un botón "Hacer una propuesta para el distrito:" con un selector con todos los distritos. Al hacer click se va al formulario de crear propuesta, donde se añade por defecto la etiqueta correspondiente al distrito (que no se podrá quitar). Esta página además de para etiquetar mejor las propuestas se usaría mucho en los distritos para redireccionar a la gente a ella, y organizar mejor sus propuestas de distrito.

Relacionado con #685

**Comment by decabeza** [comment]
Dejo un par de mockups para esto:

Página principal con sidebar nueva:

![distritos_sidebar](https://cloud.githubusercontent.com/assets/631897/11242387/a651443e-8e01-11e5-8778-981f4a6616cd.jpg)

Página a la que se llega pulsando en el mapa de "Distritos":

![distritos_page](https://cloud.githubusercontent.com/assets/631897/11242390/aae4d9b6-8e01-11e5-9876-1a65f87f5f78.jpg)

**Comment by Perisso** [comment]
Nos la quedamos Anyelo y yo.

**Comment by decabeza** [comment]
¡Perfecto @Perisso y Anyelo! :+1:

**Comment by decabeza** [comment]
Para la parte del mapa se podría usar un [HTML Map](http://www.w3schools.com/tags/tag_map.asp). Algo similar como ejemplo es lo que hacen en la web de [idealista](http://www.idealista.com/alquiler-viviendas/madrid-madrid/mapa).

**Comment by decabeza** [comment]
La parte de mostrar sólo 5 tendencias se está haciendo en el #687 :wink:

**Comment by decabeza** [comment]
@Perisso y Anyelo os dejo un JPG con la imagen del mapa y el HTML con el mapa de imagen con los enlaces a cada distrito :smile: 

![distritos_madrid](https://cloud.githubusercontent.com/assets/631897/11335128/1015e344-91da-11e5-81bb-943552c91fdb.jpg)

```html

<a href="#">

  <img src="distritos_madrid.jpg" alt="" width="425" height="504" usemap="#MadridMap"/>

  <map name="MadridMap">
    <area shape="poly" coords="3,86,27,60,134,54,220,88,295,3,348,85,312,108,230,94,270,198,248,239,200,259,57,235,34,164" href="/proposals?tag=Fuencarral-El+Pardo" title="Fuencarral - El Pardo" alt="Fuencarral - El Pardo">
    <area shape="poly" coords="54,234,200,261,185,329,115,355,125,290,105,288,90,261,50,246" href="/proposals?tag=Moncloa-Aravaca" title="Moncloa - Aravaca" alt="Moncloa - Aravaca">
    <area shape="poly" coords="199,258,228,253,224,292,199,290,196,292" href="/proposals?tag=Tetu%C3%A1n" title="Tetuán" alt="Tetuán">
    <area shape="poly" coords="190,292,222,294,224,324,193,317" href="/proposals?tag=Chamber%C3%AD" title="Chamberí" alt="Chamberí">
    <area shape="poly" coords="190,317,184,342,214,352,218,325" href="/proposals?tag=Centro" title="Centro" alt="Centro">
    <area shape="poly" coords="179,335,113,357,48,355,68,406,114,416,147,381,181,350" href="/proposals?tag=Latina" title="Latina" alt="Latina">
    <area shape="poly" coords="178,353,198,370,176,412,116,416,176,354" href="/proposals?tag=Carabanchel" title="Carabanchel" alt="Carabanchel">
    <area shape="poly" coords="184,342,218,351,238,373,214,390,183,348" href="/proposals?tag=Arganzuela" title="Arganzuela" alt="Arganzuela">
    <area shape="poly" coords="178,412,201,371,222,420" href="/proposals?tag=Usera" title="Usera" alt="Usera">
    <area shape="poly" coords="177,415,225,424,245,470,183,478,168,451" href="/proposals?tag=Villaverde" title="Villaverde" alt="Villaverde">
    <area shape="poly" coords="231,247,224,303,237,309,257,300,246,241" href="/proposals?tag=Chamart%C3%ADn" title="Chamartin" alt="Chamartin">
    <area shape="poly" coords="223,306,235,310,256,301,258,335,219,332" href="/proposals?tag=Salamanca" title="Salamanca" alt="Salamanca">
    <area shape="poly" coords="218,334,259,338,240,369,216,350" href="/proposals?tag=Retiro" title="Retiro" alt="Retiro">
    <area shape="poly" coords="214,390,250,356,265,362,271,372,295,384,291,397,256,406,243,420,223,422" href="/proposals?tag=Puente+de+Vallecas" title="Puente de Vallecas" alt="Puente de Vallecas">
    <area shape="poly" coords="227,423,258,407,292,397,295,387,322,398,323,413,374,440,334,494,317,502,261,468,246,471" href="/proposals?tag=Villa+de+Vallecas" title="Villa de Vallecas" alt="Villa de Vallecas">
    <area shape="poly" coords="271,197,297,205,320,203,338,229,305,255,301,272,326,295,277,296,258,265,262,245,249,238" href="/proposals?tag=Hortaleza" title="Hortaleza" alt="Hortaleza">
    <area shape="poly" coords="334,217,391,207,387,222,420,274,410,305,327,295,312,283,304,258,339,232" href="/proposals?tag=Barajas" title="Barajas" alt="Barajas">
    <area shape="poly" coords="246,240,258,243,258,267,285,307,301,347,258,338,255,271" href="/proposals?tag=Ciudad+Lineal" title="Ciudad Lineal" alt="Ciudad Lineal">
    <area shape="poly" coords="259,338,302,346,290,380,251,355" href="/proposals?tag=Moratalaz" title="Moratalaz" alt="Moratalaz">
    <area shape="poly" coords="282,295,404,306,372,320,351,340,335,359,303,346" href="/proposals?tag=San+Blas-Canillejas" title="San Blas - Canillejas" alt="San Blas - Canillejas">
    <area shape="poly" coords="291,381,304,347,335,362,351,342,358,355,392,358,404,342,423,360,417,392,393,387,375,438,325,413,323,393" href="/proposals?tag=Vic%C3%A1lvaro" title="Vicálvaro" alt="Vicálvaro">
  </map>
</a>

```

**Comment by Anyelito** [comment]
Vamos a crear dos tablas, una de categorias y otra de distritos. ¿Como hacemos para que esta parte del modelo de datos solo esté disponible para el ayuntamiento de Madrid y no en consul?

**Comment by xuanxu** [comment]
@Anyelito Un par de detalles:
Para las categorías no debería hacer falta un modelo nuevo, la idea es usar etiquetas. Bastaría con hacer un tipo de etiquetas nuevo.
Por otro lado esta funcionalidad no es específica de Madrid, porque los distritos y las categorías han de poder ser creados/editados desde la zona de administración, así que va bien al repo de Consul.

**Comment by Anyelito** [comment]
¿No sería conveniente que estuviera el nombre del distrito impreso en el plano?

**Comment by decabeza** [comment]
@Anyelito Creo que con el listado y el title al hacer hover es suficiente, de todas formas adjunto una versión con los nombres en el mapa para probar como queda :wink: 
  
![distritos_madrid](https://cloud.githubusercontent.com/assets/631897/11714935/190d9f7a-9f3e-11e5-8395-09dd95ac8225.jpg)

**Comment by ManjiChiba** [comment]
Esto si que es genial (y creo que urgente para descongestionar el bloque principal).
Básicamente es lo que propongo yo en https://decide.madrid.es/proposals/5994, pero mucho mas chulo y accesible con el mapa.

**Comment by voodoorai2000** [comment]
Gracias @ManjiChiba :)

Closed via #855
