### ISSUE TITLE
Mostrar las etiquetas por tiempo y categoría

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#687]
En las etiquetas 'Tendencia' mostrar las 5 etiquetas más usadas pero sólo de la última semana (no como ahora de todos los tiempos). 

Y al estar en la búsqueda de una categoría mostrar las tendencias de esa categoría, no las generales.

**Comment by pardoam** [comment]
Esta es de Elena y Ana

**Comment by voodoorai2000** [comment]
:+1: :+1:

**Comment by pardoam** [comment]
Buenos días Rai, nos podrías indicar como restar una semana a la fecha created_at de la tabla taggins? Hemos visto por internet que se calcula de esta forma ( t6 = t0 - dhms2sec(7) # resta 1
 semana) debemos incluirla en el controlador CommentableActions?

**Comment by xuanxu** [comment]
@pardoam: una forma más elegante de calcularlo que esa fórmula sería: `created_at - 7.days`

**Comment by voodoorai2000** [comment]
El lugar apropiado para añadir este código es en el modelo, utilizando un *scope*. Y después llamar a ese *scope* desde el *concern* CommentableActions.

**Comment by pardoam** [comment]
Hola, este scope estaría bien definido para que la fecha create_at sea de la última semana?
scope :last_week, -> {where create_at >= (time.now - 7.days) }

**Comment by pardoam** [comment]
Podeis incluir a Elena (morenohe@madrid.es) en la respuesta, gracias.

**Comment by xuanxu** [comment]
sería algo así: 
```ruby
scope :last_week, -> { where("created_at >= ?", 7.days.ago) }
```

**Comment by pardoam** [comment]
Hola, estoy clonando de nuevo el espacio de trabajo y me da este errror al hacer el create:
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "host"=>"localhost", "pool"=>5, "username"=>nil, "password"=>nil, "database"=>"participacion_test"}
Las carpetas están vacias. 
Ayuda, please

**Comment by microweb10** [comment]
Si no la esta haciendo nadie, me cojo esta!

**Comment by voodoorai2000** [comment]
Muchas gracias @microweb10! 
Este issue está bastante avanzando, sólo le falta algún test. https://github.com/consul/consul/pull/743
@pardoam ¿cómo vas de tiempo para finiquitar este issue?"

**Comment by microweb10** [comment]
ah! vale. Como aun llevaba la etiqueta de PR-welcome ...

**Comment by voodoorai2000** [comment]
Gracias @microweb10, etiqueta quitada!

**Comment by voodoorai2000** [comment]
Creating a new issue [857](https://github.com/consul/consul/issues/857) with the pending requirements.

Closed via #743
