### ISSUE TITLE
Estilos de comentarios ocultos

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#692]
Cuando se oculta un comentario sin hijos, queda un espacio hasta el siguiente comentario.

Por ejemplo: 
https://decide.madrid.es/debates/4298
Buscar el comentario de Carlos Sánchez que empieza por: 'La elusión fiscal en este tema ha sido enorme. '

**Comment by decabeza** [comment]
@voodoorai2000 lo único que he visto es que cuando se oculta el hijo de un comentario se queda una línea (arreglado en la rama **deleted_comments**):

![deleted_children](https://cloud.githubusercontent.com/assets/631897/11151842/90589e96-8a2f-11e5-83e4-e628815bb4ab.jpg)

Si el comentario no tiene hijos no deja rastro.

Si tiene hijos y es eliminado aparece el mensaje:

![deleted_comment_with_children](https://cloud.githubusercontent.com/assets/631897/11151860/afa280fa-8a2f-11e5-802e-22977e1f5725.png)

En esta rama fallan unos cuantos test y no sé por qué :dizzy_face:

**Comment by voodoorai2000** [comment]
:+1:

**Comment by voodoorai2000** [comment]
Old issue, this was fixed a while ago.
