### ISSUE TITLE
Ver votos emitidos

### ISSUE THREAD

**Issue by Almorca** [consul/consul#713]
Se debería poder ver los votos emitidos (tanto a debates como a otros comentarios) en el área de Mi actividad.

**Comment by Perisso** [comment]
y poder votar?

**Comment by voodoorai2000** [comment]
Gracias por la sugerencia @Almorca! Por razones de privacidad y neutralidad el area de gobierno esta estudiando si podemos y debemos implementar esta funcionalidad. De momento la cerramos.

**Comment by Almorca** [comment]
Sólo por aclarar la petición. Lo que se debería poder ver son** tus propios votos emitidos** para poder ver que propuestas has votado. Entiendo que ahí no existe ningún problema de privacidad
