### ISSUE TITLE
API Pública

### ISSUE THREAD

**Issue by alexruperez** [consul/consul#714]
Estaría muy bien hacer una API pública para poder crear aplicaciones móviles o servicios de terceros.

Hay un par de gemas compatibles con Devise que permitirían la autenticación a través de un token:
https://github.com/lynndylanhurley/devise_token_auth
https://github.com/gonzalo-bulnes/simple_token_authentication

**Comment by hrules6872** [comment]
:+1:

**Comment by Mun0n** [comment]
Gran iniciativa!

**Comment by Mun0n** [comment]
:+1:

**Comment by josepjaume** [comment]
¿Qué os parecería usar el estándar JSON API? http://jsonapi.org/

Me parece un formato muy descriptivo y fácil de implementar/consumir. Para ruby hay algunas gemas interesantes:

https://github.com/rails-api/active_model_serializers
https://github.com/cerebris/jsonapi-resources

**Comment by Mun0n** [comment]
@josepjaume desde mi punto de vista androide me parece genial. Sería un puntazo para ponernos a hacer una app funcional. Ojalá salga adelante. Gracias!

**Comment by Mun0n** [comment]
https://decide.madrid.es/proposals/5727

**Comment by albertvp** [comment]
:+1: con documentación generada por swagger
http://swagger.io
https://github.com/richhollis/swagger-docs

**Comment by voodoorai2000** [comment]
WIP in progress, we are trying two implementations, one with REST and one with GraphQL:
https://github.com/consul/consul/pull/1238
https://github.com/consul/consul/pull/1257

We are really liking GraphQL
Which one do you prefer?

**Comment by josepjaume** [comment]
GraphQL! 💃 . It's way more expressive, adapted to modern times (multiple consumers!), self-documented. Way to go!

**Comment by alexruperez** [comment]
GraphQL is cool, but I prefer REST to avoid add GraphQL dependency, here and in all future clients.

**Comment by josepjaume** [comment]
The way I see it, GraphQL is a superset of REST. You can still use GraphQL in a RESTful way - just provide fixed queries. You could even build a REST server on top of a GraphQL server, providing you're sending static queries.

The development on `graphql-ruby` is very active and GitHub is using it, so I'd say is not a dangerous dependency.

**Comment by josepjaume** [comment]
Also, I think generally it's way better to depend on a library to access an external API than to have to write a client from scratch *every* time.

**Comment by voodoorai2000** [comment]
This feature is ready to launch. You can try it out in this [branch](https://github.com/consul/consul/pull/1257) using the GUI at /graphiql

Closing this issue.

Awesome work @amiedes :raised_hands:
