### ISSUE TITLE
Mejor rendimiento en debates con muchos comentarios

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#716]
En debates como el de Manuela https://decide.madrid.es/debates/4320 con 300 comentarios, el envío de comentarios tarda muchos segundos.

Sugerencias:
Mover los callbacks que se ejecutan al crear un comentario a una cola utilizando ActiveJob

**Comment by Perisso** [comment]
Me pongo con ella.

**Comment by decabeza** [comment]
Perfecto @Perisso! :+1:

**Comment by Perisso** [comment]
Hay que usar la gema: delayed_job_active_record?

**Comment by javierm** [comment]
This issue seems to be obsolete. We're using an AJAX call to add a new comment, and the time it takes to add a comment seems to be the same whether the debate has 300+ comments or only one comment.
