### ISSUE TITLE
Add i18n to info pages

### ISSUE THREAD

**Issue by xuanxu** [consul/consul#721]
Most of the long texts in the 'more info' section are hardcoded. We have to move them to locale files.

**Comment by Ana06** [comment]
I'll do it!

**Comment by decabeza** [comment]
Thanks @Ana06! You can use [Redcarpet gem] (https://github.com/vmg/redcarpet) to use markdown :wink:

**Comment by Ana06** [comment]
Can I add i18n to info pages without translate them? I mean that the english i18n file would be in spanish.

**Comment by decabeza** [comment]
@Ana06 At the moment we won't do this because we have to delete some info pages and create only a few generic examples of pages.

**Comment by Ana06** [comment]
Ok! :)

**Comment by decabeza** [comment]
Close this issue because the info pages are already translated.

I created a new issue for this pending locale site customization feature. #1647
