### ISSUE TITLE
Add a contact email and link to github issues

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#722]
For users to report problems and improvements with ease, we should have a visible email address and reference to the repo's issue page.

Right now there is a 'Technical Assistance' link in the footer, but it does not include these two links.

**Comment by albertomg994** [comment]
Is it posible to work on issues tagged as "open" where there's no-one assigned but without the label "PRs-welcome" (this one, for example)? If affirmative, I'll try to solve this one. Which e-mail address do I have to put in the link?

**Comment by chkoun** [comment]
Hi,
Redirecting to the Github page or adding an email may be to restrictive, there is currently a Help section dedicated for Technical Assistance under the Help Page.
![Screenshot from 2021-11-06 13-18-31](https://user-images.githubusercontent.com/92028375/140609482-21b13525-d11f-4c57-bd6c-bbf26c379714.png)
We could instead redirect the user to the Help Page ( only if the feature is enable ) or hide it if there is no Help page
This allow to let the admin decide how to receive requests regarding issues ( FAQ, Email, Link to Github, Phone etc .. )

**Comment by javierm** [comment]
@chkoun Agreed :+1:.

Since issue #3125 is also about the same link and IMHO it better describes the current problem, I'm closing this issue in favor of #3125.
