### ISSUE TITLE
Use capistrano to automate maintenance mode  

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#728]
We are currently using the [turnout gem](https://github.com/biola/turnout) to enter maintenance mode.
It is necessary to ejecute the maintenance rake task in every server.
It would be nice to create a capistrano task to ejecute this rake task in every server.

**Comment by aitbw** [comment]
I'm gonna handle this one as well. Is there anything I should be aware of before proceeding?

**Comment by voodoorai2000** [comment]
Great, no warnings here :)
