### ISSUE TITLE
Configurable dictionary for full text searches 

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#730]
We are currently using Postgres's spanish dictionary for full text search.
We would like to use different dictionaries depending on the configuration of a particular Consul instance.

Suggestion:
Use a setting's key to define the desired dictionary.

**Comment by javierm** [comment]
@katafrakt has offered his help on this one. Thank you very much! :smile:

Maybe we could start by basing it on I18n.default_locale. It that doesn't seem the most simple solution to you, let us know!

**Comment by katafrakt** [comment]
Makes sense to start with that :+1:
