### ISSUE TITLE
Mostrar propuestas parecidas según se escribe una propuesta, para solucionar la repetición de las mismas

### ISSUE THREAD

**Issue by wurik** [consul/consul#748]
Hay un serio problema de repetición de propuestas; y hay una solución magnifica en la que podemos inspirarnos 
Se trata del creador / buscador de propuestas de UserVoice http://feedback.uservoice.com/forums/1-general-feedback Cuando uno crea una propuesta, al mismo tiempo también la está buscando; esto ahorraría un gran dolor de cabeza a los administradores, y permitiría un consenso más justo.

**Comment by xuanxu** [comment]
Gracias por la sugerencia @wurik!
Estamos implementando algo muy parecido: #599 
(Cierro este issue para no tener temas duplicados)
