### ISSUE TITLE
Stylesheet structuring improvements

### ISSUE THREAD

**Issue by josepjaume** [consul/consul#752]
While I'm building Barcelona's consul fork, I've realized the stylesheets might need a bit of work, particularly when it comes to organization. Here's what improvements think can be made:
### Structure files in a folder hierarchy

The stylesheet files are spread within a small amount of really long files. Take `layout.scss` for example: https://github.com/consul/consul/blob/master/app/assets/stylesheets/layout.scss

Of course there's structure inside the file, but I think splitting it into smaller files inside a `layout` folder would work better for several reasons:
- It'd be easy to find what you're looking for
- You can take full advantage of sass' caching, as we would be invalidating lesser amount of code in each recompilation.
### Unify variable management

We have variables split into two different files: `variables.scss` and `foundation_and_overrides.scss`. I believe we could have a single file that rules them all, as some variables would work better if we're to reuse them (as the `$brand` color, distances, etc).

I tried to directly import `variables.scss` into `foundation_and_overrides.scss` but everything broke and Zalgo was released. There's probably some variable collisions there.
### Use derivatives of the `$brand` color

Instead of manually defining each shade of the `$brand` color, we could use color functions as `lighten`, `darken`, `saturate`, `desaturate`, etc in order to make the developer's life easier.
### Leverage `libsass` for faster compilation

`libsass` is a C implementation of the `sass` compiler which is 4x faster and is built by Hampton Catlin (sass creator) so I don't think it's going anywhere. There's a gem that makes it compatible with sprockets:

https://github.com/sass/sassc-rails
### Feedback?

That's all for now! Since I'm in the initial stages of the project, I'd be happy to work on it straight away.

What do you think?

**Comment by voodoorai2000** [comment]
This issue has become obsolete, css structure has greatly improved.
