### ISSUE TITLE
Swap all occurrences of `Madrid` with a Setting or i18n translation

### ISSUE THREAD

**Issue by josepjaume** [consul/consul#753]
As I'm trying to customize Barcelona's fork, I've realized Madrid is hardcoded in many places. Is there any work in progress in trying to put a parameterized setting in there?

I can surely work on it.

**Comment by xuanxu** [comment]
Hey @josepjaume, this is a pending task but no one is working right now on it, so feel free to create a host_place_name setting and go for it

**Comment by josepjaume** [comment]
Great!

**Comment by josepjaume** [comment]
Working on it on https://github.com/consul/consul/pull/763

**Comment by voodoorai2000** [comment]
Closed via #763 Thank you @josepjaume!
