### ISSUE TITLE
Should pages belong in consul?

### ISSUE THREAD

**Issue by josepjaume** [consul/consul#764]
While working in https://github.com/consul/consul/pull/763, I've realized that pages maybe shouldn't belong to consul, as they're coupled with each particular process; each for will have its own.

Instead of trying to push that to the translation files, or trying to provide an in-house solution, I think it's better to leave this to each developer.

In the end, this looks like `consul` might fit in a rails engine (or maybe an ecosystem of engines) much like [Solidus](https://github.com/solidusio/solidus) does.

Thoughts?

**Comment by voodoorai2000** [comment]
Closing as pages do not belong in Consul anymore.
They are now generated through the admin section.
PR #1484
