### ISSUE TITLE
Dockerización

### ISSUE THREAD

**Issue by kikito** [consul/consul#78]
Dado que configurar ruby + rails es complicado, y requiere modificaciones significativas en el entorno de desarrollo. Es deseable utilizar un entorno de virtualización que:
- Sea lo más parecido posible al entorno de producción
- Instale todas las dependencias y configuraciones necesarias para el desarrollo en una máquina virtual
- Permita ejecutar una versión de desarrollo de la aplicación
- Permita ejecutar los tests de la aplicación

Aunque Vagrant permite realizar esta tarea, hemos decidido utilizar Docker (ver #69)

En estos momentos el entorno de producción que se está barajando es RHEL+Apache+Passenger con una base de datos PostgreSQL. Se recomienda utilizar CentOS como imagen base en Docker, ya que RHEL es problemático en este sentido por temas de licencia y disponibilidad.

**Comment by oinak** [comment]
He hecho un PR en https://github.com/AyuntamientoMadrid/participacion/pull/122 al respecto de esto.
Tengo razones técnicas para elegir la imagen base y procedimientos usados, las puedo detallar, debatir y/o cambiar si se requiere.

Espero que os sea útil.

**Comment by xuanxu** [comment]
Gracias @oinak!
En general lo veo OK excepto un par de cosas que cambiaría:

* _No modificar el database.yml_: El database.yml.example debería hacer que pasen los tests sin tocar nada y con el cambio esto [ya no pasa](https://travis-ci.org/AyuntamientoMadrid/participacion/builds/74688649) 
* _No cambiar el mailer de desarrollo_: relacionado con la razón anterior quitar letter_opener para usar smtp mete otro requisito de inicio que prefiero evitar.

Ambos cambios asumen que el entorno de desarrollo/tests por defecto va a ser usando Docker, y eso no me convence, a ver qué opina @kikito

**Comment by oinak** [comment]
En el caso del database.yml, puedo crear un database.docker-example.yml para ser amigable con el developer que elija docker Y con travis.

En el caso de letter-opener, podemos dejar la gema pero hacer la configuración de action_mailer usar mailcatcher si y solo si hay variables de entorno de Docker, ambos cambios son fáciles.

¿Bastaría con esto?

**Comment by kikito** [comment]
Me parecen bien los arreglos, adelante con ellos @oinak

**Comment by xuanxu** [comment]
En cuanto al database.yml yo creo que en vez de añadir un database.docker-example.yml es mejor que simplemente menciones en la documentación  los cambios necesarios.

**Comment by oinak** [comment]
@kikito Hechos los cambios, travis pasa.
@xuanxu un archivo de texto de 5 lineas no molesta y un cp es mas cómodo, que encontrar el detalle en la documentación y copiar contenido de ahí a un fichero.

Muchas gracias por vuestros comentarios.

**Comment by rafacouto** [comment]
Necesitamos que fijeis tags con versiones para dockerizar. Podéis basarlos en el roadmap o fechas de lanzamiento, pero fijad algún tag inicial... :abc:

**Comment by conatus** [comment]
Hi folks.

Momentum in the UK have got a version of Consul running in Docker. https://github.com/PeoplesMomentum/consul

@binocarlos is the best person to ask about its implementation however.

Apologies for the English!

**Comment by voodoorai2000** [comment]
Hey @conatus!

We are very happy to see Consul running at Peoples Momentum :))

Yes, we would love to have a Docker way of running Consul.
@binocarlos you think you could send us a PR with the basics?

Cheers and all the best at https://mxv.peoplesmomentum.com/

**Comment by conatus** [comment]
Seems Barcelona's fork also has support for Docker but in a less comprehensive way than Momentum.

https://github.com/AjuntamentdeBarcelona/decidim.barcelona

**Comment by bertocq** [comment]
Closed via #2127
