### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#784]
ToDo:
- [x] Make specs pass
- [x] Fix deprecation warnings
- [x] Manually try in staging environment to check features of major gem updates

WIP branch [rails5](https://github.com/wairbut-m2c/consul/commits/chore/rails5)

**Comment by xuanxu** [comment]
Fuck yeah

**Comment by decabeza** [comment]
:clap:

**Comment by voodoorai2000** [comment]
Closed via https://github.com/consul/consul/pull/3414
