### ISSUE TITLE
Inform users to identify themselves in order to vote comments

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#790]
When you are not logged in and try to vote for a comment there is no hint to log in. You simply cannot vote a comment.

We should implement something similar to what happens when you try to vote for a debate/proposal without being logged in.

**Comment by palomahnhp** [comment]
@MaiteHdezRivas y yo nos ponemos con este issue

**Comment by decabeza** [comment]
Already on production! :tada:
