### ISSUE TITLE
Upgrade to Ruby 2.3.0

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#791]

**Comment by tomdemeyer** [comment]
Seems to run ok on 2.3.0 (debian/jessie)

These two tests fail: 
rspec ./spec/features/legislation_spec.rb:40 # Legislation Annotations Update
rspec ./spec/features/admin/spending_proposals_spec.rb:146 # Admin spending proposals Index Filtering by valuator
Seem not to be ruby issues.

**Comment by voodoorai2000** [comment]
Thank you for trying this out @tomdemeyer!

If you have some time to send a Pull Request updating the file [.ruby-version](https://github.com/consul/consul/blob/master/.ruby-version) we can wrap up this issue.

**Comment by voodoorai2000** [comment]
Closed via #1139
