### ISSUE TITLE
Sub-secciones varias

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#795]
Buenos días, quería proponeros una distribución que creo que sería más limpia para las personas que entran a la web.

![madrid decide 1](https://cloud.githubusercontent.com/assets/16508522/12070904/c008f9ec-b090-11e5-8519-16e40130a614.jpeg)

Otra posibilidad podría ser:

![madrid decide 2](https://cloud.githubusercontent.com/assets/16508522/12070906/dedd841e-b090-11e5-929f-95221057df38.jpeg)

Se que en la parte de Distritos ya estáis trabajando, pero creo que las secciones de "El Ayuntamiento no tiene competencias" también son muy urgentes para descongestionar las más de 275 páginas x 25 comentarios de propuestas repetidas (algunas estarán repetidas, lo menos 50 veces).
Si necesitáis ayuda (y me habilitáis temporalmente la posibilidad de hacerlo), os ayudaría a moverlas o a colocarlas las etiquetas necesarias para ello.
Creo que actualmente muchas personas están abandonando la web (o su uso), debido a la descorazonadora vista de tantas propuestas repetidas hasta la saciedad, y como las que pueden ser interesantes, pero tienen pocos votos se hunden entre este maremagnun de propuestas repetidas.

**Comment by xuanxu** [comment]
Gracias por la propuesta. El tema de las subsecciones y la navegación está siempre sujeta a replanteamientos. Nos apuntamos la idea de categorizar por cantidad de apoyos. El tema de dividir por competencias creo no es lo suficientemente genérico como para incluirlo en Consul, que puede ser utilizado por entidades no gubernamentales o de diferentes niveles.

**Comment by ManjiChiba** [comment]
Bueno días de nuevo, hoy he visto que habéis puesto a la derecha el mapa de Madrid para poder ver (supongo que mediante masks, filtros o algo similar) las propuestas de un distrito concreto.
![mapamadrid](https://cloud.githubusercontent.com/assets/16508522/12613523/9e6f189c-c4fa-11e5-8e40-13b985dfa9a9.jpg)
Esta MUY bien y queda muy chulo, peeeeeeero....:
1º Me da que las propuestas que muestra son las que encuentra con una búsqueda por cadena string = nombre del Distrito (por ejemplo LATINA), peeeeero, si en el encabezado NO aparece la palabra LATINA, no la muestra.
Si hace falta algún voluntario para ir catalogando cuales son las de cada distrito... me presento voluntario, pero SOLO para las de mi distrito, volver a mirarme 1x1 las más de 7.500 propuestas me da vértigo.
Si habilitais un botón de "avisar a administración o moderación" en las propuestas podría ir informando de aquellas que vea que aunque no lo indique en la cabecera sean de mi Distrito (hay muchas que se menciona sólo el nombre de una calle, un parque o algo similar, sin indicar donde están ubicadas y habría que buscarlo en google maps).
![meristation](https://cloud.githubusercontent.com/assets/16508522/12613627/32bb3a12-c4fb-11e5-9129-6a22dbc18e14.jpg)
2º Aunque el sistema esta muy chulo (el mapa de Madrid dividido por Distritos), sigue habiendo el mismo problema, y es que, están todas las propuestas juntas (más de 7.500) sin estar separadas en sub-secciones por distritos tal y como sugería al inicio de la petición. Esto desmoraliza mucho a las personas que están entrando nuevas (ya he comprobado que mucha gente, entró, hizo una sóla propuesta y se debió de deprimir al ver la cantidad de páginas (290 y subiendo) de propuestas repetidas una tras otra, porque no ha vuelto a hacer ninguna más y me da, que ni se han vuelto a conectar).
De todas formas, mi enhorabuena por tan buen trabajo.
