### ISSUE TITLE
Poder añadir y subir fotos o gráficas (.jpg, .png) en los hilos

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#797]
Creo que sería interesante que fuera un proceso tan sencillo como aquí con un "Attach files by dragging & dropping" y que no se tengan que alojar en un hosting externo y tener que referenciarlas mediante un link (mejor que sea incrustado o embebido).

https://decide.madrid.es/proposals/6984

**Comment by xuanxu** [comment]
Aunque esta posibilidad se planteó inicialmente, ahora mismo está descartada para centrar el desarrollo en temas más prioritarios. Es posible que se replantee en el futuro, cierro el issue de momento.
