### ISSUE TITLE
Limpieza urgente y a gran escala de propuestas repetidas

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#798]
Para borrar (a petición del propio creador de la propuesta) las propuestas repetidas o sin vigencia.

https://decide.madrid.es/proposals/6918

**Comment by xuanxu** [comment]
Una vez que la propuesta está en marcha ya no es propiedad del autor. Para eliminarla haría falta el permiso de todas las personas que la han apoyado. Vamos a atacar el tema de las propuestas duplicadas mediante un [par](https://github.com/consul/consul/issues/588) de [issues](https://github.com/consul/consul/issues/599). Una vez que estén en marcha replantearemos si hace falta añadir funcionalidades relacionadas. Cierro el issue para focalizar los esfuerzos en los issues en marcha.
