### ISSUE TITLE
Que el creador de una propuesta pueda borrarla voluntariamente por duplicidad

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#799]
¿Qué tal un botón al lado del de "Editar propuesta" de "Solicitar borrado propuesta"?

Así, el propio autor de la propuesta podrá solicitar al administrador el borrado de dicha propuesta (justificando el porque de dicha solicitud).
Si en vez de Borrado se pasa a un histórico o simplemente está, pero NO se muestra (esta invisible por algún tipo de mask) eso es algo que tenéis que sopesar los administradores.

https://decide.madrid.es/proposals/6879

https://decide.madrid.es/proposals/5260

**Comment by xuanxu** [comment]
duplicado de #798
