### ISSUE TITLE
Enlace directo por e-mail a la respuesta en una conversación (¿Se puede borrar?)

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#800]
He visto, que más o menos, lo que solicitaba en este post, ya se ha solucionado con las nuevas opciones de notificación con el icono de la campanita.
Por cierto, mi enhorabuena. MUY buen trabajo. :-) (me siguen faltando los emoticonos para poder expresame mejor ;-) ).

En por ejemplo MeriStation. Cuando alguien responde a algún comentario tuyo, recibes el correspondiente e-mail con un link y al pulsar sobre él, automáticamente se te posiciona debajo del comentario de dicha persona.
En la web de Decide Madrid, creo que te lleva al encabezado de la primera página del hilo de la propuesta y te toca buscarlo personalmente.
Cuando es una sóla página de comentarios... pues no hay mucho problema, buscas el nick de la persona que te pone en el e-mail que ha recibido buscándolo con control+F y lo localizas más o menos rápido, pero cuando son varias páginas (por ejemplo tema toro con más de 7 páginas de comentarios...), tienes que ir 1 por 1 haciendo el mismo proceso hasta encontrar DONDE te han respondido.

https://decide.madrid.es/proposals/6758

**Comment by Perisso** [comment]
Me la quedo

**Comment by decabeza** [comment]
Hecho en #897 :tada:
