### ISSUE TITLE
¿Botón abstención?

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#801]
Creo que aunque ha sido marcada "como inapropiada" (tampoco creo que sea para tanto), mi propuesta 
https://decide.madrid.es/proposals/5173
tiene sentido.

No veo más que comentarios despectivos de falangistas-trolls de medio pelo, de que "esta web es un timo, y sólo la usan 4 gatos sectarios, ya que la propuesta con más apoyo, apenas llega a los 9.000 apoyos" y me jode leer esos comentarios y no poder hacerles un zasca en toda la boca.
La intención es torpedear la web y la Democracia Participativa e incluso me atrevería a afirmar que a Ahora Madrid.
Creo que se si implementara la opción de Abstención, se podría acallar bastante a estos boca-chanclas, ya que, si por ejemplo, una propuesta tuviera 5.000 apoyos pero 300.000 abstenciones, ya no les serviría el argumento ese de "esta web sólo la utilizan 4 gatos sectarios".
Yo, hay muchas propuestas, que no las apoyo (algunas, porque ni siquiera las entiendo y otras porque ni entro ni salgo en su temática), pero tampoco estoy en contra de ellas (me abstengo), y creo que no es lo mismo abstenerse (al menos he entrado y la he leido) que no apoyarla o incluso "pasar de largo" sin entrar a leer el desarrollo.
Por otra parte, creo que ver que una propuesta tuya tiene, por ejemplo, 150 apoyos y 350 abstenciones... te da una información bastante valiosa para poder mejorar tu propuesta.
A mi, me transmitiría varias posibilidades, por ejemplo:
Que la cabecera es clara e incentiva a las personas a entrar, pero el desarrollo no les termina (por algún motivo que tendré que averigüar) de convencer para apoyarla.
Si por ejemplo, resulta que cambio el enunciado y de repente pasa a 200 apoyos y 300 abstenciones (supuesto que al cambiar el enunciado se envíe automáticamente un e-mail a todas las personas que apoyoran o se abstuvieron en dicha propuesta, para avisarles de que el texto ha cambiado, por si ahora quieren apoyarlos o retirar su apoyo), entonces, estaré por el buen camino.
Por el mismo motivo, creo que también sería interesante el mismo botón en los debates.
Que tengo que definir mejor los casos a los que se aplicaría dicha propuesta.
Que pueda estar de acuerdo con algunos de los puntos de la propuesta, pero NO con otros (enmienda parcial, que, en caso de subsanarse, como he hecho en alguna de mis propuestas, ha hecho que consiga algún apoyo adicional).
En fin, espero haberme explicado con suficiente claridad.

**Comment by xuanxu** [comment]
No traction on this issue. Closing.
