### ISSUE TITLE
Para poder reunificar posts (sugerencia)

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#802]
Ya he visto que algún conciudadano a propuesto alguna idea para poder reunificar hilos (las cuales he apoyado porque me parecen oportunas). Yo quería sugerir la siguiente, y es que, haya un periodo entre que el usuario le da a "publicar" y la publicación definitiva de su sugerencia, en que, los administradores, que seguramente estén más al día y al tanto de las propuestas aparecidas, puedan sugerir su NO publicación porque ya existe una previa, y remitir al autor de la sugerencia a la existente anteriormente, por si esta de acuerdo en que no hace falta publicarla, pues exista una anterior e igual o similar.
En caso de que el autor, considere que su propuesta es diferente (por un matiz, por ser más generíca que la existente, por ser más concreta/precisa/puntual que la existente), entonces, SI, publicarla.
Vamos, que los administradores, SOLO sugerirían, pero la decisión final sobre publicarla o no, sea del ciudadano.
Os dejo también la idea de forma gráfica con un diagrama de flujo (no soy programador asi que no se si estará bien del todo, pero creo que lo suficiente para que os hagáis un idea aprox).

![madrid decide - nueva propuesta](https://cloud.githubusercontent.com/assets/16508522/12071577/7c75b65c-b0b3-11e5-98a9-903c0e2e8c60.jpeg)

Si lo necesitáis para editarlo y cambiarlo ya lo tengo hecho con con el programa free Dia.

http://madriddecide.webcindario.com/Madrid%20Decide%20-%20Nueva%20propuesta.dia

**Comment by xuanxu** [comment]
Esta posibilidad es inviable por la cantidad de tiempo de moderación necesaria, por esa razón fue descartada ya al inicio del desarrollo.
