### ISSUE TITLE
Advanced Search Polish

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#836]
Critical:
- [x] Fix cross-browser issue with Firefox when selecting a custom date (date picker does not appear) #838 

Nice to haves:
- [ ] Add two more user types: 'user' and 'collective user'
- [ ] Remove one user type: 'municipal organization'

**Comment by inobCR** [comment]
voy a por esta

**Comment by voodoorai2000** [comment]
👍

**Comment by voodoorai2000** [comment]
Partial work done [here](https://github.com/consul/consul/pull/1162), temporarily on hold, anyone feel free to continue

**Comment by javierm** [comment]
This one is obsolete since we replaced user types with official levels.

The last trace of user types disappeared with pull request #1336.
