### ISSUE TITLE
Erase phone number from a deleted account

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#837]
When a user deletes his/her account we should delete the phone number associated to that account, in case they want to create a new account with that same phone number.

**Comment by pardoam** [comment]
Elena y yo, vamos a intentar resolver esta.

**Comment by decabeza** [comment]
Perfect! :+1:

**Comment by morenohe** [comment]
El teléfono asociado a la cuenta, sólo es en el caso de organización/colectivo, no?

**Comment by decabeza** [comment]
@morenohe también sería para el caso de los usuarios (si se han verificado también tienen un teléfono asociado) :wink:

**Comment by voodoorai2000** [comment]
Closed via #930
