### ISSUE TITLE
documentacion

### ISSUE THREAD

**Issue by IB313184** [consul/consul#852]
hola.
tengo instalado consul, pero no se como seguir.

como se entra en administrador, archivos a modificar y customizacion.

gracias.

**Comment by IB313184** [comment]
necesito ayuda, el problema principal ahora es que no manda los correos para verificar del alta, por todo lo demas estaria operativo en mi municipio.

gracias.

**Comment by IB313184** [comment]
estoy añadiendo estas lineas en el "production.rb" y nada

config.action_mailer.default_url_options = { :host => 'xxx.xxx.es' }
config.action_mailer.delivery_method = :smtp
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = false
config.action_mailer.default :charset => "utf-8"
config.action_mailer.smtp_settings = {
  address: "smtp.gmail.com",
  port: 587,
  domain: "xxx.xxx.es",
  authentication: "plain",
  enable_starttls_auto: true,
  user_name: ENV["xxxx@gmail.com"],
  password: ENV["xxxxxxxx"]

o estas tambien.


config.action_mailer.delivery_method = :sendmail
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true


he de decir que ubuntu desde treminal manda correos sin problemas, el tema esta en al APP o algun archivo que a de ser configurado.

gracias.

**Comment by voodoorai2000** [comment]
Hola @IB313184!

Muchas gracias por montar Consul en tu Ayuntamiento!

En breve mejoraremos la documentación con estos temas. De momento escríbenos a muguerzaje@madrid.es y te echamos un mano en lo que haga falta :+1:
