### ISSUE TITLE
Sugerir fusión de propuestas duplicadas

### ISSUE THREAD

**Issue by tombe85** [consul/consul#853]
Si hay dos o más propuestas con el mismo fin y un usuario se da cuenta de ello, podría sugerir la fusión de ambas y que los autores de las propuestas acepten la fusión si lo creen conveniente.
En la propuesta duplicada el usuario que la detecta informaría de la duplicidad y posteriormente debería seleccionar a qué propuesta duplica.
De esta manera evitaríamos, ante un duplicado, que los apoyos de una de las propuestas se pierdan. Ya que se unirían los apoyos de ambas propuestas.

![captura de pantalla de 2016-01-24 01 35 35](https://cloud.githubusercontent.com/assets/9367649/12533750/fe855a7e-c23a-11e5-9800-8621d9defb66.png)

**Comment by decabeza** [comment]
@tombe85 Una vez que la propuesta está en marcha ya no es propiedad del autor. Para poder "fusionarla" haría falta el permiso de todas las personas que la han apoyado. 

Como es algo inviable, ahora mismo estamos trabajando para que se baje el número de propuestas duplicadas en [este issue](https://github.com/consul/consul/issues/599) :wink:

**Comment by ManjiChiba** [comment]
Talvez se podría, no añadir los apoyos, si no, simplemente indicar la nueva propuesta fusionada y que si quieren la apoyen (por ejemplo con una notificación).
Más o menos, es lo que estoy haciendo yo al fusionarlas.
Obviamente, hay personas que apoyan la nueva (fusionada), y otras que no (me da que la mayoría no se enteran, porque, simplemente, no saben donde esta el mensaje de notificación sobre la fusión, sería mucho más eficaz poder hacerlo con un Mensaje Privado en vez de una notificación).
