### ISSUE TITLE
Streamline process to unsubscribe from newsletter

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#856]
Right now if you click on the unsubscribe link in the emails send as newsletter, you are redirected to the account page, where you can unsubscribe from the newsletter.

The process of unsubscribing should not require a user to go to his/her account.

Suggestion:
Use a token in the unsubscribe link, once clicked, verify that the token is valid, unsubscribe the user and redirect him/her to a thank you page.

**Comment by Perisso** [comment]
Intento resolverla.

**Comment by voodoorai2000** [comment]
Hola @Perisso, como comentamos el otro día, este issue requeriría automatizar el envío de newsletters en lugar de hacerlo de forma manual. 
Cierro este issue hasta que estemos más cerca de poder implementarlo.
