### ISSUE TITLE
Trending tags dependent on category or district

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#857]
When we are navigating a certain category or district, the trending tags should depend on the current category or district. 

So, for example, only tags for proposals in that category should be displayed as trending.

**Comment by pardoam** [comment]
Nos ponemos Elena y yo con ello.

**Comment by voodoorai2000** [comment]
Perdona @pardoam este issue se ha vuelto high priority y ya lo tengo casi hecho. Cogeros otro por favor.

**Comment by pardoam** [comment]
Ok, estamos con la issue #837 Erase phone number from a deleted account .

**Comment by voodoorai2000** [comment]
:+1:
