### ISSUE TITLE
Poder reportar a algún administrador directamente.

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#863]
Sería genial poder reportar directamente a algún administrador, como por ejemplo tienen en MeriStation.
![meristation](https://cloud.githubusercontent.com/assets/16508522/12613960/34e643fc-c4fd-11e5-8768-cc0ba3c92067.jpg)
para los siguientes 3 casos:

1) Insultos y faltas de respeto (¿talvez hiciera falta un sistema de baneos temporales incrementales por reincidencia?).
2) Para solicitar el paso a un histórico (o borrado) de una propuesta (bien, porque ya se haya llevado a la práctica, bien por estar duplicada, bien por haber caducado como por ejemplo la de los belenes, etc).
3) Para solicitar su recolocación en una sub-sección diferente, por ejemplo, la sub-sección de un distrito, etc.

**Comment by xuanxu** [comment]
There is a flag icon in every debate/proposal you can use to report to moderators directly: 

![flag](https://cloud.githubusercontent.com/assets/6528/12614380/cab7a414-c4ff-11e5-8819-92447b24be23.png)

Closing

**Comment by ManjiChiba** [comment]
Yes, but it isn´t the same than a MeriStation for example. In MeriStation when you click over the boton of Report, it open a pop-up window where you can write why you contact with the Admin (1, 2 o 3 I write top).

**Comment by kikito** [comment]
Thank you for your comments. We'll take them into account if we need to revisit the content flagging system in the future. For now this issue will remain closed.
