### ISSUE TITLE
Por favor, emoticonos para evitar mal-entendidos.

### ISSUE THREAD

**Issue by ManjiChiba** [consul/consul#864]
¿Se podría poner una cajita con algunos emoticonos sencillos para evitar mal-entendidos?. :-)

**Comment by xuanxu** [comment]
The current standard is emoji, and the website is using UTF encoding so everyone can use emojis in the messages, as you can see here: https://decide.madrid.es/proposals/6985 
Closing

**Comment by ManjiChiba** [comment]
Ah, Ok. Allright. I don´t know what are emoji, but I search information about it. Thanks. And can deleted this Issue.
