### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by blu-IT** [consul/consul#866]
Hello,

thanks for this software!

What about bringing / setting up translations for consul to Transifex? 
I would like to help translating (e.g. German & Italian).

Regards

**Comment by xuanxu** [comment]
Thanks for the suggestion @blu-IT  but we have implemented a translation interface using Tolk where every city can have translators helping.

If you want to help with German or Italian in the Madrid fork for example, you can send an email to ag.gobiernoabierto@madrid.es
