### ISSUE TITLE
Expire admin passwords once a year

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#885]
After one year of creating the account, admin passwords should expire and the admin should be asked to set a new and different password.

**Comment by gitmarcia** [comment]
Me pongo con ella

**Comment by voodoorai2000** [comment]
:clap: :+1:

**Comment by palomahnhp** [comment]
Hemos visto que en Devise Security Extension hay un módulo :password_expirable ¿podemos usarlo o preferís otra forma?

**Comment by voodoorai2000** [comment]
Closed via #1106
