### ISSUE TITLE
Retirar apoyo a una propuesta

### ISSUE THREAD

**Issue by tombe85** [consul/consul#887]
Se puede dar el caso de que alguien apoye una propuesta accidentalmente o que cambie de opinión al enterarse bien de qué va. Según he visto en la web no hay forma de retirar el apoyo dado y creo que es algo importante a tener en cuenta.

**Comment by Perisso** [comment]
Me la quedo.

**Comment by xuanxu** [comment]
@Perisso @tombe85 Esta funcionalidad se estudió al crear la plataforma y fue descartada. 
El dar apoyo a una propuesta es equivalente a apoyar una recogida de firmas. No queremos que se alcancen los apoyos necesarios para pasar a la siguiente fase y luego los número de apoyos conseguidos puedan disminuir. Si alguien cambia de opinión o quiere retirar el apoyo, en la siguiente fase, cuando la propuesta esté en votación ciudadana puede votar en contra.

**Comment by xuanxu** [comment]
@Perisso gracias por tu interés en contribuir con Consul. Para que no vuelva a pasar esto, os sugerimos que echéis un vistazo a las issues marcadas con PR-welcome; estas son issues que ya hemos revisado sobre funcionalidades que sabemos seguro que necesitamos.

**Comment by Perisso** [comment]
Ok.
