### ISSUE TITLE
Votar en contra

### ISSUE THREAD

**Issue by rgmarcos** [consul/consul#888]
Si alguien no quiere que salga alguna propuesta por algun motivo, no tiene posibilidad de dejar su opinión. Para que fuera más justo todo se deberían tener en cuenta los votos a favor y los votos en contra.

**Comment by decabeza** [comment]
Hola @rgmarcos, ¡gracias por la sugerencia! Ahora mismo cualquier usuario ya puede dejar su opinión en los comentarios de cada propuesta.

Las propuestas tienen un número de apoyos necesarios para pasar a la siguiente fase de votación. En el caso de Madrid es de un 2% del censo (53.726 votos), después de alcanzar ese número pasan a la fase de votación para decidir si los ciudadanos quieren o no que se realice dicha propuesta. 

Con esos números consideramos por el momento que es suficiente para saber si una propuesta se quiere realizar o no. :wink:
