### ISSUE TITLE
Hide stats for obsolete marketing campaigns

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#919]
In the stats section, there are many graphs of past campaigns that slow down the page load time. 
We should hide them to speed things up.

**Comment by morenohe** [comment]
Ana y Elena queremos intentar meternos con esta issu. ¿Cuándo una campaña se considera obsoleta?

**Comment by xuanxu** [comment]
El tema es que las gráficas de los eventos tardan mucho en pintarse y sobrecargan la página, a lo mejor una solución sería hacer que no se pinte ninguna de las [gráficas de los eventos](https://github.com/ayuntamientomadrid/consul/blob/master/app/views/admin/stats/show.html.erb#L95-L100) y que en su lugar aparecieran links para poder verlas una a una a quien le interese.

**Comment by morenohe** [comment]
Os referís a las gráficas de Admin --> estadísticas (ahi solo vemos solo una gráfica de visitas)

**Comment by voodoorai2000** [comment]
Sí! [Antes de cualquier petición](https://github.com/AyuntamientoMadrid/consul/blob/master/app/controllers/application_controller.rb#L12)  se mira a ver si la url viene con un track_id y eso se convertirá en un gráfico en /admin/stats.

Para reproducirlo, habría que crear una campaña desde la consola, algo así:
Campaign.create(name: 'nueva campaña de emails', track_id: '12345678')

Y después vamos a una url con ese track_id, algo así:
http://localhost:3000?track_id=12345678

Ahora debería aparecer ese gráfico en /admin/stats para hacer pruebas!

**Comment by voodoorai2000** [comment]
Relacionada con https://github.com/consul/consul/issues/1042

**Comment by voodoorai2000** [comment]
This has been done for a while
