### ISSUE TITLE
Add stats for signups

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#922]
In the admin/stats section we should have a graph displaying the number of signups per day.

**Comment by inobCR** [comment]
Voy a por ella

**Comment by voodoorai2000** [comment]
Partial work done [here](https://github.com/consul/consul/pull/1003), temporarily on hold, anyone feel free to continue

**Comment by voodoorai2000** [comment]
This has already been implemented using Piwik/Google Analytics
