### ISSUE TITLE
Banners

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#940]
Add an admin section where banners can be set. Banners are currently displayed in the proposal and debate indexes. Banners should have an image, text and link.

Suggestion:
Regarding the image, we could display a number of sample images from which to chose from.

**Comment by palomahnhp** [comment]
Entiendo que te refieres a banners del tipo Presupuestos participativos que aparece en debates y propuestas en decideMadrid.  Nos ponemos con ello con estas premisas.  
@MaiteHdezRivas y @palomahnhp.

**Comment by decabeza** [comment]
Sí @palomahnhp y @MaiteHdezRivas es este banner:

![screen shot 2016-03-21 at 11 00 27](https://cloud.githubusercontent.com/assets/631897/13915321/406ee004-ef54-11e5-934a-ecd56bb11a65.png)

Estaría bien que tuviese los campos de:

- Título
- Texto
- Enlace
- Imagen

:wink:

**Comment by palomahnhp** [comment]
Estupendo,  gracias. 
Ss me ocurren dos formas de abordarlo:
a) incluirlo en settings, algo similar a features, que es lo mas sencillo pero no parece muy funcional  
b) o crear una nueva funcionalidad  con nuevo controlador, modelo y vistas. Sería necesaria una nueva tabla para almacenar la información del banner y se podrían incluir además de los campos que indica @decabeza fechas de inicio y fin de publicación.  
Yo empiezo con la opción b) a no ser que me digais otra cosa :)

**Comment by palomahnhp** [comment]
o si solo va a publicarse un banner cada vez no crear tabla y usar settings creando registros banner.title, banner.link etc

**Comment by xuanxu** [comment]
La opción b) es la buena, sí :ok_hand:

**Comment by xuanxu** [comment]
done in #1127
