### ISSUE TITLE
Share with WhatsApp

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#941]
Apart from sharing with twitter and facebook, users in mobile platforms should be able to share with WhatsApp.

Suggestion:
http://stackoverflow.com/questions/21935149/sharing-link-on-whatsapp-from-mobile-website-not-application-for-android

**Comment by Ana06** [comment]
I'll do it! :)

**Comment by decabeza** [comment]
Thanks! :+1:

**Comment by decabeza** [comment]
Already on production! :tada:

**Comment by voodoorai2000** [comment]
:dancer:

**Comment by Ana06** [comment]
:tada:
