### ISSUE TITLE
Admin notifications

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#944]
To inform users of updates, there should be an admin section where notifications can be created. This notifications would appear for all users in their section '/notifications'.

**Comment by palomahnhp** [comment]
Lo hacemos @MaiteHdezRivas y @palomahnhp

**Comment by ManjiChiba** [comment]
Precisamente iba crear un hilo sobre este mismo tema.
- Aviso por mensaje de que una Propuesta ha pasado a 3ª fase. (53 apoyos)
     https://decide.madrid.es/proposals/8704

**Comment by iagirre** [comment]
I'll do this one.

**Comment by decabeza** [comment]
Closed in favor to https://github.com/consul/consul/issues/2145
