### ISSUE TITLE
Add timestamps for analytics

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#948]
For analytic tools it would be useful to add to the html a creation timestamp for debates, proposals and comments. This value should be the exact time but it should not be visible to users navigating the site.

**Comment by CarmenHLedesma** [comment]
We´ll do it :) Thks!

**Comment by voodoorai2000** [comment]
I thought this was done, but I can't find the code right now...

In any case thank you very much @CarmenHLedesma we are currently covering this requirement using Piwik/Google Analytics and a public API
