### ISSUE TITLE
Make the site 100% accessible

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#950]
Yes we can!

**Comment by decabeza** [comment]
Some useful links:

- Check accessibility: 

    - http://www.sidar.org/hera/index.php.es

    - http://www.evaluera.co.uk/atester

- About how to use icon fonts: https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html

- About texts of “Lectura fácil”: http://www.discapnet.es/Castellano/areastematicas/Accesibilidad/accesibilidadcomunicacion/LecturaF%C3%A1cil/Paginas/default.aspx

**Comment by voodoorai2000** [comment]
All done except for the mighty captcha https://github.com/consul/consul/issues/360
