### ISSUE TITLE
Custom folder structure

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#953]
In order to improve the collaboration between forks and upstream, there should be a place to put custom code and a place for generic code. There are a number of possibilities to solve this issue, such as gems and engines. Whilst we think these are good options, we would like to keep things as simple as possible and start with a custom folder structure.

Some of the custom folders could be:
- [ ] MVC
- [ ] Assets
- [ ] Configuration

**Comment by andreslucena** [comment]
I think this (or something similar) could be a good starting point at least for the Assets, Views and Locales: https://github.com/yoolk/themes_on_rails
