### ISSUE TITLE
Verification Abstraction 

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#954]
Each fork uses a different user verification process. We should create a generic verification process in Consul and move Madrid's custom verification process to its fork.
- [x] Move **postal_code_in_madrid** in `models/verification/residence.rb` to a custom validation
- [x] Extract document number variants to a module in `lib/census_api.rb`
- [ ] Make **residence_in_madrid** used in `verification/residence/_errors.html.erb` generic
- [ ] Add an example `lib/custom/census_api.rb` file
- [ ] Create a generic representatión of the key methods in `lib/census_api.rb`

**Comment by hugobarthelemy** [comment]
Hello Voodoorai2000!

I'm really interested in your issue because I worked to deploy Consul budget for a city lessor in France. Do you have more documentation about CensusAPI? I don't understand how to adapt the control of residence.
Thank you

**Comment by voodoorai2000** [comment]
Hello @hugobarthelemy!

That sounds great!

Are you going to be in Paris this week? We are going to the OGPSummit (http://www.opengovpartnership.org/events/ogp-global-summit-2016-paris) maybe we could sit down and go through it.

In any case we have to update those docs, indeed! We will get on that :)

Cheers!

**Comment by hugobarthelemy** [comment]
Hello @voodoorai2000!
I am already registered for the OGPSummit in Consul group so we will can talk about docs ;)
Cheers!

**Comment by voodoorai2000** [comment]
Awesome! See you soon @hugobarthelemy :)

**Comment by javierm** [comment]
Closing in favor of #1838, since that one has references to pull requests trying to solve this issue.
