### ISSUE TITLE
Liquid Democracy

### ISSUE THREAD

**Issue by voodoorai2000** [consul/consul#956]
Users should be able to delegate their votes on other users.

Related to an [issue in a Madrid's fork](https://github.com/AyuntamientoMadrid/consul/issues/71). Once it's ready we could create a generic version for Consul.

**Comment by ManjiChiba** [comment]
Ya he visto que esta habilitada la nueva opción para poder delegar voto.... profundizando un poco más en el tema de la delegación.... ¿qué tal una delegación parcial y no total?.
Delegación parcial de voto a una persona (o asociacion) concreta en una propuesta concreta.
     https://decide.madrid.es/proposals/11994
Disculpen, si escribo donde no debo.
Si es así, hagánmelo saber. Gracias.

**Comment by xuanxu** [comment]
Hola @Manjichiba, gracias por la sugerencia, la delegación parcial está contemplada para añadirla en un futuro, cuando las tareas más prioritarias estén hechas.

De todas maneras, por favor para temas referentes a la web de decide.madrid.es, utiliza el repositorio de código del Ayuntamiento de Madrid, esta aquí: https://github.com/AyuntamientoMadrid/consul/issues
Este es el de la aplicación genérica que se usa como base para muchas otras ciudades, no incluye muchas de las cosas específicas de cada ciudad y el idioma por defecto para discusiones sobre el código es el inglés.

**Comment by ManjiChiba** [comment]
Ok.
Disculpar las molestias, no sabía que era en el otro link.
Copio y pego en la otra web, mis propuestas en unas horas, y borro de aquí.
Siento las molestias.

**Comment by javierm** [comment]
Closing to avoid confusion, since this feature has been removed from Madrid's fork. We might implement it in the future, but it won't be related to what was implemented in Madrid.
